DataDog/browser-sdk

- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/transport/httpRequest.ts
- packages/core/src/transport/sendWithRetryStrategy.spec.ts
- packages/core/src/transport/sendWithRetryStrategy.ts
- packages/core/test/specHelper.ts
Some intake requests are retried due to response status 0 while the data still reach datadog. 
- Retry request when status is 0 only when offline
- Remove `retry_after_type` debug tag
---
> 🐛 [RUMF-1435] do not retry status 0 request while online

- renovate.json
Avoid renovate PRs to be listed in change log
Add 👷 prefix to renovate PRs
generate an update PR after merge
---
> 👷 Avoid renovate PRs to be listed in change log

- renovate.json
Try to ease https://github.com/DataDog/browser-sdk/pull/1901
Exclude same dependencies that were listed in dependabot.yml and would require more effort to update.
N/A
---
> 👷 Renovate: exclude same deps as dependabot

- renovate.json
Single PR for all non major is a bit complicated for now, let's see if we can move more progressively with the backlog and re-enable it when we will be on a better state.
remove group:allNonMajor option
N/A
---
> 👷 renovate: remove group:allNonMajor

- .gitlab-ci.yml
The check-release job is failing because it looks for files that are generated when building the packages.
Build the packages before running the check-release script
---
> 👷 fix check-release job by building packages before doing the check

- developer-extension/src/background/domain/refreshDevServerStatus.ts
- developer-extension/src/background/domain/syncRules.ts
- developer-extension/src/common/constants.ts
- developer-extension/src/panel/hooks/useEvents.ts
Some extension features were not supported on applications using internal analytics domain:
-  Event source `Requests``
- Block intake requests
- Move `constants.ts` to `common`
- Use intake domain constants for both `listenEventsFromRequests` and `blockIntakeRequests`
- Add `iam-rum-intake.datadoghq.com` intake domain
---
> 🐛 extension: handle internal analytics domain

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/viewContexts.spec.ts
- packages/rum-core/src/domain/contexts/viewContexts.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
Help investigate why view event counts are often incorrect.
Add `_dd.view.document_count` reflecting the current view document count at the moment when the event is collected. In theory, the final `_dd.document_count` on View events will alway be greater than child events `_dd.view.document_count`, because any child event collected will trigger a scheduled view update. Let's verify that.
---
> 🔊 add view document_count in non-view events

- eslint-local-rules/disallowSideEffects.js
- packages/core/src/browser/addEventListener.spec.ts
- packages/core/src/browser/addEventListener.ts
- packages/core/src/index.ts
- packages/core/src/tools/runOnReadyState.ts
- packages/core/src/tools/utils.ts
We want to better understand what type of [untrusted events](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) are being recorded.
Superseds https://github.com/DataDog/browser-sdk/pull/1878
Add a telemetry debug log when an untrusted event is dispatched and caught by our SDK. We limit the number of reported events to one per event type to avoid sending too many logs.
---
> 🔊 [RUMF-1345] add telemetry logs on untrusted events

- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
Avoid to have `ddsource` query parameter in first position for internal analytics mode
Reverse query parameters order when `internalAnalyticsSubdomain` is used
---
> 👷 [RUMF-1464] Tweak query parameters for internal analytics

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/domain/logsSessionManager.spec.ts
- packages/logs/src/domain/logsSessionManager.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- packages/rum-core/src/domain/rumSessionManager.ts
- packages/rum-core/src/domain/tracing/tracer.spec.ts
- packages/rum-core/src/domain/tracing/tracer.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum/src/types/sessionReplay.ts
- sandbox/index.html
- test/e2e/scenario/eventBridge.scenario.ts
- test/e2e/scenario/rum/actions.scenario.ts
- test/e2e/scenario/telemetry.scenario.ts
Uniformise init config parameters names across SDKs
- Introduce `sessionSampleRate` and deprecate `sampleRate`
- Introduce `traceSampleRate` and deprecate `tracingSampleRate`
- Introduce `trackUserInteractions` and deprecate `trackInteractions`
**Note:** documentation will be updated after the release of those new parameters
---
> ✨[RUMF-1397] init parameter standardisation

- scripts/bump-chrome-driver-version.js
- scripts/staging-ci/staging-reset.js
- scripts/utils.js
Staging reset failed this morning. It appears to be multiple issues:
* It checks wether the branch exists on the remote, but it failed to delete the existing branch locally.
* When retried, the job failed again because it did not had any change when editing `.gitlab-ci.yml`. The retry was done on the same initial commit, so the CURRENT_BRANCH environment variable was still `staging-01`, but a commit to updathe this environment variable to `staging-02` was already pushed on  `main` branch.
* While investigating, I figured that week number computation was timezone dependent, which is a bit confusing when running parts of the script locally
* Don't check whether the branch exists remotely. Instead, only check if it exists locally, and force push (that's what the dogweb script does)
* Read …
> 👷 attempt to fix staging-reset

- scripts/staging-ci/staging-reset.js
It appears that staging branch don't necessarily have an upstream set up, especially when the branch was just created.
Be explicit on what we are trying to pull so git doesn't fail.
---
> 👷 fix staging reset last step

- scripts/bs-wrapper.js
- scripts/bump-chrome-driver-version.js
- scripts/check-licenses.js
- scripts/check-release.js
- scripts/export-test-result.js
- scripts/generate-changelog.js
- scripts/generate-schema-types.js
- scripts/replace-build-env.js
- scripts/staging-ci/check-squash-into-staging.js
- scripts/staging-ci/check-staging-merge.js
- scripts/staging-ci/merge-into-staging.js
- scripts/staging-ci/staging-reset.js
- scripts/update-peer-dependency-versions.js
- scripts/upload-source-maps.js
- scripts/utils.js
For [RUMF-1330] I will improve how nodejs scripts are executing commands, and I want to make those command execution synchronous. Thus, some scripts will be entirely synchronous. Our current `logAndExit` helper works better with asynchronous scripts, so the goal of this PR is to support future synchronous script execution.
This commit replaces the `logAndExit` function with a `runMain` function which is similar but reduces a bit the scripts boilerplate and supports synchronous main function.
Before:
```
async function main() {}
main().catch(logAndExit)
```
After:
```
runMain(async () => {})
```
---
[RUMF-1330]: https://datadoghq.atlassian.net/browse/RUMF-1330?atlOrigin=eyJpI …
> 👷 change scripts main error handler strategy

- packages/rum/src/domain/record/privacy.spec.ts
- packages/rum/src/domain/record/privacy.ts
Ignore elements of type:
```
<link rel="preload" as="script">
<link rel="modulepreload" as="script">
<link rel="prefetch" as="script">
```
to decrease payload, as they are ignored as well by replay.
---
> [RUMF-1263] ⚡ Ignore link tags with rel=modulepreload|prefetch

- packages/logs/src/boot/logsPublicApi.spec.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
Context: Synthetics Profiler doesn't tag profiles with correct service tag
I need `DD_RUM.getInitConfiguration()` to return init configuration even if it's inside synthetic test. Currently, when I call `DD_RUM.getInitConfiguration()` inside synthetic test, it returns undefined, because `initRum()` function is interrupted by:
```typescript
if (ignoreInitIfSyntheticsWillInjectRum && willSyntheticsInjectRum()) {
return
}
```
which prevents from this code to be executed:
```typescript
getInitConfigurationStrategy = () => deepClone<InitConfiguration>(initConfiguration)
```
This breaks profile tagging, as we can't infer service name (and because of that, we can't resolve source maps)
I think that `getInitConfiguration()` should return init configuration even if init process was not successful …
> Fix `getInitConfiguration()` behaviour

- packages/core/src/browser/addEventListener.spec.ts
- packages/core/src/browser/addEventListener.ts
We collected enough data around untrusted events.
This reverts commit 3a3b9c8d07c5befa628fe952b96f2adc6e478353. It does not revert other changes from the PR https://github.com/DataDog/browser-sdk/pull/1910 (keep the `runOnReadyState` module, keep allowing a few constructiors in the side-effect eslint rule), as it could be valuable in the future.
---
> Revert "🔊 [RUMF-1345] log first untrusted events of each type"

- .github/dependabot.yml
Avoid to be notified for updates by both dependabot and renovate
- remove dependabot update schedules
- remove dependabot ignored packages
Still keep dependabot.yml for commit message configuration for dependabot security updates.
---
> 👷remove scheduled dependabot updates

- .github/dependabot.yml
Following #1954, `schedule` property is actually required in the yml schema 🤦‍♂️ 
Follow [documented workaround](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) and set open PR limit to 0.
---
> 👷properly disable dependabot updates

- packages/rum/README.md
Adding documentation for newly introduced allowedTracingUrls.
NOTE: [Connect RUM and Traces](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces) needs to be updated first.
---
> 📝 Added allowedTracingUrls configuration parameter

- test/app/yarn.lock
- yarn.lock
Fix security issue raised by dependabot
Pin json5 resolution to 1.0.2 and 2.2.2
---
> 👷 bump json5 resolutions

- packages/core/src/transport/batch.spec.ts
With the upgrade of jasmine the typecheck is more strict and fails if the jasmine spy def does not match with the test assertion
---
> 🐛 Fix jasmine spy type issue

- packages/core/test/specHelper.ts
- packages/rum/src/domain/record/serialize.spec.ts
- packages/rum/src/domain/record/serialize.ts
The goal is to leave to the player the opportunity to either use inline CSS or rely on external resource
- Keep Href from link even when importing CSS
- Add missing tests on the style serialization
We now capture both `href` & `_cssText`
---
> [REPLAY] Keep Href from link even when importing CSS

- packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.ts
This issue was causing a lot of false negative dead clicks. Once an "input" event was triggered on the page, all subsequent clicks were considered to have changed an input, so no dead clicks were produced anymore.
Reset the `hasInputChanged` state whenever a new click happens.
---
> 🐛 reset input state at the beginning of each click

- packages/rum/src/domain/record/mutationObserver.spec.ts
- packages/rum/src/domain/record/mutationObserver.ts
- packages/rum/src/domain/record/observers.spec.ts
- packages/rum/src/domain/record/observers.ts
- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/serialize.spec.ts
- packages/rum/src/domain/record/serialize.ts
- test/e2e/scenario/recorder/shadowDom.scenario.ts
Remove experimental flag for shadow dom
Remove exp flag `record_shadow_dom`
---
> [REPLAY] Remove exp flag for shadow dom

- .gitlab-ci.yml
Avoid running some unnecessary steps on the CI when pushing a new commit on the same branch.
Mark some jobs as [interruptible](https://docs.gitlab.com/ee/ci/yaml/index.html#interruptible). Most jobs are interruptible, except those with side effects (release/deploy/publish and scheduled tasks...)
I tried to push a new commit on the same branch, it successfully canceled the previous pipeline.
---
> 👷 [RUMF-1472] set some CI jobs as "interruptible"

- packages/core/src/tools/utils.ts
- packages/core/test/specHelper.ts
- packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
- packages/rum-core/src/domain/requestCollection.ts
Following #1942, we still had some telemetry errors related to `response.clone()` in the case of [disturbed](https://streams.spec.whatwg.org/#is-readable-stream-disturbed) response.
Add `try/catch` around `response.clone()` to prevent any thrown error to disturb our data collection.
---
> 🐛[RUMF-1465] collect data for disturbed response

- packages/rum-core/src/browser/htmlDomUtils.spec.ts
"DEPRECATION: describe with no children (describe() or it()) is deprecated and will be removed in a future version of Jasmine."
Wrapping the `describe` in a `if` statement is not really pretty. Ideally we would use "shadow dom" APIs inside `beforeEach` or `it` blocks instead of `describe`, but this prevents us from using a list to generate test cases.
I think it's acceptable until we eventually drop IE support.
---
> ✅ fix Jasmine deprecation warning in unit tests/IE

- packages/rum/src/domain/record/shadowRootsController.ts
[REPLAY] Add telemetry for shadow dom #1978
- add shadow dom content if FF is present (only to be activated on org2 for privacy concerned)
---
> [REPLAY] Add telemetry for shadow dom

- packages/core/src/transport/httpRequest.spec.ts
- packages/core/test/collectAsyncCalls.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/record/mutationBatch.spec.ts
- packages/rum/src/domain/record/mutationObserver.spec.ts
- packages/rum/src/domain/record/record.spec.ts
- packages/rum/test/utils.ts
This particular test is quite flaky.
FMU, it was assuming that `Promise.resolve` took less than 1ms. But this was often not the case, and the `setTimeout` callback was called too often.
By using `collectAsyncCalls`, we remove this race condition.
---
> ✅ fix flaky test

- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
This ticket is part of an effort to improve dead clicks. 
* https://github.com/DataDog/browser-sdk/pull/1968 will fix an issue where a lot of dead clicks were completely ignored
* https://github.com/DataDog/browser-sdk/pull/1958 will discard dead clicks when something happens during the 'pointerup' event (previously only things happening during the 'click' event were taken into account)
* https://github.com/DataDog/browser-sdk/pull/1979 (this issue) will discard dead clicks when something happens during the 'pointerdown' event
All three fixes are behind the `dead_click_fixes` and will be released together after some dogfooding.
We observed that in some cases, click actions are flagged as "dead click" when the UI updates during "pointerdown" or "mousedown" events (happening before the …
> ⚗🐛 [RUMF-1293] discard dead clicks when activity occurs on pointerdown

- packages/rum/src/boot/recorderApi.ts
- packages/rum/src/domain/record/mutationObserver.ts
- packages/rum/src/domain/record/serialize.ts
Old browsers do not implement [NodeList.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach). Add a check to isBrowserSupported
Add NodeList.prototype.forEach check  to isBrowserSupported
---
> 🐛 [RUMF-1476] Fix removednodes.foreach is not a function

- packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
This ticket is part of an effort to improve dead clicks. 
* https://github.com/DataDog/browser-sdk/pull/1968
* https://github.com/DataDog/browser-sdk/pull/1958
* https://github.com/DataDog/browser-sdk/pull/1979
* https://github.com/DataDog/browser-sdk/pull/1986 (this issue)
All fixes are behind the `dead_click_fixes` and will be released together after some dogfooding.
When users are manipulating contenteditable elements, we often report dead clicks incorrectly
Ignore contenteditable elements for dead clicks.
---
> ⚗️🐛 ignore contenteditable elements for dead clicks

- scripts/generate-changelog.js
While releasing a new version, the generate-changelog script failed when[ fetching tags ](https://github.com/DataDog/browser-sdk/blob/6aec1d3657507bd002d57618db79d4ecfbec8d6e/scripts/generate-changelog.js#L67) because it `would clobber existing tag`
Force to fetch tags in generate-changelog script
---
> 👷 Fix generate changelog fetch tags

- yarn.lock
Fix ```GitHub found 2 vulnerabilities on DataDog/browser-sdk's default branch (2 high).```
Update ua-parser-js to 0.7.33/1.0.33
---
> 👷 Update sub-dependency ua-parser-js to 0.7.33/1.0.33

- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/record/observers.spec.ts
- packages/rum/src/domain/record/observers.ts
We have a bunch of error in the player where we have mouse record without x/y with numeric value. 
The hypothesis is that the event are not generated by the browser but by JS using `dispatchEvent` 
- Discard mouse/touch event without x/y position
- Add telemetry with `isTrusted` to validate/invalidate the theory
---
> [REPLAY] Discard mouse/touch event without x/y position

- yarn.lock
Fix ```http-cache-semantics vulnerable to Regular Expression Denial of Service ``` vulnerability
Updated http-cache-semantics to 4.1.1
---
> 👷 Update http-cache-semantics to 4.1.1

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/viewContexts.spec.ts
- packages/rum-core/src/domain/contexts/viewContexts.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
We collected enough data to confirm that most invalid counters are caused by missing view updates.
This reverts commit 1dcc3a961a58023b52ed87ea021c41845b069f51.
---
> Revert "🔊 add view document_count in non-view events (#1892)"

- packages/rum-core/src/browser/htmlDomUtils.spec.ts
- packages/rum-core/src/browser/htmlDomUtils.ts
Shadow DOM support is broken in Microsoft Edge 18. It's not quite clear whether Session Replay should support old versions of Edge, but since it works fine currently let's fix this small issue.
Don't assume `element.shadowRoot` is `null | Node`, as it can also be `undefined` in Edge
---
> 🐛 fix Shadow DOM support on old Microsoft Edge versions

- packages/core/test/specHelper.ts
- packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
- packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
- packages/rum-core/test/createFakeClick.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
This PR enables various fixes related to dead click computation:
* https://github.com/DataDog/browser-sdk/pull/1968 will fix an issue where a lot of dead clicks were completely ignored
* https://github.com/DataDog/browser-sdk/pull/1958 will discard dead clicks when something happens during the 'pointerup' event (previously only things happening during the 'click' event were taken into account)
* https://github.com/DataDog/browser-sdk/pull/1979 will discard dead clicks when something happens during the 'pointerdown' event
* https://github.com/DataDog/browser-sdk/pull/1986 will discard dead clicks triggered by manipulating content of `contenteditable` elements
* Remove experimental flags
* Adjust tests
---
I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/C …
> 🐛 [RUMF-1296][RUMF-1293] fix dead click computation

- test/e2e/scenario/rum/actions.scenario.ts
One of our scenario started to fail due to a new error on example.com:
```
https://example.com/favicon.ico - Failed to load resource: the server responded with a status of 404
```
During the test, open a new window on the current url instead of example.com.
---
> 👷 Remove dependency on example.com

- packages/rum-core/src/browser/htmlDomUtils.spec.ts
- packages/rum-core/src/browser/htmlDomUtils.ts
Fix freeze in serialization because of infinite loop
Make sure to not count form element with child input as name host as a shadow root
---
> :bug:[RUMF-1493] Avoid infinite loop on `form >  input[name="host"]` element

- packages/core/src/browser/pageExitObservable.spec.ts
- packages/core/src/browser/pageExitObservable.ts
- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/transport/batch.spec.ts
- packages/core/src/transport/batch.ts
- packages/core/src/transport/httpRequest.ts
- packages/core/src/transport/index.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.ts
- packages/rum/src/types/sessionReplay.ts
Use `pagehide` instead of `beforeunlaod` to:
- Prevent from not being bfcache in firefox
- Collect events / DOM mutations happening between `beforeunload` and `pagehide`
- Prevent from being wrongly notified if the unload is canceled by the user. The view won’t be wrongly ended. 
To assess the impact:
- Enable `collect_flush_reason` ff to collect it for RUM events and replay segments
- Enable `pagehide`  ff for 50% of users and compare both data sets
- pageExitObservablt use pagehide instead beforeunload (under `pagehide` ff)
- collect flush reason as a tag (under `collect_flush_reason` ff)
---
> [RUMF-1484] ⚗️ use pagehide as unload event

- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/instrumentMethod.ts
Issue reported to the Kendo-UI project here: https://github.com/telerik/kendo-angular/issues/3930
The issue is related to Zone.js/Angular + using the Kendo UI Grid component
1. open the official Kendo UI grid example: https://www.telerik.com/kendo-angular-ui/components/grid/examples/filter-all-columns/?theme=default-ocean-blue&themeVersion=6.1.0
2. execute the following code in the console (this is similar to what the SDK is doing):
```js
Object.defineProperty(HTMLInputElement.prototype, 'checked', { set() { setTimeout(() => { }) } })
```
3. click on the first checkbox
4. the CPU usage increases to 100%
* Angular is using Zone.js to track asynchronous executions (like `setTimeout`), and apparently in some cases triggers a component re-render when a `setTimeout` executes its callback.
* …
> 🐛 [RUMF-1443] fix Zone.js/Angular crash when recording the session

- packages/rum/src/domain/segmentCollection/startDeflateWorker.ts
When failing to create the Worker, we try to detect whether the error is related to CSP to guide the user.
When using the `require-trusted-types-for` CSP, the error does not mention "Content Security Policy". Thus, we report it as a telemetry error.
This commit adjusts this and consider it as a CSP error.
---
> 🔇 remove some errors during Worker creation from telemetry

- .eslintrc.js
- eslint-local-rules/disallowZoneJsPatchedValues.js
- eslint-local-rules/index.js
As we've seen in the past, integrating the SDK on an app that uses Angular/Zone.js causes critical issues in various ways. See related PRs:
* #376
* #866
* #1530
* #1860
* #2030
This PR adds an ESLint rule to forbid usage of some values that are known to cause trouble when they are patched by Zone.js. This PR focuses on introducing the rule and disallow `MutationObserver`. Future PRs will disallow more things.
---
> 🚨 [RUMF-1505] ESLint rule to forbid usage of Zone.js problematic values

- eslint-local-rules/disallowZoneJsPatchedValues.js
- packages/core/src/browser/timer.spec.ts
- packages/core/src/browser/timer.ts
- packages/core/src/domain/session/sessionCookieStore.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/index.ts
- packages/core/src/tools/contextHistory.ts
- packages/core/src/tools/createEventRateLimiter.ts
- packages/core/src/tools/instrumentMethod.ts
- packages/core/src/tools/utils.ts
- packages/core/src/transport/batch.ts
- packages/core/src/transport/sendWithRetryStrategy.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/browser/viewportObservable.ts
- packages/rum-core/src/domain/rumEventsCollection/action/clickChain.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViewEventCounts.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
- packages/rum-core/src/domain/waitPageActivityEnd.ts
- packages/rum/src/domain/record/observers.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.ts
Following https://github.com/DataDog/browser-sdk/pull/2031, we want to disallow native `setTimeout` usages across the codebase.
Introduce a safe `setTimeout` helper function and use it in packages.
---
> ♻️ [RUMF-1505] introduce and use a safe `setTimeout` helper function

- packages/core/src/tools/utils.ts
`requestIdleCallback` is not supported on Safari and some customer use polyfills that only polyfills `requestIdleCallback` but not `cancelIdleCallback`.
checks both requestIdleCallback and cancelIdleCallback existence
---
> 🐛 Handle undefined cancel idle callback

- package.json
- packages/core/src/browser/pageExitObservable.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/report/reportObservable.ts
- packages/core/src/tools/display.ts
- packages/core/src/tools/error.ts
- packages/logs/src/domain/logger.ts
- packages/rum/src/boot/recorderApi.spec.ts
- packages/rum/src/constants.ts
- packages/rum/src/types/sessionReplayConstants.ts
- test/e2e/lib/helpers/browser.ts
- yarn.lock
Upgrading to Prettier 2.8.4 introduces some improvements for readability with impact to the code base:
[Add parentheses for TSTypeQuery to improve readability](https://github.com/prettier/prettier/blob/main/CHANGELOG.md#add-parentheses-for-tstypequery-to-improve-readability-14042-by-onishi-kohei)
Renovate does not apply the format change so CI fails.
Updated dependencies and run `prettier --write .`
---
> 👷 Update dependency prettier to v2.8.4

- .gitlab-ci.yml
Allow to merge [dependency updates](https://github.com/DataDog/browser-sdk/pulls?q=is%3Aopen+is%3Apr+label%3Aready-to-merge) during prod freeze
Disable canary deployment
---
> 👷 Disable canary deployment

- developer-extension/src/panel/components/tabs/infosTab.tsx
- developer-extension/src/panel/components/tabs/settingsTab.tsx
Having the "end session" button in Settings is weird and impractical
Move the button next to the Session info:
---
> ♻️ [devext] move button to end the session next to the session info

- renovate.json
Try to group easy updates together to limit the number of updates PR
Add the grouping rule and exclude typescript package from this grouping since there is an ongoing failing PR about it.
---
> 👷 renovate: group minor and patch updates

- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
Expose `addFeatureFlagEvalution` API.
---
> ⚗ Expose feature flag evaluations API

- packages/core/src/index.ts
- packages/core/src/tools/error.ts
- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/logger.ts
- packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
The goal of this PR is to align capabilities for error monitoring between RUM and LOGS SDKs.
Added an optional error parameter: 
`logger.[level](message: string, messageContext?: object, error?: Error)`
which will be serialized as part of an error context, with defined fields (message, kind, stack)
---
> RUMF-1497 Allow logger APIs to pass an Error parameter

- packages/logs/README.md
Follow-up to https://github.com/DataDog/browser-sdk/pull/2029
Update documentation about new `error` parameter.
- Updated the signature of the logger functions 
- Updated the `generic` logger function section to include errors
- Added a new section showcasing the error parameter usage
---
> RUMF-1497 Update logger API documentation

- packages/core/src/transport/httpRequest.spec.ts
- packages/core/test/collectAsyncCalls.ts
- packages/core/test/getCurrentJasmineSpec.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/record/mutationBatch.spec.ts
- packages/rum/src/domain/record/observers/mutationObserver.spec.ts
- packages/rum/src/domain/record/record.spec.ts
The asynchronous call collection utility is a bit complex and suboptimal
as we wait 300ms for each test to check whether some calls are done
after the end of assertions.
* Do not wait for 300ms to check for extra calls
* Simplify usage by asserting no extra calls are done automatically
* Help debugging by printing the spec name when an asynchronous call is
done after the spec finished.
This change reduces tests execution time by 5 seconds on my machine.
Before:
```
Chrome Headless 111.0.5563.146 (Mac OS 10.15.7): Executed 1779 of 1782 (skipped 3) SUCCESS (16.335 secs / 15.842 secs)
```
After:
```
Chrome Headless 111.0.5563.146 (Mac OS 10.15.7): Executed 1779 of 1782 (skipped 3) SUCCESS (11.037 secs / 10.619 secs)
```
--- …
> ✅ improve async calls collection

- packages/core/src/tools/sanitize.spec.ts
- packages/core/src/tools/sanitize.ts
`sanitize` generates telemetry errors (Exception TypeError)
Proper computation of size for undefined values in objects and arrays
---
> 🐛 [RUMF-1470] Sanitize - Fix size computation

- performances/src/profilers/profilingUtils.ts
- performances/src/profilers/startCpuProfiling.ts
- performances/src/profilers/startMemoryProfiling.ts
- performances/src/profilers/startNetworkProfiling.ts
Avoid single utils files
rename `performances/src/utils.ts` to `performances/src/profilers/profilingUtils.ts`
---
> ♻️[RUMF-1517] rename performance utils

- .eslintrc.js
- eslint-local-rules/disallowTestImportExportFromSrc.js
- eslint-local-rules/index.js
- packages/rum/src/domain/record/observers/index.ts
Avoid to bloat customer packages with test code
- remove useless observers.specHelper exports
- add eslint rule to avoid this kind of issue
---
> 🐛[RUMF-1517] Remove specHelper export in src code

- eslint-local-rules/disallowZoneJsPatchedValues.js
- packages/core/src/browser/addEventListener.ts
- packages/core/src/browser/xhrObservable.ts
- packages/core/src/transport/httpRequest.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum/src/domain/segmentCollection/deflateWorker.d.ts
- packages/rum/src/domain/segmentCollection/segment.ts
- packages/rum/src/domain/segmentCollection/startDeflateWorker.ts
- packages/rum/test/mockWorker.ts
Follow-up of related PRs:
* #2044
* #2032
* #2031
We observed that using some `addEventListener` caused some critical issues when this function is patched by Zone.js. To work around that, the ESLint rule `disallow-zone-js-patched-values` is used to make sure we don't use `addEventListener` directly but instead use the "safe" `addEventListener` helper from `@datadog/browser-core`.
* Forbid direct `addEventListener` usages
* Use the `addEventListener` utility functions everywhere we used
`addEventListener` native methods.
---
> ♻️ [RUMF-1505] make sure we don't use Zone.js addEventListener

- .eslintrc.js
- eslint-local-rules/disallowUrlConstructorPatchValues.js
- eslint-local-rules/index.js
- packages/core/src/tools/utils/urlPolyfill.spec.ts
- packages/core/src/tools/utils/urlPolyfill.ts
- packages/rum/src/boot/recorderApi.ts
It has been observed that on some customer website, URL is badly polyfilled. It might not be a constructor, and might not provide a URL.createObjectURL function.
- Replace `checkURLSupported` by `getSupportedURL` to keep the original URL ref to avoid the `URL is not a constructor` error in the `buildUrl`.
- Check if `URL.createObjectURL` is supported for the recorder to avoid `URL.createObjectURL is not a function` error in the worker 
- Add an ESLint rule to force using `buildURL` instead of `new URL`. Inspired by [no-new-symbol rule](https://github.com/eslint/eslint/blob/main/lib/rules/no-new-symbol.js) 
---
> 🐛[RUMF-1544] Fix badly polyfilled URL 

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum/src/domain/record/shadowRootsController.ts
Housekeeping
Remove flags:
- `resource_durations`
- `shadow_dom_debug`
---
> 🔥 Cleanup unnecessary flags 

- renovate.json
Possible updates have been merged, new updates could be grouped in `all non-major dependencies` updates. 
Remove exclusion:
- `@types/node`
- `*jasmine*`
---
> 👷 remove @type/node, jasmine from renovate exclusions

- .eslintrc.js
- performances/src/trackNetwork.ts
- scripts/lib/execution-utils.js
- test/e2e/lib/framework/httpServers.ts
- test/e2e/lib/framework/serverApps/intake.ts
- test/e2e/lib/helpers/browser.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
Enforce consistent usage of `async` keywords. Proposed by @bcaudan [here](https://github.com/DataDog/browser-sdk/pull/2125#discussion_r1154381378).
* Enable `require-await`
* Make sure we don't use `async function` when we don't use `await`
---
> 🚨 add require-await rule and remove useless async

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/rumEventsCollection/view/setupViewTest.specHelper.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
This PR is a preliminary step for notifying the backend that a session has expired via a View update. In other words, the goal is [to tackle this TODO](https://github.com/DataDog/browser-sdk/blob/main/packages/rum-core/src/domain/assembly.ts#L92-L95). To do so, we need to send a view update after the session has expired, which is not possible right now.
This PR makes sure we don't send too many view updates when the session is expired. In particular, when the session expires, we now:
* end the current view which stops updates from metrics
* stops the session keep alive interval
* prevent any initial view updates
* do not accept new timings
A view can still be updated after the session expires:
* child events that started before session expiration are still collected, we need to update the …
> ✨ [RUMF-1534] allow (some) view updates after session expiration

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
- test/e2e/scenario/rum/sessions.scenario.ts
Tell the backend to end the session early when we detect that the session expired, especially useful when using `stopSession()` manually.
With this PR, the SDK will send a view update with `@session.is_active:false` every time it detects that the session expires.
---
> ✨ [RUMF-1534] send a view update when session is expiring

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/contexts/displayContext.spec.ts
- packages/rum-core/src/domain/contexts/displayContext.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
- test/e2e/scenario/rum/actions.scenario.ts
Display click heatmaps within Datadog.
Remove the `clickmap` experimental feature flag.
---
> ✨ [RUMF-1479] enable heatmaps collection

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/segmentCollection/buildReplayPayload.spec.ts
- packages/rum/src/domain/segmentCollection/buildReplayPayload.ts
- packages/rum/test/readReplayPayload.ts
- test/e2e/lib/framework/serverApps/intake.ts
- test/e2e/lib/types/serverEvents.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
Send Replay metadata as JSON instead of individual multipart entries to make it easier to extend.
See https://github.com/DataDog/browser-sdk/pull/2125
This reverts commit 6d439e56cc5f807e75096f41d65a2e2258cc3a8a.
---
> ✨ [RUMF-1530] enable sending replay metadata as json

- packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
- packages/rum-core/src/domain/contexts/featureFlagContext.ts
- packages/rum-core/test/testSetupBuilder.ts
Still some `The feature flag evaluation data is over 3KiB ...` warning in test output from time to time.
**Root cause**: Since the byte count computation is throttled, a throttled computation could unexpectedly be executed while the `fakeByteCount` is set at `3073` from the warning behaviour test.
**Change**:  Cancel throttled computation after each test.
---
> ✅ Remove remaining feature flag test warning noise

- packages/core/src/domain/error/error.spec.ts
- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/trackRuntimeError.spec.ts
- packages/core/src/domain/tracekit/tracekit.ts
- packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
Prepare handling of error without stacktrace
- add more tests
- reorganise instrumentOnError
- reorganise computeRawError
---
> ♻️ [RUMF-1508] reorganise error handling

- .gitlab-ci.yml
Avoid to run browserstack job when `to-staging` is performed from mergequeue
Exclude mergequeue staging branches from `bs-allowed-branches`.
Branch name example: `mq-working-branch-staging-17-1911075`
---
> 👷 avoid running bs jobs in mergequeue staging

- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/trackRuntimeError.spec.ts
- packages/core/src/domain/tracekit/tracekit.spec.ts
- packages/core/src/domain/tracekit/tracekit.ts
Errors require a stack trace to be automatically grouped by error tracking.
When an uncaught exception is not an error instance, we don't provide a stack trace. 
However, in some cases some info can be retrieved from the [window.onerror handler arguments](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#arguments).
- Better handle non error instance:
- Avoid to compute stack trace but build one from from handler arguments
- Pass to the caller the thrown object instead of the message
- Used computed stack trace message only when it brings extra value (error instance or successfully parsed error message) 
---
> ✨[RUMF-1508] Provide stack trace for all uncaught exceptions

- scripts/release/generate-changelog.js
Have changelog entries a bit more organised by default to have the most interesting entries at the top
Sort changelog entries by a priority based on used emojis
---
> 👷 changelog generation: move most important entries to the top

- packages/core/src/domain/console/consoleObservable.spec.ts
- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/error.types.ts
- packages/core/src/index.ts
- packages/logs/src/domain/logsCollection/console/consoleCollection.spec.ts
- packages/logs/src/domain/logsCollection/console/consoleCollection.ts
- packages/logs/src/rawLogsEvent.types.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/error/trackConsoleError.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/error/trackConsoleError.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
Support [Error Tracking custom grouping](https://docs.datadoghq.com/logs/error_tracking/custom_grouping/#overview) for RUM errors.
In order to use `my-custom-grouping-material` to group RUM errors into a single issue in Error Tracking, from the APIs:
```javascript
const error = new Error('oh snap')
error.dd_fingerprint = 'my-custom-grouping-material'
DD_RUM.addError(error)
// or
console.error(error) 
```
Or from beforeSend callback:
```javascript
DD_RUM.init({
...
beforeSend: () => {
if (event.type === 'error') {
event.error.fingerprint = 'my-custom-grouping-material'
}
},
})
```
---
> ✨ [RUMF-1573] Allow to provide custom fingerprint to RUM errors

- packages/core/src/tools/serialisation/sanitize.spec.ts
- packages/core/src/tools/serialisation/sanitize.ts
Change of behavior when serializing errors:
https://github.com/DataDog/browser-sdk/issues/2195
Previously, an errror was serialized as an empty object `{}`. However, additional properties (added manually or from a custom error) were serialized:
```
const err = new Error('test')
err.myProp = 42
JSON.stringify(err)
=> { myProp : 42 }
```
Errors fall in the catch-all within the sanitize process, resulting in :
```
sanitize(err)
=> '[Error]'
```
Specific handler for `instanceof` Error 
Serialize additional properties from errors
=> [Error] reverts back to `{}` (empty object) for errors without additional properties.
---
> 🐛 Revert Errors serialization behavior

- LICENSE-3rdparty.csv
- package.json
- yarn.lock
[`js-polyfills`](https://www.npmjs.com/package/js-polyfills) is deprecated and unused
Remove it from our dependencies
---
> ➖ remove unused js-polyfills dependency

- test/app/package.json
- test/app/yarn.lock
Test related to tests/app are sometimes failing because `yarn` is now storing checksums in `yarn.lock` and everytime we change another package the lockfile needs to be adjusted.
use `portal:` instead of `file:` so we don't have checksums in test/app/yarn.lock
See [yarn doc](https://yarnpkg.com/features/protocols#table)
---
> 👷 🐛 fix test/app install with yarn 3

- scripts/release/check-release.js
Following yarn 3 update, check release script is failing on test app dependencies 
Change dependency check exclusion from `file:` to `portal:`
---
> 👷 fix check release script

- yarn.lock
This fixes https://github.com/DataDog/browser-sdk/security/dependabot/57 
Update socket.io and engine.io subdependencies. We need to upgrade socket.io because its dependency on engine.io is too strict and doesn't allow upgrading to a patched version.
---
> 📦 update vulnerable subdependency engine.io

- packages/core/.npmignore
- packages/logs/.npmignore
- packages/rum-core/.npmignore
- packages/rum-slim/.npmignore
- packages/rum/.npmignore
Unnecessary bloat npm packages size.
cf https://github.com/DataDog/browser-sdk/issues/2221
Exclude `spec` and `specHelper` files
---
> ⚡ remove spec files from npm packages

- renovate.json
* `@types/express` have been upgraded in https://github.com/DataDog/browser-sdk/pull/2170
* `webpack` related dependencies have been upgraded in https://github.com/DataDog/browser-sdk/pull/2212
* `typescript` have been upgraded in https://github.com/DataDog/browser-sdk/pull/2202
We can include them in the global minor/patch dependency PRs from renovate.
Tweak renovate configuration
---
> 📦👷 include upgraded dependencies in minor/patch deps upgrades

- packages/rum-core/src/domain/lifeCycle.ts
- scripts/cli
Support TS projects using `isolatedModules: true` 
This PR fixes #2208.
Bug reported here: https://github.com/microsoft/TypeScript/issues/54152
* add an integration test to make sure we are compatible with this option
* use a workaround to fix the TS error
---
> 🐛 fix isolatedModules support

- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
No reason to not have this behaviour when bridge is present
Start page exit behaviour regardless of bridge present or not
---
> 🐛 when bridge is present, send a final view update on page exit

- .gitlab-ci.yml
We reached more than 100 orgs using the new CDN URL on US1. When doing a release, deploy US1 separately to limit the scope.
Split `deploy-prod-all-dcs` into `deploy-prod-minor-dcs` and `deploy-prod-us1`. I used gitlab `extend` to avoid repeating ourselves too much.
---
> use a separate job to deploy US1

- packages/rum-core/src/domain/configuration.ts
Send right data 😅
Use right config parameter
---
> 🐛 Fix `use_excluded_activity_urls` telemetry

- packages/rum/src/domain/record/observers/mutationObserver.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
If we ignore empty text nodes during serialization, any 'characterData' mutation will be discarded because we wouldn't know about the corresponding serialized node.
Don't ignore empty text nodes
---
> 🐛 [RUMF-1583][recorder] do not ignore empty text node during serialization

- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
- test/e2e/scenario/rum/actions.scenario.ts
Since the introduction of frustration signals ([official doc](https://docs.datadoghq.com/real_user_monitoring/frustration_signals/)), we have different action behaviors depending on `trackFrustrations` value:
  | trackFrustrations: false | trackFrustrations: true
-- | -- | --
No action name | No action created | Action created
No activity after click | No action created | Action created
View started after click | No action created | Action created
Additional click while an action is ongoing | No additional action created | Additional action created
We want to promote `trackFrustrations: true` as the only behaviour when tracking user interactions to avoid confusion and maintenance cost.
- Automatically collect frustrations with `trackUserInteractions: true`
- Remove `trackFrustrations` …
> 💥 Promote track frustration as default action behaviour

- packages/rum/BROWSER_SUPPORT.md
Safari and Firefox now support [FCP timing](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming).
Linked to https://github.com/DataDog/browser-sdk/issues/2174
Update BROWSER_SUPPORT.md
Tested on Safari laptop / mobile and Firefox via BrowserStack 
---
> 📝 Update FCP browser support

- developer-extension/src/panel/hooks/useSdkInfos.ts
Navigating to a site with no cookies and opening the developer panel leads to the extension erroring: 
`Datadog Browser SDK extension: [useSdkInfos] Error while getting SDK infos: Error: Failed to evaluate code: TypeError: Cannot read properties of null (reading 'slice')`
Handle the case where `document.cookie === ''` and perhaps other parsing issues.
---
> 🐛 [Extension] Fix TypeError when document.cookie is empty

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- performances/src/main.ts
- test/e2e/scenario/rum/tracing.scenario.ts
Some config parameters have been replaced by new ones
- drop `proxyUrl` in favour of `proxy`
- drop `sampleRate` in favour of `sessionSampleRate`
- drop `allowedTracingOrigins` in favour of `allowedTracingUrls`
- drop `tracingSampleRate` in favour of `traceSampleRate`
- drop `trackInteractions` in favour of `trackUserInteractions`
---
> 💥[RUMF-1554] Drop some deprecated config parameters

- developer-extension/src/panel/hooks/useSdkInfos.ts
- packages/logs/src/boot/logsPublicApi.spec.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- test/e2e/scenario/rum/init.scenario.ts
Housekeeping
- drop `DD_RUM.removeUser` in favour of `DD_RUM.clearUser`
- drop `DD_RUM.addRumGlobalContext` in favour of `DD_RUM.setGlobalContextProperty`
- drop `DD_RUM.removeRumGlobalContext` in favour of `DD_RUM.removeGlobalContextProperty`
- drop `DD_RUM.getRumGlobalContext` in favour of `DD_RUM.getGlobalContext`
- drop `DD_RUM.setRumGlobalContext` in favour of `DD_RUM.setGlobalContext`
- drop `DD_LOGS.addLoggerGlobalContext` in favour of `DD_LOGS.setGlobalContextProperty`
- drop `DD_LOGS.removeLoggerGlobalContext` in favour of `DD_LOGS.removeGlobalContextProperty`
- drop `DD_LOGS.getLoggerGlobalContext` in favour of `DD_LOGS.getGlobalContext`
- drop `DD_LOGS.setLoggerGlobalContext` in favour of `DD_LOGS.setGlobalContext`
--- …
> 💥 [RUMF-1554] Drop some deprecated public APIs

- developer-extension/src/panel/components/alert.tsx
- developer-extension/src/panel/components/app.tsx
- developer-extension/src/panel/components/columns.tsx
- developer-extension/src/panel/components/panel.tsx
- developer-extension/src/panel/components/tabBase.tsx
- developer-extension/src/panel/components/tabs/replayTab.tsx
- developer-extension/src/panel/sessionReplayPlayer/startSessionReplayPlayer.ts
- developer-extension/src/panel/sessionReplayPlayer/types.ts
Help Browser SDK users to tweak the integration by having a preview of how their website looks like via session replay.
Help Browser SDK developers investigate session replay rendering issues
---
> ✨ [devext] add a live replay tab

- packages/core/src/tools/experimentalFeatures.ts
- packages/core/src/tools/valueHistory.spec.ts
- packages/core/src/tools/valueHistory.ts
- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
- packages/rum-core/src/domain/contexts/pageStateHistory.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/test/testSetupBuilder.ts
Modern browsers today will sometimes suspend pages or discard them entirely when system resources are constrained, which can lead to unexpected behaviors. The [Page Lifecycle API](https://developer.chrome.com/blog/page-lifecycle-api/), provides lifecycle hooks so we can detect and handle these browser interventions.
This PR, collect page lifecycle state changes during a view to help Browser SDK issue investigations.
- Value history findAll accepts a duration
- Add maxEntries limit to valueHistory
- Use valueHistory in pageSateHistory
- Collect page states changes during views
- Limit the number of page states collected per view
---
> 🔊 [RUMF-1577] Collect page lifecycle states

- developer-extension/src/content-scripts/isolated.ts
Each time the extension is open, a new `isolated content script` is executed in the page. Each isolated content script transmit sdk messages to the background script, so if we two scripts are active at the same time, duplicated sdk messages are sent.
This addresses the issue by unregistering previous isolated script logic. Luckily, all isolated scripts share the same "window" scope.
---
> 🐛 [devext] unregister isolated content script listener

- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- packages/rum-core/src/domain/rumSessionManager.ts
- packages/rum-core/test/mockRumSessionManager.ts
- packages/rum-core/test/testSetupBuilder.ts
Drop deprecated parameters in favour of `sessionReplaySampleRate`
- Remove `premiumSampleRate` and `replaySampleRate`
- Remove old plans behaviour
---
> 💥 [RUMF-1587] Remove `premiumSampleRate` and `replaySampleRate`

- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- test/e2e/lib/framework/createTest.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
Have a more predictable default session replay sampling rate and target privacy by default to mitigate potential privacy concerns with the auto-start functionality.
- update default `sessionReplaySampleRate` from `100` to `0`
- update default `defaultPrivacyLevel` from `MASK_USER_INPUT` to `MASK`
---
> 💥 [RUMF-1588] Update default session replay behaviour

- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
Allow to collect stack of telemetry errors in staging and canary environments 🤦‍♂️
Allow staging and canary domains
---
> 🐛 Telemetry: do not scrub staging and canary frames

- packages/core/src/tools/serialisation/contextManager.spec.ts
- packages/core/src/tools/serialisation/contextManager.ts
- packages/logs/src/domain/logger.ts
- packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
- packages/rum-core/src/domain/startCustomerDataTelemetry.ts
Ensure that input/output of `ContextManager` internal component can't be mutated by API user
Replace internal usages:
- `get` -> `getContext`
- `set` -> `setContext`
- `add` -> `setContextProperty`
- `remove` -> `removeContextProperty`
---
> ♻️ [RUMF-1555] Remove deprecated context manager APIs

- packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
- packages/rum-core/src/domainContext.types.ts
- packages/rum/src/domain/record/observers/frustrationObserver.spec.ts
Housekeeping
In action domain context, cf [before send event contexts](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#context), drop `event` in favour of `events`.
---
> 💥 [RUMF-1555] Remove `event` in action domain context

- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/logger.ts
Consistency with other context APIs, cf https://github.com/DataDog/browser-sdk/pull/1641
- rename `logger.addContext` in `logger.setContextProperty`
- rename `logger.removeContext` in `logger.removeContextProperty`
- introduce `logger.clearContext` to clear logger context
---
> 💥 [RUMF-1555] Rework logger context APIs

- packages/core/src/domain/console/consoleObservable.spec.ts
- packages/core/src/domain/console/consoleObservable.ts
- test/e2e/scenario/logs.scenario.ts
- test/e2e/scenario/rum/errors.scenario.ts
The console error prefix was meant to be able to sort console error amongst other logs. Now that error.origin convey this information, we can remove the prefix.
Remove console error prefix 
---
> 💥[RUMF-1228] Remove console error message prefix

- packages/logs/src/boot/startLogs.ts
- packages/logs/src/domain/assembly.spec.ts
- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/logger.ts
- packages/logs/src/domain/logsCollection/console/consoleCollection.spec.ts
- packages/logs/src/domain/logsCollection/console/consoleCollection.ts
- packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.ts
- packages/logs/src/domain/logsCollection/report/reportCollection.spec.ts
- packages/logs/src/domain/logsCollection/report/reportCollection.ts
- packages/logs/src/domain/logsCollection/runtimeError/runtimeErrorCollection.spec.ts
- packages/logs/src/domain/logsCollection/runtimeError/runtimeErrorCollection.ts
- packages/logs/src/logsEvent.types.ts
- packages/logs/src/rawLogsEvent.types.ts
- test/e2e/scenario/logs.scenario.ts
Since the introduction of the `origin` attribute on all logs, `error.origin` is redundant.
- Drop logs `error.origin` attribute in favour of `origin` attribute.
- Improve logs types
---
> 💥[RUMF-1229] Logs: remove `error.origin` attribute

- renovate.json
Avoid to have PR for single package update:
- puppeteer could be updated with other packages
- ajv and ansi regex are waiting on major updates and minor updates for our versions seem unlikely
Remove excluded packages from `all non-major dependencies` updates
---
> 👷[Renovate] remove exclusion from all non major

- package.json
- packages/core/src/domain/report/browser.types.ts
- packages/core/src/domain/report/reportObservable.spec.ts
- packages/core/src/domain/report/reportObservable.ts
- packages/core/test/emulate/stubReportApis.ts
- yarn.lock
TypeScript 5.1 introduced `ReportingObserver` in `lib.dom.d.ts`. 
Removed locally declared types around `ReportingObserver`, affecting `reportObservable.ts`
---
> 👷 Update TypeScript to 5.1.3

- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
Some customers have privacy concerns about the PII potentially being collected by session replay and they want a way to ensure their usage complies with their policies. Because they can have multiple applications operated by different teams they want a central way to monitor their replay privacy level configured in their Browser RUM SDK. 
Collect replay privacy level in views
---
> ✨ Collect replay privacy level in views

- packages/logs/src/boot/logsPublicApi.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/boot/startLogs.ts
- packages/logs/src/domain/assembly.spec.ts
- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/lifeCycle.ts
- packages/logs/src/domain/logsCollection/logger/loggerCollection.spec.ts
- packages/logs/src/domain/logsCollection/logger/loggerCollection.ts
Main logger (`DD_LOGS.logger`) context and level impact logs generated by console, report, network error and runtime error which can lead to surprising behaviour. 
- 💥 add main logger context only to main logger logs
- 💥 apply main logger level only to main logger logs
- ♻️ merge logger context with message context in logger collection
---
> 💥[RUMF-1230] Only apply main logger configuration to its own logs

- packages/logs/src/domain/assembly.spec.ts
- packages/logs/src/domain/configuration.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/configuration.ts
- test/e2e/scenario/logs.scenario.ts
- test/e2e/scenario/rum/init.scenario.ts
Avoid confusing return type for `beforeSend`, cf https://github.com/DataDog/browser-sdk/issues/1605
```diff
- beforeSend(event: any, context?: any) => boolean | void
+ beforeSend(event: any, context?: any) => boolean
```
**Nb:** No change on the implementation, if no value is returned, the event is **not** discarded. 
---
> 💥 [RUMF-1556] Typings: consistent beforeSend return type

- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/index.ts
- packages/core/src/domain/configuration/intakeSites.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
- packages/core/src/index.ts
- packages/core/src/transport/httpRequest.ts
- packages/core/src/transport/sendWithRetryStrategy.ts
Similarly to mobile SDKs, use subdomain-less intake domains for all products, cf [supported endpoints doc](https://docs.datadoghq.com/real_user_monitoring/#supported-endpoints-for-sdk-domains). 
For us1 site:
```diff
- https://(rum|logs|session-replay).browser-intake-datadoghq.com/
+ https://browser-intake-datadoghq.com/
```
and similarly for other sites.
---
> 💥[RUMF-1564] remove intake subdomains

- packages/rum/src/domain/record/observers/inputObserver.spec.ts
- packages/rum/src/domain/record/observers/inputObserver.ts
- packages/rum/src/domain/record/shadowRootsController.ts
Following the release of Shadow DOM support for Session Replay (#1969), users started to notice important performance regression on applications using session replay.
The identified issue was that we instrumented input Node property setters like `input.value` or `input.checked` multiple times (once per Shadow Root). Those instrumentations are stacking up, making a significant overhead when the application set those properties.
Do not instrument setters when handling shadow roots.
Before:
After:
---
> 🐛 [RUMF-1613] fix session replay performance regression

- packages/core/src/tools/utils/urlPolyfill.spec.ts
- packages/core/src/tools/utils/urlPolyfill.ts
On Firefox window.location.origin is "null" for file: URIs, making our url normalisation fail.
(cf: https://bugzilla.mozilla.org/show_bug.cgi?id=878297)
Update getLinkElementOrigin to handle "null" case
---
> 🐛 [RUM-231] Fix location.origin is "null" for file: URIs

- packages/core/src/tools/serialisation/heavyCustomerDataWarning.spec.ts
- packages/core/src/tools/serialisation/heavyCustomerDataWarning.ts
When passing a large amount of data in global context, user info or feature flags (>3KiB) the browser SDK prints a warning. The warning was confusing and brought lot of question for customers.
Before 
> The user data is over 3KiB. On low connectivity, the SDK has the potential to exhaust the user's upload bandwidth.  
After
> The user data exceeds the recommended 3KiB threshold. More details: https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#customer-data-exceeds-the-recommended-3kib-warning
---
> 💬 [RUMF-1605] Improve heavy customer data warning message

- CHANGELOG.md
- developer-extension/package.json
- lerna.json
- packages/core/package.json
- packages/logs/package.json
- packages/rum-core/package.json
- packages/rum-slim/package.json
- packages/rum/package.json
- performances/package.json
- test/app/yarn.lock
- yarn.lock
In order to have backend behaviour corresponding to v5 SDK, use a 5.x.x version
Create a lerna premajor release
---
> 👷 Bump version to v5.0.0-alpha.0

- packages/core/src/domain/tracekit/tracekit.ts
Since https://github.com/DataDog/browser-sdk/pull/2181 the tracekit message parsing can fail:
Add tracekit try parse message failing telemetry 
---
> 🔊 Add tracekit try parse message failing telemetry

- packages/rum-slim/.npmignore
`/bundle/datadog-rum-slim.js` is missing from RUM slim npm package.
https://github.com/DataDog/browser-sdk/issues/2320
Don't ignore `datadog-rum-slim.js` in .npmignore
---
> 🐛 Fix RUM slim npm package publication

- packages/worker/.npmignore
- packages/worker/scripts/build-worker-string.js
- packages/worker/string/package.json
#2330
* export cjs, esm and types for the /string package
* unignore built files
---
> 👷 [RUM-232] fix worker/string package

- packages/core/src/domain/tracekit/tracekit.spec.ts
- packages/core/src/domain/tracekit/tracekit.ts
The tracekit error message parsing fails when the message contains new lines (\n)
Update the tracekit `ERROR_TYPES_RE` regex to handle new lines.
---
> 🐛 [RUM-238] Handle tracekit multilines message parsing

- packages/logs/src/boot/startLogs.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum/src/boot/startRecording.ts
Have an idea on how frequently we are reporting SDK errors to customers.
For now, we only report when:
- an event limiter threshold is reached
- retry strategy queue was full
Send telemetry debug when reporting an error
---
> 🔉 monitor reported errors

- lerna.json
- packages/core/package.json
- packages/logs/package.json
- packages/rum-core/package.json
- packages/rum-slim/package.json
- packages/rum/package.json
- packages/worker/package.json
When publishing for the first time a scope package, npm assumes the access is private by default and we end up the error
`Package failed to publish. You must sign up for private packages`. 
Specify the publish access `public` in package.json for all published packages 
---
> 👷 Fix scope packages npm publication

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/testSetupBuilder.ts
This PR adds the following fields to all RUM events:
* `@_dd.configuration.session_sample_rate`
* `@_dd.configuration.session_replay_sample_rate`
Those fields are private and should not be used by customers. They will reflect the corresponding initialization parameter values.
See related rum-events-format PR: https://github.com/DataDog/rum-events-format/pull/153 
* update format
* add fields
---
> ✨ [RUM-235] add sample rates fields

- packages/core/src/tools/serialisation/contextManager.spec.ts
- packages/core/src/tools/serialisation/contextManager.ts
Telemetry errors `Cannot convert undefined or null to object` in [rum assembly](https://github.com/DataDog/browser-sdk/blob/c9ec11d/packages/rum-core/src/domain/assembly.ts#L171)
If `setXXXContext()` is called with a non-object value, defaults context value to `{}`
---
> 🐛 Avoid setting non-object values for contexts

- test/app/yarn.lock
- yarn.lock
Dependabot alerts:
``` 
Versions of the package semver before 7.5.2 on the 7.x branch, before 6.3.1 on the 6.x branch, 
and all other versions before 5.7.2 are vulnerable to Regular Expression Denial of Service (ReDoS) 
via the function new Range, when untrusted user data is provided as a range.
```
Update resolutions to `5.7.2`, `6.3.1` and `7.5.2`
---
> 👷 Bump semver resolutions

- scripts/lib/build-env.js
In canary environment, the SDK version (`X.Y.Z+hash`) is not well supported by the backend since:
- [tags don't support](https://docs.datadoghq.com/getting_started/tagging/#define-tags) the `+` character and they are replace by `_`
- version are parsed using [semver regex](https://regex101.com/r/Ly7O1x/3/) that don't support the `_` character
In canary environment, send the hash with the version using the prerelease separator instead of the build separator:
```diff
- X.Y.Z+hash
+ X.Y.Z-hash
```
---
> 👷Use SDK version format supported by backend

- .prettierignore
Lerna format files using prettier. Somehow since we upgrade to prettier v3 yarn.lock is no longer ignored and `yarn lerna version` craches 
Add yarn.lock to prettierignore
---
> 🐛 Fix release script by adding yarn.lock to prettierignore

- scripts/release/check-release.js
Since https://github.com/DataDog/browser-sdk/pull/2337, browser logs and rum have been added as workspace dependencies which makes check-release fail.
Ignore workspace dependencies in check-release 
---
> 🐛 Ignore workspace dependencies in check-release 

- developer-extension/src/common/constants.ts
- developer-extension/src/panel/components/panel.tsx
- developer-extension/src/panel/monitoring.ts
On the extension monitoring, differentiate collected events by tab
track views manually and consider each tab as a different view
---
> 👷 [Extension][Monitoring] track views manually and consider each tab as a different view

- packages/rum-core/src/domain/rumEventsCollection/action/getSelectorFromElement.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/getSelectorFromElement.ts
- packages/rum/src/domain/record/observers/inputObserver.ts
From the telemetry, several errors like:
Failed to execute 'querySelectorAll' on {*}: {*} is not a valid selector.
Add some extra escaping
---
> 🐛[RUM-142] fix the generation of some invalid selectors

- packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
Remove scrollmap experimental flag
All customers will now send scroll data by default
---
> Remove scrollmap experimental flag

- packages/core/src/index.ts
- packages/core/src/transport/batch.ts
- packages/core/src/transport/index.ts
- packages/core/src/transport/startBatchWithReplica.spec.ts
- packages/core/src/transport/startBatchWithReplica.ts
- packages/logs/src/boot/startLogs.ts
- packages/logs/src/transport/startLogsBatch.ts
- packages/rum-core/src/transport/startRumBatch.ts
Currently, we create Batch instances in two places: `startBatchWithReplica` and `startRumBatch`. As I'm planning to change how Batch works, in order to avoid repeating myself, this PR factorize the two functions.
* add missing features to `startBatchWithReplica` (upsert + transform replica message)
* use `startBatchWithReplica` in `startRumBatch`
* add some tests around `startBatchWithReplica`
---
> ♻️ [RUM-253] refactor batch creation

- .gitlab-ci.yml
In order to share SDK changes, it can be a bit restrictive to regularly merge to staging or to merge in main.
Add an optional deploy step on feature branches to upload a sdk file on the staging environment.
Exemple:
SUFFIX: prerelease-v5
generates on the staging CDN:
- /datadog-rum-prerelease-v5.js
- /datadog-logs-prerelease-v5.js
- ...
---
> 👷 CI: add a deploy feature job

- .gitlab-ci.yml
More and more orgs are using `https://www.datadoghq-browser-agent.com/eu1/*`. Deploy bundles there separately from other DC.
Add a separate step to deploy to EU1
---
> 👷 add a separate step to deploy to EU1

- packages/rum/src/domain/record/serialization/serializeAttributes.spec.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.ts
We follow @import rules and inline their content so the player can uses its strategy to emulate :hover states. But if the external stylesheet is inaccessible, we should still take the @import rule into account, so the external stylesheet can be loaded in the player.
If we fail to get the external stylesheet rule, use the `@import` rule cssText as a fallback
---
> 🐛 do not ignore @import rules pointing to inaccessible stylesheets

- packages/rum-core/src/domain/rumEventsCollection/view/viewMetrics/trackInteractionToNextPaint.ts
On Firefox 88, `PerformanceObserver.supportedEntryTypes` includes `'event'`, but `PerformanceEventTiming` is not implemented.
Test in `PerformanceEventTiming` exists before using it.
---
> 🐛 fix INP support detection

- packages/rum/src/domain/record/privacy.ts
- packages/rum/src/domain/record/serialization/htmlAst.specHelper.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
See #2380. When a website uses a non-empty `<style>` element, edits it with `insertRule` or `deleteRule`, and then starts recording with `startSessionReplayRecording()`, changes made to the style are lost. Example:
>  Let's assume the page contains this piece of HTML:
> ```html
> <style>
> body { color: red }
> </style>
> ```
> If a script is modifying the <style> state:
> ```js
> document.querySelector('style').sheet.insertRule('body { font-size: 10px }')
> ```
>
> And only then we are taking a full snapshot
> ```js
> DD_RUM.startSessionReplayRecording()
> ```
> The inserted rule will be ignored during serialization. The <style> will be serialized like this:
> ```js
> {
>   type: NodeType.Element,
>   tagName: 'style',
>   attributes: {},
>   childNodes: [{
>     type: NodeType.Text,
> …
```
> 🐛 fix dynamic style serialization

- packages/core/src/domain/telemetry/rawTelemetryEvent.types.ts
- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/logs/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
From past instigation we've seen that some customers initialize the SDK from a worker using partytown. This generates telemetry errors hard to troubleshoot. This PR add env information to help:
```js
{
runtime_env: {
is_local_file: isLocalFile(),
is_worker: isWorker(),
}
}
```
Add isLocalFile and isWorker to telemetry debugs and errors
---
> 🔈 Add env information in telemetry

- .gitlab-ci.yml
- test/e2e/scenario/recorder/shadowDom.scenario.ts
The test `recorder with shadow DOM can record click with target from inside the shadow root` was failing very often on Firefox. It's output is hard to read.
* Improve e2e output readability by forcing colors
* Fix e2e test by selecting the "click" record (in some cases, a "focus" record was selected by mistake)
Before:
With improved output, it should look like this:
---
> ✅ fix flaky e2e test on firefox

- .gitlab-ci.yml
CI image bump of https://github.com/DataDog/browser-sdk/pull/2356 has been overridden by another change, so zip library is missing.
Bump ci image
---
> 👷 Bump image version for extension publication

- packages/logs/src/boot/logsPublicApi.spec.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
telemetry errors are generated when SDK init are called without configuration.
When no init configuration is provided:
- display error message
- early exit
---
> ✨ [RUM-1013] early exit when no configuration provided

- packages/core/test/leakDetection.ts
It appears that on some occasions, event listeners are called outside of specs, and the leak detection breaks
Make sure the current jasmine spec is defined before using it
---
> ✅🐛 don't blow up tests when leak detection triggers outside of a spec

- LICENSE-3rdparty.csv
- developer-extension/package.json
- developer-extension/src/panel/components/app.tsx
- developer-extension/src/panel/components/json.tsx
- developer-extension/src/panel/components/lazyCollapse.tsx
- developer-extension/src/panel/components/tabs/eventsTab/eventRow.tsx
- developer-extension/src/panel/components/tabs/infosTab.tsx
- developer-extension/src/panel/formatNumber.ts
- yarn.lock
The current JSON rendering component that we use does not allow to display a proper event description. Also it is a bit limited for future extensions.
Implement a new Json component and a better event description similar to the Datadog app
---
> ✨ [extension] revamp event description and JSON viz

- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
- packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
- packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
- packages/rum-core/test/fixtures.ts
After introducing` createPerformanceEntry()` fixture builder  ([PR](https://github.com/DataDog/browser-sdk/pull/2418)). Let's use it with all tests playing with performance entries.
Update tests:
---
> ♻️ Use performance entry fixtures in tests

- packages/rum/src/boot/recorderApi.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.ts
In the coming PR, we'll want to start the deflate worker from different places (according to a
experimental flag/configuration option). The current error message mentioning "Session Replay" is
not adequate anymore.
This PR add the ability to adjust the error message.
---
> 🔊 [RUM-253] customize deflate worker failure logs

- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/transport/httpRequest.ts
- packages/core/test/requests.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
- packages/rum/src/boot/recorderApi.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.ts
We'll need to send the encoding as a new intake URL parameter.
- Light refactoring
- Add the ability to set the encoding through "payload" objects.
---
> ♻️ [RUM-253] adapt transport to send encoded data

- packages/core/src/tools/display.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.spec.ts
- test/e2e/scenario/rum/init.scenario.ts
Mentioning that the message come from the Datadog Browser SDK could help users figure out what's wrong, especially when they are using multiple RUM SDKs at the same time.
See https://github.com/DataDog/browser-sdk/pull/2414#discussion_r1317323659
Add a `Datadog Browser SDK:` prefix to all messages displayed by the SDK.
---
> ✨ [RUM-1062] add a prefix to all console message displayed by the SDK

- packages/rum-core/src/domain/view/trackViewEventCounts.spec.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCommonViewMetrics.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.spec.ts
Following the [view metrics splitting](https://github.com/DataDog/browser-sdk/pull/2386), this PR reorganize the view tracking tests so that every spec files tests its related module.
- Cleanly stop INP tests
- Move CLS support check in trackCommonViewMetrics module
- Scope trackCumulativeLayoutShift tests
- Scope trackLoadingTime tests
- Scope trackViewEventCounts tests
- Reorganize trackViews tests
---
> ♻️ [RUM-1039] Harmonize view tests

- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Changed Reference implementation from src/getLCP.ts to src/onLCP.ts
corrects an incorrect link referencing the implementation 
changes the lcp reference implementation from src/getLCP.ts to src/onLCP.ts
> update reference implementation url in trackLargestContentfulPaint.ts

- packages/core/src/domain/session/sessionStoreOperations.spec.ts
- packages/core/src/domain/session/sessionStoreOperations.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
- packages/core/src/domain/session/storeStrategies/sessionStoreStrategy.ts
Our lock mechanism does not work with Local Storage, as we have observed a latency with the replication of the data between several tabs. 
It is safer to remove it, as there is a risk to that the browser stops while the lock is set, preventing future events from being sent.
- Move the lock eligibility to storage strategy
- Make Local Storage never eligible for the lock mechanism
---
> [RUM-1085] Remove lock usage from Local Storage strategy

- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/formatValidation.ts
During #2180 we introduced a few View event fields to track scroll. The implementation had a few shortcomings addressed in #2399, which changed how some of those fields were computed. This PR rename the fields to be more explicit.
* Improve validation error during unit test
* Update rum-events-format (see https://github.com/DataDog/rum-events-format/pull/163)
* Rename the fields:
* `maxDepthTime` -> `maxScrollHeightTime`
* `maxDepthScrollHeight` -> `maxScrollHeight`
---
> ♻️ rename scroll fields

- developer-extension/src/panel/sessionReplayPlayer/types.ts
- packages/rum-core/src/domain/action/computeFrustration.spec.ts
- packages/rum-core/src/domain/action/getActionNameFromElement.spec.ts
- packages/rum-core/src/domain/getSelectorFromElement.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
- packages/rum-core/test/dom.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/record/observers/inputObserver.spec.ts
- packages/rum/src/domain/record/observers/mouseInteractionObserver.spec.ts
- packages/rum/src/domain/record/observers/mutationObserver.spec.ts
- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
After introducing `appendElement` to ease DOM manipulation in our tests (cf [PR](https://github.com/DataDog/browser-sdk/pull/2418)), let generalise its usage.
- IsolatedDom is not isolated anymore (remove the iframe usage)
- Replace appendElement by append (we can also append text nodes)
- Replace isolatedDom by append
- Update sandbox pattern with append
---
> ♻️ [RUM-1051] Harmonize DOM manipulation in tests

- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
There are some INP outliers that can exceed a day. Let's collect all the RumPerformanceEventTiming info to see if there is a issue on our side or on the browser API side.
Collect telemetry on INP exceeding 10 min
---
>  🔊 Add INP telemetry

- packages/core/src/domain/tracekit/computeStackTrace.spec.ts
- packages/core/src/tools/utils/browserDetection.ts
- packages/core/test/browserChecks.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.spec.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.ts
Safari does not escape colons in CSS selector Text ( such as [ng:cloak] ).
This causes issues during session replay, as the styles are not applied. 
https://bugs.webkit.org/show_bug.cgi?id=184604
https://github.com/rrweb-io/rrweb/pull/1253
When a CSS rule selector contains a colon, ensure it is escaped.
Record a page containing selectors with a colon using Safari. Check that the display is as expected in Session Replay.
---
> 🐛 [RUM-1196] Escape CSS rules containing a colon for Safari compatibility

- packages/rum-core/src/browser/htmlDomUtils.spec.ts
- packages/rum-core/src/browser/htmlDomUtils.ts
- packages/rum/src/domain/record/observers/mutationObserver.spec.ts
- packages/rum/src/domain/record/observers/mutationObserver.ts
See https://github.com/DataDog/browser-sdk/issues/2424
When a node was removed from the DOM, we traverse all of its children to look for Shadow Roots to clean them up from the Shadow Root Controller. The traversing implementation had an issue and skipped some children.
I also noticed a small simplification opportunity to check whether an element is in the DOM by using `isConnected`.
---
> 🐛 [RUM-1325] fix memory leak when using shadow dom 

- packages/core/src/domain/error/error.types.ts
- scripts/cli
https://github.com/DataDog/browser-sdk/issues/2442
* Omit the 'cause' property to avoid compatiblity issues.
* We don't check TS 4.6 or 4.7 compatibility specifically, so this exact issue is not covered. I don't think we need to add compatibility checks for these specific versions, but I changed the "latest" compatibility check to include the "esnext" lib, so in the future we'll detect incompatibilities with newly introduced TS types sooner.
---
> [RUM-1211] fix compatibility with TS4.6/4.7 using ES2022

- packages/rum-core/src/domain/view/viewMetrics/trackCommonViewMetrics.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
To identify if some of the PerformanceEventTiming contributing to the view INP start before the view start, let's collect the duration between the view start and the interaction start.
Add timeFromViewStart in INP telemetry
---
> 🔊 Update INP telemetry

- packages/rum-core/src/browser/htmlDomUtils.spec.ts
- packages/rum-core/src/browser/htmlDomUtils.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
Setting a privacy attribute directly on a shadow host element does not propagate the privacy to its children.
Factorize the way we serialize "normal" children with the way we serialize shadow roots.
Before:
After:
---
> 🐛 propagate privacy defined on shadow hosts

- test/e2e/scenario/eventBridge.scenario.ts
Consistent failure on this test on firefox since the action behaviour update
Wait for the click chain timeout before flusing
---
> 🐛 bridge action e2e: wait for click chain timeout

- .gitlab-ci.yml
Since adoption will be low at first, avoid to have many unnecessary deploy steps
Split CDN deployment in two:
- us3,us5,ap1,eu1,us1
- gov (keep it always at the end)
---
> 👷 [RUM-1026] Regroup deployment steps

- packages/rum-core/src/domain/getSelectorFromElement.ts
Telemetry errors where an element don't have parent during selector computation:
It seems to only occur during web vital attribution. 
Add debug log with:
- selector of the element without parent
- element isConnected value
---
> 🔊 [RUM-1561] Add monitoring on selector from element without parent

- scripts/deploy/upload-source-maps.js
With v5, upload source maps is broken for root files
- Keep uploading source maps for all datacenter (just in case) 
- Since we could live with the root files for quite some time, don't rely on specific version anymore
On next release
---
> 👷 Fix upload source maps for root files

- packages/rum-core/src/domain/view/trackViews.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCommonViewMetrics.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
Fix 2 issues about INP:
- Some of the [PerformanceEventTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming) duration are outliers. So now we CAP INP values to 1 min maximum.
- Some of the [PerformanceEventTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming) reported on one view actually started on the previous view. We now attach them to the previous view.
---
> 🐛 [RUM-1360] Cap INP outliers

- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
The CLS target selector is computed  only when the CLS score increases.  It means that by the time the computation happens the target node might have been removed from the DOM making the selector computation fails.
This PR collects telemetry to assess if we could compute the selector each time the target is updated in the current CLS window.
This PR collects:
- The number of time the CLS target is updated in a CLS window
- The computation time of the target selector (`getSelectorFromElement`)
---
> 🔊 Add CLS target selector telemetry

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
- packages/rum/src/types/sessionReplay.ts
Monitor manual/automatic session replay recording usage.
Add extra `_dd.configuration.start_session_replay_recording_manually` field to view events.
---
> 🔉 [RUM-1658] Add extra field to identify sessions recorded manually

- renovate.json
Prevent renovate from bumping wdio deps while we don't have a workaround for https://github.com/webdriverio/webdriverio/issues/11533
Exclude from non-major deps PRs packages matching `@wdio` or `webdriverio`
on next non-major deps PR
---
> 👷 Exclude wdio from non-major deps PRs

- packages/core/src/tools/utils/browserDetection.spec.ts
- packages/core/src/tools/utils/browserDetection.ts
The fix we introduced in #2440 does not apply in iOS webviews as the user agent don't mention "Safari".
Adjust `isSafari` to also match iOS webviews.
---
> 🐛 [RUM-1863] fix iOS webview detection 

- test/e2e/lib/framework/intakeRegistry.ts
- test/e2e/lib/framework/serverApps/intake.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
- test/e2e/scenario/transport.scenario.ts
Add E2E tests related to RUM data compression
- Light refactoring
- Add E2E tests related to RUM data compression
---
> ✅ [RUM-253] add E2E tests related to compression

- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
Fix #2143, improve performances when `trackResources` is `false` and resources aren't traced.
Don't collect RUM Resource event when `trackResources` is `false` and don't match `allowedTracingUrls`.
---
> 🐛 [RUM-2016] don't collect useless resources events

- packages/core/src/browser/cookie.ts
- packages/core/src/domain/session/oldCookiesMigration.spec.ts
- packages/core/src/domain/session/oldCookiesMigration.ts
- packages/core/src/domain/synthetics/syntheticsWorkerValues.ts
- packages/core/src/tools/utils/stringUtils.spec.ts
- packages/core/src/tools/utils/stringUtils.ts
- packages/core/test/emulate/syntheticsWorkerValues.ts
We observed that the SDK is spending a significant amount of time reading from `document.cookie` during initialization.
Introduce a alternative function to `getCookie` that caches cookies once,  and use it where it makes sense.
---
> ⚡️[RUM-2017] optimize cookie accesses

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/configuration.ts
- test/e2e/scenario/transport.scenario.ts
Depending on how it is used, the Browser SDK can send a lot of data to the Datadog intake. This PR introduce a new `compressIntakeRequests` initialization parameter to allow users to opt-in to request compression. Before using it:
* if you are using the `proxy` initialization parameter, make sure your that your proxy supports binary payloads, regardless of the `Content-Encoding` or `Content-Type` headers
* if you are using `Content-Security-Policy` headers, make sure you allow blob workers (see [doc](https://docs.datadoghq.com/integrations/content_security_policy_logs/?tab=firefox#session-replay-worker))
* follow-up of #2400 , replace the experimental flag with an initialization parameter
---
I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING. …
> ✨ [RUM-253] enable RUM request compression via the `compressIntakeRequests` parameter

- packages/rum-core/src/domain/getSelectorFromElement.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
The CLS target selector is computed only when the CLS score increases. It means that by the time the computation happens the target node might have been removed from the DOM making the selector computation fails.
- Check that the node is attached before computing the CLS CSS selector
- Remove related telemetry
---
> 🐛 [RUM-1561] Fix CLS selector computation on detached node

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
As discussed in #2429 and #2471, the [current proxy strategy](https://docs.datadoghq.com/real_user_monitoring/guide/proxy-rum-data/?tab=npm#proxy-setup) with the `ddforward` parameter, storing the target path and parameters, can be challenging to implement.
A solution allowing to have the path and parameters appended to the provided proxy URL was initially discarded since one of our URL pattern was already blocked, cf [easylist](https://github.com/easylist/easylist/blob/997fb6533c719a015c21723b34e0cedefcc0d83d/easyprivacy/easyprivacy_general.txt#L3840).
However, some customers may want to use a proxy regardless of the privacy blocking or could want to tweak themselves the final proxy url to prevent the blocking.
Allow to pass a function to the `proxy` init parameter:
```ts
init({
... …
```
> ✨[RUM-2158] Allow more flexible proxy URL

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Currently the web vitals are reported with a single value representing the vital score. These scores provide valuable insights to customers, allowing them to determine the performance quality of their website. However, to effectively improve them, it is crucial to identify the specific component to which a vital refers.
Remove `web_vitals_attribution` feature flag
---
> ✨ [RUM-1214] Collect core web vitals target selectors

- .gitlab-ci.yml
Enough customers on us1 to extract a dedicated deploy step
Split `step-1_deploy-prod-all-dcs` into:
- `step-1_deploy-prod-minor-dcs`
- `step-2_deploy-prod-us1`
next release
---
> 👷 extract deploy step for us1

- packages/rum-core/test/allJsonSchemas.d.ts
- packages/rum-core/test/allJsonSchemas.js
- packages/rum-core/test/formatValidation.ts
- test/e2e/lib/helpers/validation.ts
When adding a new JSON schema file, SDK tests are failing because file imports are hardcoded manually.
Ex in this PR: https://github.com/DataDog/rum-events-format/pull/170 (see [this CI job output](https://github.com/DataDog/rum-events-format/actions/runs/6906138216/job/18790474030#step:6:17))
Load JSON schema files dynamically.
* In unit tests, uses webpack `require.context` ([doc](https://webpack.js.org/guides/dependency-management/#requirecontext))
* In e2e tests we can just use Node.js APIs
---
> ✅ import JSON schemas dynamically in tests

- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/shadowRootsController.ts
Shadow Roots need to be instrumented with a `MutationObserver` and an `input` event listener to properly generate incremental snapshots for changes happening inside of them. We do this instrumentation during serialization.
The issue is, when serializing the same Shadow Root multiple times (ex:  when a route_change view is created and a second Full Snapshot is taken), Shadow Roots are instrumented multiple times, so inner incremental snapshots are generated multiple times whenever a single change is done.
Make sure we instrument Shadow Roots only once
---
> 🐛 [RUM-2280] fix duplicated mutations when using Shadow DOM

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
- packages/rum-core/test/fixtures.ts
Collect telemetry on LCP with startTime to 0:
```js
{
entry // the entry reported by the performanceObserver API
previousNonZeroLcp,
navigationStart // check if there is an unexpected navigationStart
timeOrigin // check if there is an unexpected timeOrigin
now: performance.now() // check the diff between now and the entry timings,
visibilityState // check if these reports happens when "hidden" | "visible" | "prerender",
prerendering: document.prerendering,
}
```
Add telemetry on LCP with a startTime at 0
---
> 🔊[RUM-2324] Telemetry on LCP with startTime to 0

- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/intakeSites.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
Allow to use SDK in fed staging environment
Use logs intake domain when site is fed staging
---
> 👷 [RUM-1586] Use logs intake domain for fed staging

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Following https://github.com/DataDog/browser-sdk/pull/2515, some LCP data seemed wrong for other reasons than startTime = 0. 
- collect debug logs for `LCP with startTime < previous LCP`
- collect debug logs for `LCP with size < previous LCP`
- remove some debug data:
-  `visibilityState`: always visible
- `prerendering`: always false
- `navigationStart`: from one case, the value did not really make sense (~30s after timeOrigin) but not sure how reliable it is supposed to be anyway.
- add `lcpEntries` to the debug data, to double check if the implementation difference with google may have an impact
---
> 🔊[RUM-2324] Telemetry on other wrong LCP cases

- packages/core/src/browser/fetchObservable.ts
- packages/core/src/browser/pageExitObservable.ts
- packages/core/src/browser/xhrObservable.ts
- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/report/reportObservable.ts
- packages/core/src/tools/observable.spec.ts
- packages/core/src/tools/observable.ts
- packages/rum-core/src/browser/domMutationObservable.ts
- packages/rum-core/src/browser/locationChangeObservable.ts
- packages/rum-core/src/browser/viewportObservable.ts
- packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.ts
- packages/rum-core/src/domain/waitPageActivityEnd.ts
This is a simple quality of life improvement, but also fixes a typing issue I stumbled upon where TS claimed that the "observable" variable was not well defined when it referred to the outer scope variable (see [example](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwPICNkhgNykwhAB4AVAPngG8AoeRAewDtkAXGAVzDcZgAoWAMQCWMdgGVOmMDBGYQALniDsuAkSUY1+QsXIUAlPAC8Vfv2Nn4eRiODGAPjbsP68ZozYiAZgE9LZVt7WgBfWlofTmYeERZ4AFsoAGsQCUYEkDYACxFmAHMAdREcsmyQLBxdTVUqjWJlSvU9UmZOBIUYIxp3Rh16kAA6T29-SzCI0CQ4eCiY73i89i5M5jYAWSzsxmAAQWZgAGEoCAh0OXy8k4N+KGUyABp4TGV+MHurKmCHZWp4dkYAAdXp8XPZ4KF4BFItFYvFZCAoGwQEIsmBsk1qsQAPrYzCcfKWHoMMAsdjwPp1FqmDwgADu2ipmhIbQ6uAoFlBdAYJLJbBo-14gIhNKWHHaIDWmxyO32RxOZwuVwg-AAjE8idYkql0pkcnkiiVsmUKv0WrVmppDIZ3Aw4GxODBmIKge5Qja7VlHc7KZbiBNoTD5nFnQikSi0RizZpcXS+MlkETufB7d7aQ …
> ♻️ pass the Observable instance to the onFirstSubscribe callback

- README.md
In #2319 we introduced a new NPM package. This PR adds it to the list of NPM packages.
add @datadog/browser-worker package to readme
---
> 📝 add @datadog/browser-worker package to readme

- packages/core/src/browser/fetchObservable.ts
- packages/core/src/browser/xhrObservable.ts
- packages/core/src/domain/error/trackRuntimeError.ts
- packages/core/src/index.ts
- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/instrumentMethod.ts
- packages/rum-core/src/browser/locationChangeObservable.ts
- packages/rum-core/src/domain/waitPageActivityEnd.ts
- packages/rum/src/domain/record/observers/styleSheetObserver.ts
In the process of fixing RUM-211 (some methods are "readonly" and their instrumentation breaks the SDK), I wanted to use the functions to instrument methods in more places. This PR is a step in that direction: it revamps and factorizes our existing intrument methods functions into a single, more easily extendable one.
This PR changes the `instrumentMethodAndCallOriginal` signature to call the intrumentation callback with a [`InstrumentedMethodCall`](https://github.com/DataDog/browser-sdk/blob/cd0ccb17cebd8d54fef0a168bcdcdb30e5a89508/packages/core/src/tools/instrumentMethod.ts#L5-L10) object containing the `target` and `parameters` properties instead of  passing them directly as `this` and function `arguments`.
This new `InstrumentedMethodCall` object also allows to:
* register a "post …
> ♻️ [RUMF-1436] instrument method improvements

- packages/rum/src/boot/recorderApi.spec.ts
- packages/rum/src/boot/recorderApi.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
When restarted quickly, the Session Replay recorder unexpectedly stops.
* Run the following on an instrumented page with active session replay:
```js
DD_RUM.stopSessionReplayRecording()
DD_RUM.startSessionReplayRecording()
```
* Move the cursor a bit
* Look at the replay in Datadog (the issue is not visible in the Developer Extension because the extension receives the records before they are deflate-encoded)
The last cursor movements should be visible
The last cursor movements are missing
This commit makes sure the recorder keeps using the same DeflateEncoder instance when restarted. This ensures the underlying stream (identified by `DeflateEncoderStreamId.REPLAY`) is emitting DeflateWorkerAction with continuous identifiers.
--- …
> 🐛 [RUM-2689] fix recorder crash when restarted quickly

- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-slim/src/boot/stubRecorderApi.ts
- packages/rum-slim/src/entries/main.ts
- packages/rum/src/boot/recorderApi.ts
The goal of this commit is to simplify the rumPublicApi module by using the `recorderApi` directly, without buffering the calls.
This is possible because the recorder api already has logic to support early calls to `start` and `stop`. The `getSessionReplayLink` implementation had to be slightly changed to work similarly to `start` and `stop`.
---
> ♻️ [RUM-2445] do not buffer early recorder API calls

- packages/rum/src/domain/record/serialization/htmlAst.specHelper.ts
- packages/rum/src/domain/record/serialization/serializationUtils.ts
- packages/rum/src/domain/record/serialization/serializeAttribute.spec.ts
- packages/rum/src/domain/record/serialization/serializeAttribute.ts
Default censored image dimension is 1x1 which can cause rendering issue when the image size ratio is used by the browser to display the image.
Generate a censored image from the [natural dimensions](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalWidth) of the image, fallback to rendered dimension if not avialable. 
---
> 🐛[RUM-2752] Replay: generate censored images with custom dimensions

- packages/rum-core/src/boot/rumPublicApi.ts
cf https://github.com/DataDog/browser-sdk/issues/2552, document add timing relative time issue
mention on the API doc that relative time usage is discouraged
---
> 📝 Document addTiming API relative time issue

- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/boot/startRecording.ts
- packages/rum/src/domain/record/observers/observers.ts
- packages/rum/src/domain/record/observers/viewEndObserver.spec.ts
- packages/rum/src/domain/record/observers/viewEndObserver.ts
- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/record.ts
- packages/rum/src/domain/record/startFullSnapshots.spec.ts
- packages/rum/src/domain/record/startFullSnapshots.ts
- packages/rum/src/domain/segmentCollection/segment.spec.ts
- packages/rum/src/domain/segmentCollection/segment.ts
- Move record logic from `startRecording` to the record module
- Move the replay record stats from the `segment` to the `record` module to also work with the webview bridge
- Move viewEnd record generation from `startRecording` to the `record` module
- Collocate fullsnapshot logic in its own `/record/startFullsnapshot` module
- Move the replay record stats from the `segment` to the `record` module to also work with the webview bridge
---
> ♻️ [RUM-2203] Move record logic from startRecording to the record module

- packages/core/src/tools/utils/urlPolyfill.spec.ts
- packages/core/src/tools/utils/urlPolyfill.ts
- test/unit/karma.base.conf.js
Relative URLs are wrongly “normalized”, and those incorrect URL are used:
* to define the `@resource.url` in Resource events, giving a wrong information to customers
* to match the corresponding `PerformanceTiming`, so the SDK fails to find the corresponding timing, so the Resource event lacks detailed timings and size
Fix `normalizeUrl` and remove some unused functions
---
> 🐛 [RUM-2940] fix normalize URL for relative paths

- packages/core/test/leakDetection.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/browser/scroll.spec.ts
- packages/rum/test/readReplayPayload.ts
- scripts/lib/bs-utils.js
- scripts/lib/execution-utils.js
- scripts/test/bs-kill.js
- scripts/test/bs-wrapper.js
- test/browsers.conf.js
- test/e2e/scenario/rum/views.scenario.ts
- test/e2e/wdio.bs.conf.ts
Try to fix consistent `unit:bs` failure
- Bump safari used versions
- Add a script to kill running bs workers while debugging
- Fix listener leak on safari
---
> 👷 Try to improve `unit:bs` stability

- packages/rum/src/domain/record/observers/mutationObserver.ts
- packages/rum/src/domain/record/privacy.spec.ts
- packages/rum/src/domain/record/privacy.ts
A customer reported that `getNodePrivacyLevel` was a big performance bottleneck on their application when the devtools were open. On our side, we didn't observe a huge performance impact caused by this function (with or without devtools open), but still find a way to optimize it, which might help the customer case.
Cache the node privacy level when processing mutations. The cache is local to the `proccessMutations` function so we don't have to implement a complex way to invalidate it. Even with this simple cache, we observed a nice speedup while processing mutations (from ~10ms to ~1.5ms in a specific case on the Datadog App)
---
> ⚡️ [RUM-2917] optimize getNodePrivacyLevel by adding a cache

- .github/dependabot.yml
cf https://github.com/DataDog/browser-sdk/pull/2588, `karma-webpack` update is not working.
Ignore update for now and revisit later
---
> 👷[RUM-3130] ignore karma-webpack updates

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/trackingConsent.spec.ts
- packages/core/src/domain/trackingConsent.ts
- packages/core/src/index.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/logs/src/boot/preStartLogs.spec.ts
- packages/logs/src/boot/preStartLogs.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/boot/startLogs.ts
- packages/logs/src/domain/logsSessionManager.spec.ts
- packages/logs/src/domain/logsSessionManager.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- packages/rum-core/src/domain/rumSessionManager.ts
- test/e2e/scenario/trackingConsent.scenario.ts
Allows starting/stopping data collection based on user consent (ex: regarding to RGPD rules and such).
Related issue: https://github.com/DataDog/browser-sdk/issues/1008
For both RUM and Logs SDKs:
* Introduce a `trackingConsent: "granted"/"not-granted"` initialization parameter (defaults to `"granted"` for backward compatibility)
* Add a `setTrackingConsent` method to set the consent state before or after calling `init()`. If called before `init()`, the initialization parameter will be ignored.
* On init, do not start collecting data until consent is granted
* When the consent is withdrawn, stops the session and clear the cookie. No new session will be created on user interaction.
* This change is behind an experimental flag and should not be used by customers yet.
---
I have gone over …
> ⚗️✨ [RUM-2445] implement Tracking Consent management

- developer-extension/src/panel/components/tabs/eventsTab/eventRow.tsx
- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/trackEventCounts.spec.ts
- packages/rum-core/src/domain/trackEventCounts.ts
- packages/rum-core/src/domain/vital/vitalCollection.spec.ts
- packages/rum-core/src/domain/vital/vitalCollection.ts
- packages/rum-core/src/domainContext.types.ts
- packages/rum-core/src/index.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
- packages/rum/src/entries/main.ts
- test/e2e/lib/framework/intakeRegistry.ts
- test/e2e/scenario/rum/vitals.scenario.ts
Initial PR to provide APIs to track custom duration as vital events
Behind `custom_vitals` flag, add APIs:
```js
DD_RUM.startDurationVital('foo')
// do some stuff
DD_RUM.stopDurationVital('foo')
```
and support the new event type across the code base:
**Note:** First PR with the simplest API, more features in following PRs (customer context, rate limiter, ...)
---
> ⚗️[RUM-2889] Bootstrap custom vital APIs

- .github/dependabot.yml
- renovate.json
karma-webpack introduced a breaking change in v5.0.1 that breaks our test suite: https://github.com/codymikol/karma-webpack/issues/587
Ignore karma-webpack in renovate (for dependabot, it was done in https://github.com/DataDog/browser-sdk/pull/2592 )
---
> 🔧 ignore karma-webpack for now

- .gitignore
- .gitlab-ci.yml
- scripts/export-bundles-sizes.js
- scripts/lib/browser-sdk-version.js
- scripts/lib/build-env.js
- scripts/lib/execution-utils.js
- scripts/release/generate-changelog.js
- scripts/release/update-peer-dependency-versions.js
To send bundle sizes to logs and check the evolution with dashboard.
Added a script to retrieve git commit Id, version, branch and bundle size then send them to logs with fetch request.
---
> ✨[RUM-3151] Report bundle sizes to logs

- packages/rum-core/src/domain/vital/vitalCollection.spec.ts
- packages/rum-core/src/domain/vital/vitalCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
- test/e2e/scenario/rum/vitals.scenario.ts
Collect `vital.name` attribute
- bump schema
- add `vital.name` attribute
---
> ⚗️[RUM-3235] collect vital.name attribute

- yarn.lock
This PR addresses this reported security issue https://github.com/DataDog/browser-sdk/security/dependabot/73 found in the [ip package](https://www.npmjs.com/package/ip)
- Bump `socks` to `2.8.0` that doesn't use ip
- Bump `pac-resolver` to `7.0.1` that doesn't use ip
---
> 👷 Fix ip package vulnerability by bumping dependant packages

- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/trackingConsent.spec.ts
- packages/core/src/domain/trackingConsent.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/logs/src/boot/preStartLogs.spec.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- test/e2e/scenario/trackingConsent.scenario.ts
This PR publicly exposes the API introduced in #2589 
Remove the `tracking_consent` experimental flag.
---
> ✨ [RUM-3349] introduce a Consent Management API

- renovate.json
This should fix the issue we have with every single "update all non-major dependencies" regarding `@types/react` ending with different versions and failing the build.
It will also make installing dependencies a bit faster since it won't have to download as many versions as before. 
I chose the "highest" strategy (instead of "fewest"), because:
* let's try to be as much up-to-date as possible
* renovate will use the official `yarn dedupe` instead of a third party package
---
> 🔧 configure renovate to deduplicate subdependencies

- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/instrumentMethod.ts
- test/e2e/scenario/rum/tracing.scenario.ts
When running `fetch(url)`, the request is missing tracing headers, no matter the initialization parameters used.
This is a regression from https://github.com/DataDog/browser-sdk/pull/2551
`parameters` was directly the [`arguments`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Functions/arguments) object from the function call. It turns out adding an entry to this kind of array does not work.
To fix this issue, convert the `arguments` to an actual array.
---
> 🐛 [RUM-3502] fix `fetch(url)` tracing

- .eslintrc.js
Events generated by the SDK should have snake_case properties but nothing is checking it.
Add an eslint rule to check snake_case in `**/*Event.types.ts`
---
> 🔧 Enforce snake case for event type properties

- scripts/report-bundle-size/report-as-a-pr-comment.js
We want to have a more precise indication of the difference change. 
Added a threshold based on previous PR values, to set a status. If the value is below 5 % then the status is ✅ otherwise the status is a warning and message appear at the end of the Pr Commenter.
---
> ✨ [RUM-3495] Add Pr Commenter Threshold

- packages/rum-core/src/browser/htmlDomUtils.ts
It was suggesting that we could improve the performance of the child node iteration by using a more efficient method.
This [benchmark](https://measurethat.net/Benchmarks/Show/15720/0/fastest-way-to-list-children-childnodes-vs-children-vs) suggest that using `nextSibling` is 5 times faster than using `childNodes.forEach`.
In reality the improvement is not so significant for our use case (see below), however the change is pretty small and safe so it's can't hurt to implement.
Refactor `forEachChildNodes()` to use `nextSibling` instead of `childNodes.forEach`.
I've ran some benchmarks locally to get numbers that matches better our use-case.
- ran the benchmark on https://app.datadoghq.com
- measure the time it takes to make a full session replay recording
results:
| | `childNodes.forEach` | …
> ⚡ [RUM-2633] Optimize DOM iteration in the recorder

- LICENSE-3rdparty.csv
- package.json
- scripts/deploy/check-monitors.js
- scripts/lib/bs-utils.js
- scripts/lib/execution-utils.js
- scripts/report-bundle-size/report-as-a-pr-comment.js
- scripts/report-bundle-size/report-to-datadog.js
- scripts/test/bump-chrome-version.js
- yarn.lock
Inside ci scripts, mixed usage of native fetch and fetchWrapper as fetch with different APIs.
- 🔥 remove node-fetch dependency, native fetch introduced in node 18
- ♻️ rework fetchWrapper, now exported as `fetchHandlingError` and letting the caller handle the response
---
> 👷 Rework fetch usages in ci scripts

- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/intakeSites.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
Requests to PCI compliant endpoint are captured by RUM as resources, while they shouldn't be.
RUM initialisation doesn't have access to Logs config. Thus, PCI endpoint requests are not skipped and are captured as RUM resources.
When the provided site is `datadoghq.com`, push PCI intake url to the intake prefixes used to ignore resources 
---
> 🐛 [RUM-3598] Ignore collecting requests to logs PCI intake as RUM resources

- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/instrumentMethod.ts
Some websites are removing native methods on purpose. Re-defining the method breaks them.
Don't define undefined instrumented methods.
---
> 🐛 [RUM-3599] do not define undefined instrumented method

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/index.ts
- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/core/src/index.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
- packages/rum-core/src/domain/tracing/tracer.spec.ts
- packages/rum-core/src/domain/tracing/tracer.ts
APM is working on building more granular sampling control on the backend side which can't be applied if the sampling decision is already taken on the client side.
Added a field `traceContextInjection` in the configuration to control context injection. 
This new configuration allows more granular sampling at the backend and does not bring any break changes. It is available along with sampling rate configuration.
`traceContextInjection` is an opt-in configuration defaults to "all" which means no behavior changes. If opt-in for the "sampled" option, you would see only sampled requests having trace context attached to them.
| Sampling Decision | traceContextInjection | Expected Behavior | 
|--------|--------|--------|
| Sampled | all | Inject trace context with sampling priority 1 | 
| …
> ✨ [RUM-3542] Add trace context injection control in rum configuration

- package.json
- yarn.lock
Local build is failing with error:
```
@datadog/browser-rum-core: ../core/cjs/domain/error/trackRuntimeError.d.ts(9,32): 
error TS2694: Namespace '"packages/rum-core/src/index"' has no exported member 'noop'.
```
This behaviour has been introduced with the update of typescript from 5.3.3 to 5.4.3, so reverting to last working version while investigating.
---
> 👷 [RUM-3709] Fix local build

- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/lifeCycle.ts
- packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/networkError/networkErrorCollection.ts
- packages/logs/src/rawLogsEvent.types.ts
- packages/rum-core/src/domain/requestCollection.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- packages/rum-core/src/domainContext.types.ts
Since we compute an isAborted property, we wanted to provide it as a beforeSend context attribute to allow customer to use it how they want, ex:
- implement the concept of domain context for Logs' `beforeSend` method
- forward `isAborted` so it's available in the beforeSend context for Logs and Rum
---
> ✨ [RUM-3387] forward isAborted  to beforeSend context

- renovate.json
Typescript 5.4.0 introduced a change that breaks our local build, cf #2670 
Exclude typescript from renovate updates
---
> 👷 Exclude typescript updates

- packages/rum-core/src/domain/action/computeFrustration.spec.ts
- packages/rum-core/src/domain/action/computeFrustration.ts
- packages/rum-core/src/domain/action/listenActionEvents.spec.ts
- packages/rum-core/src/domain/action/listenActionEvents.ts
- packages/rum-core/test/createFakeClick.ts
- test/e2e/scenario/rum/actions.scenario.ts
Currently, click on scrollbars, or more generally clicks resulting in page or element scrolling, are reported as `dead_clicks` or `rage_clicks` (if more than three clicks occurred).
This behaviour is misleading since those clicks did result in a change, which is the scrolling. Therefore, they shouldn't result in a frustration signal.
- Add an event listener over scroll and report it to `userActivity`
- Ignore clicks with `scroll` user activity from being reported as `dead_click`s and `rage_click`s 
> [!WARNING]  
> Clicks on scrollbar that do not result in a scroll event will still be reported as frustrations.
---
> 🐛 [RUM-96] Ignore frustrations on clicks resulting in scrolls

- packages/logs/src/domain/configuration.ts
- packages/logs/src/domain/lifeCycle.ts
- packages/logs/src/domain/networkError/networkErrorCollection.ts
- packages/logs/src/domainContext.types.ts
fixes #2685 
Add missing context argument to log's `beforeSend` type definition
---
> 🐛 fix beforeSend type definition for logs

- scripts/report-bundle-size/report-as-a-pr-comment.js
While running report-bundle-size, we do a git fetch origin to try to find the branch common commit with main.
We should not fetch the entire git history for that: not only it has performance implications, but also produces a huge output, cluttering the CI output. Also, sometimes [it fails](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/477865434)
Use the --depth option to limit the number of commits to fetch (see [doc](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---depthltdepthgt))
---
> ⚡️ [RUM-3283] Do not fetch the entire git history in report-bundle-size

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
Before this PR, we dropped any `PerformanceResourceEntry` that had inconsistent timings. With this commit, when the experimental feature "tolerant_resource_timings" is enabled, the various timings are validated independently.
This should improve the situation on Chrome when a Service Worker is involved. In this case, most of the time, connection timings are unexpectedly set after the `requestStart` timing (see [Chromium issue][1]). Before this change, the whole `PerformanceResourceEntry` would be ignored, and no timings would be included. With this change (and the flag enabled), relevant timings will be correctly defined.
Related issue: #2566
[1]: https://issues.chromium.org/issues/323703325
Before/without the flag:
After:
--- …
> ⚗ [RUM-2782] validate resource timings more granularly

- developer-extension/package.json
- yarn.lock
The update to css-loader@v7 broke the execution of the extension 😕
Reverts css-loader to v6
> Revert "👷 Update dependency css-loader to v7"

- developer-extension/src/panel/components/tabs/eventsTab/eventRow.tsx
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/telemetry/index.ts
- packages/core/src/domain/telemetry/rawTelemetryEvent.types.ts
- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/core/src/index.ts
- packages/core/test/coreConfiguration.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/rumEvent.types.ts
- sandbox/index.html
Collect some API usage telemetry
- introduce `addTelemetryUsage`
- monitor `set-tracking-consent`, `stop-session`, `start-session-replay-recording`
---
> 👷 [RUM-4029] Collect first usage telemetry

- packages/rum/src/domain/record/serialization/serializeAttribute.spec.ts
- packages/rum/src/domain/record/serialization/serializeAttribute.ts
Currently HTML passed using the srdoc attribute of an iframe is not masked by session replay when `data-dd-privacy` set to `mask`.
Example:
```
<div data-dd-privacy="mask">
<iframe srcdoc="<html><body>test</body></html>">
</iframe>
</div>
```
We expect browser sdk to mask the iframe content with privacy override keyword "mask"
Add `srcdoc` attribute to the masking list in `serializeAttribute`.
---
> 🐛[RUM-4109] Mask iframe srcdoc with privacy override

- scripts/performance/cpu-performance/compute-cpu-performance.js
Data from main branch are not send as there is no PR. As a result there is no data in the base column.
We should continue the script anyway to send data of the last common commit when main branch pipeline is triggered. For that we define no pr number in the synthetics test
---
> 🔨 Update no pull request case for cpu performance

- developer-extension/src/panel/components/tabs/infosTab.tsx
- packages/core/src/domain/session/README.md
- packages/core/src/domain/session/oldCookiesMigration.spec.ts
- packages/core/src/domain/session/oldCookiesMigration.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/session/sessionState.spec.ts
- packages/core/src/domain/session/sessionState.ts
- packages/core/src/domain/session/sessionStore.spec.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/domain/session/sessionStoreOperations.spec.ts
- packages/core/src/domain/session/sessionStoreOperations.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
- packages/core/src/domain/session/storeStrategies/sessionStoreStrategy.ts
- packages/logs/src/domain/logsSessionManager.spec.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- sandbox/index.html
- test/e2e/lib/helpers/browser.ts
- test/e2e/lib/helpers/session.ts
- test/e2e/scenario/recorder/shadowDom.scenario.ts
- test/e2e/scenario/recorder/viewports.scenario.ts
- test/e2e/scenario/rum/sessions.scenario.ts
- test/e2e/scenario/trackingConsent.scenario.ts
Makes session management resilient to clearing the cookie. If a cookie is deleted outside of the browser SDK, we do not create a new session automatically. 
This solves an issue with Adguard that delete the cookie every second. This had for effect to generate a large amount of short lived sessions.
- When a session is expired, we set the cookie to `isExpired=1` with an expiration delay of 4h (instead of deleting the cookie)
- When the cookie is altered by a 3rd party, we can now differentiate it from an expired session and won't start a new session automatically after a user action.
---
> ✨ [RUM-3710] Update session ID handling to support cookie deletion

- .gitlab-ci.yml
- .gitlab/deploy-auto.yml
- .gitlab/deploy-manual.yml
- scripts/deploy/deploy-auto.js
- scripts/deploy/deploy-prod-dc.js
- scripts/lib/command.js
Automate the different deployment steps of a release 
- extract `deploy-prod-dc` script:
- to deploy all the artifacts for specified DCs
- add an option to check the monitor status every minute for 30 minutes after the deployment
- notify for both manual and automatic deployment:
- split deployment in two child pipelines:
---
> 👷 Introduce a way to automate the release deployment 

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/domain/vital/vitalCollection.spec.ts
- packages/rum-core/src/domain/vital/vitalCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
Allow backend and app to make assumption on the vital value unit when it is computed by the SDK.
Attach `_dd.vital.computed_value` to vital events
---
> ✨[RUM-4179] vital: collect `computed_value` property

- test/e2e/lib/framework/waitForRequests.ts
- test/e2e/lib/helpers/browser.ts
- test/e2e/scenario/eventBridge.scenario.ts
- test/e2e/scenario/logs.scenario.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
- test/e2e/scenario/recorder/shadowDom.scenario.ts
- test/e2e/scenario/recorder/viewports.scenario.ts
- test/e2e/scenario/rum/errors.scenario.ts
- test/e2e/scenario/rum/resources.scenario.ts
- test/e2e/scenario/rum/sessions.scenario.ts
- test/e2e/scenario/rum/tracing.scenario.ts
- test/e2e/scenario/rum/views.scenario.ts
- test/e2e/scenario/rum/vitals.scenario.ts
- test/e2e/scenario/telemetry.scenario.ts
- test/e2e/scenario/trackingConsent.scenario.ts
Custom type definition where introduce to fix a [bug](https://github.com/webdriverio/webdriverio/issues/3796) in webdriverio. this bug is now fixed so there is no need to maintain our own custom types.
Moreover, the custom type was incomplete and I had to augment them in [this PR](https://github.com/DataDog/browser-sdk/pull/2673#discussion_r1547376370)
Use `browser.execute` and `browser.executeAsync` instead of our custom wrapper.
---
> ♻️ use browser.execute and browser.executeAsync directly

- .gitlab-ci.yml
- developer-extension/src/panel/index.tsx
- package.json
- test/e2e/scenario/developer-extension/developerExtension.scenario.ts
- test/e2e/wdio.base.conf.ts
- test/e2e/wdio.developer-extension.conf.ts
Avoid to break the developer extension without noticing it
Introduce a simple e2e test ensuring that the extension is usable
---
> 👷 [developer extension] Add a simple e2e test

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- test/e2e/scenario/rum/vitals.scenario.ts
Provide **beta** APIs to track custom durations as vital events
```js
DD_RUM.startDurationVital('foo', { context, startTime })
// do some stuff
DD_RUM.stopDurationVital('foo', { context, stopTime })
```
---
> ✨⚗️ [RUM-4275] Expose custom vitals API for beta phase

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- test/e2e/scenario/rum/vitals.scenario.ts
In the end, wait a bit more and GA directly
Revert "✨⚗️ [RUM-4275] Expose custom vitals API for beta phase"
[RUM-4275]: https://datadoghq.atlassian.net/browse/RUM-4275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "✨⚗️ [RUM-4275] Expose custom vitals API for beta phase"

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
- packages/rum-core/src/domain/contexts/featureFlagContext.ts
This PR enables sending feature flags with the API introduced in https://github.com/DataDog/browser-sdk/pull/2096
Remove the `feature_flags` experimental flag.
---
> ✨ [RUM-4287] Enable feature flags API

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
site is a [Datadog-wide parameter](https://docs.datadoghq.com/getting_started/site/). The current non-sanitized implementation of site config parameter offers backward compatibility when a new datacenter is created. But in the context of a browser, site has a completely different meaning and could be mistaken for “my website”.
Add a non-breaking change to only accept values meeting a pattern like:`/(datadog|ddog|datad0g|dd0g)/`.
This would allow to retain backward compatibility and some degree of flexibility, while adding an extra protection layer.
---
> ✨ [RUM-4052] Sanitize `site` parameter in configuration

- scripts/deploy/deploy-prod-dc.js
Following https://github.com/DataDog/browser-sdk/pull/2720, there were some typos
fix deploy script
---
> 🐛fix deploy script

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/boot/rumPublicApi.ts
Provide more visibility on how some SDK APIs are used
Monitor usage of:
- startView
- addAction
- addError
- addFeatureFlagEvaluation
- startDurationVital
- setGlobalContext
- setUser
---
> 🔊[RUM-4360] monitor more API usages

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
Setting a non-string value for the customer provided tags init option causes the SDK to fail silently.
Add validation to ensure that the tags parameters are properly defined as strings.
---
> 🐛 [RUM-97] Sanitize tags parameter in configuration

- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/logs/src/domain/configuration.spec.ts
Avoid to loose some telemetry when a single event is spammed, ex:
Discard already seen telemetry events
---
> 🔊 Deduplicate telemetry events

- packages/core/src/domain/telemetry/index.ts
- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/core/src/index.ts
- packages/logs/src/domain/logsTelemetry.ts
- packages/rum-core/src/boot/startRum.ts
Avoid to loose telemetry events happening before the start of the SDK.
Use a `BoundedBuffer` to store early events and drain it when the telemetry is properly configured.
---
> 🔊 collect pre start telemetry

- .github/ISSUE_TEMPLATE/feature_request.md
We have a GitHub issue template for feature requests but we redirect them to support. Maybe we can tell people to contact support directly in the template to optimize the process.
> 👷 review feature request process

- packages/rum-core/src/browser/polyfills.ts
- packages/rum-core/src/domain/getSelectorFromElement.ts
Some small cleanup opportunities I stumbled upon within the last few days
- Remove some commented code and fix a small typo.
- Remove reference to possibly expose `isGeneratedValue` as this came up in #2751 and commented that it might not be a good idea after all.
> Ideally, we should tackle it internally and find a way to improve the performance for everyone without requiring users to fine tune the internals of the SDK.
---
> ✏️ various comment fixes

- scripts/staging-ci/merge-into-staging.js
When the `check-staging-merge` job fails on a PR, the logs suggest a way to fix it:  https://github.com/DataDog/browser-sdk/blob/f221bc91ebe8010eb2d86ee9d48c1d1d7e39d7ae/scripts/staging-ci/check-staging-merge.js#L30-L32
I'm adding similar help message when `check-staging-merge` fails on the `main` branch.
Add a link to [How to fix staging](https://datadoghq.atlassian.net/wiki/spaces/FRON/pages/2548269306/How+to+fix+staging+conflicts) in confluence as instructions are a bit different than for a PR branch.
---
> 👷 add link to conflict resolution documentation in confluence

- packages/rum-core/src/browser/polyfills.spec.ts
- packages/rum-core/src/browser/polyfills.ts
- packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
- packages/rum-core/src/domain/resource/matchRequestTiming.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
- test/e2e/scenario/rum/resources.scenario.ts
Fixes an issue where resource timing where not matched to a resource when the same resource is requested twice at the same time.
e.g.
```js
Promise.all([
fetch("http://localhost:8080/"),
fetch("http://localhost:8080/")
])
```
The issue is that when the second request resolves, we have 2 resource timings matching the request hence we were not able to decide which one is the correct one.
When a match is found between a resource timing and a request, we store the timing in a `WeakMap`, that way we can filter it out of the available timings when the 2nd resource resolve.
---
> 🐛 [RUM-4434] fix timing matching for the same resource requested twice at the same time

- packages/rum-core/src/domain/action/actionCollection.spec.ts
- packages/rum-core/src/domain/action/actionCollection.ts
- packages/rum-core/src/domain/discardNegativeDuration.ts
- packages/rum-core/src/domain/view/viewCollection.ts
We noticed that we have actions with negative actions negative loading time. This is probably due to the fact that Date.now() is not monotonic and sometimes goes “back in time” 
If that's the case, we could just not set the loading time of the action event.
---
> 🐛 [RUM-1666] Don't set negative action loading time 

- developer-extension/src/common/types.ts
- developer-extension/src/content-scripts/main.ts
- developer-extension/src/panel/components/panel.tsx
- developer-extension/src/panel/components/tabs/settingsTab.tsx
- developer-extension/src/panel/hooks/useDebugMode.ts
- developer-extension/src/panel/hooks/useSettings.ts
- developer-extension/src/panel/setDebugMode.ts
Errors happening in RUM and LOGS are monitored but not displayed in the developer console by default. Both SDKs exposes an API (`_setDebug(value: boolean)`) to allow these error to be displayed in the developer console.
This PR adds and option to enable this debug mode from the developer extension.
---
> 👷 add option to enable debug mode in the developer extension

- packages/core/src/browser/pageExitObservable.spec.ts
- packages/core/src/browser/pageExitObservable.ts
- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/core/src/transport/batch.spec.ts
- packages/core/src/transport/batch.ts
- packages/core/src/transport/httpRequest.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
- packages/rum/src/boot/recorderApi.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
Cleanup experimental features:
- https://github.com/DataDog/browser-sdk/pull/1890
- https://github.com/DataDog/browser-sdk/pull/2020
- https://github.com/DataDog/browser-sdk/pull/2515
- https://github.com/DataDog/browser-sdk/pull/2348
Remove features/experimentations code and feature flags
---
> 🔥 Cleanup experimental features

- packages/core/test/forEach.spec.ts
Unit tests were failing because the cookies were not correctly cleared prior to some tests (see https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/518528355)
Clear cookies *before* tests rather than after.
---
> ✅ fix clearing cookies between tests

- packages/rum-core/src/domain/action/trackClickActions.ts
- packages/rum-core/src/domain/getSelectorFromElement.spec.ts
- packages/rum-core/src/domain/getSelectorFromElement.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
Sometimes we compute CSS selectors on detached nodes (ex: when an LCP occurs but the LCP target element is quickly removed from the DOM before we get the PerformanceEntry), making the Browser SDK crash.
Make sure we never compute CSS selectors on detached nodes.
---
> 🐛 [RUM-4493] do not compute selectors for detached elements

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/rum-core/src/domain/configuration.spec.ts
- packages/rum-core/src/domain/configuration.ts
Some customer pass `null` as version. Now that we validate that parameter, the initialization fails.
See https://github.com/DataDog/dd-sdk-flutter/issues/616
Regression caused by https://github.com/DataDog/browser-sdk/pull/2744
Do not reject `null` for tags.
---
> 🐛 [RUM-4629] accept `null` as env/version/service

- packages/core/src/boot/init.ts
- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/tags.spec.ts
- packages/core/src/domain/configuration/tags.ts
- packages/core/src/domain/context/customerDataTracker.ts
- packages/core/src/index.ts
- packages/core/src/tools/display.ts
- packages/core/src/transport/batch.ts
- packages/logs/src/boot/logsPublicApi.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum/src/domain/deflate/deflateWorker.ts
JSDoc annotations are visible through the IDE, providing developers with immediate and comprehensive documentation as they integrate with our SDK.
- Document all public APIs
- Add links to the public doc in browser SDK warnings when useful
---
> 📝 [RUM-158] Add jscdoc to public APIs

- packages/rum-core/src/domain/getSelectorFromElement.spec.ts
- packages/rum-core/src/domain/getSelectorFromElement.ts
Optimize the computation of CSS selector when for huge DOM.
When running the same operation on an artificial huge DOM:
Before:
After:
---
> ⚡️ [RUM-4468] improve CSS selector computation performance

- packages/core/src/boot/init.ts
We should warn when the SDK is loaded multiple times as it can lead to unexpected behaviour. 
As we don't want a breaking change for now, we can just send a warning if the sdk is already loaded in the define global function.
---
> 🐛 [RUM-98] Warn when SDK is loaded multiple times

- developer-extension/README.md
- developer-extension/src/panel/components/panel.module.css
- developer-extension/src/panel/components/panel.tsx
Help users to navigate using the extension.
Added usage tips in extension readme file and direct users to it in the extension.
---
> 👷 Add extension usage tips doc and link in ui

- scripts/performance/cpu-performance/compute-cpu-performance.js
- scripts/performance/memory-performance/compute-memory-performance.js
I added a new page on the sdk playground for the memory as it was linked to the cpu benchmark previously. We need to modify the url in the performance test to match with the new one
---
> [RUM-4652] Update url after playground changes

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/index.ts
- packages/core/src/tools/experimentalFeatures.spec.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/logs/src/boot/preStartLogs.ts
- packages/rum-core/src/boot/preStartRum.ts
Being able to use experimental features early in the SDK lifecycle
Initialize the experimental feature in the `preStartRum` instead of waiting the `startRum`
---
> ♻️ Set the experimental feature flags as early as possible

- packages/core/src/domain/configuration/configuration.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
Now that we collect pre start telemetry (cf [PR](https://github.com/DataDog/browser-sdk/pull/2755)) we can move configuration sending to `preStartRum`. This avoid passing the `initConfiguration` down to [startRum](https://github.com/DataDog/browser-sdk/blob/94d4fbc152286d7dbdc4938bde9e83d3bb2e8dac/packages/rum-core/src/boot/startRum.ts#L54).
Sends configuration telemetry from preStartRum
---
> ♻️ Sends the conf telemetry from preStartRum

- scripts/performance/memory-performance/compute-memory-performance.js
- scripts/performance/report-as-a-pr-comment.js
Add a link at the beginning of the pr commenter bot to directly test on a playground environment (realworld) the local bundle.
Some changes made on playground to support prNumber in url to access to correct rum bundle / logs bundle. 
Added a link to redirect to realworld
---
> [RUM-4895] Add link to playground with pr's bundle

- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
There is no reason why we shouldn't accept different types there. See https://github.com/DataDog/browser-sdk/pull/2781#issuecomment-2150324514
Change types, convert falsy values to undefined
---
> Use the same service/version type in `init()` and `startView()`

- packages/rum/src/domain/record/mutationBatch.spec.ts
- packages/rum/src/domain/record/mutationBatch.ts
When recording for Session Replay, [MutationRecord](https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord) objects are batched together (see [mutationBatch](https://github.com/DataDog/browser-sdk/blob/fd44db8f0a9e6b0e08396deb182eebf69a3ef4d3/packages/rum/src/domain/record/mutationBatch.ts#L1)), then deduplicated on processing (ex: [here](https://github.com/DataDog/browser-sdk/blob/d48922fe03946c67412665a2976e4b4f978c28b6/packages/rum/src/domain/record/trackers/trackMutation.ts#L337)).
When the same mutation happens continuously on the same element, for example with JS-driven animations, a lot of MutationRecords can be notified by the browser in a very short amount of time, which can significantly inflate the data sent to Datadog, and have a performance impact both on the …
> ⚡️[RUM-3570] Batch the records for 16ms minimum before processing them

- developer-extension/src/content-scripts/main.ts
Fix issue with the developer extension when dev mode option is enabled:
Makes sure `_setDebug` exists before calling it (same as in `overrideInitConfiguration`)
---
> 🐛 fix developer extension crashing when dev mode enabled

- .gitlab-ci.yml
Allow merging PRs on `main` during the production freeze.
Disable canary deployment in the CI
---
> 👷 disable canary deployment during production freeze

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
Make `enablePrivacyForActionName` feature not behind experimental feature flag.
Remove experimental feature flag `enable_privacy_for_action_name` and remove the checks.
---
> 👷‍♀ Remove experimental feature flag for action name privacy control

- test/unit/karma.base.conf.js
- webpack.base.js
There are misleading TS errors during tests due to the extension using a different `tsconfig` than the default one set in webpack base configuration, which is used by karma. 
We use `transpileOnly` option for ts-loader in webpack to avoid type-checking during unit tests. We ignore the warnings caused by this setting. 
---
> 👷‍♀️ Skip typechecks during unit tests

- packages/core/src/tools/experimentalFeatures.ts
- packages/logs/src/domain/console/consoleCollection.spec.ts
- packages/logs/src/domain/console/consoleCollection.ts
- packages/rum-core/src/domain/action/actionCollection.spec.ts
- packages/rum-core/src/domain/action/actionCollection.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/error/errorCollection.spec.ts
- packages/rum-core/src/domain/error/errorCollection.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- test/e2e/scenario/microfrontend.scenario.ts
Enable Micro frontend for private beta
remove the `micro_frontend` experimental feature flag 
---
> 👷‍♀ Remove experimental flag for micro frontend

- yarn.lock
https://github.com/DataDog/browser-sdk/security/dependabot/82
Upgrade of messed `yarn.lock` file 
---
> 👷 engine.io and socket.io-adapter packages to fix ws vulnerability

- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
Without a span id, the backend does not create the RUM span
Generate a random span id for the RUM span.
---
> 🐛 [RUM-5209] provide a span id for the initial document trace

- packages/core/src/browser/fetchObservable.ts
- packages/core/src/browser/xhrObservable.ts
- packages/core/src/index.ts
- packages/logs/src/boot/preStartLogs.spec.ts
- packages/logs/src/boot/preStartLogs.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
When RUM's initialisation is delayed because of consent not being granted initially, some libraries (such as Apollo Client) do store some methods aside to be re-used (mainly `window.fetch`), which leads to the un-instrumented method being used for http requests, even after consent being granted.
Instrument `fetch` method on sdk initialisation. The instrumentation process is idempotent.
---
> 🎨 Instrument fetch and XHR before trying to init consent

- packages/rum-core/src/browser/performanceObservable.spec.ts
- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/test/emulate/mockPerformanceObserver.ts
Looking at the telemetry, it seems that users still use very old version of Chrome (<75) and Apple Mail which do not support performance observer [buffered](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe#buffered) and [type](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe#type) parameters. This PR adds a fallback strategy for these cases using:
- performance observer [entryTypes](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/observe#entrytypes) and 
- [performance.getEntriesByType()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType) for the buffered entries
Add fallback strategy to createPerformanceObservable
--- …
> 🐛 [RUM-958] Fix performance observable compatibility with old browser version

- scripts/release/generate-changelog.js
When we created the CHANGELOG, we chose to only show public changes (bug fixes, new features, …).
In practice, this is not always respected. Sometimes, it’s not clear whether it is a public or internal change. We are a bit hesitant to show experimental features or not. Sometimes we do releases with only internal changes, and having an empty entry is not ideal.
Let’s add everything, but to help the reading, split changes into two sections (ex: public/internal changes). The generate_changelog script should handle the formating based on gitmojis.
---
> ♻️ [RUM-159] Categorize changes as public or internal in the CHANGELOG

- packages/rum-core/src/domain/contexts/viewContexts.spec.ts
- packages/rum-core/src/domain/contexts/viewContexts.ts
- test/e2e/scenario/rum/init.scenario.ts
The API 'update view name' doesn't update the last view in the context history. This mean next events such as action would not be linked to the view with the new name. 
Added a subscribe to view_updated, so it update the last view from the context history with the correct name. 
---
> 🐛 Fix update view name api in context history

- scripts/release/update-peer-dependency-versions.js
`rum-react` package peerDependencies on `@datadog/browser-core` and `@datadog/browser-rum-core` are not updated by release script.
- Reading the content of `./packages` to retrieve packages name. 
- Update packages with peerDependencies on `@datadog` modules.
---
> Update rum-react peerDependencies

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
- sandbox/react-app/main.tsx
We want to expose plugins to customers, but this should still be considered as "beta".
* Remove "PLUGINS" feature flag
* rename init config "plugins" to "betaPlugins"
---
> ⚗️ enable plugins as a beta feature

- packages/rum-react/README.md
Document how to use the react integration. See it rendered: https://github.com/DataDog/browser-sdk/blob/benoit/react-doc/packages/rum-react/README.md
Add documentation to the README
---
> 📝 [RUM-5172] add react integration documentation

- .gitlab-ci.yml
Sometime some gitlab job are failing to setup properly, (e.g: [test-performance](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/581316267)) and re-running the job works. This PR attempt to retry automatically when the job fail because of a [runner_system_failure](https://docs.gitlab.com/ee/ci/yaml/?query=runner_system_failure#retrywhen)
Edit gitlab config to retry automatically on runner system failure
---
> 👷 retry gitlab jobs on runner_system_failure

- packages/core/src/browser/fetchObservable.spec.ts
- packages/core/src/browser/fetchObservable.ts
- packages/core/test/emulate/mockFetch.ts
We have a lot of telemetry errors concerning Fetch error that are not an Error object but a string or undefined.
- Handling the non-object Fetch Error and Response
- Supporting abort status from AbortController
> 🐛 Handle non-object response and error

- packages/rum-core/src/browser/performanceCollection.spec.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/browser/performanceObservable.spec.ts
- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/test/emulate/mockPerformanceObserver.ts
Following #2855 and #2818, we are using more granular PerformanceObserver. We observe less entry types in the PerformanceObserver from `performanceCollection`, and  in the new `performanceObservable`, we observe a single type at once.
We observed that in old versions of Safari, if all entry types supplied to `.observe(..)` are unsupported, an exception is thrown: `entryTypes contained only unsupported types`. Illustration:
```ts
// assuming 'resource' is supported but not 'longtask'
new PerformanceObserver().observe({ entryTypes: ['resource', 'longtask'] }) // succeeds
new PerformanceObserver().observe({ entryTypes: ['longtask'] }) // throws
```
To work around this issue, this PR wraps `.observe(..)` calls in `try/catch` blocks to prevent the SDK from crashing.
--- …
> 🐛 fix unexpected exception when no entry type is supported in PerformanceObserver

- .gitlab-ci.yml
Enabling performance tests after fixing APP_KEY
Tests enablement
---
> Revert "👷 disable test-performance job (#2904)"

- scripts/lib/git-utils.js
- scripts/performance/report-as-a-pr-comment.js
I'm doing PRs to the `v6` feature branch, however the bundle size comment on the PR ar comparing to the main branch instead of the base branch of the PR.
Calculate the size difference using the PR's base branch instead of the main branch
see [this PR](https://github.com/DataDog/browser-sdk/pull/2909#issuecomment-2260675178) for an example in actions
---
> 🐛 bundle size: calculate diff from PR base instead of main

- packages/rum-core/src/boot/startRum.ts
`pageStateHistory.stop()` is called twice. I believe this is a mistake!
---
> ♻️ remove duplicate pageStateHistory.stop()

- scripts/staging-ci/merge-into-staging.js
Use [devflow](https://datadoghq.atlassian.net/wiki/spaces/DEVX/pages/2905376710/Devflow) to merge `main` back into `staging-XX`. 
If this fails, it will create a [fix PR](https://github.com/DataDog/browser-sdk/pull/2916) and log something like this:
```
couldn't merge the [main](https://github.com/DataDog/browser-sdk/tree/main) branch of [browser-sdk](https://github.com/DataDog/browser-sdk) into [thomas.lebeau/test-devflow-conflic](https://github.com/DataDog/browser-sdk/tree/thomas.lebeau/test-devflow-conflic), there was a conflict...
We have created a conflict resolution PR for you [#2916](https://github.com/DataDog/browser-sdk/pull/2916)
Alternatively, you can also reset the integration branch by using the following slack command: `/devflow reset-branch -r browser-sdk -b …
```
> 👷 use devflow to merge main into staging

- scripts/staging-ci/merge-into-staging.js
This reverts commit 6b867f7b003fcc5d529edc35cc055f0490f94e70.
The token on the CI does not seems to work, reverting for now.
---
> Revert "👷 use devflow to merge main into staging (#2917)"

- packages/core/src/domain/console/consoleObservable.spec.ts
- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/report/reportObservable.spec.ts
- packages/core/src/domain/report/reportObservable.ts
- packages/core/src/index.ts
- packages/logs/src/domain/console/consoleCollection.spec.ts
- packages/logs/src/domain/console/consoleCollection.ts
- packages/logs/src/domain/createErrorFieldFromRawError.spec.ts
- packages/logs/src/domain/createErrorFieldFromRawError.ts
- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/logger.ts
- packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/networkError/networkErrorCollection.ts
- packages/logs/src/domain/report/reportCollection.spec.ts
- packages/logs/src/domain/report/reportCollection.ts
- packages/logs/src/domain/runtimeError/runtimeErrorCollection.spec.ts
- packages/logs/src/domain/runtimeError/runtimeErrorCollection.ts
- packages/logs/src/rawLogsEvent.types.ts
- packages/rum-core/src/domain/error/errorCollection.spec.ts
- packages/rum-core/src/domain/error/trackConsoleError.spec.ts
- packages/rum-core/src/domain/error/trackConsoleError.ts
- packages/rum-core/src/domain/error/trackReportError.ts
**Please review commit by commit**
This PR implements error.handling to logs, similarly to RUM error events.
This PR contains a bit of refactoring in order to unify how we define the `error` field in logs. The idea is to format all kind of errors as `RawError` objects, then use `RawError` objects in RUM (to create RUM Error events) and Logs (to define the `error` field). This `RawError` creation logic was already present in RUM, so I just had to move it in `core`. 
**Note:** Network errors are kind of special and only supported in logs, so I didn't use `RawError` there. Also, we can't be sure whether they are handled or not by the customer app, so to avoid any confusion, they don't have `error.handling`.
---
I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/ma …
>  ✨ [RUM-5712] add error.handling to logs 

- .gitlab-ci.yml
`runner:main` is deprecated, use `arch:amd64` as per the [documentation](https://datadoghq.atlassian.net/wiki/spaces/DEVX/pages/2411528655/Onboarding+To+Gitlab+CI#Gitlab-runner-tags--%3Agitlab-runner%3A)
---
> 👷 upgrade gitlab runner

- packages/core/test/emulate/mockLocation.ts
- packages/rum-core/src/browser/locationChangeObservable.ts
We wrongly instrument history API, potentially breaking the instrumentation of other vendors, cf: #2943 
Wrap `History.prototype.pushState` instead of `history.pushState`
---
> 🐛 [RUM-5921] Fix history API instrumentation

- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
This reverts commit 68d89a1e35ec029d9147f76ea3151a119f4607fd.
Testing of INP Null target has finished. We do not need to include this in the release.
revert INP null target telemetry
---
> Revert "[RUM-5590] Add telemetry for INP null target (#2895)"

- test/unit/karmaSkippedFailedReporterPlugin.js
`baseReporterDecorator` implements a bunch of methods that display messages in the console. Since we already have a reporter for that, messages are displayed twice.
Remove `baseReporterDecorator` usage from our karma "skipped failed reporter" plugin.  Without `baseReporterDecorator`, `specSkipped` and `specFailure` "hooks" don't exist anymore, so let's use `onSpecComplete` instead.
---
> 👷 don't print log messages twice in unit tests

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- test/e2e/scenario/rum/vitals.scenario.ts
Exposing the Custom Vital API.
Remove custom_vitals FF.
---
> Remove custom_vitals FF

- .gitlab-ci.yml
- scripts/update-branch.js
The next major feature branch (`v6`) will be a long living branch, we need to make sure we're merging main into it regularly to avoid larger conflicts resolution later.
This job will merge main into v6 and trigger the CI.
If merging fails, devflow will create a fix PR (link in the logs). We will need to follow the created PR's instruction (i.e. fixing the conflict ant resuming the job) and then re-run the job to continue the pipeline
- Add a CI job to automatically merge the main branch into the next major feature branch (currently `v6`)
- refactor `update-branch` to trigger the CI after updating the branch
---
> 👷 add job to merge main into next major feature branch (v6)

- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.ts
When a view created in background, its loading time can be inflated due to the browser pausing the javascript execution, which leads to data inconsistencies. It's better to not send the loading time of those views, rather than sending an erroneous value.
If the page is initially hidden, discard attaching `loading_time` to view event
---
> :sparkles: Discard loading time when page is hidden

- packages/rum-core/src/browser/performanceObservable.spec.ts
- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
- packages/rum-core/src/domain/resource/matchRequestResourceEntry.ts
- packages/rum-core/src/domain/resource/matchRequestTiming.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
- packages/rum-core/src/rawRumEvent.types.ts
Starting with Chrome 128, blob URLs are reported as PerformanceResourceTiming entries. Those entries have (always?) negative durations, which is unexpected. The intake rejects RUM Resource events with negative duration already, so sending them is useless and breaks our e2e tests when validating the events against the rum-events-format.
Let's ignore resource entries with negative duration.
Note: I opened a [Chromium issue](https://issues.chromium.org/issues/363031537) about this, but in the meantime, there is absolutely no value in sending those entries to the intake.
This PR also rename a bunch of "PerformanceResourceTiming"-related function to have consistent naming.
---
> 🐛 [RUM-94] ignore performance resource timings with negative duration

- packages/core/src/domain/eventRateLimiter/createEventRateLimiter.spec.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/tools/utils/timeUtils.ts
- packages/core/test/emulate/mockClock.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
- packages/rum-core/src/domain/contexts/urlContexts.spec.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.spec.ts
- packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
- packages/rum-core/test/emulate/mockPerformanceObserver.ts
Before this commit, `mockClock` was adjusting the `navigationStart` value so calling `performance.now()` before any `clock.tick()` returned 0. This was useful for assertions on relative times, ex:
```js
clock = mockClock()
clock.tick(10)
expect(relativeNow()).toEqual(10)
```
Unfortunately, it lead to incoherences because some other timings were not adjusted. For example `performance.timing.responseStart` was not adjusted, so it was before `navigationStart`, which is unexpected.
To work around this, we locally tweak the mocked clock (ex: (here)[1] and (here)[2]). Those tweaks are hard to understand, especially on "integration tests" where those incoherences are deeply nested into lower-level code.
So, this leaves us we two solutions to make things coherent again:
* Mock more things: …
> ✅♻️ do not mock `navigationStart` in `mockClock`

- .gitlab-ci.yml
to use variables, we need to use `variables` instead of `refs`, like for `.staging`:
https://github.com/DataDog/browser-sdk/blob/73ae1f5caaa04c2659d5eee2c4f2a5222742beb0/.gitlab-ci.yml#L68-L71
---
> 👷 fix next major deploy job config

- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/browser/performanceCollection.spec.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
- packages/rum-core/src/domain/longTask/longTaskCollection.ts
Following the introduction of `performanceObservable` to move away from `performanceCollection`: [PR](https://github.com/DataDog/browser-sdk/pull/2818)
Let use `performanceObservable` for long-task entries.
- Remove long-task from `performanceCollection`
- Use `perfomanceObservable` in `startLongTaskCollection`
---
> ♻️ [RUM-6180] Use performanceObserver for long-task entries

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
> 🔥 cleanup unused Experimental Features

- packages/rum-core/src/browser/performanceCollection.spec.ts
- packages/rum-core/src/browser/performanceCollection.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Following the introduction of `performanceObservable` to move away from `performanceCollection`: [PR](https://github.com/DataDog/browser-sdk/pull/2818)
Let use `performanceObservable` for LCP entries.
- Remove LCP from `performanceCollection`
- Use `perfomanceObservable` in `trackLargestContentfulPaint`
---
> ♻️ [RUM-6181] Use performanceObserver for LCP entries

- .gitlab-ci.yml
Sometime the e2e-bs job is losing connection to Browserstack ([example](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/640299576)), this result is the job not doing anything until it times out, after 1 hour.
In the past month, no successful job has taken more that 30 minutes ([query](https://app.datadoghq.com/ci/pipeline-executions?query=ci_level%3Ajob%20%40ci.pipeline.name%3A%22DataDog%2Fbrowser-sdk%22%20%40ci.job.name%3Ae2e-bs%20-%40ci.status%3A%28skipped%20OR%20canceled%29%20%40duration%3A%3E1800000000000&agg_m=%40duration&agg_m_source=base&agg_q=%40ci.status&agg_q_source=base&agg_t=avg&analyticsOptions=%5B%22line%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cipipeline_explorer_sort=time%2Cdesc&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5 …
> 👷 timeout e2e-bs ci job after 30 minutes

- packages/rum-core/src/boot/rumPublicApi.ts
Experimental Features are added to `RumPublicApi` when RUM is started. This could be improved by exposing them right after the initialisation of the SDK
Move `updateViewName` exposure to init method
---
> 🎨 RUM-6203: Expose experimental features in init method

- developer-extension/src/background/domain/syncRules.ts
Enable local dev bundle to be loaded properly even when the `browser_sdk_next_major_version` is enabled
Tweak the redirect rules to account for the `v6-canary` bundles loaded when the next major feature flags is enabled
---
> 🐛 fix to redirect v6-canary bundles urls to local dev bundles

- packages/rum-react/src/domain/reactRouterV6/createRouter.spec.ts
- packages/rum-react/src/domain/reactRouterV6/startReactRouterView.spec.ts
- packages/rum-react/src/domain/reactRouterV6/startReactRouterView.ts
- sandbox/react-app/main.tsx
- tsconfig.base.json
React Router routes defined with a '*' as a path are often used to create custom routing logic. It doesn't bring much value within a View name, as it could lead to very different pages. 
Replace the wildcards with the actual path they are matching. For example, with the following router:
```
router = ceateBrowserRouter(
[
{
path: '/foo',
children: [{ path: '*' }]
}
]
)
```
Accessing `/foo/bar` will create the view name `/foo/bar` instead of `/foo/*`.
---
> ✨replace react-router wildcard routes with their actual path name

- test/e2e/scenario/rum/init.scenario.ts
We want to have e2e tests to ensure the new APIs loaded and will not break the page.
Add view context api check in init e2e test file.
---
> [RUM 6237] Add e2e test for view context API init

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- test/e2e/scenario/rum/init.scenario.ts
Make view specific context apis public without experimental feature flag.
Removed feature flag and set APIs public by defualt.
---
> [RUM 4813] Remove feature flag for view specific context

- packages/rum/src/boot/recorderApi.ts
- packages/rum/src/boot/startRecording.ts
- packages/rum/src/domain/recordsCaching/index.ts
- packages/rum/src/domain/recordsCaching/recordsCaching.ts
Implementation of Error Mode Replay recorder.
- Initialise records caching module
- Start session replay recording as long as session is tracked (no matter what sample state)
- If session is sampled in for replay, start segments collection, otherwise forward records to cache
- When session replay is forced to start, start segment collection from cache
---
> ✨ Add records caching logic and cache records if session is sampled out

- .gitlab-ci.yml
Bump timeout a bit as job can sometimes take a bit longer, especially when waiting for the job to start the runner.
---
> 👷 bump e2e-bs ci job timeout to 35 minutes

- packages/core/src/domain/telemetry/telemetry.ts
- packages/logs/package.json
- packages/rum-slim/package.json
- packages/rum/package.json
- scripts/lib/build-env.js
Add SDK setup to the telemetry events
```js
telemetry: {
sdk_setup: 'npm' | 'cdn'
}
```
---
> 🔊 Add SDK setup telemetry

- packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.spec.ts
- packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
We need to send the _raw_ `start_time` property as it serve as a reference for calculating various timings:
---
> 🧪 add missing start_time

- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
On "route change" views, the CLS computation took any buffered layout shift entry into account, so in some cases it reflected the CLS of an anterior view. 
This commit fixes the issue by ignoring layout shifts that happened before the view start.
We still use the buffered entries so we can use layout shift entries that happens before the SDK is initialized.
---
> 🐛 ignore layout shifts that happen before view start

- packages/core/src/transport/httpRequest.spec.ts
- packages/core/test/interceptRequests.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
Use registerCleanupTask for interceptor cleanup
---
> ♻️ [RUM-5101] Use registerCleanupTask for interceptor cleanup

- packages/core/src/browser/xhrObservable.spec.ts
- packages/core/src/domain/synthetics/syntheticsWorkerValues.spec.ts
- packages/core/test/emulate/mockSyntheticsWorkerValues.ts
- packages/core/test/emulate/mockXhr.ts
- packages/core/test/interceptRequests.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/domain/contexts/rumInternalContext.spec.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/contexts/syntheticsContext.spec.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
- Use registerCleanupTask for mockXhr cleanup
- Use registerCleanupTask for mockSyntheticsWorkerValues cleanup
---
> ♻️ Use registerCleanupTask for mock cleanups

- .gitlab-ci.yml
We don't need to merge main into the next major branch on scheduled pipelines as it's only eventually creating a PR to bump the Chrome version if new version is available.
When the bump Chrome PR is merged, it will be normally merged into the next major.
---
> 👷 skip merge into next major on scheduled pipelines

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.ts
There's some missing replay segment, because most likely the browser/javascript execution stop before data is compressed or uploaded.
Flush data more often, like every 5 seconds instead of 30 seconds could increase the chances to send Replay data
---
> 🐛 [RUM-6483] Investigate reducing the batch time limit for Replay

- .gitlab-ci.yml
Hi, Devx team here - I started investigating OOM kills in CI, and the `e2e-bs` job showed up fairly often.
No variable is defined explicitly, so each job uses the [default values](https://github.com/DataDog/dd-source/blob/main/domains/devex/ci/gitlab/config/k8s/gitlab-runner/values/resources-managed.template.yaml#L12-L17) (currently, 1 cpu request, no cpu limit, 2Gi ram request and 6Gi ram limit).
It seems like allocating more memory would help.
For example, another pr I opened this morning (#3079) is currently blocked because of this test, and it appears that 40 processes were killed by k8s during the job execution - [events](https://app.datadoghq.com/event/explorer?query=source%3Aoom_kill%20ci-job-name%3Ae2e-bs%20ci-job-id%3A676670230%20&cols=&fromUser=false&index=%2A&messageDisplay=expa …
> 👷 CI - assign static resources for e2e-bs job

- scripts/deploy/publish-developer-extension.js
The developer extension is now public, hence it's no longer possible to publish it to `trustedTesters` only anymore
---
> 👷 publish chrome extension to all users

- repository.datadog.yml
[Build Impact Analysis](https://datadoghq.atlassian.net/wiki/spaces/DEVX/pages/2907573392/Build+Impact+Analysis) service supports indexing native yarn packages.
BIA integrates with the mergequeue, to enable parallel merge of prs that don't have any overlap in changed or impacted packages.
The "yarn strategy" is mature: it has been enabled in web-ui repository as well for several months, and used at scale to parallelize merges.
Other use cases can also consume this data (e.g. adding labels on every pull requests with the list of changed packages, viewing the dependency graph of a service)
Enable indexing the repository with yarn strategy.
This is a CI-only change, that should not impact this repository in any way visible to users (enabler for activation of new features in the future) …
> 👷 CI - Enable yarn strategy on the repository

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.ts
We can now go for GA to reduce batch time limit 
Remove feature flag
---
> 👷‍♀ Enable reduced Session Replay data batch time limit

- .gitlab-ci.yml
Temporarily disable browserStack tests on the v6 branch.
---
> 👷 [RUM-6366] disable browserStack tests

- packages/core/src/domain/configuration/index.ts
- packages/core/src/domain/configuration/intakeSites.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
- packages/core/src/index.ts
- packages/core/test/interceptRequests.ts
- packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/networkError/networkErrorCollection.ts
- packages/rum-core/src/browser/performanceObservable.spec.ts
- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
- packages/rum-core/src/domain/requestCollection.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
- test/e2e/lib/framework/pageSetups.ts
We collect network errors from older version sdks, because the intake urls have different prefixes. 
We check `isIntakeUrl` on parameter keywords instead of the full prefix.
---
> 👷[IR-30972] Include older version intake urls matching

- packages/rum-core/src/domain/privacy.spec.ts
- packages/rum-core/src/domain/privacy.ts
Hello,
There are multiple ways to hide an element from RUM Session Replay ([documentation](https://docs.datadoghq.com/fr/real_user_monitoring/session_replay/browser/privacy_options/)):
- Using an HTML attribute: `data-dd-privacy="allow" | "mask" | "hidden" | "mask-user-input"`
- Using CSS classes: `class="dd-privacy-allow" | "dd-privacy-mask-user-input" | "dd-privacy-mask" | "dd-privacy-hidden"`
By default, some HTML elements are automatically masked:
- Input elements of type password, email, and tel
- Elements with autocomplete attributes for credit card numbers, expiration dates, and security codes
However, this doesn't currently handle [new-password](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#new-password) and …
> ✨ add new privacy rule for autocomplete password value

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- test/e2e/scenario/rum/init.scenario.ts
An "updateViewName" function has been introduced in [RUM-4819](https://github.com/DataDog/browser-sdk/pull/2808) 
This function has been dogfooded by RUM-apps, and was proven useful.
Rename it to setViewName to match the newly introduced setViewContext / remove the experimental flag
---
[RUM-4819]: https://datadoghq.atlassian.net/browse/RUM-4819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 👷 [RUM-6562] Enable and rename update view name API

- CHANGELOG.md
- scripts/release/generate-changelog/lib/addNewChangesToChangelog.js
Every week a new staging branch is created and the `CURRENT_STAGING` variable is updated in gitlab.yml file. This creates a commit on the main branch that is not needed to include in the changelog as it has little value.
- Update the generate-changlog script to skip bump staging commit messages.
- Edit the Changelog to remove these commit to the previously released version.
---
> 👷 do not include staging bump commit to changelog

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/browser/performanceUtils.spec.ts
- packages/rum-core/src/browser/performanceUtils.ts
- packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
Resource performent entries have a workerStart property
Worker processing time is defined as workerProcessingTime = entry.fetchStart - entry.workerStart
Similarly to @resource.connect etc. we could have @resource.worker where:
@resource.worker.start would be workerStart
@resource.worker.duration would be fetchStart - workerStart
---
> [RUM-6801] Collect resource worker processing time

- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/timer.spec.ts
- packages/core/test/emulate/mockReportingObserver.ts
- packages/core/test/leakDetection.ts
- packages/core/test/registerCleanupTask.ts
- packages/rum-core/src/domain/error/trackReportError.spec.ts
We are transitionning from using `afterEach` to `registerCleanupTask` API to clean our tests. However with `registerCleanupTask`, tasks are executed in the wrong order:
<table>
<tr><th>afterEach</th><th>registerCleanupTask</th></tr>
<tr><td>
```ts
describe('Test', () => {
beforeEach(() => { 
console.log('instrument')
})
afterEach(() => { 
console.log('clean instrumentation')
})
describe('Nested test', () => {
beforeEach(() => {
console.log('instrument 2')
})
afterEach(() => { 
console.log('clean instrumentation 2')
})
})
})
```
</td><td>
```ts
describe('Test', () => {
beforeEach(() => {
console.log('instrument')
registerCleanupTask(() => {
console.log('clean instrumentation')
})
})
describe('Nested test', () => {
beforeEach(() => {
console.log('instrument 2')
registerCleanupTask(() => { …
```
> ✅ Fix test cleanup tasks order

- packages/rum-react/src/domain/reactRouterV6/startReactRouterView.spec.ts
- packages/rum-react/src/domain/reactRouterV6/startReactRouterView.ts
When the react router route `/*` is matched with the `/` (root) path, the produced view name is `/*` instead of the expected `/`.
When matching the route `/*` with the path `/`, the `*` param is an empty string (obviously). In that case, we shouldn't consider the `*` as missing and proceed with replacing the star.
---
> ⚗️🐛 [rum-react][RUM-6226] fix for empty splats

- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
PR #3118 introduced `resource.worker.start/duration` properties to reflect the time it took for a potential worker to process the resource. But those properties were defined even if no worker were present.
Make sure `workerStart` is defined (greater than 0) before using it.
---
> 🐛 skip worker timing when no worker is used

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/action/actionCollection.spec.ts
- packages/rum-core/src/domain/action/actionCollection.ts
- packages/rum-core/src/domain/action/getActionNameFromElement.spec.ts
- packages/rum-core/src/domain/action/getActionNameFromElement.ts
- packages/rum-core/src/domain/action/trackClickActions.spec.ts
- packages/rum-core/src/domain/action/trackClickActions.ts
- packages/rum-core/src/rawRumEvent.types.ts
- test/e2e/scenario/rum/actions.scenario.ts
We want to add a field to indicate from which source the action names are generated.
Add a `name_source` field in `@_dd.action` object
---
> ✨ [RUM-6956] Add action name source

- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/error/error.spec.ts
- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/trackRuntimeError.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/core/src/index.ts
- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/logger.ts
- packages/rum-core/src/domain/error/errorCollection.ts
using DD_RUM.addError(error) but the error comes from a different context than the document (ex: created insde an iframe or a window.open), the SDK doesn not consider it as an Error instance and serializes it as JSON.
Use class object to determine if it's an error or not.
---
> 🐛 [RUM-87] AddError should support Error instances coming from other JS contexts

- packages/core/src/domain/error/trackRuntimeError.spec.ts
- packages/core/src/transport/httpRequest.spec.ts
- packages/core/test/collectAsyncCalls.ts
- packages/rum/src/boot/startRecording.spec.ts
- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/trackers/trackMutation.spec.ts
Use promise in collectAsyncCalls instead of a callback.
This will also benefit for the replay lazy loading tests: [PR](https://github.com/DataDog/browser-sdk/pull/3152)
- Use promise in `collectAsyncCalls` instead of a callback. 
- Use the async await syntax in the corresponding tests.
---
> ✅ [RUM-6813] Use promise in `collectAsyncCalls` instead of a callback

- packages/core/src/domain/configuration/configuration.spec.ts
- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/intakeSites.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
- packages/core/test/coreConfiguration.ts
- packages/rum-slim/src/domain/getSessionReplayLink.spec.ts
- packages/rum/src/domain/getSessionReplayLink.spec.ts
Strongly type the site parameter, this will allow customer using typescript to have better autocompletion and avoid misconfiguration. This is not a bulletproof solution, especially if user are not using typescript, but it will help the ones that do.
If we were to add new datacenters, we would need to add them to the type definition, release a new minor and have customer update to the latest SDK.
Customer wanting to use the new datacenters without using the new SDK will still have the option to ignore the type error using `// @ts-expect-error` or `as any`
---
> ✨ [RUM-6814] strongly type site parameter

- packages/core/src/domain/configuration/tags.ts
Fix comment as we still support browser that don't support unicode character escape in regex.
---
> 👷 [RUM-6819] fix comment on browser support for unicode character escape

- packages/core/src/tools/utils/timeUtils.ts
- packages/core/test/emulate/mockClock.ts
Edit comment about the browser support of `performance.timeOrigin`
---
> 👷 [RUM-6820] fix comment about performance.timing.navigationStart

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/fixtures.ts
The “delivery type” has been introduced on resources performance entries: [PerformanceResourceTiming: deliveryType property - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/deliveryType)
---
> ✨ [RUM-6799] Add new delivery type property

- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
We had some customer cases where they have seen some sessions being recorded even if they were specifically set `sessionReplaySampling: 0`. This was caused by another SDK instance (injected via an extension) setting the session type to "replay", so it worked "as expected" but was still pretty confusing to the customer as they specifically didn't want to collect replay (for privacy reasons).
Set the default value of `startSessionReplayRecordingManually` to `true` if `sessionReplaySampleRate` is `0`, keep it `false` otherwise.
Technically, this is a small breaking change: a customer could want to record sessions only for users visiting a given page `/foo`. In that case, they could set a `sessionReplaySampleRate: 0`, and only in `/foo` they would run `startSessionReplayRecording({ force: …
> ✨ [RUM-6182] don't start recording automatically when replay sample is 0

- packages/rum/src/boot/recorderApi.spec.ts
I spotted that two Recorder tests where broken after we automatically started the recorder https://github.com/DataDog/browser-sdk/pull/2275.
---
> ✅ [RUM-6813]Fix recorder tests

- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/domain/assembly.spec.ts
- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/configuration.spec.ts
- packages/logs/src/domain/configuration.ts
Remove `sendLogsAfterSessionExpiration` option and makes sending logs after session expiration the default behavior
---
> 💥 [RUM-6816] remove sendLogsAfterSessionExpiration

- packages/rum/src/boot/postStartStrategy.ts
- packages/rum/src/boot/preStartStrategy.ts
- packages/rum/src/boot/recorderApi.spec.ts
- packages/rum/src/boot/recorderApi.ts
The recorderApi module is a bit large and we want to add more logic before starting to lazy load the recorder. It is a good time to extract the "pre start" logic like we did with RUM and Logs: https://github.com/DataDog/browser-sdk/pull/2575.
- Introduce a `Strategy` interface for behaviors that differs before and after starting the SDK.
- Introduce a `createPreStartStrategy` to initialize the strategy before the SDK is started
- Introduce a `createPostStartStrategy` to update the strategy after the SDK is started
---
> ♻️ [RUM-6813] Split the recorder API module

- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
`trackResources`, `trackLongTasks`, and `trackUserInteractions` are set by default in the snippet we provide in the Application configuration page and in the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/setup/client?tab=rum#npm) configuration 
---
> 💥 new default for track* initialization options

- packages/core/src/browser/cookie.ts
- packages/core/src/domain/session/sessionConstants.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/session/sessionState.ts
- packages/core/src/domain/session/sessionStateValidation.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/domain/session/sessionStoreOperations.spec.ts
- packages/core/src/domain/session/sessionStoreOperations.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
- packages/core/src/domain/session/storeStrategies/sessionStoreStrategy.ts
- packages/core/src/domain/user/user.spec.ts
- packages/core/src/domain/user/user.ts
- packages/core/src/index.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/core/test/emulate/mockStorages.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/rumSessionManager.ts
- packages/rum-core/test/mockRumSessionManager.ts
Add device id as anonymous id in session cookie behind a feature flag.
Maintain anonymous id when session expires.
Extend cookie age.
Same as previous PR. Already tested on staging.
---
> [RUM-6075] Test anonymous id on staging behind ff

- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
- packages/rum-core/src/domain/tracing/tracer.spec.ts
Improve Trace <> RUM correlation with RUM without limits
makes `sampled` the new default for traceContextInjection init option
---
> 💥 [RUM-7676] default traceContextInjection to sampled

- .eslintrc.js
- .gitlab-ci.yml
- eslint-local-rules/disallowNonScripts.js
- package.json
- scripts/deploy/deploy.js
- scripts/deploy/deploy.spec.js
- scripts/deploy/lib/testHelpers.js
- scripts/deploy/upload-source-maps.js
- scripts/deploy/upload-source-maps.spec.js
- scripts/lib/gitUtils.js
Our deployment scripts have become increasingly complex, and the lack of tests makes further changes both challenging and prone to errors. This PR adds test for the CDN deployment script and the source maps upload script.
I’ve chosen to test the scripts by verifying their outputted commands rather than splitting the script and testing each function. I found this approach clearer, as it allows us to easily see the expected commands directly in the tests.
- Adds tests deploy.spec.js and upload-source-maps.spec.js
- Adapt eslint rules for script spec files
---
> 👷 [RUM-7634] Add deploy and source maps upload scripts tests

- packages/core/src/domain/error/error.ts
- packages/rum-core/src/domain/error/errorCollection.spec.ts
Recently, all errors of type [AxiosError](https://github.com/axios/axios/blob/ce350f1e2163a7c3b7dec874fc9991038f0dc4f9/lib/core/AxiosError.js#L16-L34) stopped logging properly. Instead of the standard log with Error object, it was serializing the error object instead.
After some investigation I tracked down the regression to #3144 - which changes the object type check from `param instanceof Error` to `Object.prototype.toString.call(error) === '[object Error]'`. Unfortunately, the way AxiosError is created, that toString call just produces `[object Object]`. However, the `instanceof` check works just fine.
I've addressed the regression by using both the original `instanceof Error` check as well as the new `toString` check. Supporting both checks cover both the old and the new feature …
> 🐛 AddError should support all instances of type Error

- packages/core/src/tools/stackTrace/capturedExceptions.specHelper.ts
- packages/core/src/tools/stackTrace/computeStackTrace.spec.ts
- packages/core/src/tools/stackTrace/computeStackTrace.ts
Support Electron apps when using custom schema. 
https://github.com/DataDog/browser-sdk/issues/3131
Add new work to the regex that parses error URLs.
---
> ✨ Support custom schema for Electron

- packages/core/src/tools/serialisation/sanitize.spec.ts
- packages/core/src/tools/serialisation/sanitize.ts
Enhance serialization for `Event` and `RegExp`
---
> ✨ [RUM-175] sanitize RegExp and Event

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/session/oldCookiesMigration.spec.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/session/sessionState.ts
- packages/core/src/domain/session/sessionStore.spec.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/domain/session/sessionStoreOperations.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/core/test/coreConfiguration.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/logsSessionManager.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/mockRumConfiguration.ts
- test/e2e/lib/helpers/session.ts
- test/e2e/scenario/rum/sessions.scenario.ts
- test/e2e/scenario/sessionStore.scenario.ts
Remove the anonymous id feature flag to prepare for v6 release
Removed feature flags everywhere
Fixed unit and e2e tests of session storage to include anonymous id
---
> 💥 [RUM-7704] Remove anonymous user feature flag for v6

- developer-extension/src/panel/hooks/useEvents/eventFilters.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/action/actionCollection.spec.ts
- packages/rum-core/src/domain/action/actionCollection.ts
- test/unit/karma.base.conf.js
In  the v6 branch, we started seeing a lot of leak detection warnings. We identified that the main issue was brought by https://github.com/DataDog/browser-sdk/pull/3190, switching the default `trackUserInteraction` to `true`: since we are now tracking user interaction every time `startActionCollection` is called, we need to clean it up as well.
Another issue was identified in the leak detection logic: the leak detection cleanup was done too soon, and the `removeEventListener` function was unpatched before some events were removed. [Because leak detection is wrapping the listener function into another "`wrappedListener`" function](https://github.com/DataDog/browser-sdk/blob/8acb3d08836977188a260060709cd7f1609c04f5/packages/core/test/leakDetection.ts#L24), the original function failed to be …
> ✅ fix leak detection issues

- scripts/deploy/deploy.js
- scripts/lib/gitUtils.js
- scripts/performance/lib/reportAsAPrComment.js
The PR comments are broken since #3211 because `LOCAL_BRANCH` does not exist anymore (it has been replaced by a `getLocalBranch` function).
Restore `LOCAL_BRANCH`, remove `getLocalBranch`, as I don't see any reason why it should be a function (but maybe @amortemousque has more context)
---
> 💚 fix CI PR comment

- test/e2e/scenario/sessionStore.scenario.ts
In v6 we now have both `id` and `aid` in the session cookie / local storage
fix e2e to match `id` but not `aid`
---
> ✅ fix session store e2e to account for anonymous id

- scripts/deploy/upload-source-maps.js
- scripts/deploy/upload-source-maps.spec.js
We don't suffix chunks, so we should not try to rename them as this would fail:
```
Error: Command failed with exit status 1: mv packages/rum/bundle/chunks/recorder-d7628536637b074ddc3b-datadog-rum.js packages/rum/bundle/chunks/recorder-d7628536637b074ddc3b-datadog-rum.js
---- stderr: ----
mv: 'packages/rum/bundle/chunks/recorder-d7628536637b074ddc3b-datadog-rum.js' and 'packages/rum/bundle/chunks/recorder-d7628536637b074ddc3b-datadog-rum.js' are the same file
----
```
We didn't ran into the issue before because `deploy-next-major-canary` don't upload sourcemaps (I guess we should fix that for next time)
---
> 👷 do not rename bundle file when name does not change

- packages/rum/src/boot/lazyLoadRecorder.ts
- packages/rum/src/boot/postStartStrategy.ts
- packages/rum/src/boot/recorderApi.ts
Webpack throws  `ChunkLoadError` if a chunk fail to load. This PR prevents collecting the webpack ChunkLoadError as it is already collected as a RUM resource.
Catch ChunkLoadError and do nothing
---
> 🐛 Prevent collecting the webpack ChunkLoadError

- packages/rum/test/segments.ts
- test/e2e/scenario/recorder/recorder.scenario.ts
`record input interactions` and `don't record ignored input interactions` are the two most flacky e2e tests. This is because they are ensuring they only collect one segment, however, we have _recently_ [reduce the batch time limit](https://github.com/DataDog/browser-sdk/pull/3077) for replay segments to 5 seconds. It seems this test might takes longer sometimes, generating more segments that initially expected.
Stop expecting a fix number of segments and flatmap search for records across all segments when needed.
This only fixes these two tests as they are the only real flaky ones, but we could extend this strategy to all other tests if needed.
---
> ✅ don't rely on segment counts on e2e tests

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
This PR adds code to generate the new web vitals attribution fields that were added to the event format in [this PR](https://github.com/DataDog/rum-events-format/pull/240).
For now, the old web vitals fields remain. To remove them safely without breaking backwards compatibility, we need backend changes, so we'll hold off until those are done.
* The `rum-events-format` submodule has been updated to include the new fields.
* The new fields have been added to the appropriate type definitions.
* The code to populate the new fields has been added to `viewCollection.ts`.
* The tests have been updated appropriately.
---
> ✨ [RUM-6567] Generate new web vitals attribution fields

- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- test/e2e/scenario/rum/init.scenario.ts
After adding set view context we need to have a get view context api
Add a new api
---
> ✨ [RUM-7572] Add get api of view specific context

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/test/fixtures.ts
When trying to understand the causes and impact of a Cumulative Layout Shift score, it's often helpful to see how the affected element's position and size has changed.
This PR adds the capability to capture the previous and current rects associated with layout shifts on supported browsers. The changes build on the standard [LayoutShiftAttribution](https://developer.mozilla.org/en-US/docs/Web/API/LayoutShiftAttribution) API and the recent changes in [rum-events-format](https://github.com/DataDog/rum-events-format/pull/242) which gave us a place to store this data.
---
> ✨ [RUM-6565] Capture previous and current rects in CLS attribution data

- test/e2e/scenario/recorder/recorder.scenario.ts
- test/e2e/scenario/rum/actions.scenario.ts
two e2e test start failing quite consistently since around a week ago on Chrome android. The root cause is increased latency in the webdriver <> browserstack connection wich makes 3 consecutive clicks happens slower than a second, not triggering the expected `rage_click` frustration.
The mitigation involve using synthetic events instead of webdriver's API to guaranty the clicks happens fast enough to be recognized as rage clicks.
This is not ideal and will be revisited in the future when we move away from webdriver protocol.
---
> ✅ mitigate e2e protocol latency

- packages/core/src/domain/report/reportObservable.spec.ts
- scripts/test/export-test-result.js
- test/e2e/scenario/recorder/recorder.scenario.ts
- test/e2e/scenario/rum/actions.scenario.ts
Three tiny fixes:
- fix a some test that show as failed in test visibility because they are skipped but the `afterEach` throws an error. (but Gitlab still mark the job as passed)
- remove unnecessary allowUntrustedEvents options in some e2e test setup
- add logs in export test report script 
---
> 👷 various tiny fixes

- packages/core/src/index.ts
- test/e2e/lib/framework/createTest.ts
- test/e2e/lib/framework/intakeRegistry.ts
- test/e2e/scenario/telemetry.scenario.ts
Telemetry usage e2e test were missing
- Add missing e2e test for `telemetryUsage`
- Add comment explaining why we setup `*SampleRate: 100` in the default e2e test config. 
---
> ✅ Add e2e test for telemetry usage

- packages/rum-react/src/domain/performance/reactComponentTracker.spec.tsx
fix the following error:
```
/go/src/github.com/DataDog/browser-sdk/packages/rum-react/src/domain/performance/reactComponentTracker.spec.tsx
42:9   error  Identifier 'UNSTABLE_ReactComponentTracker' is not in camel case  camelcase
80:13  error  Identifier 'UNSTABLE_ReactComponentTracker' is not in camel case  camelcase
```
use `as` to import `ReactComponentTracker` without the `UNSTABLE` prefix in spec file. This avoid multiple `eslint-disable-next-line` comments and will generate smaller diff when making the component stable.
---
> 👷 fix eslint error on UNSTABLE_ReactComponentTracker case

- packages/rum-core/src/boot/startRum.spec.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/urlContexts.spec.ts
- packages/rum-core/src/domain/contexts/urlContexts.ts
- packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/hooks.spec.ts
- packages/rum-core/src/hooks.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/test/formatValidation.ts
- packages/rum-core/test/mockContexts.ts
The overall goal is to create a Modular SDK to simplify contributions and enhance extensibility.
This PR introduces a **hook system**, initially used to `decouple event assembly`. Each collection module can now independently handle the assembly of its own properties.
- Introduce a Hooks system
- Use the Assemble hook in viewCollection to manage the assembly of view properties
- Use the Assemble hook in urlContext to manage the assembly of url properties
---
> ♻️ [RUM-8123] Introduce a hook to assemble events

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/browser/performanceUtils.ts
- packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.spec.ts
- packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
- packages/rum-core/test/fixtures.ts
Before this PR, we used the navigation entry duration as the duration for the document resource. However, that duration includes the time it takes to load the page until the `load` event (including the load of assets declared in the HTML like JS, CSS, images...).
This PR fixes this by adjusting the duration to `responseEnd`, which conforms with the duration of other resource entries.
---
> 🐛 fix document resource duration

- packages/rum/src/domain/record/trackers/trackStyleSheet.spec.ts
registerCleanupTask fail when the test is [skipped](https://github.com/DataDog/browser-sdk/blob/61fda307c02d80acbe694a9d2cab5646348401e8/packages/rum/src/domain/record/trackers/trackStyleSheet.spec.ts). The job will pass but CI visibility will mark the test as failed.
---
> ✅ fix failing skipped test

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/contexts/viewHistory.spec.ts
- packages/rum-core/src/domain/contexts/viewHistory.ts
- packages/rum-core/src/domain/lifeCycle.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- test/e2e/scenario/rum/init.scenario.ts
Updating of view context automatically triggers view updates, which could trigger excessive requests in edge cases. We should throttle view updates while maintaining current view context update behavior.
Added a new LifeCycleEvent type so we can update the view context for in viewHistory immediately
Use `scheduleViewUpdate` to throttle the view updates
---
> 🐛 [RUM-8353] Throttle view context update

- packages/rum/src/domain/replayStats.ts
The browser SDK generates internal metadata about the size of replay data for each view in a data structure called `ReplayStats`; this helps us debug when something goes wrong. This metadata is also used internally to track whether each view has any replay data at all; when a view update is sent to the server, the `ReplayStats` data is translated into a flag called `has_replay` that's used by Datadog's Session Replay UI.
To avoid consuming memory unnecessary, the browser SDK currently only tracks `ReplayStats` for the last 10 views; the `ReplayStats` for older views are dropped. This is controlled in the code by the `MAX_STATS_HISTORY` constant.
Some SPA websites change `document.location` very quickly, which can cause them to generate new views extremely fast. We've observed that in rare …
> 🐛 [RUM-7694] - Keep more ReplayStats history to avoid wrongly marking views as having no replay

- packages/rum-core/src/browser/viewportObservable.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/formatValidation.ts
Remove `RumContext` type in favor of  `CommonProperties` type which is auto generated by the rum event format. 
---
> 🔥 Remove RumContext type

- packages/core/src/tools/valueHistory.spec.ts
- packages/core/src/tools/valueHistory.ts
When assembling an event for a given timestamp, the **view context** is found, but the **URL context** is missing. (cf [telemetry PR](https://github.com/DataDog/browser-sdk/pull/3313)) 
```ts
const viewHistoryEntry =  viewHistory.findView(startTime) // get an entry
const urlContext = urlContexts.findUrl(startTime) // get undefined
```
This happens because both `viewHistory` and `urlContexts` rely on `createValueHistory`, which clears old entries via `setInterval`. So, the clean-up task of the URL context occurs before the view context.
<table>
<tr><td>What happens</td><td>What we expect</td></tr>
<tr><td>
1.  `urlContexts` cleanup task runs first.
2. Event is assembled, but URL context is missing.
3. `viewHistory` cleanup task runs. 
</td><td>
1.  `urlContexts` cleanup task runs
2. …
> 🐛 Fix missing URL context

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
GA remote configuration
- Remove 'remote_configuration' feature flag
---
> ✨ GA remote configuration

- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/limitModification.spec.ts
- packages/rum-core/src/domain/limitModification.ts
- packages/rum-core/src/rumEvent.types.ts
We want to be able to modify `source_url` and `invoker` properties of Loaf script attributions from the `beforeSend` function. This allow customer to scrub urls for potential PII.
Refactor `limitModification` to allow arrays to be present in the path. (e.g. `long_task.scripts[].source_url` will allow to modify `source_url` in long tasks (LoaF) events
Allow modification on `long_task.scripts[].source_url` and `long_task.scripts[].invoker`
---
> ✨ Allow to modify source_url property in Loaf script attributions

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/action/actionCollection.spec.ts
- packages/rum-core/src/domain/action/actionCollection.ts
- test/e2e/scenario/rum/actions.scenario.ts
Masquerade apps, login apps, etc. apps without authentication are not handled by current feature flag roll out workflows. This could cause different subdomains not covered with `dd-action-name` have arbitrary data in action names.
Remove feature flag of `action_name_masking`, so we have name_source everywhere with latest version.
---
> [RUM-8526] Remove ff for action name masking

- packages/rum-core/src/domain/contexts/viewHistory.spec.ts
- packages/rum-core/src/domain/contexts/viewHistory.ts
- packages/rum-core/src/domain/lifeCycle.ts
- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
- test/e2e/scenario/rum/init.scenario.ts
Excessive requests could be triggered when sending too much data, so every view update triggers requests. Related PR https://github.com/DataDog/browser-sdk/pull/3314 is on v6. Backporting this fix to v5 to mitigate the situation.
Note: the issue will still persist while triggering view updates through other APIs.
---
> ⚡ [RUM-8353] throttle view update in set view context

- developer-extension/src/panel/backgroundScriptConnection.ts
- developer-extension/src/panel/components/app.tsx
Connect background script when the developer extension loads. This prevent error message in [unit test console](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/811453829):
```
Chrome Headless 133.0.0.0 (Linux x86_64) ERROR LOG: 'Datadog Browser SDK extension:', '[backgroundScriptConnection]', 'While creating connection:', TypeError: Cannot read properties of undefined (reading 'connect')
TypeError: Cannot read properties of undefined (reading 'connect')
at connectToBackgroundScript (http://localhost:9876/absolute/tmp/_karma_webpack_607690/commons.js?7e5dad90306c0398a735c523345dcf0765954e1f:1193:49)
at ./developer-extension/src/panel/backgroundScriptConnection.ts (http://localhost:9876/absolute/tmp/_karma_webpack_607690/commons.js?7e5dad90306c0398a735c523345dcf0765954e1f:1185:1)
at …
```
> 👷 only connect to background script when the extension is actually loaded

- packages/rum-core/src/domain/getSelectorFromElement.spec.ts
- packages/rum-core/src/domain/getSelectorFromElement.ts
In v6, we dropped support for browsers not supporting ES2015. I found a couple of "old browser mitigations" that are not relevant anymore.
* Assume the browser supports CSS `:scope` ([caniuse](https://caniuse.com/mdn-css_selectors_scope))
* Assume the browser supports `element.isConnected` ([caniuse](https://caniuse.com/mdn-api_node_isconnected)) (also we already [assume this for session replay](https://github.com/DataDog/browser-sdk/blob/a1ba24165e3d424d1894870242ad0c73b191f102/packages/rum/src/domain/record/trackers/trackMutation.ts#L135))
---
> 🔥 remove some workarounds related to unsupported browsers

- packages/rum-core/src/browser/crypto.ts
- packages/rum-core/src/domain/tracing/identifier.spec.ts
- packages/rum-core/src/domain/tracing/identifier.ts
- packages/rum-core/src/domain/tracing/tracer.ts
`getCrypto` was used to retrieve the correct API depending on the browser. Now that we dropped IE11 we can directly use `window.crypto`.
Remove getCrypto and use `window.crypto`.
---
> ♻️ Use `window.crypto` instead of `getCrypto` wrapper

- .gitlab-ci.yml
- package.json
- test/e2e/lib/framework/pageSetups.ts
Refactor, so that the e2e test can be run in https://github.com/DataDog/rum-events-format/pull/253
- Move build from gitlab config to npm script
- use `process.env.CI` instead of `process.env.CI_JOB_ID` because it is available both in github and gitlab
---
> ♻️ [RUM-59] refactor npm scripts

- test/e2e/lib/framework/createTest.ts
- test/e2e/lib/helpers/validation.ts
Format error when validating events:
---
> 👷 format rum event format validation errors

- packages/core/test/forEach.spec.ts
- packages/rum-react/src/domain/error/errorBoundary.spec.tsx
- packages/rum-react/src/domain/performance/reactComponentTracker.spec.tsx
- packages/rum-react/src/domain/reactRouterV6/routesComponent.spec.tsx
- packages/rum-react/src/domain/reactRouterV6/useRoutes.spec.tsx
- packages/rum-react/test/appendComponent.ts
Following the use of act in react-router test, change all flushsync to avoid error log in test. 
Update flushsync, set isReactEnvironment to true to avoid this error : 'The current testing environment is not configured to support act(...)'
---
> ✅ Change flush sync into act

- packages/core/src/domain/console/consoleObservable.spec.ts
- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/error/error.spec.ts
- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/error.types.ts
- packages/logs/src/domain/console/consoleCollection.spec.ts
- packages/logs/src/domain/console/consoleCollection.ts
- packages/logs/src/domain/createErrorFieldFromRawError.spec.ts
- packages/logs/src/domain/logger.spec.ts
- packages/logs/src/domain/report/reportCollection.ts
- packages/logs/src/domain/runtimeError/runtimeErrorCollection.spec.ts
- packages/logs/src/domain/runtimeError/runtimeErrorCollection.ts
- packages/rum-core/src/domain/error/errorCollection.spec.ts
- packages/rum-core/src/domain/error/errorCollection.ts
- packages/rum-core/src/domain/error/trackConsoleError.spec.ts
When throwing an exception in an App, Browser SDK users sometimes want to provide more context that is only accessible locally when the error is constructed.
support error.dd_context as a custom error property
---
> ✨ [RUM-7459] Collect error context from a custom Error field

- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
The property url report an empty string if the value is not available, we shouldn't report it in this case.
Add a check  function to discard empty string value
---
> 🐛 Fix empty string for resource url in LCP 

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/tracing/sampler.spec.ts
- packages/rum-core/src/domain/tracing/sampler.ts
Before, the `traceSampleRate` was re-evaluated randomly for each request.
With this PR, the `traceSampleRate` is computed based on the session id, ensuring all request of a given session are either traced or not.
* Remove the flag introduced by #3352 
---
> ✨ [RUM-8622] introduce session-consistent trace sample rate

- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/viewCollection.spec.ts
- packages/rum-core/src/domain/view/viewCollection.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
https://datadoghq.atlassian.net/browse/RUM-8744
Implementation of small adjustments in Browser SDK for CLS attribution:
- Include `devicePixelRatio` attribute: 
- Recent discoveries showed that Layout Instability API does not report viewPort coordinates for `prevRect` and `currentRect`.
- We'd need to include this data in `_dd.cls.device_pixel_ratio`. See [this document](https://datadoghq.atlassian.net/wiki/spaces/~614b8bf2071141006ad0cebd/pages/4757587959/Bug+discovered+on+Google+Layout+Instability+API) for more context
- Include new attribute `devicePixelRatio` in the CLS attribution
Tested in local:
---
> 🐛 [RUM-8744] CLS tracking: provide cls `devicePixelRatio` to adjust cls rect scale

- test/e2e/lib/helpers/browser.ts
Firefox is sometimes showing a console warning about `Layout was forced before the page was fully loaded.` in our e2e tests. It's not consistent but makes test to fails unexpectedly from time to time. 
---
> 👷 filter out "Layout was forced..." console warning in e2e tests on Firefox

- packages/rum/src/boot/lazyLoadRecorder.spec.ts
- packages/rum/src/boot/lazyLoadRecorder.ts
- packages/rum/src/boot/recorderApi.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.spec.ts
- packages/rum/src/domain/deflate/deflateWorker.ts
- packages/rum/src/domain/scriptLoadingError.ts
Lazy loading the recorder module can fail, either due to a customer-side issue (like a CSP misconfiguration) or due to an issue on our end (like failing to upload the chunk to the CDN). We should report an error when this happens and add telemetry.
The current situation is a bummer since the failure is totally silent; no error is reported anywhere. I spent quite a bit of time over the past couple of days trying to understand why one of my local changes wasn't working. The root cause turned out to be #3324; the problem would've been instantly obvious with the changes in this PR.
This PR adapts the current error reporting we do when the compression worker fails to load so that it can be used for both the compression worker and the lazy loaded recorder module. We now use the same code in …
> 🐛 [RUM-8429] Report an error when lazy loading the recorder module fails

- packages/core/src/domain/configuration/configuration.ts
Added missing JSDoc comment for the beforeSend configuration option to maintain documentation consistency.
Added documentation comment for the beforeSend callback function in InitConfiguration.
---
> [RUM-8912] Add documentation to the beforeSend function in configuration

- webpack.base.js
The default webpack strategy to lazy load chunks is "jsonp" which adds around 4kb to bundles
Using "import" should reduce the webpack boilerplate for lazy-loading bundles.
---
> ⚡️ use `import()` for lazy loading chunks

- webpack.base.js
This is one of a series of PRs experimenting with enabling more aggressive options for Terser, with the goal of reducing the size of the browser SDK bundles.
This PR enables the following options:
* `passes: 4`
The default is `passes: 2`. I tried `passes: 3` as well in [this draft PR](https://github.com/DataDog/browser-sdk/pull/3415), but `passes: 4` seems to be enough of an improvement to be worth it.
---
> 👷 Use four Terser passes

- webpack.base.js
This is one of a series of PRs experimenting with enabling more aggressive options for Terser, with the goal of reducing the size of the browser SDK bundles.
This PR enables the following options:
* `unsafe_methods: true`
* `ecma: 2018` (Using `ecma: 6` or greater is required for `unsafe_methods`; I matched the target we're using for webpack.)
* `module: true` (This specifies that we're bundling ES modules, again matching the webpack configuration.)
The focus here is `unsafe_methods: true`. Here's what the Terser docs have to say about it:
> unsafe_methods (default: false) -- Converts { m: function(){} } to { m(){} }. ecma must be set to 6 or greater to enable this transform. If unsafe_methods is a RegExp then key/value pairs with keys matching the RegExp will be converted to concise …
> 👷 Enable the Terser unsafe_methods option

- developer-extension/src/panel/components/tabs/eventsTab/eventRow.tsx
`DD_LOGS.logger.log({})` crashes the extension
Use the Json component to display the value in this case.
---
> [devext] 🐛 fix non-string log message

- .gitlab-ci.yml
when integrating a branch to staging, the test-performance job does not add much value. Skipping it will make deployment of staging branch almost 2 times faster.
---
> 🔧 Update GitLab CI to exclude staging branch from performance tests

- webpack.base.js
This is one of a series of PRs experimenting with enabling more aggressive options for Terser, with the goal of reducing the size of the browser SDK bundles.
This PR enables the following options:
* `unsafe: true`
Here's what the Terser docs have to say about `unsafe: true`:
> It enables some transformations that might break code logic in certain contrived cases, but should be fine for most code. It assumes that standard built-in ECMAScript functions and classes have not been altered or replaced. You might want to try it on your own code; it should reduce the minified size. Some examples of the optimizations made when this option is enabled:
> * new Array(1, 2, 3) or Array(1, 2, 3) → [ 1, 2, 3 ]
> * Array.from([1, 2, 3]) → [1, 2, 3]
> * new Object() → {}
> * String(exp) or exp.toString() …
> 👷 Enable the Terser unsafe option

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.ts
When a page is in background, the browser can pause or slow down its execution to preserve resources. This is known to skew page-load related metrics (ex: vitals like FCP/FID and other like `@view.loading_time`): when the user opens a page in background (ex: middle click), those timings can be arbitrary long (as long as the tab stays in background). This is why we try to detect that a page was hidden/in background and discard those timings in this case.
But we only do so once init is called: we don’t know whether a page was in background before init is called, or even before the SDK was loaded.
Chrome is providing Performance entries called visibility-state that are notified whenever a page gets hidden/visible: [VisibilityStateEntry - Web APIs | …
> 🐛 [RUM-8606] Track First Hidden before init

- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/transport/httpRequest.spec.ts
- packages/core/src/transport/httpRequest.ts
- packages/core/test/interceptRequests.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
Over time we've added a fixes to our xhr strategy to account for bad implementations/overrides (IE content type header, multiple onResponse callbacks, untrusted events...)
Instead of yet another fix to account for the combination of dynatrace + zonejs making xhr request to fail, and as we don't support IE anymore, we can use plain fetch instead of xhr.
closes #3394 
---
> ♻️ [RUM-8795] Replace XHR with Fetch for HTTP requests

- packages/core/src/domain/configuration/configuration.ts
If options are not aligned between RUM and LOGS the SDK could not initialised correctly.
Add Js doc to highlight this better
---
> 📝 [RUM-7705] Add js doc about option that need to be aligned

- webpack.base.js
This reverts commit b8f902ec1dec9eaa9ceb3bb31ef97739e7e61b27.
```
Datadog Browser SDK: Recorder failed to start: an error occurred while initializing the module: TypeError: Failed to resolve module specifier './chunks/recorder-94a4290a03c458bec36d-datadog-rum.js'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
```
---
> Revert "⚡️ use `import()` for lazy loading chunks (#3399)"

- packages/rum-core/src/domain/view/trackViews.spec.ts
- packages/rum-core/src/domain/view/trackViews.ts
Follow-up on #3406. After discussion with the backend, we figured that setting the view as inactive on potential page exit was not worth it:
* The backend already "closes" (set is_active to false) the view for us after 20 minutes of inactivity
* Setting the view as inactive too soon could have an impact on rum2metrics if the page stays active
* Sending View updates on inactive views is unexpected from a backend perspective, so we would need to add extra logic so reset `is_active:true` for future updates.
* The "active" view concept is already used within the SDK to designate the current view. Diverging from this would be confusing
Don't set view as inactive on page exit, just trigger an update.
---
I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIB …
> 👌 [RUM-99] don't set views as inactive when the page is exiting

- packages/rum/src/boot/profilerApi.ts
- packages/rum/src/domain/profiling/profiler.spec.ts
- packages/rum/src/domain/profiling/profiler.ts
- packages/rum/src/domain/profiling/transport/transport.ts
- packages/rum/src/domain/profiling/types/rumProfiler.types.ts
- packages/rum/src/domain/profiling/utils/longTaskRegistry.ts
- Attribute `view.ids` had a `s` that was not coherent with other attributes.
- Views are missing from the exported JSON.
- Long Tasks are missing the  RUM Long Task `id` (when available)
- Long Tasks are full `PerformanceEntry` objects, and we don't need most of it.
- Fix how we capture views so that we now report them properly. 
- Add name to view entry so that Profiling BE can do aggregation using that name. In the UI it would ultimately use the `viewId` to get the latest name.
- Make sure attribute fields are coherent.
- Add `id` to the Long Task entry, and make it a lighter object than the full performance entry.
- Tested locally and in staging that everything is now reported. 
- In staging, you can : 
- Open any page, 
- Stay on a single page from the initial page load
- Assert that …
> [RUM Profiler] Improvements around Views and Long Tasks

- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/browser/cookieObservable.spec.ts
- packages/rum-core/src/browser/cookieObservable.ts
- packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
- packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
The test `should notify observers on cookie change` is very flaky and it does not seems to be cause by the test setup or mocks.
In the other hand the fallback does not seems to suffer the same problems, so let's only use the fallback
---
> ♻️ Refactor cookieObservable to not rely on cookieStore

- packages/rum/src/domain/profiling/profiler.spec.ts
- packages/rum/src/domain/profiling/profiler.ts
- packages/rum/src/domain/profiling/types/rumProfiler.types.ts
- Whenever the visibility change to `hidden` (eg. user switch away to another tab), the profiler is paused. 
- Whenever users come back, the profiler is not re-started properly and does not collect profiles anymore.
- On pause, we are cleaning-up tasks including the listeners to `DOM_EVENT.VISIBILITY_CHANGE`. 
- When user comes back, nothing is listening to `DOM_EVENT.VISIBILITY_CHANGE` value and thus the profiler is never restarted.
- Move "global" listeners outside of the instance (eg. visibility change and unload handlers). Global listeners are not associated to a single instance and now live outside.
- Add unit test.
---
> [RUM Profiler] Fix collection of profiles after visibility change

- packages/rum-react/.npmignore
Currently the entry point to react router v7 is not accessible via NPM
Update .npmignore to fix that
---
> 🐛 Update .npmignore to include react-router 7

- scripts/release/check-release.js
We recently released a pr to use local tarballs for e2e test (instead of portals)
The check-release script was failing for release due to not filtering the new type of dependencies used in test apps. 
Filter "file : "
---
> 👷 Filter out package.json files for check release script

- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
- packages/rum-core/src/domain/tracing/tracer.spec.ts
- packages/rum-core/src/domain/tracing/tracer.ts
Switch usr.id / account.id context forwarding to `baggage` instead of `tracestate`. 
Adds a flag `propagateTraceBaggage` to activate the baggage forwarding.
---
> use baggage for user.id / account.id forwarding

- packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
- packages/rum-core/src/domain/contexts/pageStateHistory.ts
- packages/rum-core/test/emulate/mockPerformanceObserver.ts
When a page is in background, the browser can pause or slow down its execution to preserve resources. Our SDK currently tracks page state changes (active, passive, hidden, frozen, terminated) to understand user engagement and to properly interpret performance metrics. However, we only start tracking these states after the SDK is initialized, which can create a gap in our understanding of the page's history.
Currently, our page state tracking begins only after the SDK is initialized. This means we have no visibility into the page's state history before initialization.
Chrome provides Performance entries called 'visibility-state' that are recorded whenever a page changes visibility state. We can use performance.getEntriesByType('visibility-state') to retrieve these entries and backfill our …
> ✨ [RUM-9302] Page state consolidation

- packages/core/src/domain/context/contextManager.spec.ts
- packages/core/src/domain/context/contextManager.ts
- packages/logs/src/boot/logsPublicApi.spec.ts
- packages/rum-core/src/boot/rumPublicApi.spec.ts
- packages/rum-core/src/domain/contexts/accountContext.spec.ts
- packages/rum-core/src/domain/contexts/userContext.spec.ts
Certain context properties like `usr.id` and `usr.name` are converted to strings. This PR stops converting `undefined` and `null` values to strings, aligning the behavior with other context properties.
ex: 
```ts
DD_RUM.setUser({ id: null, name: undefined })
````
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
```json
{ 
"id": "null", 
"name": "undefined", 
}
```
</td><td>
```json
{ 
}
```
</td></tr>
</table>
---
> 🐛 Improve context properties sanitization

- packages/core/src/domain/context/contextManager.spec.ts
Some logs are shown when running unit tests.
Mock display.error so they aren't showing up.
---
> ✅ hide unexpected unit test logs

- .gitlab-ci.yml
Some time to time I'm frustrated that there is no timestamps in gitlab logs, this fixes it.
Note that this is a feature-flag, but it was also [enabled in web-ui](https://github.com/DataDog/web-ui/pull/193581) so it's probably safe to use in our repo too.
---
> 👷 Enable timestamps for GitLab CI logs in configuration

- packages/rum-core/src/domain/tracing/tracer.spec.ts
- packages/rum-core/src/domain/tracing/tracer.ts
This lets the APM backend know about the Session which started a trace, useful for Joint Sampling, and also for ad-blocker metrics
* Refactor tracer test setups a bit
* Refactor baggage header formatting
* Add some unit tests on baggage header
* ... and finally, propagate `session.id``
> ⚗️ ✨  [RUM-8365] Propagate session id in `baggage` header

- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/displayContext.spec.ts
- packages/rum-core/src/domain/contexts/displayContext.ts
- packages/rum-core/test/mockContexts.ts
Decouple the display context from assembly using hooks
---
> ♻️ Decouple the display context from assembly using hooks

- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/connectivityContext.spec.ts
- packages/rum-core/src/domain/contexts/connectivityContext.ts
Decouple the connectivity context from assembly using hooks
---
> ♻️ Decouple the connectivity context from assembly using hooks

- packages/logs/webpack.config.js
- packages/rum-slim/webpack.config.js
- packages/rum/webpack.config.js
- packages/worker/webpack.config.js
- scripts/dev-server.js
- webpack.base.js
When using the `Use development bundles` feature of the developer extension, with the `On NPM setup` experimental option, I would receive the following message from the application (Chrome 135):
- Force the publicPath in webpack config to be `http://localhost:8080` when in development mode. 
The browser SDK extension now shows the version as `dev` as expected, however, the following warning is issued:
Functions updated in the development SDK seems to be called properly.
Take the PR locally, run `yarn dev` and find a website using NPM to bundle the SDK. Try to override with your local bundles using: 
---
> ✨ Add publicPath configuration to webpack setups

- packages/core/src/tools/stackTrace/computeStackTrace.spec.ts
- packages/core/src/tools/stackTrace/computeStackTrace.ts
Add support for parsing correctly stack trace in a safari wasm context. Cf https://github.com/DataDog/browser-sdk/issues/3479
Modify computeStackTrace function / add unit test
---
> 🐛 [RUM-9465] Add support for parsing Safari Wasm stack trace

- developer-extension/src/content-scripts/main.ts
- packages/logs/webpack.config.js
- packages/rum-slim/webpack.config.js
- packages/rum/webpack.config.js
- packages/worker/webpack.config.js
- scripts/dev-server.js
- webpack.base.js
Since v6, we lazy load some chunks (session replay, profiler) from the main SDK bundle. This broke the developer extension "Use development bundle on NPM setup" feature as we are loading the SDK code in an inline `<script>` tag and the Webpack runtime does not know from which URL it should load the chunks.
https://github.com/DataDog/browser-sdk/pull/3488 fixed this issue by configuring Webpack to hardcode the dev server URL (`http://localhost:8080`) in the development bundle.
Unfortunately, it turns out doing this broke local e2e test execution as (since #3420) the SDK code is loaded through [a "proxy"](https://github.com/DataDog/browser-sdk/blob/8f0b943a179d2b3e5c3a4230b3264074bac54c65/test/e2e/lib/framework/serverApps/mock.ts#L126) and the dev server (`http://localhost:8080`) isn't …
> 🐛 [devext] fix "Use development bundle on NPM setup"

- packages/core/src/domain/console/consoleObservable.ts
- packages/core/src/domain/error/error.spec.ts
- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/trackRuntimeError.spec.ts
- packages/core/src/domain/error/trackRuntimeError.ts
- packages/core/src/tools/stackTrace/computeStackTrace.ts
- packages/logs/src/domain/console/consoleCollection.spec.ts
- packages/logs/src/domain/logger.ts
- packages/rum-core/src/domain/error/errorCollection.ts
- packages/rum-core/src/domain/error/trackConsoleError.spec.ts
Small refactors around errors to reduce maintenance, reduce bundle size, and potentially simplify generating error events from the `rum-react` plugin (cf "Enable web targets of mobile platforms" project)
* compute the error stack trace in `computeRawError`, so we don’t have to compute it in most places
* use `computeRawError` everywhere (the only place missing was in `consoleObservable`)
* make sure we don’t generate unusable stack traces (from onerror)
As this is mostly a refactor, the functional changes are limited, although we should have the error type for errors collected from console.error now.
Using `yarn dev` sandbox:
```js
DD_RUM.init({
clientToken: 'xxx',
applicationId: 'xxx',
})
DD_LOGS.init({
clientToken: 'xxx',
forwardErrorsToLogs: true,
})
console.error('This is an error …
```
> ♻️ [RUM-9667] refactor stack trace computation

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/resource/resourceUtils.spec.ts
- packages/rum-core/src/domain/resource/resourceUtils.ts
To debug network-level issues with sending data to the intake, it would be useful to optionally record the network requests, instead of filtering them out as we do now.
This PR adds an experimental feature flag that enables recording of network requests to the intake.
It's straightforward to test this feature locally by enabling the new experimental feature flag using the developer extension.
> Add experimental feature flag to enable intake request tracking

- packages/logs/.npmignore
- packages/rum-slim/.npmignore
- packages/rum/.npmignore
- packages/worker/.npmignore
Fixes #3512
Un-ignore all .js files from the bundles directory, not just the main bundle.
Check that the RUM package includes the chunks:
```bash
$ yarn build
$ npx lerna run pack
$ tar -tf packages/rum/package.tgz '*/bundle/*' 
package/bundle/chunks/profiler-2eb0077dd11567238403-datadog-rum.js
package/bundle/chunks/recorder-f24e5f2f7ba365163d90-datadog-rum.js
package/bundle/datadog-rum.js
```
> 🔧 [RUM-9766] include bundle chunks in NPM packages

- packages/rum/src/domain/profiling/profiler.ts
- packages/rum/src/domain/profiling/profilingCorrelation.ts
- packages/rum/src/domain/profiling/transport/transport.ts
- packages/rum/src/domain/profiling/types/rumProfiler.types.ts
- packages/rum/src/domain/profiling/utils/longTaskRegistry.ts
We are not using the exact same clocks when collecting long tasks (& LoAF) in both the Browser SDK and the RUM Profiler. 
Let's have the RUM Profiler use the same clocks.
- Relative time should now use `RelativeTime` types.
- Make use of clocks helpers to get corrected relative and absolute time.
- Save the drift for debugging purposes.
- No behavior change expected. Only start/end time should be slightly updated, as they now take the drift into account.
> [RUM Profiler] Use clocks for start/end time

- yarn.lock
Fix vulnerability on axios raised by dependabot: https://github.com/DataDog/browser-sdk/security/dependabot/109
Bump nx resolution to the latest satisfying `nx@npm:>=17.1.2 < 21` which bump axios to a version without the vulnerability
nx is used by lerna, build commands are working on the ci.
Last thing to test would be the release.
> 👷️Bump nx resolution

- renovate.json
Automatically update transitive dependencies, it should prevent some security issues to be opened
Enable [`lockFileMaintenance`](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance):
```
You can use lockFileMaintenance to refresh lock files to keep them up-to-date.
When Renovate performs lockFileMaintenance it deletes the lock file and runs the relevant package manager. 
That package manager creates a new lock file, where all dependency versions are updated to the latest version. 
Renovate then commits that lock file to the update branch and creates the lock file update PR.
```
Conf validated with `npx --yes --package renovate -- renovate-config-validator`
Let's see how it will behave when merged
> 👷️enable renovate `lockFileMaintenance`

- packages/rum-slim/README.md
Clarify the difference between rum and rum-slim
mention missing `compressIntakeRequests` support in rum-slim readme
Check the [rendered readme](https://github.com/DataDog/browser-sdk/blob/benoit/mention-request-compression-in-rum-slim-readme/packages/rum-slim/README.md)
> 📝 mention missing `compressIntakeRequests` support in rum-slim readme

- developer-extension/src/panel/flushEvents.spec.ts
- developer-extension/src/panel/flushEvents.ts
The flush button in developer extension does not work because SDK now only flush on trusted events.
Set `__ddIsTrusted` for the events to trigger flushing.
Added a unit test for flush events script.
Should pass added test case
> 🐛 [devx] Enable flush manually in developer extension

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- test/e2e/scenario/microfrontend.scenario.ts
* This change allows you to override the `service` and `version` on`view` events in the `beforeSend` callback.
* This feature exists for errors, resources and actions as part of the original microfrontend support.
* This provides further microfrontend support for changing the view when using custom view tracking is not feasible.
* Includes `ROOT_MODIFIABLE_FIELD_PATHS` (`service`/`version`) for `RumEventType.VIEW`.
* Add unit test reassigning `service` and `version` with a `view` event.
* Add e2e test reassigning `service` and `version` with a `view` event.
* I did not yet, but can add this as an experimental feature if desired.
* I am unaware of any other implications this could create but will make updates as the discussion advances.
* Configure a `beforeSend` hook to update …
> ✨ Allow overriding service and version for views events in beforeSend

- test/unit/karma.base.conf.js
Since #3308, error reported by karma in the terminal were suboptimal as it pointed to the common JS chunk instead of the source file.
* Apply source maps to the common chunk
Before:
```
rum session keep alive
✗ should send a view update regularly [Chrome Headless 136.0.0.0 (Mac OS 10.15.7)]
Error: test error
at UserContext.<anonymous> (/var/folders/n3/mnsy_yb16416d6hb4sn2w7fc0000gq/T/_karma_webpack_626493/commons.js:178805:15)
at <Jasmine>
```
After:
```
rum session keep alive
✗ should send a view update regularly [Chrome Headless 136.0.0.0 (Mac OS 10.15.7)]
Error: test error
at UserContext.<anonymous> (/Users/benoit.zugmeyer/go/src/github.com/DataDog/browser-sdk/packages/rum-core/src/boot/startRum.spec.ts:193:11 <- /var/folders/n3/mnsy_yb16416d6hb4sn2w7fc0000gq/T/_karma_webpack_866647/com …
```
> 🔧 apply sourcemaps to unit tests common chunk

- scripts/deploy/upload-source-maps.js
- scripts/deploy/upload-source-maps.spec.js
- scripts/lib/datadogSites.js
source map upload for the root upload type failed while handling the new DC:
```
...
Uploading logs source maps with prefix / for ap1.datadoghq.com... 
Uploading logs source maps with prefix / for false... 
Script exited with error: TypeError: site.replaceAll is not a function
at getTelemetryOrgApiKey (/go/src/github.com/DataDog/browser-sdk/scripts/lib/secrets.js:20:31)
at uploadToDatadog (/go/src/github.com/DataDog/browser-sdk/scripts/deploy/upload-source-maps.js:98:26)
at uploadSourceMaps (/go/src/github.com/DataDog/browser-sdk/scripts/deploy/upload-source-maps.js:65:5)
at async main (/go/src/github.com/DataDog/browser-sdk/scripts/deploy/upload-source-maps.js:40:5)
at async /go/src/github.com/DataDog/browser-sdk/scripts/deploy/upload-source-maps.js:34:5 
```
Regression caused by …
> 👷️ [RUM-9996] fix internal source maps upload for root upload type

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/tracing/tracer.spec.ts
- packages/rum-core/src/domain/tracing/tracer.ts
ddtracer-py 3.7.0 is actively using baggage header, we want to remove the feature flag and release from SDK side. 
Remove Feature Flag USER_ACCOUNT_TRACE_HEADER
Pass CI and behaviours on staging should stay same.
> 👷‍♀️ [RUM-10010] Send the user, account and session using the trace baggage header

- packages/core/src/browser/addEventListener.spec.ts
- packages/core/src/browser/browser.types.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/browser/cookieObservable.spec.ts
- packages/rum-core/src/browser/cookieObservable.ts
- packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
- packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
https://github.com/DataDog/browser-sdk/issues/3548
* Revert https://github.com/DataDog/browser-sdk/pull/3456
* Make the flaky test reliable by waiting a bit
> ⚡️ [RUM-10104] avoid polling the cookie for `ciVisibilityContext`

- README.md
Bundle list is outdated, referencing v5 and missing ap1
- Use v6 links
- Add AP1 files
> 📝 update bundle list

- packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
This PR fixes some usage of non-existent configuration options in `remoteConfiguration.spec.ts`, and tweaks things such that the compiler will catch the issue in the future. This probably doesn't matter too much in terms of correctness of the tests, but it avoids potentially confusing people who (like myself today) are searching around in the codebase to find places where these options are referenced.
> ✅ Fix usage of non-existent configuration options in remoteConfiguration.spec.ts

- packages/core/src/domain/session/sessionConstants.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/session/sessionState.spec.ts
- packages/core/src/domain/session/sessionStore.spec.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/index.ts
- packages/logs/src/domain/logsSessionManager.ts
- packages/rum-core/src/domain/rumSessionManager.ts
Next.js 12 introduced the `swcMinify` to opt-in using SWC to minify JS. The SWC version used at the time was very early and suffered from major issues. In particular, it was observed that the `computeSessionState` function in `rumSessionManager.ts` was minified incorrectly in such a way that it returned `undefined` every time.
This commit fixes this issue by adjusting the faulty function implementation.
Instead of returning a "session state", it only returns the "session tracking type" and consider that all sessions with tracking type '0' are not tracked.
This reduces the bundle size a tiny bit, and prevents the concept of "session state" to leak outside of `sessionStore`.
* Create a Next.js v12 app 
* Enable `swcMinify` using the following `next.config.js`:
```
module.exports = { …
```
> 🔥 🐛 fix Next.js 12 + swcMinify compatibility

- packages/rum-core/src/domain/view/trackViews.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.ts
- packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
- packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.ts
- sandbox/react-app/main.tsx
This PR addresses two issues with the current implementation of loading time when the page is hidden during loading.
**Issue 1**  
During the initial load, we check the `PerformanceObserver` to determine if the page was hidden or visible while loading. We do this because the SDK loads asynchronously, so we only have access to future events from that point onward.
The previous implementation had a problem: the performance observer was accessed even during client-side navigation. 
This condition will always be true, potentially leading to an entry in the observer that is lower than the loading time.
**Issue 2**  
This issue is related to Issue 1. The time compared during client-side navigation was always based on the time origin instead of the loading view. 
This means that if the page …
> 🐛 [RUM-10002] Verify the document was not hidden while loading

- package.json
Following a recent Renovate [change](https://github.com/renovatebot/renovate/pull/35869), Renovate will now assume our repo is using the yarn version defined by volta (1.22.22) and adapt `yarn` command line arguments accordingly. But in reality, even if yarn 1.22.22 is specified in Volta, yarn will load the up-to-date version defined by the `packageManager` property and cached in the [.yarn/releases](https://github.com/DataDog/browser-sdk/tree/main/.yarn/releases) folder, so the `yarn` invocation [fails](https://github.com/DataDog/browser-sdk/pull/3589#issuecomment-2934130645).
This PR updates the `volta.yarn` version to match the one in specified by `packageManager`.
Alternatives that have been considered:
* removing `volta.yarn` and relying only on `packageManager`
* removing …
> 👷 update yarn version to 4.9.1 in package.json

- .github/CODEOWNERS
- packages/flagging/INTEGRATE-FLAGGING-PACKAGE.sh
1. When packing artifacts as a dependency by a `web-ui` app, we need to generate a new `version` otherwise they are cached and not updated. Individual packages don't control the version, it is bumped together with other packages in this directory.
2. A bug in the codeowners file regarding matching order, last rule has highest precendence. The change in this ideally should only be reviewed by the ffe team but `rum-browser` is tagged.
* When publishing the pre-release packed artifact, write to the flagging `package.json` as prerelease tag with a uuid; this breaks the cache in the application using it as a dependency.
* Restore the `package.json` file to its existing version
* Fix the codeowners file to have `packages/flagging` changes be routed to team `ffe`
```
➜  browser-sdk …
```
> 👷[FFL-125] support npm pre-release with uuid tagging on flagging package

- packages/flagging/INTEGRATE-FLAGGING-PACKAGE.sh
- packages/flagging/src/openfeature/provider.ts
Want to connect the SDK to the ffe-service endpoint for precomputed assignments
- fix the path portion
- fixed path in INTEGRATION script
- moved `DD-API-TOKEN` from URL to header
- added content-type header
This branch is based on `flagging-dev`. Run the integration script and point it at the browser-flagging-package in `web-ui` as the destination.
> FFL-158: fix flagging api path

- .github/workflows/changelog-to-confluence.yml
- For easier maintanenaince, the secrets variables were added to the Datadog Organization;
- In Confluence a page only can have an unique name for a certain space, which could create conflicts with other pages
- Updates secrets names on the Github Workflow
- Updates name of the page to be published
- Remove previous github Secrets from the repo
- `CONFLUENCE_BASE_URL`
- `ATLASSIAN_USERNAME`
- `ATLASSIAN_API_TOKEN`
> Update changelog-to-confluence: Update secret names, name of page being published

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/configuration/configuration.ts
RUM Profiler is in a state where we can start using it externally.
Let's remove the need need for the `profiling` experimental flag.
- Remove the `profiling` experimental flag, and remove its usage.
- Run the Browser SDK without the `profiling` experimental flag, but still use the `profilingSampleRate`. 
- Assert you are able collect RUM Profiles.
> [RUM Profiler] Remove `profiling` experimental flag

- test/e2e/scenario/developer-extension/developerExtension.scenario.ts
Refactored developer extension scenario to use the `createTest` fixture.
This provides code reusability and makes it follow the other extensions testing format.
Refactored `developerExtension.scenario.ts`
Same e2e tests should pass. 
Note: I had to use `flushBrowserLogs()` because the test navigates to the `baseUrl` which creates console errors.
This wasn't tested before as we didn't navigate thru this page in the old test.
- [X ] Tested locally
> ♻️ [RUM-10074] Use createTest in developer extensions tests

- packages/core/src/domain/session/sessionManager.ts
See if the unexpected session state is always related to multiple session cookies
add cookie info to debug logs
> 🔊 [IR-39238] add cookie data in debug logs

- packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
Restore changes for cookie expiration after incident 39238
Cherry-pick [reverted changes](https://github.com/DataDog/browser-sdk/pull/3559)
> 🍒 [RUM-10101] Persist session cookie to one year when opt-in anonymous user tracking (#3559)

- packages/rum-core/src/rumEvent.types.ts
- test/e2e/lib/framework/pageSetups.ts
- test/e2e/lib/framework/serverApps/mock.ts
Currently, our E2E test suite is loading bundles using a relative URL (ex: /datadog-rum.js). Because of this, we missed a faulty configuration change that broke Session Replay
Let’s use a cross-origin URL to load our bundles in E2E tests. We could just use the [“crossOrigin” server](https://github.com/DataDog/browser-sdk/blob/42739576f614e5b25582706fd83833389c4a0231/test/e2e/lib/framework/httpServers.ts#L27) that we already use for some tests.
> 👷 [RUM-9218] Adjust E2E setup to use cross-origin URLs for loading CDN bundles

- test/unit/karma.base.conf.js
Currently the only way to focus on a single test suite is to use `fdescribe` or `fit` method. The issue with this solution is it's require to edit test file which makes it harder to use by AI agent such as cursor.
This PR adds support for `--spec` flag on the various unit test commands, allowing faster testing feedback loop.
```
yarn test:unit --spec packages/core/src/browser/addEventListener.spec.ts
OR
yarn test:unit --spec "packages/**/addEventListener.spec.ts"
```
> 👷 add `--spec` option to `yarn test:unit`

- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
I'm not sure how we forgot these in the first place but there is no reason to not have them modifiable.
add `service` and `version` to the list of modifiable fields for vitals and long_task events
> 🐛 Allow service and version to be modifiable for long_task and vital events

- scripts/test/bs-wrapper.js
Karma is [intercepting](https://github.com/karma-runner/karma/blob/master/lib/server.js#L391) `SIGTERM` and exit the process with a 0 status code which makes the CI job succeed even though there is some errors or it timeout.
use `SIGKILL` instead of `SIGTERM`
> 👷 use SIGKILL instead of SIGTERM to kill child jobs

- packages/core/src/domain/telemetry/telemetry.spec.ts
- packages/core/src/domain/telemetry/telemetry.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/boot/startLogs.ts
- packages/logs/src/domain/contexts/trackingConsentContext.spec.ts
- packages/logs/src/domain/contexts/trackingConsentContext.ts
- packages/logs/src/domain/hooks.ts
- packages/rum-core/src/boot/startRum.ts
- packages/rum-core/src/domain/contexts/trackingConsentContext.spec.ts
- packages/rum-core/src/domain/contexts/trackingConsentContext.ts
- packages/rum-core/src/domain/hooks.ts
- test/e2e/scenario/telemetry.scenario.ts
A customer reported that Logs continue to send information even after consent has been revoked. We discovered that this issue arises from the PR that allows logs to be sent after the session has expired.
This PR introduces consent context and utilizes it to verify whether the event was consented to be sent.
Additionally, the consent state is passed to telemetry and check every time we want to send any information.
> [!IMPORTANT]
> Although this change should be applied to all products (RUM and Logs), there is added complexity with the manual and automatic start views. This PR just focused on resolved the problem of blocking sending logs after the consent is revoked.
**Case 1**
- _Check the consent was granted_
- Send a log with `DD_LOGS.logger.log('something')`
- _Verify that the log was …
> 🐛 prevent log reporting after consent revocation

- packages/rum-core/src/browser/performanceObservable.ts
- packages/rum-core/src/browser/performanceUtils.spec.ts
- test/unit/browsers.conf.js
Browser Stack Unit BS was flaky after this [fix](https://github.com/DataDog/browser-sdk/pull/3703)
This PR aims to resolve it. 
Bumped device and OS version.
Fixed spec
Because the new version of Safari does not contain
`decodedBodySize: number
encodedBodySize: number
transferSize: number`
We set it up as optional and only test against them when they exist.
Unit and UnisBS should pass.
- [X ] Tested locally
> 👷 Bump OS and device version.

- packages/core/src/domain/allowedTrackingOrigins.ts
Add a telemetry debug in isUnsupportedExtensionEnvironment to see how many users are affected in the future change where we will make `allowedTrackingOrigins` required.
Added a telemetry debug
All should remain the same
> 🔊 Add telemetry to isUnsupportedExtensionEnvironment

- test/envUtils.js
- test/unit/karma.local.conf.js
Unlike Karma reporters, Istanbul coverage reporter `dir` options (`coverageIstanbulReporter.dir`) does not fallback to a default directory if it is set to `undefined` and this breaks the `yarn test` command even when no reporters are writing to disk.
- Make `getCoverageReportDirectory()` default to `coverage`
- Add `clover` coverage reported only when running in the CI. This was the intent before but it was inferred from the value of `getCoverageReportDirectory()`
> 👷 fix coverage report directory

- packages/logs/src/domain/logger.spec.ts
Some unit tests for the Logger are showing some console logs. This PR hides them.
> 👷 hide tag sanitization console warning in unit tests

- test/unit/karma.local.conf.js
With or without coverage info on pull requests, I use this one to explore coverage info, I missed its removal in https://github.com/DataDog/browser-sdk/pull/3710
Generate html coverage report when running unit tests
```
yarn test:unit
open coverage/index.html
```
> 👷add back html coverage report

- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
Adding support for new EVP exposures track, so that feature flagging SDK can send exposure events.
Adds new `exposures` track type to the core.
~The one difference from the rest of the tracks is that staging endpoint is `https://event-platform-intake.datad0g.com/api/v2/exposures` (production stays on `browser-intake-datadoghq.com`).~ Decided to use the same intake for now.
> ✨ [FFL-450] Add support for exposures track

- packages/core/test/interceptRequests.ts
- packages/rum-core/src/boot/preStartRum.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
- packages/rum-core/src/domain/configuration/remoteConfiguration.ts
With IE drop in last major, we can now use fetch instead of xhr
- use fetch to retrieve remote configuration
- switch to promise instead of callback
> ♻️ use fetch to retrieve remote configuration

- .gitlab-ci.yml
Util now, when a PR is merged to main, we automatically merge main into staging. However, there is occasionally some conflict that can make the job fails and this prevent main from being deploy to canary. When this happen we need to fix staging and remember to re-run the failed job in order to have main deployed to canary.
This PR allow the `merge-into-stating` job to fail, so that main is always deployed to canary. This is safe because:
- commits pushed to main are running all non browserstack tests anyway 
- PRs can't be merged to main without all test passing (including browserstack)
- if `merge-into-stating` fails, we still get a slack notification ([example](https://dd.slack.com/archives/CR1MFPWDD/p1753973908438199))
> 👷 Allow `merge-into-stating` CI job to fail

- packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
- packages/rum-core/src/domain/configuration/remoteConfiguration.ts
- packages/rum-core/src/domain/configuration/remoteConfiguration.types.ts
- remote-configuration/rum-sdk-config.json
Support remote configuration of new fields:
- allowedTracingUrls
- allowedTrackingOrigins
- traceSampleRate
- trackSessionAcrossSubdomains
- update remote config schema
- resolve applied value in a generic fashion
Take a remote configuration with the new options configured
```
DD_RUM.init({
remoteConfigurationId: 'my-id'
})
DD_RUM.getInitConfiguration()
```
The returned init configuration should match the remote configuration
> ✨[RUM-10960][Remote config] add support for new static fields

- packages/rum-core/src/browser/performanceObservable.spec.ts
- packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
- packages/rum-core/test/emulate/mockPerformanceObserver.ts
- packages/rum-core/test/fixtures.ts
Before this PR, we had `PerformanceObserver` mock and `performance.*`  buffer mock completely separated, while in reality when a performance timing is notified, it should be both added to the `performance.*` buffer and notified through `PerformanceObserver`.
For [RUM-10146], I need to write tests that rely on resource performance entries both in the buffer and notified via `PerformanceObserver`. This PR makes things simpler closer to the native implementation, so it's easier to write tests.
Mock global performance buffer when mocking PerformanceObserver. Adjust related tests.
If tests are green, it should be fine.
[RUM-10146]: https://datadoghq.atlassian.net/browse/RUM-10146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ [RUM-10146] mock global performance buffer when mocking PerformanceObserver

- packages/rum-react/src/domain/error/addReactError.spec.ts
- packages/rum-react/src/domain/error/addReactError.ts
Attaching local error context with dd_context was not supported via addReactError API. This PR adds that support.
https://github.com/DataDog/browser-sdk/issues/3774
> 🐛 Support error.dd_context for addReactError API

- packages/rum/src/domain/record/serialization/index.ts
- packages/rum/src/domain/record/serialization/serializationStats.spec.ts
- packages/rum/src/domain/record/serialization/serializationStats.ts
- packages/rum/src/domain/record/serialization/serializeAttributes.ts
- packages/rum/src/domain/record/serialization/serializeDocument.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/startFullSnapshots.spec.ts
- packages/rum/src/domain/record/trackers/trackMutation.spec.ts
- packages/rum/src/domain/record/trackers/trackMutation.ts
- packages/rum/src/domain/segmentCollection/buildReplayPayload.spec.ts
- packages/rum/src/domain/segmentCollection/buildReplayPayload.ts
- packages/rum/src/domain/segmentCollection/segment.spec.ts
- packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
- packages/rum/src/domain/segmentCollection/startSegmentTelemetry.spec.ts
- packages/rum/src/domain/segmentCollection/startSegmentTelemetry.ts
In preparation for making changes to the DOM serialization algorithm used by session replay, it'd be helpful to gain some observability into our current DOM serialization performance. We can use this to evaluate the new algorithm. In addition, I hope that this additional observability will help us identify any current performance issues we don't know about.
This PR collects timing information at the top-level entry points into DOM serialization for both full and incremental snapshots and adds it to the existing `SerializationStats` data structure for inclusion in segment network request metrics.
> ✨[PANA-3818] Add telemetry for DOM serialization performance

- packages/rum-core/src/domain/configuration/configuration.ts
- packages/rum/src/boot/lazyLoadRecorder.spec.ts
- packages/rum/src/boot/postStartStrategy.ts
- packages/rum/src/boot/recorderApi.spec.ts
- packages/rum/src/domain/startRecorderInitTelemetry.spec.ts
- packages/rum/src/domain/startRecorderInitTelemetry.ts
We're investigating whether some changes to the initialization process for the session replay recorder could improve reliability and/or fidelity during early page load. To decide how best to approach the problem, and to evaluate any change we do make, it would be helpful to have some metrics about the recorder initialization process.
This PR adds metrics for recorder initialization that are relevant to near-term arcs of work around session replay reliability and fidelity. The metrics (sampled at 1%) measure:
* How long it took to lazy-load the recorder module.
* How long it took to wait for the document to be ready. (Under the hood, this boils down to "how long did we wait for DOMContentLoaded?")
* How long recorder initialization took overall.
* Whether recorder initialization succeeded …
> ✨[PANA-3819] Add telemetry for recorder initialization

- .gitlab/deploy-auto.yml
- .gitlab/deploy-manual.yml
Grant DDOCTOSTS_ID_TOKEN env access in GitLab deploy jobs to fix create-github-release
```diff
.base-configuration:
tags: ['runner:main', 'size:large']
image: $CI_IMAGE
+  id_tokens:
+     DDOCTOSTS_ID_TOKEN:
+      aud: dd-octo-sts
```
Tested in this [pipeline job](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/1097035948)
> 👷 Fix create-github-release job

- packages/core/src/transport/sendWithRetryStrategy.spec.ts
- packages/core/src/transport/sendWithRetryStrategy.ts
Using the session replay telemetry we've recently added, we've observed that session replay data is sometimes getting dropped before it can be sent to the server because the internal queue used by `HttpRequest` fills up. We'd like to stop this from happening to improve session replay reliability.
This PR increases the `HttpRequest` queue size limit from 3MiB to 20MiB. As of today, the backend limit for session replay requests is 10MiB, so 20MiB is large enough to hold two maximally-sized session replay requests. We believe this should allow enough capacity to handle realistic use cases, but we will monitor telemetry and consider increasing the queue size further if we see data that suggests otherwise.
> 🐛 [PANA-3960] Allow more queued request data for better session replay reliability

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/configuration/configuration.ts
- packages/rum-core/src/rumEvent.types.ts
Some new configuration options were not reported as telemetry. I am mostly interested in the `profiling_sample_rate` see when an org starts using profiling.
Include those new configuration options in telemetry.
Check if those options are reported as telemetry
> 🔉  report missing configuration options

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/endpointBuilder.spec.ts
- packages/core/src/domain/configuration/transportConfiguration.ts
Source overrides only currently support Flutter, and should support Unity as a source override as well.
Add `unity` both to the allowed TypeScript definitions and to the check that validates proper sources. Add a unit tests that checks that the `unity` source is forwarded properly.
To to staging
Override the configuration and add:
```js
"source": "unity",
```
Check that events are sending the new information
Check that events in https://dd.datad0g.com/rum/sessions?query=%40type%3Asession%20%40usr.id%3A33803929&agg_m=count&agg_m_source=base&agg_t=count&from_ts=1752574307484&to_ts=1753179107484&live=true shows the new information
> ✨ [RUM-11701] Add unity as a source override

- scripts/performance/lib/reportAsAPrComment.spec.ts
- scripts/performance/lib/reportAsAPrComment.ts
Regression introduced by the [migration of scripts to typescript](https://github.com/DataDog/browser-sdk/pull/3732).
Avoid to miss impactful size change by not having warnings added to the PR.
- add unit tests on create message logic
- remove number type checks
- PR without warning: [cf comment](https://github.com/DataDog/browser-sdk/pull/3845#issuecomment-3299483910)
- PR with warning: [cf comment](https://github.com/DataDog/browser-sdk/pull/3844#issuecomment-3299485520)
> 👷 [Performance script] fix regression on size increase warnings

- renovate.json
Mitigate the risk of pulling a vulnerable package in our CI.
There has been a lot of vulnerabilities in popular NPM packages lately, namely:
* https://www.aikido.dev/blog/npm-debug-and-chalk-packages-compromised
* https://nx.dev/blog/s1ngularity-postmortem
* https://www.aikido.dev/blog/s1ngularity-nx-attackers-strike-again
Stay safe!
Configure renovate to wait a week before upgrading a dependency version using the [minimumReleaseAge](https://docs.renovatebot.com/configuration-options/#minimumreleaseage) option.
> 🔧 configure renovate to wait 1 week before upgrading dependencies

- packages/rum/src/domain/profiling/transport/buildProfileEventAttributes.spec.ts
- packages/rum/src/domain/profiling/transport/buildProfileEventAttributes.ts
- packages/rum/src/domain/profiling/transport/transport.ts
We want to allow filtering by view name in the Profiling explorer (ie. `@view.name:/my-view`). 
In order to make the view name query-able, we need to pass it as the event's attributes (just as we do for view ids)
- new `view.name` attribute in the Profile's `event.json` sent to intake.
- Browse a website with this version of the SDK, with the RUM Profiler active.
- After a while (tipically a minute of navigation), assert you can see a call the the profile intake.
- Assert you can see the `event.json` sent includes the new `view.name` attribute.
- Go over the Profiling's Explorer [page](https://app.datadoghq.com/profiling/explorer) 
- Filter using the search bar to `@view.name:<the-view-you-were-browsing>` and you should see a Flame Graph.
> [RUM Profiler] send view names as event attributes

- scripts/lib/executionUtils.ts
- scripts/lib/gitUtils.ts
Help debugging failing scripts
* Add the response body as an error `cause`. Node.js will pick it up when displaying the error.
* Add context on which github API we were trying to call
It looks like this:
```
Script exited with error: Error: Failed to call GitHub API: GET releases/tags/v6.20.0
at callGitHubApi (file:///Users/benoit.zugmeyer/go/src/github.com/DataDog/browser-sdk/scripts/lib/gitUtils.ts:124:11)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async createGitHubRelease (file:///Users/benoit.zugmeyer/go/src/github.com/DataDog/browser-sdk/scripts/lib/gitUtils.ts:51:5)
at async file:///Users/benoit.zugmeyer/go/src/github.com/DataDog/browser-sdk/scripts/release/create-github-release.ts:18:21 {
[cause]: Error: HTTP Error Response: 401 Unauthorized …
```
> 👷 [ci] when a request fails, display the response error

- eslint.config.mjs
- scripts/deploy/deploy.spec.ts
- scripts/deploy/upload-source-maps.spec.ts
- scripts/lib/executionUtils.spec.ts
- scripts/lib/executionUtils.ts
- scripts/lib/gitUtils.ts
- scripts/performance/lib/reportAsAPrComment.spec.ts
The 'create-github-release' script failed because of an authentication issue. We were deleting the octo token too early.
This commit fixes the problem by `await`ing the call to the GitHub API. It also removes the deprecated ['no-return-await' ESLint rule](https://eslint.org/docs/latest/rules/no-return-await) as it's not recommended anymore.
Test script:
```js
createGitHubRelease();
async function createGitHubRelease() {
using token = getToken();
return callGitHubApi(token);
}
function getToken() {
console.log("Create token");
return {
[Symbol.dispose]() {
console.log("DISPOSE");
},
};
}
async function callGitHubApi(_token) {
console.log("Calling API...");
await Promise.resolve();
console.log("API called");
}
```
`DISPOSE` is called too soon. This logs:
```
Create token
Calling API... …
```
> 👷🐛 fix `create-github-release`

- scripts/lib/computeBundleSize.ts
- scripts/lib/executionUtils.ts
- scripts/lib/gitUtils.ts
- scripts/performance/index.ts
- scripts/performance/lib/bundleSizes.ts
- scripts/performance/lib/constants.ts
- scripts/performance/lib/cpuPerformance.ts
- scripts/performance/lib/fetchPerformanceMetrics.ts
- scripts/performance/lib/memoryPerformance.ts
- scripts/performance/lib/reportAsAPrComment.spec.ts
- scripts/performance/lib/reportAsAPrComment.ts
- scripts/performance/lib/reportToDatadog.ts
- scripts/show-bundle-size.ts
The "bundle sizes" PR comment was proven very valuable, however the `test-performances` job is sometimes failing.
Make the `test-performances` script more resilient by clearly separating the three tasks (bundle sizes, memory and CPU). Each task can update its own part of the PR comment, so if a task fails it doesn't prevent the other tasks to succeed.
See [this PR comment](https://github.com/apps/cit-pr-commenter)
> 👷 [mob-session] make `test-performances` more resilient

- scripts/performance/index.ts
- scripts/performance/lib/bundleSizes.ts
- scripts/performance/lib/cpuPerformance.ts
- scripts/performance/lib/memoryPerformance.ts
- scripts/performance/lib/reportAsAPrComment.spec.ts
- scripts/performance/lib/reportAsAPrComment.ts
With latest refactoring, reporting is not done on main because no PR is opened
if no pr is opened, still report local metrics to datadog
> 👷🐛[performance] fix reporting on main branch

- developer-extension/package.json
- developer-extension/webpack.config.ts
This was broken when we migrated webpack.config files to TS.
Fix [react-refresh-typescript](https://www.npmjs.com/package/react-refresh-typescript) usage
> [devext] fix `yarn dev` command

- .github/CODEOWNERS
As we begin to transition to a more platform-like model for the browser SDK, it makes sense to gradually transition ownership of some team-specific code to the appropriate teams. My hope is that this will reduce the degree to which browser SDK team members are on the critical path for wide variety of projects, enabling various teams to work in parallel a bit more easily.
This PR transfers ownership of the session replay code to the new `session-replay-sdk` Github team.
Note that in the short term, I still anticipate that changes will need review from the browser SDK team, but I'm planning to add `session-replay-sdk` team members as additional reviewers, in the hope that eventually the more isolated PRs will no longer require browser SDK team review. (Though we can work out the details …
> 👥 [PANA-4375] Transfer replay code to session-replay-sdk team in CODEOWNERS

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/resource/resourceCollection.ts
- test/e2e/scenario/rum/graphql.scenario.ts
After testing the graphql tracking on datadog internal app we can now remove the feature flag.
> [RUM-11434] Remove ff for graphql tracking

- packages/core/src/tools/experimentalFeatures.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
As we now have a way to collect graphql request via new init parameter (see : https://github.com/DataDog/browser-sdk/pull/3805) we don't need this experimental feature anymore.
> 🔥 [RUM-11434] Remove writable_resource_graphql experimental feature

- packages/rum/src/domain/record/nodeIds.spec.ts
- packages/rum/src/domain/record/nodeIds.ts
- packages/rum/src/domain/record/record.ts
- packages/rum/src/domain/record/serialization/htmlAst.specHelper.ts
- packages/rum/src/domain/record/serialization/index.ts
- packages/rum/src/domain/record/serialization/serialization.types.ts
- packages/rum/src/domain/record/serialization/serializationScope.ts
- packages/rum/src/domain/record/serialization/serializationUtils.spec.ts
- packages/rum/src/domain/record/serialization/serializationUtils.ts
- packages/rum/src/domain/record/serialization/serializeDocument.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
- packages/rum/src/domain/record/shadowRootsController.ts
- packages/rum/src/domain/record/startFullSnapshots.spec.ts
- packages/rum/src/domain/record/startFullSnapshots.ts
- packages/rum/src/domain/record/trackers/trackInput.spec.ts
- packages/rum/src/domain/record/trackers/trackInput.ts
- packages/rum/src/domain/record/trackers/trackMediaInteraction.spec.ts
- packages/rum/src/domain/record/trackers/trackMediaInteraction.ts
- packages/rum/src/domain/record/trackers/trackMouseInteraction.spec.ts
- packages/rum/src/domain/record/trackers/trackMouseInteraction.ts
- packages/rum/src/domain/record/trackers/trackMove.spec.ts
- packages/rum/src/domain/record/trackers/trackMove.ts
- packages/rum/src/domain/record/trackers/trackMutation.spec.ts
- packages/rum/src/domain/record/trackers/trackMutation.ts
- packages/rum/src/domain/record/trackers/trackScroll.spec.ts
- packages/rum/src/domain/record/trackers/trackScroll.ts
- packages/rum/src/domain/record/trackers/trackStyleSheet.spec.ts
- packages/rum/src/domain/record/trackers/trackStyleSheet.ts
- packages/rum/src/domain/record/trackers/trackViewportResize.spec.ts
I'm preparing to implement a prototype of a new DOM serialization algorithm behind a feature flag. To cleanly integrate this new algorithm into the existing code, we need to add a small amount of abstraction.
This PR focuses on adding an abstraction layer around node ids. Currently, the association between DOM nodes and their ids is tracked using global variables which persist across views; however, with the new algorithm, each view needs its own node id namespace. To abstract over this difference cleanly, it's helpful to get rid of the global variables and create an object to provide an explicit lifetime to this state.
This PR adds a new `SerializationScope` type which tracks state associated with a specific stream of serialized events. It also removes the global variables we use right …
> 🎨 [PANA-4372] Explicitly scope serialization state

- packages/rum/src/domain/record/serialization/htmlAst.specHelper.ts
- packages/rum/src/domain/record/serialization/serialization.types.ts
- packages/rum/src/domain/record/serialization/serializeDocument.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
- packages/rum/src/domain/record/trackers/trackMutation.ts
`SerializeOptions#parentNodePrivacyLevel` doesn't really make sense as member of `SerializeOptions`; as the name implies, it's a value that's only applicable for a particular node's children. This scope mismatch has led to the implementation of some optimizations in the code that try to avoid copying `SerializeOptions` constantly during serialization, but the more natural fix is simply to pass this value around as a normal function parameter.
This PR converts `SerializeOptions#parentNodePrivacyLevel` into a normal function parameter, updates all call sites, and removes the now-unnecessary code for the optimization described above.
> 🎨 [PANA-4398] Convert SerializeOptions#parentNodePrivacyLevel into a normal function argument

- packages/core/src/domain/session/sessionManager.ts
Keep the session cookie telemetry until RUM-10845 is closed.
Update the telemetry expiration date
> 🔊 delay the session cookie debug telemetry date

- packages/logs/src/boot/logsPublicApi.ts
- packages/logs/src/domain/configuration.ts
- packages/logs/src/entries/main.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/configuration/configuration.ts
- packages/rum-react/react-router-v6/package.json
- packages/rum-react/react-router-v6/typedoc.json
- packages/rum-react/react-router-v7/package.json
- packages/rum-react/react-router-v7/typedoc.json
- packages/rum-react/src/domain/error/addReactError.ts
- packages/rum-react/src/domain/error/errorBoundary.spec.tsx
- packages/rum-react/src/domain/error/errorBoundary.ts
- packages/rum-react/src/domain/error/index.ts
- packages/rum-react/src/domain/reactPlugin.ts
- packages/rum-react/src/domain/reactRouter/routesComponent.ts
- packages/rum-react/src/domain/reactRouter/types.ts
- packages/rum-react/src/entries/main.ts
- packages/rum-react/src/entries/reactRouterV6.ts
- packages/rum-react/src/entries/reactRouterV7.ts
- packages/rum-react/typedoc.json
- packages/rum-slim/src/entries/main.ts
- packages/rum/src/entries/main.ts
- typedoc.json
Various small improvements for the API documentation done during the Mob programming session.
- Merge configuration and API categories to prevent composed name (i.e. `API/RumGlobal`, `Configuration/RumInitConfiguration`)
- Improve React plugin categories: `Main` and `Error`
- Rename `RumGlobal` to `DatadogRum` so that the name matches the export from NPM. (and the same for log)
- Add some examples
- Hide feature operation APIs
| Before | After |
|--------|--------|
| <img width="394" height="666" alt="Screenshot 2025-10-03 at 16 07 31" src="https://github.com/user-attachments/assets/5b3b1735-3b2b-4756-b5b1-b5b60af25325" /> |  <img width="416" height="826" alt="Screenshot 2025-10-03 at 16 29 30" src="https://github.com/user-attachments/assets/38935b04-8c4c-4deb-973e-5f5951b5eccb" /> |
> 📝 improve API documentation
