DataDog/browser-sdk

packages/core/src/requestCollection.ts
packages/core/test/requestCollection.spec.ts

https://fetch.spec.whatwg.org/#concept-filtered-response-opaque
then, we don't know if the request is a success or an error

🐛[request] do not consider opaque response as error

---

packages/core/src/transport.ts

To help debug the weird measure values shown in the View Explorer, this adds debug logs when the SDK sends abnormal load event duration (above one day). This is intentionaly at the lowest level possible (right before serialization) to make sure we have the final value transmited to the backend.

🔊🐛 [RUMF-201] add internal logs for buggy load event measures

---

lerna.json

Scoped packages are considered private by default.

✨[packages] allow to publish publicly

---

packages/rum/src/rum.ts
packages/rum/src/viewTracker.ts
packages/rum/test/rum.spec.ts
packages/rum/test/viewTracker.spec.ts

When the session is renewed, a final view event is sent with the previous view id, but the session id has already change at this time.
This PR fixes the issue by changing the session id only after the final view event has been sent.

[RUMF-158] fix view id associated to different session id

---

packages/core/src/transport.ts
packages/rum/src/viewTracker.ts

This information will help us debug the issue by providing more context on the navigation entry (ex: its name, initiatorType, ...) and will show previous measures if any.  We expect only one PerformanceNavigationTiming should happen when a page is loading, but maybe that's not the case, so previous measures will tell us if it's happening.

[RUMF-201] add debug monitoring for navigation timing entries

---

packages/core/src/requestCollection.ts
packages/core/src/tracekit.ts
packages/core/test/parser.spec.ts
packages/logs/src/logs.entry.ts
packages/rum/src/performanceCollection.ts
packages/rum/src/rum.entry.ts
packages/rum/test/rum.spec.ts

in order to avoid types conflict when the library is compiled alongside other libraries/projects

 🐛[types] do not globally override ts types

---

packages/rum/src/performanceCollection.ts

This will make sure https://github.com/DataDog/browser-sdk/pull/217 will solve the adnormal timing issue.

🔊🐛 [RUMF-201] add internal logs for abnormal timeOrigin

---

test/e2e/scenario/helpers.ts

Since a few days, a change from the cross-browser-testing side breaks our E2E tests on Edge.  It seems `browser.getCookies()` can return `null` now.  Let's fallback on an empty array in this case.

✅ fix e2e cbt tests on Edge

---

packages/core/src/utils.ts
packages/rum/src/performanceCollection.ts

Using `performance.timing.navigationStart` instead of `performance.timeOrigin` has several advantages:
* it is defined on more browsers ;
* it produces timings closer to the real PerformanceNavigationTiming
event ;
* performance.timeOrigin may be far in the past for some reason, causing
abnormal timings.
More context in https://datadoghq.atlassian.net/jira/software/projects/RUMF/boards/119?selectedIssue=RUMF-201

🐛 [RUMF-201] use timing.navigationStart to compute fake timings

---

packages/core/src/transport.ts
packages/core/src/utils.ts
packages/core/test/transport.spec.ts
packages/rum/src/rum.ts
packages/rum/src/viewTracker.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts

Limit the number of view events to process on the backend by ensuring that there is only one view event by view id by batch.

⚡️[batch] limit view update events

---

test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts

Some logs/rum requests were handled by the server after the end of the test.
Before:
```
GET /logs 
[]
GET /reset
POST /logs 
XXX
YYY
```
After:
```
GET /logs 
[]
POST /logs 
XXX
YYY
GET /logs 
[XXX,YYY]
GET /reset
```

♻️[e2e] wait request to reach server before assertions

---

test/server/server.js

Debug case:
```
undefined is not an object (evaluating 'window.DD_LOGS.logger')
```
[gitlab job](https://gitlab.ddbuild.io/DataDog/browser-sdk/-/jobs/23762559)
Info so far:
- Webdriver navigates to `/bundle-e2e-page.html`
- logs and rum files are not downloaded from the server.
Add:
- logging for html download
- status code for all requests

🔊[e2e] add extra logging

---

.gitlab-ci.yml
package.json
packages/logs/README.md
packages/rum/README.md
packages/rum/src/rum.ts
packages/rum/test/rum.spec.ts
test/app/package.json
test/app/webpack.config.js
test/app/yarn.lock

Following issues from customer using 3.2 and 2.5 versions.
Supporting the last major version bump (06/2018) seems a good compromise.
Document the support and add a workaround for older version.

🏷 [TypeScript] ensure 3.0 minimal support

---

packages/core/src/init.ts

On Safari, visible document seems to pass by the prerender state which prevent the initialisation of the sdk.
closes #238

🐛[init] remove deprecate prerender check

---

packages/core/src/utils.ts
packages/core/test/utils.spec.ts

🐛[jsonStringify] do not crash on serialization error

---

packages/rum/src/viewTracker.ts

observed performance.now() older than the deployment date
=> page origin will give us the timestamp of the sdk execution
in abnormal load event, domComplete and loadEvent are close to a new view creation (< 1min) whereas other timings are very old (> 1 day)
**hypothesis**: a "situation" that create a new view also generate a new navigation entry with a refresh of dom complete + load event

🔊 [RUM-257] add more abnormal info

---

packages/core/src/errorCollection.ts
packages/core/src/index.ts
packages/core/src/init.ts
packages/core/src/internalMonitoring.ts
packages/core/test/internalMonitoring.spec.ts
packages/logs/src/logger.ts
packages/logs/src/logs.entry.ts
packages/logs/test/logger.spec.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/test/rum.spec.ts

It would allow us to identified more precisely in which context an issue occurred (org id, session id, ...)

✨[internal monitoring] add RUM/Logs context

---

packages/core/src/requestCollection.ts
packages/core/src/specHelper.ts
packages/core/test/requestCollection.spec.ts

When consuming a fetch response body, it can be disturbed or locked, a rejected promise is then returned (cf [fetch spec](https://fetch.spec.whatwg.org/#concept-body-consume-body)).
This rejected promise was displayed on the browser console and the corresponding request was not collected.
Handle the rejected promise and add the corresponding error to the collected request response.

🐛[RUMF-293][fetch] handle fetch response text error

---

test/e2e/scenario/agents.scenario.ts

try to fix e2e issue:
`Unable to get property 'logger' of undefined or null reference`
calls to load the page url from the server are not in server.log

✅[e2e] wait for browser url loaded

---

packages/rum/src/rum.ts

**Reasoning**
Reported abnormal navigation entries had a performance.now() in the past.
Let's see how many cases we have in the wild.

🔊[RUMF-257] report abnormal performance.now()

---

.gitlab-ci.yml
LICENSE-3rdparty.csv
scripts/check-licenses.js

Enforce to list all package.json dependencies inside LICENSE-3rdparty.csv

📄 add check-licenses script

---

packages/rum/src/rumSession.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts

a tracked session must have a session id

🐛[RUMF-308] do not track session without id

---

packages/rum/src/rum.ts
packages/rum/src/viewTracker.ts

- remove unneeded info
- ease logs search/reading
- track load event with a listener to compare with other timing sources that can be updated

🔊[RUMF-257] rework logging

---

.gitlab-ci.yml
package.json
packages/rum/src/rum.entry.ts
test/e2e/browsers.conf.js
test/e2e/scenario/agents.scenario.ts
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html
test/static/npm-e2e-page.html

- Add async e2e setup to ensure that early timings are well retrieved
- Add test to ensure that early resources are collected

:bug: [RUM] fix retrieving early timings

---

.gitlab-ci.yml
package.json
packages/core/src/utils.ts
packages/logs/src/logs.entry.ts
packages/rum/src/rum.entry.ts
scripts/fail.sh
test/app/app.ts
test/app/package.json
test/app/tsconfig.json
test/app/webpack.config.js
test/app/yarn.lock
test/e2e/wdio.base.conf.js

In loading code, retrieve global object depending on the environment instead of window.
Automate check by executing test app source code.
fixes #235

✨[RUMF-264] add compatibility with server side rendering

---

packages/core/src/errorCollection.ts
packages/core/src/utils.ts
packages/core/test/errorCollection.spec.ts
packages/logs/src/logger.ts
packages/rum/src/rum.ts
packages/rum/src/viewTracker.ts

Use startTime instead of collection time in order to have a more accurate date for events.

✨[RUMF-342] use startTime for events timestamp

---

packages/core/src/utils.ts
packages/rum/src/performanceCollection.ts
packages/rum/src/resourceUtils.ts
packages/rum/test/resourceUtils.spec.ts
packages/rum/test/rum.spec.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts

Send an event resource for the initial document

✨[RUMF-315] collect initial document timing

---

packages/core/src/specHelper.ts
packages/core/src/utils.ts
packages/rum/src/resourceUtils.ts
packages/rum/test/resourceUtils.spec.ts
packages/rum/test/rum.spec.ts
test/app/app.ts
test/e2e/scenario/helpers.ts
test/e2e/wdio.base.conf.js
test/server/server.js
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

when several SDKs are setup on the same page, client tokens can differ.

🐛[RUMF-330] fix intake requests exclusion

---

packages/core/src/requestCollection.ts
packages/core/test/requestCollection.spec.ts
test/e2e/scenario/agents.scenario.ts
test/server/server.js
test/unit/karma.base.conf.js
test/unit/karma.cbt.conf.js

An xhr request can be [aborted](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort) after completion, overriding its original status by an aborted one (ie. statusCode: 0).
Use [onreadystatechange](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange) in order to retrieve xhr status as soon as possible.
Convert existing xhr e2e tests to unit tests.
closes #257

🐛[RUMF-266] fix xhr incorrect status reported on late abortion

---

packages/core/src/configuration.ts
packages/core/src/transport.ts
packages/rum/src/rum.ts

add an `enableExperimentalFeatures` init options that would allow us to test some features only on datadog app

⚗️[RUMF-371] add batch time to rum intake requests

---

packages/core/src/requestCollection.ts
packages/core/test/requestCollection.spec.ts
packages/rum/test/rum.spec.ts

In case where `onreadystatechange` is overridden, add a fallback on `addEventListener` in order to not miss some requests.
relates to #283

🐛[RUMF-266] xhr tracker: add fallback on event listener

---

LICENSE-3rdparty.csv
packages/core/package.json
packages/core/src/index.ts
packages/core/src/requestCollection.ts
packages/core/src/urlPolyfill.ts
packages/core/src/utils.ts
packages/core/test/requestCollection.spec.ts
packages/core/test/urlPolyfill.spec.ts
packages/rum/src/resourceUtils.ts
packages/rum/src/rum.ts
packages/rum/test/viewTracker.spec.ts
test/app/yarn.lock
yarn.lock

The dependency used to polyfill URL API is modifying the global scope which caused an issue for a customer.
Since we don't use a lot of URL features, replace this polyfill by a simple implementation that support only our current needs.

🐛[RUMF-320] Remove url-polyfill dependency

---

packages/core/src/utils.ts

In some rare cases, view date change over the time which break the backend aggregation.
performance.timing.navigationStart seems to be the culprit.

🐛[RUMF-396] try to fix view date shift

---

packages/core/src/urlPolyfill.ts
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html
test/static/npm-e2e-page.html

URL api was never used and for customer with base-uri csp restrictions, the polyfill raised an exception.
cf [bug report](https://github.com/DataDog/browser-sdk/pull/294#issuecomment-598279956)
Add similar restrictions to e2e pages.

🐛[RUMF-403] fix checkURLSupported 

---

packages/core/src/init.ts

What it does
replace
by
Context
[https://github.com/DataDog/browser-sdk/issues/288](https://github.com/DataDog/browser-sdk/issues/288)
[RUMF-376](https://datadoghq.atlassian.net/browse/RUMF-376)
Changes
- replace console.error by console.warn

🐛 replace console.error by console.warn when cookies are not supported

---

packages/core/src/configuration.ts
packages/logs/README.md
packages/logs/src/logs.entry.ts
packages/logs/test/logs.entry.spec.ts
packages/rum/README.md
packages/rum/src/rum.entry.ts
packages/rum/test/rum.entry.spec.ts

What it does
Add a new and optional init option : `silentMultipleInit?: boolean`
Context
[https://github.com/DataDog/browser-sdk/issues/280](https://github.com/DataDog/browser-sdk/issues/280)
Changes
- Update README files
- Add the new `silentMultipleInit?: boolean` property to the `UserConfiguration` type
- Check the boolean while being already initialized

✨add an option to silent multiple Init errors

---

packages/core/src/configuration.ts
test/app/app.ts
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

remove flag from e2e test, let's see how it goes

[RUMF-382] prepare support for multiple feature flags

---

packages/rum/src/resourceUtils.ts
packages/rum/src/rum.ts
packages/rum/test/resourceUtils.spec.ts
packages/rum/test/rum.spec.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts
test/e2e/wdio.base.conf.js
test/server/fake-backend.js

With this PR, we try to improve the resources timing collection in different ways:
* Better cross browser support:
* If `timing.duration` isn't available or 0, use `responseEnd - startTime` instead, if available (Safari)
* If `redirectStart` isn't available, use `startTime` instead (Firefox)
* If `redirectEnd` isn't available, use `fetchStart` instead (Firefox)
* Change how the timings `start` are computed: use difference (in nanosecond) between the request `startTime` and the timing start, so we can build reliable timings diagram.
* Discard any timing lower than `startTime` instead of 0 since it should not happen and would provide negative timings `start`.
* Report timings for all cached resources, as we've seen that we can't accurately know if a resource is cached or not (timings may …

[RUMF-407] improve resource timings collection

---

packages/core/src/configuration.ts
packages/core/src/internalMonitoring.ts
packages/core/src/utils.ts
packages/rum/src/newSessionChecks.ts
packages/rum/src/rum.entry.ts

Add checks to measure new session strategy impacts on collected sessions
Introduce a `_dd_exp_s` cookie to store session creation date.
Put checks behind `'new-session-checks'` flag.

🔊[RUMF-408] add new session check logs

---

packages/core/src/configuration.ts
packages/rum/src/rum.entry.ts

- array.include not supported on IE
- ensure enableExperimentalFeatures is an array to avoid `Object doesn't support property or method 'includes'`

🐛fix feature check

---

packages/core/src/oldCookiesMigration.ts
packages/core/src/sessionManagement.ts
packages/core/test/oldCookiesMigration.spec.ts
packages/core/test/sessionManagement.spec.ts
packages/logs/src/loggerSession.ts
packages/rum/src/rumSession.ts

🔥[RUMF-430] stop maintaining old cookies

---

packages/core/src/sessionManagement.ts
packages/core/src/transport.ts
packages/core/src/utils.ts
packages/core/test/oldCookiesMigration.spec.ts
packages/core/test/requestCollection.spec.ts
packages/core/test/sessionManagement.spec.ts
packages/logs/src/loggerSession.ts
packages/logs/test/loggerSession.spec.ts
packages/rum/src/performanceCollection.ts
packages/rum/src/rumSession.ts
packages/rum/src/userActionCollection.ts
packages/rum/src/viewTracker.ts
packages/rum/test/rumSession.spec.ts
packages/rum/test/userActionCollection.spec.ts
test/static/bundle-e2e-page.html

- Allow page with iframe displayed to continue to expand the session even if there is no interaction with the main page
- Reduce long lasting sessions
Behind the 'new-session' flag:
- Check page visibility every 1 minute to expand the session
- Add a session timeout at 4h
- Enforce the session expiration if last interaction was more than 15 minutes ago

✨[RUMF-430] new session strategy

---

packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts
packages/rum/test/userActionCollection.spec.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/serverTypes.ts

After a few tests on staging, user actions needs two adjustments:
* change the data model so `user_action_id` becomes `user_action.id` on all RUM events
* convert the duration in nanoseconds to be in line with other rum events

[RUM] User action collection adjustements

---

packages/core/src/utils.ts
test/static/bundle-e2e-page.html

Unless adding `unsafe-eval`, Function is blocked by CSP restriction on older browsers.
Use black magic instead 🙈
fixes #328

🐛[RUMF-431] fix CSP issue with global object strategy

---

packages/rum/src/rum.ts

- `user` for regular session
- `synthetics` for browser test sessions

✨[RUMF-435] add session type on all events

---

.gitlab-ci.yml
package.json

Other jobs are not typechecking all TS source files, or at least not failing when there is a TS error:
* `yarn run build`: will fail if there is an typecheck error on files included in the bundle, but not on test files
* `yarn run test` (and any test executed by karma): karma will not fail if there is a typecheck error in files, and I didn't find a way to configure it otherwise
* `yarn run lint`: tslint does not typecheck the code

👷 add a typecheck job to the CI

---

packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts

Logs and traces will automatically pick up and associate this to their sent data.

✨ [RUMF-438] add user action reference to the internal context

---

packages/core/src/configuration.ts
packages/core/test/configuration.spec.ts

Send data through a proxy before sending it to datadog servers.
Correct datadog host to forward the data is added to requests in the `ddhost` query parameter
Ex:
By setting `proxyHost` init option to `my.proxy.io`
Requests URL will look like:
https://my.proxy.io/some/path/token?ddhost=service.datadog-domain.com&some=parameters
And must be forwarded to:
https://service.datadog-domain.com/some/path/token?some=parameters

✨[RUMF-43] add proxyHost init option

---

packages/rum/src/getElementContent.ts
packages/rum/test/getElementContent.spec.ts

reduce the maximum content length from 200 to 100 characters
[RUMF-467](https://datadoghq.atlassian.net/browse/RUMF-467)
- update the truncate function
- add ✅

reduce getElementContent truncate to 100 chars

---

packages/core/src/sessionManagement.ts
packages/core/src/utils.ts
packages/core/test/utils.spec.ts
packages/rum/src/viewCollection.ts
packages/rum/test/viewCollection.spec.ts

With the last release (v1.11.0), we have seen a lot of "duplicated" views, meaning view events with the same id but a different date. This is likely caused by the throttled `updateView` function, sending a view update after the view ends when a timing or a event count have changed right before the view end.
This fixes the issue by ensuring that the view sending an update is still the current view.

🐛 [RUM] fix view update after its end

---

packages/rum/src/domMutationCollection.ts

Angular uses Zone.js to provide a context persisting accross async tasks.  Zone.js replaces the global `MutationObserver` constructor with a patched version to support the context propagation. There is an ongoing issue[[1](https://github.com/angular/angular/issues/26948), [2](https://github.com/angular/angular/issues/31712)] with this setup when using a `MutationObserver` within a Angular component: on some occasions, the callback is being called in an infinite loop, causing the page to freeze (even if the callback is completely empty).
To work around this issue, we are using the Zone `__symbol__ `API to get the original, unpatched MutationObserver constructor.

🐛 [RUMF-469] fix angular compatibility

---

.gitlab-ci.yml

Only deployments to:
- not pollute ops channel with other notifications
- keep all deployments related notifications in a dedicated channel

🔊 add staging/prod deployment notifications in ops channels

---

test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

Fix runtime error occurring in `async-e2e-page.html` and `bundle-e2e-page.html` static test files

🐛 prevent runtime error in static test files

---

test/browsers.conf.js
test/unit/karma.bs.conf.js

Microsoft drop the support this year: https://betanews.com/2020/03/04/ends-ie10-support-windows-server-2012/
Remove IE10 from tested browsers.
All polyfills are still used for IE11.
---

👷[RUMF-453] remove IE10 from tested browsers

---

packages/core/src/configuration.ts
packages/core/src/init.ts
packages/core/test/configuration.spec.ts
packages/logs/src/buildEnv.ts
packages/rum/src/buildEnv.ts

Allows users to configure optional fields that tag their RUM events and logs with a specific service, environment and version.
New optional configuration options have been added to the log, rum init process. If define, these new fields will then create new tags for each of the logs and RUM events send to the intake.
1. add the optional `clientService, clientEnv, clientVersion` fields to the `window.DD_RUM.init and window.DD_LOGS.init`
2. check in the network tab that the intake URL carries the new tags ex: `&ddtags=sdk_version:dev,env:envaaa,service:serviceaaa,version:versionaaa`

✨[RUMF-465] collect client service, env and version

---

packages/rum/test/performanceCollection.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

Ease bootstrapping of RUM unit tests by:
- avoid to wire test subjects with all their dependencies
- abstract mock setup (fake server, clock, ...) 
- mutualize cleanup
```ts
beforeEach(() => {
setupBuilder = setup()
.withFakeServer()
.withRum()
.withViewCollection()
})
afterEach(() => {
setupBuilder.cleanup()
})
it('should ...', () => {
const { server, lifeCycle } = setupBuilder.build()
server.requests = []
lifeCycle.notify(...)
...
})
```
- remove a useless test
- introduce test setup builder
- use it in existing tests when relevant
---

✅ [RUM] introduce test setup builder

---

packages/logs/README.md
packages/rum/README.md

Missing documentation for service, env, version in `init` API
Add documentation
N/A
---

📝 [RUMF-465] add service, env, version to API docs

---

LICENSE-3rdparty.csv
packages/core/package.json
packages/core/src/internalMonitoring.ts
packages/core/src/transport.ts
packages/core/src/utils.ts
packages/core/test/utils.spec.ts
packages/logs/package.json
packages/logs/src/logger.ts
packages/logs/src/logs.entry.ts
packages/rum/package.json
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
test/app/yarn.lock
yarn.lock

The SDK code being quite large – as you can see on [bundlephobia](https://bundlephobia.com/result?p=@datadog/browser-rum@1.11.4)  – I wanted to remove lodash as it's quite big and can easily be replaced with something smaller.
Two dependencies got replaced:
- `lodash.merge` got replaced with a function that does the same thing, just without the ability to merge objects with circular references
- `lodash.assign` got replaced with simple loop re-assigning keys
Everything should work _exactly the same_, but happy to write more tests if needed.
---

👷 Removing lodash dependencies

---

scripts/generate-changelog.js

Avoid commits already released when generating the changelog
fecth tag from remote before retrieving commits
issue reproduced locally with missing tags, let's see how it behaves in next release
---

👷 [changelog] ensure to retrieve latest tags

---

packages/core/src/configuration.ts

debug for #incident-4632
back is going to hide it in order to not be displayed in the UI
add application id as `_dd.application_id` query parameter
Tested for events generated by rum and logs, only appears for rum
---

👷 [RUM] add application id as query parameter

---

packages/rum/src/getActionNameFromElement.ts
packages/rum/src/getElementContent.ts
packages/rum/src/userActionCollection.ts
packages/rum/test/getActionNameFromElement.spec.ts
packages/rum/test/getElementContent.spec.ts
packages/rum/test/userActionCollection.spec.ts

Improve the name of click actions.
* Improve the name extraction from elements by adding different strategies and adjusting priorities.
* Don't collect actions if a name cannot be found.
This should be left on staging for a little while to verify that it does not break thing, and indeed improve the action names.
---

✨ [RUMF-385] improve click action naming

---

packages/rum/README.md
packages/rum/src/getActionNameFromElement.ts
packages/rum/test/getActionNameFromElement.spec.ts

We want to allow RUM library users to declare action names directly within the HTML markup (or DOM tree).
Add a new, top priority strategy to the `getActionNameFromElement` function that look for a `data-dd-action-name` attribute on the element or any of its parent.
Unit tests should be enough
---

✨ [RUMF-385] implement a declarative API to set the action names

---

packages/core/src/configuration.ts
packages/rum/README.md
packages/rum/src/rum.entry.ts
test/app/app.ts
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

Let the user chose if they want to track user interactions. This replaces the 'collect-user-actions' FF.
Add a `trackInteractions` flag for the RUM init options.
---

✨ [RUMF-549] add an option to enable the user interaction tracking

---

.github/CODEOWNERS

Stop using global @DataDog/rum team
Use @DataDog/rum-browser instead
---

👷[codeowners] use rum-browser

---

packages/core/src/transport.ts
packages/core/src/utils.ts
packages/core/test/transport.spec.ts

Improve RUM and Log SDK performance when numerous console.error occur.
1000 console error loaded in 15000ms 
1000 console error loaded in 7000ms 
- ⚡️ improve sizeInByte calculation

⚡️[RUMF-510] Improve sizeInByte calculation performance

---

packages/core/package.json

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
core package should not contain side effect, a few functions can then be safely removed while building target files
mark core package as side effect free
- rum: 44k -> 42k
- logs: 30k -> 29k
---

👷[build] allow sideEffects optimization on core

---

packages/rum/src/rum.entry.ts
packages/rum/src/viewCollection.ts
packages/rum/test/specHelper.ts

Looking good on datadog, enable everywhere
Remove feature flag
---

✨[RUMF-513] enable keep alive mechanism

---

packages/core/src/internalMonitoring.ts
packages/rum/src/rum.ts

Investigate event without sessionId
Add internal log when detecting one
---

[RUMF-559] debug undefined sessionId

---

packages/core/test/sessionManagement.spec.ts
packages/rum/src/rum.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts

Some events are sent to the intake without a session id.
Scenario to reproduce:
- sdk initialized with a session not tracked on two different tabs
- session expiration
- one tab renew the session in a tracked state
- generate some events on the second tab without interacting with it
then the second tab still considers to be on the last view of the first session, so `viewContext.sessionId = undefined`.
Events can be added to the batch because `session.isTracked() = true` due to the value of the cookie.
No matter what is the visibility state of the second tab, we don't want to create a new view and  collect the associated events before any real user action on this tab.
Ensure that `viewContext.sessionId` is defined to allow events to be added to the batch.
--- …

🐛[RUMF-559] prevent event without sessionId

---

packages/core/src/configuration.ts
packages/core/src/index.ts
packages/core/src/init.ts
packages/core/src/internalMonitoring.ts
packages/core/test/configuration.spec.ts
packages/logs/src/buildEnv.ts
packages/logs/src/logger.ts
packages/rum/src/rum.ts

Allow to analyze staging events in prod environment
**Constraint**
For RUM, we need to have different application id when sending events.
**Strategy**
For each event source (rum, logs, internal monitoring), instantiate a primary and a replica batch. Each event is added to both.
**Extra configuration**
```
{
replica?: {
applicationId?: string
clientToken: string
}
}
```
Manual test
---

👷[RUMF-528] allow dual shipping in staging

---

packages/rum/src/resourceUtils.ts

I've notice favicon and other .ico files are not classified as images.
Add `ico` to the list of file extensions considered for resources of image kind.
Using a local built of this SDK classifies .ico files properly.

Classify favicons (and icons in general) as resources of image kind

---

packages/core/src/cookie.ts
packages/core/src/specHelper.ts
test/e2e/scenario/helpers.ts

Firefox has started to display a warning for all used cookies that don't specify a same site attribute.
Let's specify one to get rid of it.
fixes #430 
Specify `samesite=strict` on all our cookies updates, we don't need to pass cookies to server requests, so let's use the more restrictive option.
cf https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#Write_a_new_cookie
Tested in dev, warning has disappeared in firefox.
---

✨[RUMF-594] specify same site attribute on cookies

---

packages/logs/README.md
packages/rum/README.md

Datacenter values are now exposed in an enum.
In a typescript setup, it is required to use it to avoid compilation issues.
fix #434 
Update setup instructions to retrieve Datacenter enum.
---

🐛 use Datacenter enum in setup doc

---

packages/logs/README.md
packages/logs/src/index.ts
packages/rum/README.md
packages/rum/src/index.ts

Avoid to add browser-core in dependencies
export Datacenter enum from logs and rum
---

✨[RUMF-609] export Datacenter enum from logs and rum

---

packages/rum/src/lifeCycle.ts
packages/rum/src/rum.ts
packages/rum/src/trackEventCounts.ts
packages/rum/src/userActionCollection.ts
packages/rum/src/viewCollection.ts
packages/rum/test/rum.spec.ts
packages/rum/test/trackEventCounts.spec.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

Prepare future work on associate events with its parents based on start time
Fix discard user action on view created instead of view update
Introduce new events:
- VIEW_CREATED: when a view is created
- VIEW_UPDATED: when a view is updated
- ACTION_CREATED: when an action is created
- ACTION_COMPLETED: when an action is completed
- ACTION_DISCARDED: when an action is discarded
---

✨[RUMF-603] Introduce and use new lifecycle events

---

.codecov.yml
package.json
yarn.lock

coverage was not reported on PR
upgrade codecov
notify even if the ci is not finished
---

🐛  fix pr coverage

---

packages/core/src/utils.ts
packages/logs/src/logger.ts
packages/rum/src/lifeCycle.ts
packages/rum/src/parentContexts.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts
packages/rum/src/viewCollection.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

Following #438, prepare future work on associate events with its parents based on start time.
- introduce parentContexts
- use parentContexts
- handle view url & session in parentContexts
- return structured context
- prepare usage with startTime
- rework userActionCollection
---

♻️ [RUMF-604] introduce parentContexts to return current contexts

---

packages/rum/src/lifeCycle.ts
packages/rum/src/parentContexts.ts
packages/rum/src/rum.ts
packages/rum/src/trackEventCounts.ts
packages/rum/src/userActionCollection.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/trackEventCounts.spec.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

ACTION_COMPLETED is triggered by both auto and custom user actions.
Action context can then be reset by custom user action happening during an auto user action
Split custom and auto life cycles which are pretty different.
Remove previous checks on action type on ACTION_COMPLETED subscription
View event counts track both completion events to update the user action count
---

🐛 fix current action context reset on custom action

---

packages/core/src/internalMonitoring.ts
packages/core/src/transport.ts
packages/core/src/utils.ts
packages/core/test/transport.spec.ts
packages/logs/src/logger.ts
packages/rum/src/rum.ts

Following #440, dual shipping was broken due to wrong application id being associated with replica events.
This was due to an incorrect merge order.
Remove context provider from Batch and let the caller process him self the message before passing it to the batch.
---

🐛 fix dual shipping

---

extension/src/background/background.ts
extension/src/contentscript/listenRumEvents.ts
extension/src/popup/src/App.tsx

Mieux comprendre vos 2 derniers commits et en jouant avec je voulais clean un peu pour mieux comprendre, une chose en entrainant une autre voila la PR.
- message format `{ type: string, payload: any }`
- merge `tabsState` and `tabsViews` and send only views for the active tab
- init (to have some data when opening the popup)
- auto-refresh
- display documentVersion to see update
---

refact message format, tabState by tagID,  add auto refresh and init

---

packages/core/src/index.ts
packages/rum/src/parentContexts.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/userActionCollection.spec.ts
test/static/bundle-e2e-page.html

Events were attached to parent view or action when we received them. It caused some issues in the waterfall display where we could see events starting before the start of the view (or the action) which were very confusing.
Keep an history of parent contexts to retrieve the one (if any) corresponding to the start time of the event.
Clear automatically old context on session renew or after a time out delay.
---

✨ [RUMF-605] associate event to parent context by start date (behind flag)

---

packages/rum/src/parentContexts.ts
packages/rum/src/rum.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/specHelper.ts
test/static/bundle-e2e-page.html

cf [✨ associate event to parent context by start date (behind flag)](https://github.com/DataDog/browser-sdk/pull/445)
Remove flag
---

✨ [RUMF-605] enable event association to parent context by start date

---

packages/rum/src/viewCollection.ts
packages/rum/test/viewCollection.spec.ts

**Given**
startViewCollection
**When**
on window.location.hash changes
**Then**
check if the views are different. 
If the hash fragment has changed, then the views are different.
- ✨    add a `trackHash` function
- ✨    modify `areDifferentViews` to handle hash changes
✅    hash changes tests have been added both for pushStates and window.location.hash window.location.hash
Test with the Vue router without `mode: 'history'`:
`const router = new VueRouter({
routes
})`
SDK: better support for SPA routing - STEP 2/2 : filter out html anchor tags changes

SDK: better support for SPA routing - STEP 1/2 : add hash tracking

---

packages/core/src/urlPolyfill.ts
packages/rum/src/lifeCycle.ts
packages/rum/src/parentContexts.ts
packages/rum/src/rum.ts
packages/rum/src/viewCollection.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

When a SPA changes its URL, the ending view gets updated with the new URL. It should keep its initial URL no matter what.
See https://datadoghq.atlassian.net/browse/RUMF-625
When formating a RumViewEvent, use the one from the collected View object instead of the ViewContext which already contains the new URL
---

[RUMF-625] make sure view url doesn't change

---

yarn.lock

Fix security vulnerability
Bump version
---

Bump dot-prop to 5.2.0

---

.gitignore
packages/core/src/errorCollection.ts
packages/core/src/fetchProxy.ts
packages/core/src/index.ts
packages/core/src/requestCollection.ts
packages/core/src/specHelper.ts
packages/core/src/utils.ts
packages/core/src/xhrProxy.ts
packages/core/test/errorCollection.spec.ts
packages/core/test/fetchProxy.spec.ts
packages/core/test/requestCollection.spec.ts
packages/core/test/xhrProxy.spec.ts
packages/logs/src/logs.entry.ts
packages/logs/test/logs.entry.spec.ts
packages/rum/src/lifeCycle.ts
packages/rum/src/matchRequestTiming.ts
packages/rum/src/requestCollection.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/test/machRequestTiming.spec.ts
packages/rum/test/requestCollection.spec.ts
packages/rum/test/rum.entry.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/trackPageActivities.spec.ts

Current proxies of XHR and fetch were managed by request collection which was handled as a singleton to avoid to proxy XHR and fetch multiple times.
With the future integration of tracing inside the sdk (cf #461), we would want to collect request with trace id for rum but not for logs. 
In a npm setup this would be problematic since the request collection instance would be shared between rum and logs.
1.  Extract XHR and Fetch proxies that:
- instrument browser API only once
- deal with request data, not with domain logic (request id, trace id, request type) 
- provide hooks to attach/retrieve info during the request life cycle
2. Use proxies in request collection and error collection
3. Move request collection to rum package
--- …

[RUMF-617] Extract XHR and Fetch proxies

---

packages/logs/README.md
packages/logs/src/logger.ts
packages/logs/src/logs.entry.ts
packages/logs/test/logger.spec.ts

In issue #409 it was suggested updating the logger API to allow users to remove keys from the logger. 
This PR updates the logger API to have a removeContext method that removes a key from the context object. No existing methods have been modified as part of this work.
To test this new functionality, the user must call removeContext with an existing key. A unit test has been added to test the existing addContext function and the new removeContext function. 
---

✨ Update context api to include removeContext method

---

.gitlab-ci.yml
README.md
package.json
packages/core/src/configuration.ts
packages/core/src/index.ts
packages/core/src/init.ts
packages/core/test/configuration.spec.ts
packages/logs/README.md
packages/logs/src/buildEnv.ts
packages/logs/webpack.config.js
packages/rum/README.md
packages/rum/src/buildEnv.ts
packages/rum/webpack.config.js
scripts/build-env.js
scripts/deploy.sh
scripts/replace-build-env.js
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

Allow to easily support future datacenters and align configuration parameter with other libraries.
- Support site configuration
- Build new bundle files without suffix: `datadog-rum.js` and `datadog-logs.js`
- Use new bundle files everywhere
---

✨ [RUMF-626] use site configuration and deprecate suffixed bundle

---

packages/core/src/xhrProxy.ts
packages/core/test/xhrProxy.spec.ts

Issue raised by customer
Check that xhr has been instrumented on `open` to instrument `send`
---

🐛[RUMF-639] xhr proxy: do not instrument xhr already opened

---

packages/rum/src/rum.ts
packages/rum/test/rum.spec.ts

Load timings where not converted to nanosecond anymore
Make sure load timings are converted to nanosecond
---

🐛 [RUM] fix loading measures conversion to nanoseconds

---

package.json
yarn.lock

The dot-prop version bump #473 45adeed86645dadf4aaaa81ceb6df08e842abebb only changed the lockfile. 
Adjust the package.json so a correct lockfile is generated when re-running yarn.
---

👷 fix lock file

---

packages/core/package.json
packages/logs/package.json
packages/rum/package.json
yarn.lock

See #493 
To reduce the SDK cost when using it through NPM, we should accept any semver compatible tslib version, so it can use an already present tslib version if any.
The bundled SDK is still using tslib 1.10.0 as specified by yarn.lock
Adjust the required tslib version in package.json
---

👷 relax tslib version for SDKs installed through npm

---

packages/core/src/configuration.ts
packages/core/test/configuration.spec.ts
packages/logs/src/logger.ts
packages/logs/test/logger.spec.ts
packages/rum/src/rum.ts

There is a few issues with #494 : 
* The corresponding facet hasn't been updated by the backend
* Mobile SDKs are still using the tag instead of the attribute
* The SidePanelHeader is using the tag, not the attribute https://github.com/DataDog/web-ui/blob/43b199c540d7b026bcb8b9f6a8cd191e36810a99/javascript/datadog/rum/components/side-panel/SidePanelHeader/EventContextRow/EventContextRow.tsx#L36
Those issues should be addressed before deploying #494 , maybe by dual shipping the service as a tag and an attribute #501 , but we should discuss about it a bit more.
This reverts commit ff82247eb18a17568f3d3fb03293ed8dd2afe1ac.
---

Revert "[RUMF-620]: Send "service" as an attribute, not a tag (#494)"

---

packages/rum/src/lifeCycle.ts
packages/rum/src/parentContexts.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts
packages/rum/src/viewCollection.ts
packages/rum/test/parentContexts.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/userActionCollection.spec.ts
packages/rum/test/viewCollection.spec.ts

For `route_change` views, use the previous view URL as referrer.
For the sake of simplicity, lifecycle types have been improved a bit so we can re-use them easily. Then, the referrer has been set to the View context so it can be used everywher the View context is used. Finally, the view collections is retrieving the previous view URL when creating the new view on URL change or session renew.
---

[RUMF-621] set view referrer to the previous view URL

---

packages/core/src/configuration.ts
packages/core/src/errorCollection.ts
packages/core/src/index.ts
packages/core/test/errorCollection.spec.ts
packages/rum/src/resourceUtils.ts

Intake request errors are reported which cause a loop of errors 
Exclude intake request errors like intake resource events
---

🐛[RUMF-645] do not track intake request errors

---

packages/rum/src/tracer.ts
packages/rum/test/tracer.spec.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/helpers.ts

some requests headers possible types were not copied with the tracing headers, resulting in some request failures due to missing headers.
Handle other headers types
---

🐛[RUMF-617] fix missing headers on traced requests

---

packages/rum/src/requestCollection.ts
packages/rum/src/rum.ts
packages/rum/src/trackPageActivities.ts
packages/rum/test/requestCollection.spec.ts
packages/rum/test/trackPageActivities.spec.ts
test/e2e/scenario/agents.scenario.ts
test/e2e/scenario/serverTypes.ts

Allow future link from APM trace to corresponding RUM resource
- rename requestId in requestIndex
- add resource id for traced request
Traced requests are sent with a resource id
---

[RUMF-634] add resource id for traced request

---

packages/core/src/errorCollection.ts
packages/core/src/init.ts

Before this commit, the RUM and Logs were dependent:
* when initializing the RUM SDK first, setting `forwardErrorsToLogs: false` option was ignored;
* when initializing the Logs SDK first, and setting `forwardErrorsToLogs: false`, errors were not collected in RUM
This fixes the issue by avoiding calling `startErrorCollection` if error collection is not needed.
Setup both SDKs with NPM/webpack (the bundle version does not have this issue because the 'core' modules are not shared between logs and rum). Start by calling `init` for RUM, then on Logs with `forwardErrorsToLog: false`. Errors should not be forwarded to logs.
---

[RUMF-684] fix error collection configuration

---

packages/core/src/utils.ts
packages/rum/src/performanceCollection.ts
packages/rum/test/performanceCollection.spec.ts

Because the RUM SDK can be initialized synchronously when the document is loading, the DOM may not be fully accessible when getting the trace id set by APM. In particular, if meta tags are written after the SDK snippet, the SDK will not have access to them during init.
Wait for DOM to be loaded before getting the trace id and generating the initial document resource.
Tests have been written in the integration test POC PR https://github.com/DataDog/browser-sdk/pull/524
---

🐛 [RUMF-670] wait for the DOM to be ready before getting the trace id

---

packages/logs/README.md
packages/logs/src/logger.ts
packages/logs/src/logs.entry.ts
packages/logs/test/logger.spec.ts
packages/rum/README.md
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/test/rum.spec.ts

Allow users to remove a global context.
* Implements `removeGlobalContext` in the Log package
* Implements `removeGlobalContext` to the Rum package
add some unittests
---

✨ SDK: Add new functionality to remove global context to SDK

---

packages/core/src/configuration.ts
packages/core/test/configuration.spec.ts

fix https://github.com/DataDog/browser-sdk/issues/529
Remove useless buggy check and add missing unit tests
---

🐛 fix issue when using proxy

---

LICENSE-3rdparty.csv
package.json
yarn.lock

1. We have multiple security issues in sub-dependencies (cf `yarn audit`)
2. We want to limit forced version `resolution` in `package.json` by upgrading dependencies that used outdated sub-dependencies.
Upgrade some dependencies.
All dependencies implied were dev dependencies (used by build or tests). Running CI should be fine.
---

👷 fix security issues in dependencies

---

yarn.lock

Get rid of handlebars warnings when executing unit tests (the latest
version of istanbul-reports isn't using handlebars anymore, see
https://github.com/istanbuljs/istanbuljs/pull/503 )
Upgrade istanbul-reports from 2.2.6 to 2.2.7
Run unit tests. No handlebar warnings should be shown in the output.
---

⬆️ Upgrade istanbul-reports

---

packages/core/src/configuration.ts
packages/core/src/specHelper.ts
packages/core/test/configuration.spec.ts
packages/core/test/errorCollection.spec.ts
packages/logs/test/logger.spec.ts
packages/rum/test/resourceUtils.spec.ts
test/app/app.ts
test/server/fake-backend.js
test/static/async-e2e-page.html
test/static/bundle-e2e-page.html

When using a proxy on the same origin than the current page, some resources may be incorrectly filtered out.
Test the beginning of the path to make sure this is a intake url.
---

[RUMF-699] isIntakeRequest: test the path as well

---

packages/core/src/configuration.ts
packages/logs/src/logger.ts
packages/logs/test/logger.spec.ts
packages/rum/src/rum.ts

The move of `service` from tag to attribute must be done in two steps to ease the transition.
Send `service` as attribute as well as tag.
---
Closes #501

[RUMF-620]: Dual-ship "service" as tag and attribute

---

packages/core/src/internalMonitoring.ts
packages/core/src/utils.ts
packages/core/test/utils.spec.ts
packages/logs/src/logger.ts
packages/rum/src/rum.ts

Ensure that nothing breaks when the user unexpectedly pass `null` for values that end up in a `Context`.
Add proper support for `null` value in context.
Unit tests have been upgraded. You can test it manually by calling `DD_RUM.init({ service: null, clientToken: 'xxx', applicationId: 'xxx' })`
---

✨ [RUMF-709][core] support 'null' as a context value 

---

packages/core/src/configuration.ts
packages/core/test/configuration.spec.ts
packages/rum/README.md

Some customers hi-jack the host to also have a path.
Since it is working, ensure that it is fully supported.
- check that request contain `v1/input`, not only start with it
- doc: replace proxy url by proxy host with an example to avoid confusion
---

🐛 consider proxy host with custom path request as intake request

---

packages/rum/README.md

Wrong option name in doc
Use right option name
none
---

doc: fix wrong option name

---

packages/core/src/utils.ts
packages/core/test/utils.spec.ts
packages/rum/src/getActionNameFromElement.ts

Some UTF-8 characters can be composed of a pair of "surrogate" characters.
more details:  [MDN#encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)
Ensure that our string truncate don't make invalid string by keeping only the first part of the pair.
unit test
---

🐛[RUMF-716] fix invalid action name

---

packages/core/src/contextManager.ts
packages/core/src/index.ts
packages/core/src/init.ts
packages/core/test/contextManager.spec.ts
packages/logs/src/logger.ts
packages/logs/src/logs.entry.ts
packages/logs/test/logger.spec.ts
packages/logs/test/logs.entry.spec.ts
packages/rum/src/lifeCycle.ts
packages/rum/src/requestCollection.ts
packages/rum/src/rum.entry.ts
packages/rum/src/rum.ts
packages/rum/src/userActionCollection.ts
packages/rum/test/requestCollection.spec.ts
packages/rum/test/rum.entry.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts
packages/rum/test/trackEventCounts.spec.ts
packages/rum/test/viewCollection.spec.ts

We want to allow using RUM APIs before initialising the SDK. (see #545 for the Logs side)
* Remove stubs and regroup the public API implementation
* Use a bounded buffer to collect pre-init user actions and send them at init
* Make `getInternalContext` return `undefined` before init
Unit tests have been updated. Manual testing can be done by running some `DD_RUM.addUserAction('foo')` or `DD_RUM.getInternalContext()` before `DD_RUM.init()`.
---

✨ [RUMF-530][RUM] allow using RUM API before init 

---

test/e2e/wdio.bs.conf.js

Stabilise bs e2e tests
- add 1 spec file retries
- add browser name to differentiate runner logs
---

✅[RUMF-732] e2e:bs add spec file retries

---

packages/rum/src/assembly.ts
packages/rum/src/batch.ts
packages/rum/src/index.ts
packages/rum/src/lifeCycle.ts
packages/rum/src/rum.ts
packages/rum/test/assembly.spec.ts
packages/rum/test/rum.spec.ts
packages/rum/test/specHelper.ts

Split responsibilities, preliminary work for v2 format
- trackRumEvents send `RAW_RUM_EVENT_COLLECTED` life cycle events
- assembly listen `RAW_RUM_EVENT_COLLECTED` and send `RUM_EVENT_COLLECTED`
- batch listen `RUM_EVENT_COLLECTED`
---

♻️[RUMF-725] Extract RUM assembly and batch logic 

---

packages/core/src/index.ts
packages/core/src/init.ts
packages/logs/src/logs.entry.ts
packages/rum/src/rum.entry.ts
test/e2e/lib/framework/pageSetups.ts

Have a proper way to execute code when the SDK is ready.
* Implement `logs.onReady` and `rum.onReady` to execute previously stored callbacks
* Change the e2e tests async setup to use the new official async snippet
---

 ✨ [RUMF-534] implement logs.onReady and rum.onReady 

---

test/app/package.json
test/app/yarn.lock

https://github.com/DataDog/browser-sdk/network/alert/test/app/yarn.lock/serialize-javascript/open
Updates terser-webpack-plugin to allow a newer javascript-serialize version.
This commit also removes the need for 'resolution' by updating the sub-dependencies directly in yarn.lock instead.
E2E tests and compat:tsc tests should be enough
---

⬆️ update sub-dependencies to fix security issues in test/app

---

LICENSE-3rdparty.csv
package.json
packages/core/src/specHelper.ts
packages/core/test/xhrProxy.spec.ts
packages/rum/test/requestCollection.spec.ts
test/unit/karma.base.conf.js
test/unit/karma.bs.conf.js
yarn.lock

unit test on bs are brittle because requests to karma middleware are randomly not completing
- use xhr stub to avoid any issue with real requests during unit tests
- add seed reporter to ease ci failure reproduction
---

✅[RUMF-732] use stub instead or real xhr in unit test

---

packages/core/src/cookie.ts

The function `getCurrentSite` can yield invalid result when a SDK is initialized multiple times within 1 second.
* Cache `getCurrentSite` result
* Use an unique cookie name for `getCurrentSite`
Setup the RUM SDK on a test page, and print its internal context. Beforehand, clear any cookie on the current domain. Then, refresh the page quickly 2 times: the session should stay the same, and the cookie should be created with a valid domain.
---

:bug: [RUMF-742] fix cookie creation domain when trackSessionAcrossSubdomains: true

---

packages/rum/src/domain/assemblyV2.spec.ts
packages/rum/src/domain/assemblyV2.ts

in v2, customer attributes are encapsulated in a context attribute
move customer attribute to context
unit tests
---

🐛 [RUMF-745] fix V2 context

---

.gitlab-ci.yml

Avoid running multiple browserstack CI jobs in parallel to comply to the parallel test quota.
CI only
---

👷 [RUMF-750] add the resource_group gitlab option to browserstack tests

---

test/e2e/lib/framework/pageSetups.ts

Limit e2e-bs job flakiness.
By default, only run tests with the 'bundle' setup on BS
CI only
---

👷 [RUMF-751] only use the 'bundle' setup on BS by default

---

scripts/bs-wrapper.js

Retry e2e-bs test when wdio fails to create the browserstack session
Restore the retry strategy by checking the test stdout to look for specific error messages.
CI only
---

[RUMF-752] restore retry strategy on session creation failure

---

test/browsers.conf.js
test/e2e/browsers.conf.js
test/e2e/scenario/rum/resources.scenario.ts

Mitigation for https://datadoghq.atlassian.net/browse/RUMF-753. Edge 18 is outdated and have a tiny market share, let's support the last version of Edge instead.
Update Edge version to 86 in BrowserStack tests
CI
---

[RUMF-753] ✅ bump BrowserStack Edge version

---

packages/core/src/boot/init.ts
packages/core/src/domain/errorCollection.spec.ts
packages/core/src/domain/errorCollection.ts
packages/core/src/index.ts
packages/logs/src/boot/logs.spec.ts
packages/logs/src/boot/logs.ts
packages/rum/src/boot/rum.spec.ts
packages/rum/src/boot/rum.ts
packages/rum/src/domain/assembly.spec.ts
packages/rum/src/domain/assemblyV2.spec.ts
packages/rum/src/domain/lifeCycle.ts
packages/rum/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum/src/domain/trackEventCounts.spec.ts
packages/rum/src/types.ts
packages/rum/src/typesV2.ts

Following #570, migrating error to v2 format
- mutualize collection start for provided and auto error
- handle error in v2
- use internal unstructured error format to ease usage across logs, rum V1 and rum v2
unit tests, staging
---

✨[RUMF-740] migrate error to v2 format (experimental)

---

packages/logs/src/boot/logs.ts
packages/rum/src/boot/rum.spec.ts
packages/rum/src/boot/rum.ts
packages/rum/src/domain/internalContext.spec.ts
packages/rum/src/domain/internalContext.ts
packages/rum/test/specHelper.ts

Following #570, migrating internal context to v2 format
- extract to dedicated file
- handle v2
- keep v1 properties for logs for now
unit tests, staging
---

✨[RUMF-518] migrate internal context to v2 format (experimental)

---

packages/core/src/domain/internalMonitoring.ts
packages/core/src/index.ts
packages/core/src/tools/context.spec.ts
packages/core/src/tools/context.ts
packages/core/src/tools/contextManager.ts
packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts
packages/core/src/transport/transport.ts

Support cyclic references in various Context manipulations.
Related issue: #587
The cyclic references are set to 'undefined', and will be skipped in JSON serialization.
* Simple test: `a = { b: 1 }; a.c = a; DD_LOGS.logger.log('foo', a)` should not fail, and 'c' should not appear in log context
* CI tests have been added
---

[RUMF-756] cyclic reference support in Context

---

test/app/yarn.lock
test/e2e/lib/framework/createTest.ts
test/e2e/lib/helpers/validation.ts
test/e2e/lib/types/serverEvents.ts
test/e2e/scenario/logs.scenario.ts
test/e2e/scenario/rum/actions.scenario.ts
test/e2e/scenario/rum/errors.scenario.ts
test/e2e/scenario/rum/resources.scenario.ts
test/e2e/scenario/rum/tracing.scenario.ts
test/e2e/scenario/rum/views.scenario.ts
test/e2e/tsconfig.json
tslint.json

With migration of different event types to v2 format, validate events generated during e2e tests.
- use v2 format in e2e tests
- add validation in tearDown
---

[RUMF-729] validate rum events in e2e

---

packages/core/src/boot/init.ts
packages/core/src/browser/fetchProxy.ts
packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/src/domain/automaticErrorCollection.ts
packages/core/src/domain/internalMonitoring.ts
packages/core/src/index.ts
packages/core/src/tools/error.spec.ts
packages/core/src/tools/error.ts
packages/logs/src/boot/logs.ts
packages/rum/src/boot/rum.ts
packages/rum/src/domain/lifeCycle.ts
packages/rum/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/src/domain/trackEventCounts.spec.ts
packages/rum/src/domain/trackEventCounts.ts

The recent introduction of RAW_RUM_EVENT_COLLECTED lifecycle events allows to simplify the event counts tracking.
* Adjust view measures tests a bit
* Use RAW_RUM_EVENT_COLLECTED and RAW_RUM_EVENT_V2_COLLECTED instead of various events in trackEventCounts
* Remove the now unused RESOURCE_ADDED_TO_BATCH event
* Replace the ERROR_COLLECTED event by listening directly to the raw error observable.
Unit and e2e tests
---

[RUMF-748] use RAW_RUM_EVENT_COLLECTED to compute event counts

---

.gitmodules
package.json
packages/rum/src/boot/rum.spec.ts
packages/rum/src/domain/assemblyV2.spec.ts
packages/rum/src/domain/rumEventsCollection/action/actionCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum/test/createRawRumEvent.ts
packages/rum/test/formatValidation.ts
packages/rum/test/specHelper.ts
test/unit/karma.base.conf.js

events were validated on wrong schema 🤦 
- use the correct schema
- make rum-events-format to track master
- fix unit tests to pass validation
unit tests
---

🐛 Fix unit test format validation

---

packages/rum/src/domain/assemblyV2.spec.ts
packages/rum/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceUtils.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/test/fixtures.ts

Quick fix to see if demo website shorter browser spans could be related to wrong timing association.
Since TAO is not enabled on shopist, we should observe a duration increase for RUM fetch events.
Do not consider invalid or incomplete timing in match request timing.
unit test, manual tests on DD + demo
if hypothesis is confirmed, discuss proper strategies. 
---

[RUMF-766] prevent request duration override by wrong matching timing

---

packages/core/src/tools/specHelper.ts
packages/rum/package.json
packages/rum/src/boot/rum.spec.ts
packages/rum/src/browser/performanceCollection.spec.ts
packages/rum/src/domain/assembly.spec.ts
packages/rum/src/domain/assemblyV2.spec.ts
packages/rum/src/domain/internalContext.spec.ts
packages/rum/src/domain/parentContexts.spec.ts
packages/rum/src/domain/rumEventsCollection/action/actionCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum/test/specHelper.ts
test/unit/karma.base.conf.js

The line between what should be in specHelper and what should not is blurry. Most of domain-related `withXXX` methods are only used by the related domain spec file. It seems that `beforeBuild` is a good way to start a given function based on a testing context (session, configuration, etc.).
This PR tries to simplify the unit test specHelper by reducing its responsabilities:
* the `withFakeServer` is replaced with a spy on `RUM_EVENT_COLLECTED` lifecycle events
* a `withConfiguration` method has been added to the spec helper to allow modifying the configuration before any `beforeBuild` call
* the `beforeBuild` method has been extended to expose more context to the callback, and allow to specify a cleanup function
* domain-specific `withXXX` methods have been inlined to their related spec …

✅ [RUMF-759] cleanup RUM unit tests specHelper

---

packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.ts
packages/rum/src/typesV2.ts

Allow to debug match request timing on real data
Should be reverted after the analysis
when `'match-debug'` enabled, add debug infos to resource events
tested locally
---

⚗️[RUMF-766] add match request timing debug infos (experimental)

---

packages/logs/src/boot/logs.entry.spec.ts
packages/logs/src/domain/logger.spec.ts
packages/logs/src/domain/logger.ts

Fixing https://github.com/DataDog/browser-sdk/issues/589
The context is now included when using the `console` handler. It's passed as the second parameter to `console.log` call instead of calling it twice.
I updated the logs unit tests to check that the context is included.
---

✨ [RUMF-762] include the context when using console handler

---

packages/logs/README.md
packages/logs/src/boot/logs.entry.ts
packages/logs/src/domain/loggerSession.ts
packages/rum/src/boot/rum.entry.ts

Simply debugging by providing getters for global contexts.
- Couple of small changes (correcting return type and removing unused import).
- Added `getLoggerGlobalContext` and `getRumGlobalContext`
- Updated README
No new tests were added since the contextManager methods are already tested and those getters are just aliases of `contextManager.get`.
---

✨ [RUMF-771] Add getLoggerGlobalContext and getRumGlobalContext

---

packages/logs/src/boot/logs.ts
packages/rum/src/domain/internalContext.spec.ts
packages/rum/src/domain/internalContext.ts
packages/rum/src/typesV2.ts

Following #593, keep compatibility with logs data format
in v2, internal context still returns v1 format
unit, staging
---

✨ [RUMF-758] keep internal context in v1 format (experimental)

---

packages/core/src/tools/specHelper.ts
packages/core/src/tools/utils.ts
packages/rum/src/browser/performanceCollection.ts
packages/rum/src/domain/rumEventsCollection/view/trackFirstHidden.spec.ts
packages/rum/src/domain/rumEventsCollection/view/trackTimings.spec.ts
packages/rum/src/domain/rumEventsCollection/view/trackTimings.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum/src/typesV2.ts

Expose the web-vitals LCP on initial views
* Implement LCP tracking
* Use it on initial views
CI + manual tests on chrome
---

✨ [RUMF-775] implement Largest Contentful Paint

---

packages/rum/src/browser/performanceCollection.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum/src/typesV2.ts

Expose the web-vitals CLS on all views
* Implement CLS tracking
CI + manual tests
---

✨ [RUMF-777] implement Cumulative Layout Shift

---

packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.ts

toJSON is not available in IE11, prevent execution error
check if toJSON available before using it
manual
---

🐛 [RUMF-791] prevent IE11 performance entry error

---

packages/rum/src/domain/requestCollection.spec.ts
packages/rum/src/domain/requestCollection.ts
packages/rum/src/domain/tracing/tracer.spec.ts
packages/rum/src/domain/tracing/tracer.ts

Do not trace cancelled requests because they lack backend information.
Set `request.traceId` to `undefined` if the request was cancelled.
Added unit tests to ensure that `traceId` is removed from the `LifeCycleEventType.REQUEST_COMPLETED` event when the `request.status == 0`.
---

✨ [RUMF-770] Disable tracing for cancelled requests

---

packages/core/src/boot/init.ts
packages/core/src/domain/automaticErrorCollection.ts
packages/core/src/domain/configuration.spec.ts
packages/core/src/domain/configuration.ts
packages/core/src/index.ts
packages/core/src/tools/specHelper.ts
packages/rum/src/domain/rumEventsCollection/resource/resourceUtils.ts

Use the new public intake for US site
Applies the new intake domain when the US site is used in the configuration.
Unit tests of configuration generation have been updated.
---

✨ [RUMF-764] Use new intake domain for US

---

packages/logs/README.md

Users should only use objects as global context, not string
Adjust the documentation
Documentation only
---

📝 [LOGS] fix logger doc typo

---

packages/core/src/domain/internalMonitoring.ts
packages/core/src/domain/tracekit.spec.ts
packages/core/src/domain/tracekit.ts

Object thrown with an object message instead of a string is forwarded as is, which is not compatible with our backend and our UI.
ex:
```js
throw { message: { foo: 'bar' }}
```
sent:
```json
{ "message": { "foo": "bar" }, "stack": "Error: { \"foo\": \"bar\" }"}
```
expected:
```json
{ "message": "Uncaught { \"foo\": \"bar\" }", "stack": "'No stack, consider using an instance of Error'"}
```
- Check inside tracekit that StackTrace message and name are string
- allow `StackTrace.message = undefined` which was already checked in the code
automated tests + sandbox
---

🐛 fix tracekit handling of exotic errors

---

packages/core/src/domain/tracekit.spec.ts
packages/core/src/domain/tracekit.ts

Following #651, we still observe some malformed errors when tracekit can compute a stacktrace but the message is malformed.
Do not assume input exception type and try to sanitize properties before using them.
---

🐛 sanitize error properties even when there is a valid stack

---

packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/src/domain/tracekit.spec.ts
packages/core/src/domain/tracekit.ts

Following #651 and #655, we still observed malformed errors with object messages and stack:
```
Error: [object Object]
at undefined @ undefined
```
That seems related to tracekit handling of `window.onerror` direct calls.
Update tracekit direct calls strategy to endup on the case where we advise to use an instance of Error.
---

🐛 handle direct onerror calls with objects

---

scripts/deploy.sh

By keeping an outdated version while revalidating the sdk version, usage of new APIs can lead to undefined functions error.
Remove stale-while-revalidate from cache options
---

🐛 [CDN cache] remove stale-while-revalidate

---

packages/logs/src/index.ts
packages/rum/src/index.ts

fix #654 
Add in exports:
- rum: ProvidedSource
- logs: StatusType, HandlerType
N/A
---

[RUMF-807] Export types used in API

---

packages/core/src/tools/contextManager.ts
packages/logs/src/boot/logs.entry.ts
packages/logs/src/domain/logger.ts
packages/rum/src/boot/rum.entry.ts

Using Context or ContextValue in our APIs is not convenient for typescript customers since customer interfaces won't be compatible with them due to [index signature missing on interfaces](https://github.com/microsoft/TypeScript/issues/15300).
Replace Context by object and ContextValue by any in APIs
Keep using Context and ContextValue internally.
fix #603 
---

[RUMF-807] Broaden context types in APIs

---

LICENSE-3rdparty.csv
packages/rum-recorder/package.json
packages/rum-recorder/src/domain/rrweb/index.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
yarn.lock

Previous PR: #657 
Next PR: #670 
Import RRWeb in the rum-recorder codebase
---

[RUMF-803] import RRWeb

---

.gitlab-ci.yml
packages/core/tsconfig.cjs.json
packages/core/tsconfig.esm.json
packages/logs/tsconfig.esm.json
packages/logs/tsconfig.json
packages/rum-core/tsconfig.cjs.json
packages/rum-core/tsconfig.esm.json
packages/rum-core/tsconfig.json
packages/rum-recorder/tsconfig.cjs.json
packages/rum-recorder/tsconfig.esm.json
packages/rum-recorder/tsconfig.json
packages/rum/tsconfig.cjs.json
packages/rum/tsconfig.esm.json
packages/rum/tsconfig.json
tsconfig.base.json
tsconfig.json
webpack.base.js

The staging build is broken: `yarn build:bundle` fails because the rum-recorder webpack build can't find the `@datadog/browser-rum-core` package (transitive dependency).
For some reason, `yarn build` works though.
* read paths from `tsconfig.base.json` when building with webpack: this avoids having to redeclare paths in each packages
* add a ci job to check for `yarn build:bundle`
CI
---

👷 fix build bundle

---

.gitlab-ci.yml
packages/logs/.npmignore
packages/logs/package.json
packages/logs/webpack.config.js
packages/rum-recorder/package.json
packages/rum-recorder/webpack.config.js
packages/rum/.npmignore
packages/rum/package.json
packages/rum/webpack.config.js
scripts/build-env.js
scripts/deploy.sh
scripts/dev-server.js
scripts/replace-build-env.js
webpack.base.js

Since `rum-recorder` is a new bundle, we don't have to support the legacy bundle with a suffix, so I didn't add the extra logic to generate it in the webpack configuration. The deploy job expect to have it though, and tries to add a comment banner on a non-suffixed file, which is unexpected and fails.
Don't build rum-recorder bundle with a suffix.
---

👷 fix build bundle (continuation)

---

scripts/codecov.sh
webpack.base.js

Code coverage have been broken since 8a55636ed3d8d8bb7e79a23a05696c60667db665.
Invert ts and string-replace loaders in webpack configuration. Changing the loader order fixes the code coverage during unit tests.  I investigated deeply into istanbul and string-replace-loader,  I have a gut feeling that it is because string-replace-loader does not support source maps, but can't confirm it.
CI, https://codecov.io/gh/DataDog/browser-sdk/tree/546c12eaf46d48f9f802dbf62458c249b34331f4/packages
---

👷 [RUMF-818] fix unit tests code coverage

---

packages/logs/BROWSER_SUPPORT.md
packages/logs/README.md
packages/rum/BROWSER_SUPPORT.md
packages/rum/README.md

Document RUM features support by main browsers.
Similar to [logs/BROWSER_SUPPORT.md](https://github.com/DataDog/browser-sdk/blob/master/packages/logs/BROWSER_SUPPORT.md), add a browser support doc for RUM features.
NA
---

📝 [RUMF-792] add RUM browser support

---

packages/core/src/domain/tracekit.ts
packages/core/src/domain/tracekitParser.spec.ts
packages/core/test/capturedExceptions.ts

iOS capacitor app stack traces are not correctly parsed.
fixes #645
Test case corresponding to [this error](https://github.com/getsentry/sentry-javascript/issues/1863#issuecomment-562910174).
Similar modifications in tracekit than the [one in sentry](https://github.com/mrlowe/sentry-javascript/commit/3a09f918e0cbadfdbc1c11d6d779d4718d597fb0)
Unit test only
---

✨[RUMF-802] add support for iOS capacitor app stack traces

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/src/rumEvent.types.ts

Following #670 , I forgot to add the `session.has_replay` flag during event assembly. It will be used to filter events that have a session replay in web-ui. Its backend support (facet and merge on Session events) are being implemented.
* add `session.has_replay` on events
Unit tests, manual testing
---

[RUM] add session.has_replay

---

packages/core/src/domain/configuration.spec.ts
packages/core/src/domain/configuration.ts

Ensure that tags value are properly interpreted on backend side.
Note: most of the special characters are converted to underscore anyway, cf [tags doc](https://docs.datadoghq.com/getting_started/tagging/#defining-tags).
URL encode value of `tags` query param in intake requests 
Unit + manual test
---

🐛[RUMF-809] URL encode tags in intake requests

---

packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts

* Replays are watched by session. If a session doesn’t start with a full snapshot, it cannot be played from the start.
* Records can happen in multiple tabs simultatenously. This causes an issue during replay, because the player gets incremental snapshot but doesn’t know on which fullsnapshot it should apply. By starting all views with a full snapshot, the player can drop segments with a different view from the previous one but without full snapshot. This an easy workaround that can be improved in the future. 
* Add the ability to manually trigger full snapshots in RRWeb
* Use it via LifeCycle events
Unit + manual
---

[RUMF-813] take full snapshots when the view changes or the session is renewed

---

packages/core/src/browser/fetchProxy.ts
packages/core/src/tools/specHelper.ts
packages/rum-core/src/domain/tracing/tracer.spec.ts
packages/rum-core/src/domain/tracing/tracer.ts
test/e2e/lib/helpers/browser.ts
test/e2e/scenario/rum/tracing.scenario.ts

Support `Request` instances in tracing
```js
fetch(
new Request('http://localhost:3000', {
headers: {
'x-foo': 'bar',
},
})
)
```
Clone instance and add trace headers if the fetch init argument is a `Request`.
Unit
---

[RUMF-824] support Request instances in tracing

---

packages/core/src/boot/init.ts
packages/core/src/domain/configuration.spec.ts
packages/core/src/domain/configuration.ts
packages/core/src/domain/transportConfiguration.spec.ts
packages/core/src/domain/transportConfiguration.ts
packages/core/src/index.ts

Alternate govcloud intake has replaced the classic one, only us and eu can use classic intakes now.
- Update `getIntakeType` logic to only support classic for us and eu
- move INTAKE_SITE and Datacenter to avoid tooling issue
unit + manual on gov app
---

✨ [RUMF-826] Allow classic intake only for us and eu

---

package.json
scripts/cli

Avoid to manually update/revert it 
- extract version cli command
- update test app lockfile before making the version commit
next release
---

👷 Update test app lockfile on release

---

packages/rum-core/src/rawRumEvent.types.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.spec.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.ts

`session.has_replay` should not be set if the record has not been started, to be consistent with the RUM bundle without recorder.
This change only affects the recorder with flag `postpone_start_recording`.
Set hasReplay to undefined by default.
Adjust typings to enforce this.
Unit
---

[recorder] set 'hasReplay' to undefined by default

---

package.json
packages/core/test/forEach.spec.ts
yarn.lock

fix socket io vulnerability
Fix socket.io resolution to 2.4.0
**Note:**
Don't bump Karma to 6.0.0 since safari and IE browserstack tests seems to have trouble with it for now.
Could be related to https://github.com/karma-runner/karma-browserstack-launcher/issues/186
ci
---

⬆️ Bump socket.io version

---

packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/test/utils.ts

I want to abstract the pattern [introduced while working on the recorder tests](https://github.com/DataDog/browser-sdk/pull/670/commits/0dbceac30bdad343aced91277a9792280ad55877) to be used in other test specs. Since there is many ways of implementing this, I'd like to share this beforehand so we can agree on the best way of doing so.
* define `expectNoExtraCalls` and `waitCalls` in the recorder `test/utils`
* use it in `recorder.spec.ts`. Because now only `jasmine.Calls` objects are exposed instead of transformed `{ data: FormData, size: number }` objects, a `getRequestData` helper  has been introduced locally.
Unit
---

[RUMF-814] extract the "waitRequests" pattern as a util function

---

packages/core/src/tools/utils.ts
packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/types.ts

Add focus information to always show the currently focused view during replay
* adjust types
* adjust rrweb architecture a bit to externalize records generation: the goal is to avoid implementing new records in the RRWeb codebase, to be more modular and easier to test. In a future PR, I'll remove some records from RRWeb, limiting its usage to recording DOM changes.
* add Focus records tracking
Unit tests, manual tests
---

[REPLAY-164] track Focus records

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts

Timing name is used as facet path, use of unsupported characters can then prevent the measure creation:
- Sanitize timing name by replacing unsupported characters by `_`
- Warn when a sanitization is performed
unit + manual
---

🐛[RUMF-836] sanitize unsupported characters in timing name

---

LICENSE-3rdparty.csv
packages/rum-core/src/domain/lifeCycle.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-recorder/package.json
packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/types.ts
packages/rum-recorder/test/utils.ts
webpack.base.js
yarn.lock

This is part of multitab tracking strategy. To let the player know a view has ended, a new record is added when the view ends or before unloading the page.
There is some limitations with this strategy:
* there may be multiple ViewEnd per view because a ViewEnd record is added even if the "beforeunload" event gets cancelled. We may add a way to detect "beforeunload" cancellations in the future
* there may be no ViewEnd for a view: if the browser fails to send the segment for whatever reason (sendBeacon limitations, connection issues, ...)
* there may be records or segments added after the ViewEnd record: the "beforeunload" event is triggered when the page starts to unload, and it can take a moment (the browser is waiting for the first byte of the next page response to actually leave the …

[REPLAY-149] implement ViewEnd record

---

packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/domain/segmentCollection.spec.ts
packages/rum-recorder/src/domain/segmentCollection.ts
packages/rum-recorder/src/types.ts

When the session is renewed, a new View is created. In the RUM recorder, we are subscribing to both events, so we run the same action twice when a session is renewed.
This commit removes unneeded callbacks invoked when the session is renewed, since they are already triggered when a view is created.
Manual
---

⚡️ [RUMF-841] remove session renew support in rum recorder

---

.gitlab-ci.yml
package.json
packages/core/src/browser/cookie.ts
packages/core/src/domain/sessionManagement.ts
packages/core/src/tools/utils.ts
packages/rum-core/src/domain/parentContexts.ts
packages/rum-core/src/domain/trackPageActivities.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
packages/rum-recorder/src/domain/segmentCollection.ts
test/e2e/tsconfig.json
test/unit/karma.base.conf.js
tsconfig.base.json
tsconfig.json
webpack.base.js

All types present in node_modules are used for every type of compilations (typecheck, bundle, ...) which can then lead to some type ambiguity.
ex: setTimeout defined by DOM and node
- list needed types depending on the context
- used compiled sources in e2e compilation to avoid ambiguity, move typecheck e2e to build-and-lint accordingly
- simplify code used to avoid previous ambiguities
ci / editor
---

🔧 [RUMF-825] restrict which types are used depending on the context

---

packages/rum-recorder/src/domain/rrweb/mutation.spec.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts

When importing rrweb code, I made a typo and `index--` became `index +=
1`.
https://github.com/DataDog/browser-sdk/pull/658/commits/ecc09e7fe83407f003097f23ca2b277d0bdc5436#diff-7e32def6242fea74b49dc8381d38f18941e632957f7cea33951a0ecb07597705L280-R281
It should fix the "Cannot read property 'value' of null" and "Position outside of list" errors
Restore loop direction!
---

🐛 [RUMF-834] fix loop direction

---

.eslintrc.js
LICENSE-3rdparty.csv
package.json
packages/logs/src/boot/logs.entry.ts
yarn.lock

1. Avoid to merge `fit` or `fdescribe`
2. Current warn on master 
1. install [eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine#rules), I have not spotted other must have rules but open to suggestion
2. @typescript-eslint/no-unused-vars seems to be the only "warn" rule, promote it to error and fix the current issue
ci
---

👷 Lint improvements

---

packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/segment.spec.ts
packages/rum-recorder/src/domain/segmentCollection.spec.ts
packages/rum-recorder/src/types.ts
sandbox/index.html

Player does not use `DomContentLoaded`, `Load` or `Custom` record type.
- Remove related code
- Do not mess with RecordType enum indexes
ci + manual
---

🔥[RUMF-821] remove unused record types

---

packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
test/e2e/lib/types/serverEvents.ts
test/e2e/scenario/recorder.scenario.ts
test/e2e/tsconfig.json

Avoid to touch shared API if it is not needed
Replace `forEach` polyfills by a forEach utility function
ci
---

🔥 recorder: remove forEach polyfills

---

packages/core/src/domain/internalMonitoring.ts
packages/core/src/index.ts
packages/rum-recorder/src/domain/deflateSegmentWriter.ts
packages/rum-recorder/src/domain/deflateWorker.d.ts
packages/rum-recorder/src/domain/deflateWorker.js

Keep an eye on worker execution
- try/catch worker execution
- new `DeflateWorkerResponse` for error
manual
---

⚗ [RUMF-823] monitor deflate worker

---

.eslintrc.js
packages/core/src/tools/utils.ts
packages/logs/src/boot/logs.entry.spec.ts
packages/logs/webpack.config.js
packages/rum-core/src/boot/rum.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-recorder/webpack.config.js
packages/rum/webpack.config.js
scripts/generate-changelog.js
test/app/webpack.config.js
test/e2e/lib/framework/httpServers.ts
test/e2e/lib/framework/serverApps/mock.ts

Remove unused parameters from the code.
- Customize ESLint rule `@typescript-eslint/no-unused-vars` to check all parameters and only ignore the ones starting with `_` (we need this to ignore some parameters coming from external libraries). 
ci
---

🔥 Remove unused parameters

---

packages/rum-recorder/src/domain/privacy.spec.ts
packages/rum-recorder/src/domain/privacy.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb-snapshot/types.ts
packages/rum-recorder/src/domain/rrweb/mutation.spec.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
test/e2e/browsers.conf.js
test/e2e/lib/helpers/recorder.ts
test/e2e/scenario/recorder.scenario.ts

Following up on https://github.com/DataDog/browser-sdk/pull/692 we figured it was best to expose privacy controls leveraging both classes & data attributes. Data attributes are used by other places of the SDK, and it made sense to show consistency.
This PR introduces the "privacy.ts" file with various helpers used by rrweb & rrweb-snapshot. This results in the recorder:
- ignoring the content of an element (obfuscation) if it has the attribute `data-dd-privacy` set to `hidden` or a class of `dd-privacy-hidden` 
- ignoring input events of an element if it has the attribute `data-dd-privacy` set to `input-ignored` or a class of `dd-privacy-input-ignored`, or if it is an input of type "password", "email" or "tel"
Further work could be done to offer a third strategy for inputs, obfuscating …

replay: add dd-privacy attribute for obfuscation & ignoring input

---

packages/rum-recorder/src/domain/privacy.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
test/e2e/scenario/recorder.scenario.ts

This PR is a follow up on https://github.com/DataDog/browser-sdk/pull/715
As a node can be hidden from a data attribute rather than a class,
only adding the class to the snapshot node attributes means we can't
properly style the node when rebuilding it.
This PR ensures the `data-dd-privacy=hidden` attribute is always
set, even if the node was hidden using the class.
Additionally, we set the ID as a/ it helps with testing, b/ we can
assume it doesn't contain PII and c/ it may be used when
rebuilding (CSS rules could be selecting by ID).

replay: set data-dd-privacy attribute on snapshot node if hidden

---

.gitlab-ci.yml
Dockerfile
test/e2e/wdio.local.conf.js

To allow e2e with local chrome 88
Bump chrome driver + chrome installed in docker
ci + local
---

e2e: 🔼 Chrome version to 88

---

package.json
packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.spec.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/test/forEach.spec.ts
yarn.lock

TS 4.x needed to update wdio dependencies
- Bump ts version
- Remove useless BrowserWindow
- Tweak some casts for INode and NodeInLinkedList 😕
ci
---

🔼 Bump TypeScript to 4.1.5

---

yarn.lock

Cf: https://github.com/DataDog/browser-sdk/security/dependabot/developer-extension/package.json/react-dom/open
The security issue is on react-dom, but since react and react-dom are
tightly coupled, let's upgrade both to the latest 16.x version just to
be safe.
---

⬆️🔒 upgrade react-dom and react

---

README.md

`rum-core` is missing in packages list
add `rum-core`
NA
---

Readme: add missing rum-core package

---

packages/core/src/domain/configuration.ts
packages/core/src/tools/limitModification.spec.ts
packages/core/src/tools/limitModification.ts
packages/logs/src/boot/logs.spec.ts
packages/logs/src/boot/logs.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/trackEventCounts.spec.ts
packages/rum-core/src/domain/trackEventCounts.ts

Allow customers to dismiss RUM events.
- Use `RUM_EVENT_COLLECTED` event to update event counts.
- Dismiss the event if `beforeSend` returned `false` and it's not a view event.
- Show a warning if `beforeSend` returned `false` for a view event.
- unit tests
- manual
---

✨ [RUMF-854] Enable beforeSend to dismiss events

---

packages/core/src/domain/configuration.ts
packages/rum/README.md

No reason to promote this configuration parameter since it is not aligned with billing.
It only confuses customers and generate support questions.
Remove resourceSampleRate from doc + add deprecated note in configuration
NA
---

📝 Doc: remove resourceSampleRate

---

packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts

Remove duplicated code by re-using the core "throttle" function in rum-recorder
* Adjust the "throttle" function so it keeps the function arguments 
* use it is RRWeb codebase
* remove RRWeb utils throttle
Manual
---

[RUMF-845] use core throttle function in recorder

---

packages/core/src/tools/utils.ts
packages/rum-core/src/browser/performanceCollection.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts

Reduce duplicated logic in core/rrweb
* Mutualize `runOnReadyState` (this function was using `addEventListeners`, so instead of re-implementing it in rrweb, just mutualize it)
* Adjust typings so the listener gets any event type as argument
* Replace `on` usages with `addEventListener`
* Make `DOM_EVENT` a `const enum`
CI, manual
---

[RUMF-845] use core 'addEventListener' in recorder

---

packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb-snapshot/types.ts
packages/rum-recorder/src/domain/rrweb/mutation.spec.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
packages/rum-recorder/src/internal.ts

Lighter bundle, less code to maintain
Removed options:
* inlineStylesheet
* packFn
* mask input
* sampling
* hooks
* checkoutEvery*
Removed recording strategies:
* fonts
* canvas
See commit messages for rationals.
CI
---

[RUMF-846] remove unused rrweb parts

---

packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.spec.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb-snapshot/types.ts
packages/rum-recorder/src/domain/rrweb/mutation.spec.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/rrweb/utils.ts

A bit less code (removed option) and lighter snapshots ("slim DOM" option always enabled)
* Remove the "slim DOM" option
* Always apply all "slim DOM" strategies
* Add some unit testings
Unit, manual
---

[RUMF-845] remove slimDOM option and enable strategies to ignore elements

---

.eslintrc.js
LICENSE-3rdparty.csv
package.json
performances/README.md
performances/package.json
performances/src/format.ts
performances/src/main.ts
performances/src/profiling.ts
performances/src/trackNetwork.ts
performances/src/types.ts
performances/tsconfig.json
yarn.lock

Evaluate the Browser SDK performance impact on a given scenario
Implement a tool to run various profilings with puppeteer. You can try it with:
```
git checkout benoit/performance-doc
yarn
cd performances
yarn start
```
Example output:
```
Illustrates a mostly static site scenario.
* Navigate on three Wikipedia articles
* Do a search (with dynamic autocompletion) and go the first result
Memory (median): 294 kB (4.83%)
CPU: 258 ms (4.24%)
Bandwidth:
upload: 116 kB
download: 20.5 kB
Illustrates a SPA scenario.
* Navigate to the top trending topics
* Click on the first trending topic
* Click on Top, Latest, People, Photos and Videos tabs
* Navigate to the Settings page
* Click on a few checkboxes
Memory (median): 225 kB (0.51%)
CPU: 391 ms (1.01%)
Bandwidth:
upload: 186 kB
download: 20.5 kB …
```

⚗ performance impact summary tool

---

packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.ts

Sometimes, in Chrome Browser on Chrome OS or obscur browsers like [Puffin](https://www.puffin.com/), the first input delay timing is negative. Discard those invalid timings, since they are likely not representing a real value. 
The issue have been reported to the [chromium tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1185815)
Discard negative FID values
Unit
---

🐛 [RUMF-855] discard negative first-input delays

---

packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.ts

Help debug the negative FID, see comment 1 in https://bugs.chromium.org/p/chromium/issues/detail?id=1185815#c1
Add internal monitoring log when the FID is negative
Manual
---

🔊 [RUMF-855] add negative FID monitoring

---

packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/src/domain/automaticErrorCollection.ts
packages/core/src/tools/error.ts
packages/core/src/tools/utils.ts
packages/core/test/forEach.spec.ts

Ease Error Tracking grouping
behind `console-stack` FF:
- remove error stack from raw error message
- set raw error stack to first error instance stack
unit tests + manual
---

⚗ [RUMF-863] rework console error calls containing error instances

---

.eslintrc.js
eslint-local-rules/disallowConstEnumExports.js
eslint-local-rules/disallowEnumExports.js
eslint-local-rules/disallowSideEffects.js
eslint-local-rules/index.js
package.json
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/types.ts
tsconfig.json
yarn.lock

Exporting `const enum` values only works if the user builds their package with TypeScript. Other bundlers don't use type informations, so can't use `const enum` values.
* Change `MediaInteractions` to a standard enum
* Add an ESLint rule to avoid this kind of issue in the future
Manually
---

[RUMF-862] fix export MediaInteractions enum

---

packages/rum-recorder/src/boot/rumRecorderPublicApi.spec.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.ts

Adjust the way to postpone the recording start
This PR should not be merged before we adjust our internal usages of `postpone_start_recording`.
* introduce the new `manualSessionReplayRecordingStart` option
* rename `startSessionRecord` to `startSessionReplayRecording`
Everything is still under the same `postpone_start_recording` flag
---

[RUMF-866] adjust postpone start recording

---

developer-extension/package.json
developer-extension/webpack.config.js
package.json
test/app/package.json
test/app/webpack.config.js
test/app/yarn.lock
test/unit/karma.base.conf.js
tsconfig.webpack.json
webpack.base.js
yarn.lock

Upgrade ssri to v8.0.1 to fix https://github.com/advisories/GHSA-vx3p-948g-6vhq
To do this cleanly, it forces us to upgrade lerna and webpack to new major versions.
* for lerna, [v4 does not bring any breaking change](https://github.com/lerna/lerna/releases/tag/v4.0.0) appart from the minimal supported nodejs version, which is fine.
* for webpack, this was a bit trickier because generally other related dependencies were not compatible with v5. I took the opportunity to upgrade a bunch of things.
Bundles are a bit smaller with webpack 5
```
Minified bundle sizes in bytes, not gzip
before   after
datadog-logs.js           33,254   32,036
datadog-rum.js            59,739   58,606
datadog-rum-recorder.js  107,797  106,842
```
* Upgrade lerna, webpack and webpack-related dependencies
* Upgrade …

⬆️ upgrade lerna, webpack and related

---

packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackTimings.ts

We collected enough data to investigate the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1185815). Remove the monitoring, and adjust negative FID to 0 as per [Chromium developer recommendation](https://bugs.chromium.org/p/chromium/issues/detail?id=1185815#c5).
* Revert #759 
* Adjust negative FID to 0
Unit
---

Revert negative FID monitoring and adjust to 0

---

packages/core/src/tools/utils.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts

Having more than 4 decimals to the cumulative layout shift score produce more noise than value. Since this score is compared to minimum `0.1`, the precision is still 3 orders of magnitude below, so it should be completly fine.
Round the cumulative layout shift score to 4 decimals.
Unit
---

[RUMF-857] round CLS to 4 decimals

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/lifeCycle.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/fixtures.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.spec.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.ts
packages/rum-recorder/src/domain/segmentCollection.spec.ts
packages/rum-recorder/src/domain/segmentCollection.ts

Implement a method to stop session replay recording
* Add the method
* Make sure the last segment is flushed when stop recording
* Make sure the view keeps its has_replay field to `true`.
Unit, manual
---

[RUMF-867] implement stop recording

---

packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/src/domain/automaticErrorCollection.ts
test/e2e/scenario/rum/resources.scenario.ts

Releasing #768 can lead to a big drop of network errors in some applications, and could impact some customer monitoring setup. We are planing to remove network errors entirely in the near future, so we decided to not release this publicly yet and wait for proper communication to be ready.
Put #768 behind a experimental feature flag
CI
---

[RUMF-853] introduce a feature flag for aborted network errors

---

packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/boot/recorder.ts
packages/rum-recorder/src/domain/rrweb/observer.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/rrweb/record.ts
packages/rum-recorder/src/domain/rrweb/types.ts
packages/rum-recorder/src/domain/segment.spec.ts
packages/rum-recorder/src/domain/segment.ts
packages/rum-recorder/src/domain/segmentCollection.ts

Previously, the Focus record logic was uncorrelated with the FullSnapshot logic, and we have seen cases where Focus records where emited in a segment before the initial FullSnapshot record (because rrweb waits for `onload` before starting to generate records)
This PR moves the Focus record logic to be closer to the FullSnapshot logic and uses the same guarantees as the Meta record to ensure all three events are correctly added in the same segment.
Unit, manual
---

[RUMF-869] Ensure the "Focus" records are emited in the same segment as the "FullSnapshot"

---

.eslintrc.js
packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/src/domain/automaticErrorCollection.ts

cf #762:
* remove error stack from raw error message
* set raw error stack to first error instance stack 
Remove feature flag + outdated tests
unit
---

✨ [RUMF-863] Enable console error with stack traces

---

developer-extension/webpack.config.js

With the recent upgrade to Webpack 5, process.env is not defined by default, so bumbag crashes because it uses it to check if it is running in a test environment.
Define `process.env.BUMBAG_ENV` to `"production"`. Bumbag only test if it is equal to `"test"`, so it doesn't matter too much if we set it to `"production"`, `"development"` or something else.
Manual
---

🐛 fix developer extension popup

---

packages/rum-recorder/src/boot/rumRecorderPublicApi.spec.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.ts

Snippets, that are still using `postpone_start_recording` and aren't using `manualSessionReplayRecordingStart: false`, are problematic because the recording starts when using DD_RUM.init even if it should be postponed.
Don't automatically start recording when `postpone_start_recording` experimental feature is enabled.
CI, manual
---

[RUMF-886] don't start recording when 'postpone_start_recording' is enabled

---

packages/rum-core/src/domain/rumEventsCollection/view/trackLocationChanges.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackLocationChanges.ts

Better support for hash routers.
Do not take the "search" (anything starting from a `?`) part of a hash into account when comparing URLs to generate a new view.
Unit
---

[RUMF-868] ignore paramaters stored in the hash

---

packages/core/src/domain/tracekit/report.ts
packages/core/src/transport/transport.ts

Some execution errors were not caught by the internal monitoring, cf #794
Add missing monitoring wrappers
ci + manual (for flush)
---

🐛 add missing monitoring wrappers

---

packages/core/src/domain/transportConfiguration.ts

This parameter is not used anymore.
Remove it from the intake URL
Manual
---

[RUMF-877] remove _dd.application_id from the URL

---

packages/core/src/transport/transport.spec.ts
packages/core/src/transport/transport.ts

From the spec, sendBeacon can throw TypeError.
cf #794 
Fallback to xhr when sendBeacon throws
unit
---

🐛 fallback to xhr when sendBeacon throws

---

.gitlab-ci.yml
Dockerfile
test/e2e/wdio.local.conf.js

Allow to run local e2e tests with latest chrome version
Bump chrome driver and ci chrome versions
ci
---

e2e: bump chrome and driver version

---

.eslintrc.js
packages/core/src/browser/xhrProxy.ts
packages/core/src/tools/utils.ts
packages/logs/src/boot/logs.entry.spec.ts
packages/rum-core/src/browser/domMutationCollection.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.spec.ts
packages/rum-recorder/src/domain/rrweb-snapshot/snapshot.ts
packages/rum-recorder/src/domain/rrweb/mutation.ts
packages/rum-recorder/src/domain/rrweb/utils.ts
packages/rum-recorder/test/forEach.spec.ts
test/e2e/scenario/rum/tracing.scenario.ts

This rule is a bit annoying for our codebase because we actually use "underscore dangles" in some of our variable/properties.
Remove the rule from ESLint commit and all "disable" comments.
---

🚨 remove ESLint rule "no-underscore-dangle"

---

developer-extension/src/background/domain/replaceBundles.ts

This allows to use the extension in staging. I think the file name is explicit enough to prevent false positives.
Relax bundle URLs in the developer extension
Manual
---

relax bundle URLs in the developer extension

---

packages/core/src/tools/timeUtils.ts

With #809 enabled, some documents start 1 ms before the start of the view.
Relative time can have sub milliseconds precision, taking the floor of the value can easily introduce a 1 ms error:
```
Request start               10.925
Navigation start            11
floor(Request start)        10   < Navigation start    
round(Request start)        11   = Navigation start
```
With some tests to compare rounding strategies:
0 ms: request start = navigation start
1 ms: request start < navigation start
-1 ms: request start > navigation start
Using round seems more accurate.
Use round instead of floor.
Manual
---

🐛 [RUMF-889] fix relative time rounding

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-recorder/src/boot/recorder.spec.ts
packages/rum-recorder/src/domain/segmentCollection.spec.ts
packages/rum-recorder/src/domain/segmentCollection.ts

We have noticed that a tab in an expired session state can send events if another tab as an active session.
Prevent to send event when current session id is not the same that the view context session id.
unit + manual
---

🐛[RUMF-900] prevent events to be sent from expired session

---

packages/rum-core/src/domain/lifeCycle.ts
packages/rum-core/src/domain/parentContexts.spec.ts
packages/rum-core/src/domain/parentContexts.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-recorder/src/boot/recorder.spec.ts

When a view is ended when changing page, some events can still be tracked and attached to the view after its end, which seems quite surprising.
Clear current view context on view end
unit + manual
---

🐛 [RUMF-900] clear parent view context when view end

---

packages/rum-core/src/domain/rumEventsCollection/resource/matchRequestTiming.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/matchRequestTiming.ts

Flaky e2e tests put in evidence that timing associated to an instrumented request can not alway be perfectly nested.
Observed case:
```
Req start     593.3949999
Timing start  593.5950000
Req end       799.3949999
Timing end    799.5550000
```
Allow a 1 ms error margin in the matching condition.
unit + ci
---

🐛 allow 1 ms error for matching request

---

test/e2e/lib/helpers/browser.ts

Fix flaky tests
Use loadend event to consider e2e XHR done to be more aligned with SDK implementation.
(Not 100% sure that it improves the situation)
ci
---

✅ try to stabilise some e2e tests

---

.github/PULL_REQUEST_TEMPLATE.md
.gitlab-ci.yml
packages/logs/README.md
packages/rum/README.md

Following #829, rename default branch
Rename `master` to `main`
- Rename default branch
- Merge PR
- Update [doc configuration](https://github.com/DataDog/documentation/blob/b4c8f125bae04235f44bfcb63529a33a28c8c93b/local/bin/py/build/configurations/pull_config.yaml#L413)
---

👷 update default branch name

---

packages/core/src/domain/internalMonitoring.spec.ts
packages/core/src/domain/sessionManagement.spec.ts
packages/core/src/tools/errorFilter.spec.ts
packages/core/src/tools/utils.spec.ts
packages/core/test/specHelper.ts
packages/logs/src/boot/logs.entry.spec.ts
packages/logs/src/boot/logs.spec.ts
packages/logs/src/domain/loggerSession.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum-core/src/domain/rumSession.spec.ts
packages/rum-core/src/domain/trackPageActivities.spec.ts
packages/rum-core/test/specHelper.ts
packages/rum-recorder/src/domain/rrweb/record.spec.ts
packages/rum-recorder/src/domain/segmentCollection.spec.ts

https://github.com/DataDog/browser-sdk/pull/828#discussion_r625591812
Our clock system is becoming a bit more complex. In #828, I introduced spec helper function to help mock the clock based on the rum-core spec helper. This PR slightly change the implementation and generalize its usage over all spec files.
* Change the mock a bit to avoid having a destructuring assignement and using two distinct variables.
* Replace all `jasmine.Clock` usages by the new `mockClock` function.
Unit
---

✅ use `mockClock` everywhere

---

package.json
test/e2e/lib/framework/logger.ts
yarn.lock

A few subdependencies have been updated to address new security advisories. Notes:
* Bumbag uses fixed versions for its dependencies, and didn't release a version with the new lodash version, so we hane to force the lodash version there. This has been reported [here][1]
* `yarn audit` will still warn about a "moderate" vulnerability in the hosted-git-info subdependency, but this is a false-positive: the author backported the fix in version [2.8.9][2], but the security advisory hasn't been updated with this information.
* Somehow, when upgrading subdependencies, I ugraded `@types/node`, and a wild typecheck issue appeared.
[1]: https://github.com/bumbag/bumbag-ui/issues/105#issuecomment-834398613
[2]: https://github.com/npm/hosted-git-info/blob/v2/CHANGELOG.md#289-2021-04-07
CI
---
I have …

📦 [RUMF-905] update vulnerable dependencies

---

scripts/bs-wrapper.js

Improve BS tests by removing the buggy and unneeded retry logic from bs-wrapper.
* Add some documentation to have an history of what was previously attempted with this script.
* Remove the retry logic
CI
---

✅ remove the retry logic from bs-wrapper

---

packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts

Provide an API to clear a previously set user without having to clear all its attributes.
#774
Allows you to clear a  previously set user with the API `removeUser()`
Unit, manual
---

✨ Clear previously set user context

---

packages/core/src/tools/timeUtils.ts
packages/core/src/transport/transport.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/specHelper.ts

Provide extra context info for debugging
- remove monotonic batch time from requests
- attach current drift in `_dd.drift` field
ci, manual
---

✨[RUMF-908] attach current drift value to events

---

packages/core/src/tools/display.ts

`Invalid calling object` errors reported since 2.9.0, related to #847.
Explanation: IE 11 console implementation has still some behavior differences when devtools are open or not
To reproduce:
- open the page with devtools closed
- open the devtools
- create a console logger and log a message
Result: `Invalid calling object` exception
Expected: message loged in console
bind console object to function references
manual
---

🐛 [logs] Fix IE11 console.log issue

---

scripts/generate-changelog.js

Regression introduced by #848 
Force using a shell for spawn commands
manual with:
- `EDITOR=vi node scripts/generate-changelog.js`
- `EDITOR='vi -e' node scripts/generate-changelog.js`
---

🐛 fix changelog generation

---

packages/rum-recorder/src/constants.ts
packages/rum-recorder/src/domain/record/mutationBatch.spec.ts
packages/rum-recorder/src/domain/record/mutationBatch.ts
packages/rum-recorder/src/domain/record/mutationObserver.spec.ts
packages/rum-recorder/src/domain/record/mutationObserver.ts
packages/rum-recorder/src/domain/record/observer.spec.ts
packages/rum-recorder/src/domain/record/observer.ts
packages/rum-recorder/src/domain/record/privacy.spec.ts
packages/rum-recorder/src/domain/record/privacy.ts
packages/rum-recorder/src/domain/record/serializationUtils.spec.ts
packages/rum-recorder/src/domain/record/serializationUtils.ts
packages/rum-recorder/src/domain/record/serialize.spec.ts
packages/rum-recorder/src/domain/record/serialize.ts
packages/rum-recorder/src/domain/record/types.ts
test/e2e/scenario/recorder.scenario.ts

Let the user chose to mask input values (replacing the characters with asterisks) instead of completely ignoring them via a new privacy attribute value `data-dd-privacy="input-masked"` / `class="dd-privacy-input-masked"`.
This PR removes the collection of some input values (radio/checkbox). Those values are likely to be useless during replay (note: if you think of a usecase, let me know). This way, we don't have to chose whether we should ignore/mask them.
It introduces an "input privacy mode", either computed by iterating over a node parent or propagated while serializing nodes.
It factorizes the input elements "value" computation by introducing a common function that will respect the "input privacy mode" and will be used while:
* the value is changed by the user, triggering an "input" …

✨ [RUMF-913] allow masking input values

---

packages/core/src/tools/boundedBuffer.spec.ts
packages/core/src/tools/boundedBuffer.ts
packages/logs/src/boot/logs.entry.ts
packages/rum-core/src/boot/rum.spec.ts
packages/rum-core/src/boot/rum.ts
packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
test/app/app.ts
test/e2e/lib/framework/createTest.ts
test/e2e/lib/framework/pageSetups.ts
test/e2e/scenario/rum/init.scenario.ts

First step in the manual view naming strategy
behind `view-renaming` flag, introduce new API:
```ts
DD_RUM.startView(name?: string)
```
Allowing to manually start a new view with an optional name
unit / manual
---

⚗ [RUMF-878] add startView API

---

packages/rum-recorder/src/domain/record/serializationUtils.spec.ts
packages/rum-recorder/src/domain/record/serializationUtils.ts

The RUM recorder tries to transform URLs in attributes or CSS to make them absolute. Sometimes, the value passed as an URL fails to parse, and an error is thrown. 
Just return the original value in this case.
Unit
---

🐛 do not break the recorder when an URL fails to parse

---

package.json
scripts/cli

Add early check to prevent release from main branch by mistake.
- introduce a `release` cli command
- check current branch with `git branch --show-current` (git >= 2.22)
manual
---

👷 prevent release from main branch

---

packages/core/src/tools/utils.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceUtils.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
sandbox/index.html

customer report with some values in weeks 
add monitoring log with extra info on clock state to see if there is any inconsistencies
manual
---

🔊 [RUMF-927] monitor timings with high values

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts

In case of renew session, restart tracking with a view name as soon as an user interaction occurs.
Regardless of the view tracking mode:
- create a new view on renew session
- use current view name for the new view
unit
---

⚗ [RUMF-878] manual view tracking: create new view on renew session

---

package.json
yarn.lock

Should fix [dependabot alerts](https://github.com/DataDog/browser-sdk/security/dependabot) and `yarn audit` issues.
Update a few subdependencies.
The 'get-pkg-repo' sub-dependency version resolution has been forced because it pulls a vulnerable dependency and conventional-changelog takes its time to upgrade it[1]. Since we don't use conventional-changelog through our lerna setup it shouldn't matter.
[1]: https://github.com/conventional-changelog/conventional-changelog/pull/809
---

⬆️ update vulnerable dependencies

---

packages/core/src/browser/fetchProxy.spec.ts
packages/core/src/domain/automaticErrorCollection.spec.ts
packages/core/test/specHelper.ts
packages/rum-core/src/domain/requestCollection.spec.ts
packages/rum-core/src/domain/requestCollection.ts
packages/rum-core/src/domain/tracing/tracer.spec.ts
packages/rum-core/src/domain/tracing/tracer.ts

Improve the chance to have a complete distributed trace on request resources: requests aborted by the application are likely to reach the server even if they ends up with a 0 status.
Keep trace information for requests aborted by the application.
CI
---

✨ [RUMF-920] keep trace id on aborted requests

---

.gitlab-ci.yml

Speed up Gitlab pipeline
Enable global cache for npm_modules
Save ≈ **24 sec** per pipeline (will save 48 sec with the Canary version) 
Save ≈ **75 Mo** of network data transfert per pipeline
Gitlab
---

👷 Configure global dependencies cache

---

.gitlab-ci.yml

Speed up gitlab pipelines by enabling cross pipeline cache
Change gitlab cache config
Locally
---

👷 Enable cross pipeline Gitlab cache

---

packages/rum-recorder/src/boot/startRecording.spec.ts
packages/rum-recorder/src/boot/startRecording.ts
packages/rum-recorder/src/domain/record/record.ts
packages/rum-recorder/src/domain/record/types.ts

Pending mutations were flushed when a FullSnapshot was taken, but in this case the new view was already active, so pending mutations were incorrectly attributed to the new view.
To fix this issue, we should flush pending mutations when the view ends.
Manual testing, unit test.
---

🐛 fix new view segment starting with an IncrementalSnapshot

---

packages/logs/src/logsEvent.types.ts

Allows to scrub `error.stack` in logs `beforeSend`.
Fixes #917
make logs event error.stack writable
---

🏷️🐛 make logs event error.stack writable

---

packages/core/src/domain/configuration.ts
packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts

It can be useful to reuse existing tagging in the html to retrieve the action name rather than forcing customer to duplicate their tagging for every third party that need to retrieve this info.
take over of #903 
Introduce new `actionNameAttribute` init configuration option
Usage:
```html
<script>
DD_RUM.init({
...
trackInteractions: true,
actionNameAttribute: 'data-custom-name'
...
})
</script>
<a onclick="triggerSomeRequestOrDomChange()" data-custom-name="Login button">Try it out!</a>
```
Both `data-dd-action-name` and configured attribute can be used, `data-dd-action-name` is favored when both are present on an element.
unit, locally
---

✨ [RUMF-945] allow users to customize the attribute used to define the action name

---

packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/boot/startLogs.ts
test/e2e/lib/framework/pageSetups.ts
test/e2e/scenario/logs.scenario.ts

This PR makes it possible to add custom attributes to logs event on `beforeSend` as requested here https://github.com/DataDog/browser-sdk/issues/896 
- Allow modification of any field, not only sensitive fields.
- Allow addition of new fields.
- unit
- e2e
- local
---

✨ [RUMF-932] Allow context edition in logs beforeSend

---

packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-recorder/src/boot/rumRecorderPublicApi.spec.ts
test/e2e/scenario/rum/init.scenario.ts

To better identify and group views, a `view.name` concept has been introduced.
In order to provide this `view.name` at the right time and to be sure that it will be include in children events: 
- allow customers to handle themselves the view creation lifecycle rather than relying on url changes
- allow customers to provide a name when starting a new view
Related PRs: #850, #867, #887
```ts
DD_RUM.startView(name?: string)
```
Allow to manually start a new view with an optional name
when `trackViewsManually: true`:
- rum start is postponed until the first `startView` call
- on location change:
-  no new views are created
- current view location is still updated
ci
---

✨ [RUMF-928] enable manual view tracking

---

packages/core/src/browser/cookie.ts

Firefox does not seem to quickly clean cookie based on expiration date, so test cookies can pile up quickly during a navigation.
fixes #926
Explicitly delete test cookie after the test
manual
---

🐛 ensure that test cookie is correctly deleted after the test

---

packages/core/src/index.ts
packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/internalContext.spec.ts
packages/rum-core/src/domain/parentContexts.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum-core/src/domain/rumSession.spec.ts
packages/rum-core/src/domain/rumSession.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/specHelper.ts
packages/rum-recorder/src/boot/startRecording.spec.ts
packages/rum-recorder/src/domain/segmentCollection/segmentCollection.spec.ts

Send the session plan to the intake for each RUM events so they can apply specific rules to them.
This commit introduces a new method to get the plan from a `RumSession`. For now, it is hardcoded to `REPLAY`, but in the future (RUMF-940) it will be defined by an `Configuration` option.
Unit
---

✨ [RUMF-938] add the session plan to RUM events

---

packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/index.ts
packages/rum-recorder/src/index.ts
packages/rum/src/index.ts

In order to avoid any confusion on how to enrich RUM data, we advice user to use addError `context` attribut.
In that regard, all errors captured with addError are now classified as custom. 
Remove addError 'source' argument
Unit, Locally
---

💥 remove addError 'source' argument

---

packages/core/src/index.ts
packages/logs/src/boot/startLogs.ts
packages/logs/src/domain/trackNetworkError.spec.ts
packages/logs/src/domain/trackNetworkError.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
test/e2e/scenario/logs.scenario.ts
test/e2e/scenario/rum/errors.scenario.ts
test/e2e/scenario/rum/resources.scenario.ts

RUM errors are not the best way to trigger attention for network requests with a bad status code. We already collect that information within RUM resources. By stopping the generation of RUM errors for these resources, we simplify the value proposition of RUM errors.
- Remove the feature flag
- Move network error code in Logs
Unit, Locally
---

💥 enable network errors removal

---

packages/rum/webpack.config.js
scripts/deploy.sh

Don't build and upload unnecessary bundles anymore
* remove unprefixed bundle upload
* remove -eu and -us bundles generation and upload
---

👷 [RUMF-954] remove deprecated bundles upload

---

CHANGELOG.md

To avoid any confusion for NPM users on the version 3 release, all the breaking changes need to be available to them.
Update the changelog
Locally
---

📝  changelog v3

---

packages/rum/src/boot/recorderApi.spec.ts
packages/rum/src/boot/recorderApi.ts

Some LITE sessions have the replay enabled while they shouldn't. Using sample rates, it's possible to go from a REPLAY session to a LITE or an untracked session. In these cases, the recorder should stop recording.
Stop recording when a new session with a LITE plan or untracked is started
Unit
---

🐛 fix recording session renewal

---

packages/logs/package.json

In the context of RUM v3, we want to forbid Log from being updated in v3 before all changes are done.
Update Log package.json
None
---

👷 npm log private

---

README.md
packages/rum/README.md
performances/src/main.ts

The CDN URL changed for V3. This PR updates a few URLs in our codebase documentation.
Add `-v3` to CDN URLs
---

📝 update CDN URLs for V3

---

CHANGELOG.md
packages/rum-core/src/boot/rumPublicApi.ts

EU doesn't have the new intake domain available yet.
This reverts commit 6fd361cf06d86cc07ce67a5f1f8a1a7b6dfc32a6.
CI
---

[RUMF-972] Revert "💥 always use alternative domains for RUM (#944)"

---

package.json
packages/core/src/boot/init.ts
packages/core/src/domain/configuration.spec.ts
packages/core/src/domain/transportConfiguration.spec.ts
packages/core/src/domain/transportConfiguration.ts
packages/logs/src/boot/buildEnv.ts
packages/logs/webpack.config.js
packages/rum-core/src/boot/buildEnv.ts
packages/rum-slim/webpack.config.js
packages/rum/webpack.config.js
scripts/build-env.js
scripts/deploy.sh
scripts/replace-build-env.js
webpack.base.js

Prepare for the Logs V3 release
* Following the RUM pattern, suffix the Logs bundle with the major version
* Remove deprecated upload of eu and us bundles and do some related cleanup
CI
---

[RUMF-978][RUMF-980] adjust deploy for logs v3

---

packages/core/src/domain/configuration.ts
packages/core/src/domain/transportConfiguration.spec.ts
packages/core/src/domain/transportConfiguration.ts
packages/core/src/index.ts
packages/logs/src/boot/logs.entry.spec.ts
packages/logs/src/boot/logs.entry.ts
packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts

Prepare logs V3: remove deprecated options support
* Remove `publicApiKey` and `datacenter` options
* Remove RUM support for omited options
CI
---

💥 [RUMF-981] remove deprecated logs options

---

packages/logs/src/boot/startLogs.ts
packages/logs/src/index.ts
test/app/app.ts

Prepare Logs V3: remove deprecated type
* remove deprecated LogsUserConfiguration type
CI
---

💥 [RUMF-982] remove deprecated LogsUserConfiguration type

---

packages/core/test/specHelper.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts

Synthetics browser tests now add a specific value in the user agent to ease the identification, cf [doc](https://docs.datadoghq.com/synthetics/guide/identify_synthetics_bots/?tab=browsertests)
- Check user agent instead of global variable
- Check only once
unit test
Need to check on staging
---

✨ [RUMF-974] use user-agent to detect synthetics sessions

---

scripts/dev-server.js

allow to redirect canary or head files to files served by the dev server
add some redirections in the dev server
locally
---

👷 dev server: redirect suffixed files

---

CHANGELOG.md

Warn NPM users about breaking changes in Logs V3
Ajust the CHANGELOG message for V3
---

[RUMF-984] update CHANGELOG for logs breaking changes

---

packages/rum-core/src/browser/performanceCollection.ts

Try to retrieve `largest-contentful-paint`, `first-input` and `layout-shift` values that could have been emitted before SDK init.
behind `'buffered-perf'` flag, create one buffered observer for each experimental type.
locally
---

⚗ [RUMF-970] experiment with buffered PerformanceObserver

---

packages/core/src/browser/xhrProxy.ts

`xhr._datadog_xhr` is problematic because it is shared between SDKs
Deprecate `xhr._datadog_xhr`. No replacement for now, but we might want to remove it in a future major version.
---

📝🗑 deprecate the XHR context, to be removed in V4

---

packages/logs/package.json

Logs V3 is almost ready, let's make it public again so it will be published on NPM
This reverts commit 323db551d4a56c5cabcf2734cc87aa0ffe0ff0e3.
---

Revert "👷 npm log private (#959)"

---

packages/core/src/domain/internalMonitoring.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceUtils.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
packages/rum-core/src/domain/trackSleep.spec.ts
packages/rum-core/src/domain/trackSleep.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum/src/domain/segmentCollection/segment.spec.ts

This is part of an investigation where we observed abnormally high resource durations and web vital timings
Add an experimental way to detect when the computer goes to sleep. Use it on resources and internal monitoring logs to help investigation.
Unit, manual
---

⚗ [RUMF-971] experiment to detect when the computer goes to sleep 

---

packages/core/src/domain/configuration.ts
packages/core/src/domain/transportConfiguration.spec.ts
packages/core/src/domain/transportConfiguration.ts
packages/core/test/specHelper.ts

Trace intake requests are emitted by deprecated beta of dd-trace-js.
We no longer need to exclude trace intake requests from RUM resource events.
Remove trace endpoint
Unit
---

🗑️ Remove deprecated trace endpoint

---

packages/rum-core/src/domain/foregroundContexts.ts

Too much logging in the foregroundContext manager
- do not log error if two events are coming real close: https://bugs.chromium.org/p/chromium/issues/detail?id=1237904
- add now to extimate the user impact better

Limit log monitoring + add more details

---

yarn.lock

https://github.com/advisories/GHSA-r628-mhmh-qjhw
The [dependabot PR](https://github.com/DataDog/browser-sdk/pull/975 ) updated tar 4.x. This PR updates tar 6.x
CI
---

👷 update tar to fix vulnerability

---

packages/rum-core/src/browser/performanceCollection.ts

Retrieve `largest-contentful-paint`, `first-input` and `layout-shift` values that could have been emitted before SDK init.
Remove 'buffered-perf' flag
related PRs:
- #972  
- #978 
Manual + DD app
---

✨[RUMF-970] enable buffered PerformanceObserver

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts

User agent used by synthetics can be overwritten by the customer. So user agent check is not enough.
Restore check on global. 
Previous PR:
#969 
unit
---

🐛[RUMF-990] restore global check to detect synthetics sessions

---

README.md
packages/logs/README.md

- promote v3 files
- fix logs url
update name + logs link
manual
---

📝 Update Readme for v3 cdn links

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/src/rumEvent.types.ts

Allow linking RUM to Synthetics tests
Add Synthetics test id and result id to all RUM events based on global variables. In the future, it will also use cookies, but since we don't know yet how they will be defined, let's do only global variables first.
Manual, Unit
---

 ✨ [RUMF-996] set synthetics ids on RUM events 

---

.gitlab-ci.yml
Dockerfile
test/e2e/wdio.local.conf.js

Chrome was updated on our work laptop and the local e2e tests can't be run anymore.
Update the chrome version for local e2e tests
---

✅ update chrome version for e2e local tests

---

packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/domain/trackPageActivities.spec.ts
packages/rum-core/src/domain/trackPageActivities.ts
packages/rum-core/test/specHelper.ts

Page activities (used to compute views and actions loading_time) is bounded to 10 seconds. This is because we may recurrent activities (ex: periodic requests or DOM mutations) that may cause an infinite loading duration.
Because of this 10 second limit, the loading time distribution looks strange in the UI: an abnormal amount of views and actions end at 10 seconds.
This is an experiment (behind 'experimental feature flag') to evaluate the impact on removing this limit. We can expect:
* more views with an undefined loading_time 
* less automatic actions (since actions can't happened concurrently)
Add a feature flag to remove the page activities limit
Unit
---

[RUMF-989] experiment with removing page activities max duration

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts

Some customer proxy configurations rely on the intake v1 path to root the requests. For instance they may use a wildcard to identify RUM like so `/v1/input/`. By enabling the intake version 2, the path would become `/api/v2/...` and these customers would break their proxy configuration.
In order to guarantee backward compatibility for future intake versions, we need to change our approach. 
- Add a new **proxyUrl** option parameter
- Implement the new strategy
---

✨ [RUMF-993] New proxy strategy

---

packages/rum/src/domain/record/privacy.spec.ts
packages/rum/src/domain/record/privacy.ts

A customer is embedding a large "data:" URI resource. This impacts performance without sufficient corresponding benefit to this customer. As a general quick fix, we shall truncate this attribute value. We do not wish to generalise recorder limits at this time, so have specifically targeted only attributes starting with "data:" exceeding 100,000 length (somewhat arbitrarily chosen, but corresponds to 5*X < 1MB).
New tests added.
---

🐛[REPLAY-371] Truncate long "data:" URIs

---

.gitlab-ci.yml

The goal of this PR is to allow testing the `to-staging` command. This
variable is required to be present on the main branch so `to-staging`
can do its magic.
Add a dummy `CURRENT_STAGING` variable to `.gitlab-ci`.
---

👷⚗ [RUMF-991] add CURRENT_STAGING variable to .gitlab-ci

---

packages/logs/README.md

Clarify that:
- All properties are updatable 
- No context is available for logs
- Discard is possible
- Update scrubbing section to reflect that all properties are updatable 
- Replace link to RUM guide by discard example
- Replace `event` occurrences by `log`
N/A
---

📝[RUMF-1009] Rework logs beforeSend documentation

---

packages/core/src/domain/error/trackConsoleError.spec.ts
packages/core/src/domain/error/trackConsoleError.ts

On npm setup, with both logs and RUM enabled, `console.error` calls generate an unexpected number of logs.
Regression after error collection refactoring in https://github.com/DataDog/browser-sdk/pull/930.
fixes https://github.com/DataDog/browser-sdk/issues/1022
Ensure that `console.error` can only be overwrite once.
unit test
---

🐛 [RUMF-1012] fix console.error loop on npm setup

---

packages/rum-core/src/rawRumEvent.types.ts

InternalContext `view.name` property is missing from the types.
Add it
CI
---

🏷️ add InternalContext.view.name

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/internalMonitoring.spec.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/logs/src/boot/startLogs.spec.ts

Fix intake v2 `dd-request-id` to be unique per request
Add dd-request-id  to HttpRequest 
Locally, Unit
---

🐛 [RUMF-1005] Fix dd-request-id endpoint query param

---

packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts

The strategy to compute CLS [has changed](https://web.dev/evolving-cls/). 
**Old strategy:** CLS is the sum of all layout shifts
**New strategy:**
- Layout shifts are grouped into session windows.
- A session window is a period that starts when a layout shift happens, and ends when no layout shift happens during 1 second or more. If a layout shift happens after that, it creates a new session window.
- A session window cannot be longer than 5 seconds. So if adding a layout shift to a session window would make it longer than 5 seconds, then a new session window is created with that layout shift.
- The value of CLS is max value of session windows
- Implement the new CLS strategy
- Add new unit tests
unit, CI
--- …

✨ [RUMF-992] New CLS implementation

---

packages/rum-core/src/domain/foregroundContexts.spec.ts
packages/rum-core/src/domain/foregroundContexts.ts

[Only happened 32 times in two days](https://app.datadoghq.com/logs?query=source%3Abrowser-agent-internal-monitoring%20Event%20not%20trusted%20for%20foreground&agg_m=count&agg_q=&agg_t=count&cols=%40view.url_details.host%2Csdk_version%2C%40http.useragent_details.browser.family&index=browser-agent-internal-monitoring&integration_id=&integration_short_name=&messageDisplay=inline&saved_view=64420&sort_m=&sort_t=&stream_sort=desc&top_n=&top_o=&viz=stream&from_ts=1627738775248&to_ts=1627911575248&live=true)
- Clean monitoring
- Ignore not trusted event

Remove monitoring & ignore untrusted events

---

packages/rum/src/domain/record/mutationObserver.ts
packages/rum/src/domain/record/privacy.spec.ts
packages/rum/src/domain/record/privacy.ts
packages/rum/src/domain/record/serialize.spec.ts
packages/rum/src/domain/record/serialize.ts

Migrates `serializeAttribute()` from privacy.ts to serialize.ts as more appropriate position.
---

👷Minor reorg/cleanup

---

packages/rum/src/domain/record/mutationObserver.spec.ts
packages/rum/src/domain/record/privacy.spec.ts
packages/rum/src/domain/record/privacy.ts
packages/rum/test/htmlAst.ts

Currently the privacy-by-default implementation replaces sensitive content with `᙮᙮᙮᙮᙮ ᙮᙮᙮ ᙮᙮᙮᙮᙮` like strings. These '᙮' characters are not your standard ASCII 'x' characters. In balancing the tradeoff between empirical pixel perfect sizing vs simple ASCII (font support etc), we decided to lean towards simple ASCII. Therefore we are replacing codePoint=5742 ('\u{166e}') with to codePoint=120.
---

[RUM] Switch Unicode `᙮` to Ascii `x`

---

packages/core/src/transport/batch.spec.ts
packages/core/src/transport/batch.ts
packages/core/src/transport/httpRequest.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/segmentCollection/segment.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts
packages/rum/src/transport/send.ts

The browser SDK uses sendBeacon() when available and the size < (16KB for rum, 60ko for replay). If not, it falls back to XMLHttpRequest. In some cases the XHR requests fail. This PR adds some information in the internal monitoring to better understand the reasons of this issue.
- Add flush reason
- Increase response text length
Unit, Locally
---

[RUMF-976] add info to monitor failing xhr fallback

---

packages/rum-core/src/domain/foregroundContexts.spec.ts
packages/rum-core/src/domain/foregroundContexts.ts
packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/test/specHelper.ts

We have quite a log of `Reached maximum of foreground time` errors but the views do not have 500 items.
Let's split the max in two: 
- a max of periods stored to limit memory used
- a max of periods by view to limit bandwidth
It's unit tested

Introducing new max for foreground periods

---

packages/logs/README.md
packages/rum/README.md

Add proxy URL README documentation
Update docs
Locally
---

📝 Add proxyUrl option documentation

---

.github/CODEOWNERS

Give more visibility to replay members on recorder code changes
add @DataDog/rum-session-replay on `packages/rum` containing specific code for the recorder
N/A
---

👷 [ownership] add replay team on recorder code

---

packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts

LCP and FCP reported after 10 minutes are meaningless therefore we discard them
Discard LCP and FCP reported after 10 min
Unit, Locally
---

✨ Discard long FCP and LCP

---

packages/rum-core/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/domain/trackPageActivities.spec.ts
packages/rum-core/src/domain/trackPageActivities.ts
packages/rum-core/test/specHelper.ts

Remove limit on view.loading_time to avoid having a weird distribution chart in the UI
* Revert the flag introduced by #1019 
* Remove the constant maximum duration for track page activities
* Pass the 10 seconds maximum duration for actions only
CI, manual
---

✨ [RUMF-1029] remove the limit on view.loading_time 

---

packages/core/src/tools/observable.spec.ts
packages/core/src/tools/observable.ts
packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/browser/domMutationObservable.ts
packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/domain/trackPageActivities.ts

preliminary refactoring
- add `Observable` callback as constructor param:
```ts
const observable = new Observable(() => {
// on first subscribe logic
...
return () => {
// on last unsubscribe logic
...  
}
})
```
- use it to not duplicate `Observable` logic in  `domMutationObservable`
Unit
---

♻️ [RUMF-1015] add callback capabilities to observable

---

packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/foregroundContexts.spec.ts
packages/rum-core/src/domain/foregroundContexts.ts

Activate foreground periods issue for all our user.
Analysis: https://docs.google.com/document/d/17FsROHTNE8hh_Ra6blCgNwyZn8m2PqRefS_WIWjfBSk/edit#
- remove FF
- remove monitoring

Remove focus feature flag

---

packages/rum-core/src/domain/assembly.ts

Try to understand how this edge cas can happen
add monitoring log in assembly
Locally
---

🔊 [RUMF-1021] add monitoring on lite plan with replay

---

packages/core/src/tools/utils.ts
packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/contextHistory.spec.ts
packages/rum-core/src/domain/contextHistory.ts
packages/rum-core/src/domain/internalContext.spec.ts
packages/rum-core/src/domain/internalContext.ts
packages/rum-core/src/domain/parentContexts.spec.ts
packages/rum-core/src/domain/parentContexts.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/urlContexts.spec.ts
packages/rum-core/src/domain/urlContexts.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts

With the introduction of manual view tracking (#924), the creation of a view can be decoupled from URL changes.
In the case of a URL change occurring just before the end of a view, the view URL could wrongly be updated with the new location. 
**Previous behavior:**
- view events: URL updated during the lifecycle of the view
- other events: URL corresponding to the end of the event
**New behavior:**
- use the URL corresponding to the start of the event
- Introduce `UrlContexts` to store URL states history
- Use `UrlContexts` from `assembly` to retrieve URL and referrer
- Simplify `ContextHistory` since we no more need to dynamically generate the current context
Unit, manually
---
I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) …

♻️ [RUMF-1015] use the url corresponding to the start of the event

---

developer-extension/README.md
developer-extension/src/background/constants.ts
developer-extension/src/background/domain/replaceBundles.ts
developer-extension/src/background/store.ts
developer-extension/src/common/types.ts
developer-extension/src/popup/panel.tsx

The developer extension still has a 'rum-recorder' notion and doesn't intercept -v3 bundles.
* Replace "Use RUM Recorder" with "Use RUM Slim" to force using the slim bundle
* Intercept v3 bundles
Manual
---

🧑‍🏭 Update developer extension to support new V3 bundles

---

packages/rum-core/src/domain/assembly.ts

cf #1066 
add full event + cookie value
locally
---

🔊 Add extra monitoring info on lite session with replay

---

.eslintrc.js
.gitlab-ci.yml
scripts/staging-ci/merge-into-staging.js
scripts/staging-ci/staging-reset.js
scripts/utils.js

We want to setup a staging workflow similar to web-ui: instead of deploying main on staging, a new staging-xx branch is created every week. This branch is updated on every main commits and will be deployed on staging. PRs can be merged to this branch to allow testing them early.
This PR implement the merge into staging job, which merge main into staging on each main commit.
- Create merge into staging script
- Update gitlab-ci
Locally, Gitlab
---

👷 implement merge into staging job

---

.gitlab-ci.yml
scripts/staging-ci/check-staging-merge.js
scripts/utils.js

We want to setup a staging workflow similar to web-ui: instead of deploying main on staging, a new staging-xx branch is created every week. This branch is updated on every main commits and will be deployed on staging. PRs can be merged to this branch to allow testing them early.
This PR implement the check staging merge job to check if the current branch is mergeable with the staging
- Add check-staging-merge script
- Update gitlab-ci
Gilab
---

👷 [RUMF-1026] Add check-staging-merge

---

packages/core/src/domain/sessionManagement.ts

cf #1066, #1072
Add log on unexpected session type change
locally
---

🔊 Add monitoring on session type change

---

packages/core/src/tools/timeUtils.ts
packages/core/src/tools/utils.ts
packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts

Allow users to pass a custom time parameter to `addTiming`. Particularly useful in async setups, see https://github.com/DataDog/browser-sdk/issues/1005
* support relative and absolute times in view.addTiming
* add custom timing parameter support
CI
---

✨ [RUMF-1000] add a custom time parameter to `addTiming`

---

packages/core/src/domain/configuration/configuration.ts
packages/logs/src/boot/startLogs.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/rawRumEvent.types.ts
scripts/cli
test/app/app.ts

TS 4.4 introduced a new option called `exactOptionalPropertyTypes`, that disallows passing `undefined` to optional properties. Example:
```ts
interface Options {
foo?: number
}
let options: Options = {
foo: undefined // this will raise an error with `exactOptionalPropertyTypes: true`
}
```
To ease SDK integration in projects that are using this TS option, we want to explicitly allow passing `undefined` as a value for optional properties. 
* add a small compatibility test to check for this configuration
* explicitly allow `undefined` for all `init` configuration optional properties
CI
---

[RUMF-1034] allow passing `undefined` options to RUM and Logs init

---

packages/core/src/domain/sessionManagement.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/rumSession.ts
packages/rum-core/test/mockRumSession.ts

cf #1066, #1072, #1075, #1080
- detect session type change on expand session
- detect session type change regularly
- add inMemory session type in lite session with replay message
manual, staging
---

🔊[RUMF-1021] add extra monitoring on session type change

---

packages/core/src/domain/sessionManagement.ts

monitoring code introduced by #1091 can prevent session to be renewed by overwriting the in memory session id.
Overwrite in memory session id only in `expandOrRenewSession`
local, staging
---

🐛 [RUMF-1021] fix regression on renew session

---

packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/trackPageActivities.spec.ts
packages/rum-core/src/domain/trackPageActivities.ts

Some views and actions have a negative loading time.
Because it happens more often on actions, this PR only adds internal monitoring to them.
The first step is to identify if this behaviour comes from `waitIdlePageActivity`.
Add internal monitoring on actions with negative loading time
---

🔊 [RUMF-1036] Add negative loading time internal monitoring

---

.gitlab-ci.yml
scripts/staging-ci/check-staging-merge.js
scripts/staging-ci/merge-into-staging.js

Lots of notifications are now triggered during the staging process, making noise. Our goal is to rationalize notifications to avoid spamming.
- Remove staging deploy notification
- Rename channel #rum-deploy to #browser-sdk-deploy
Gitlab
---

👷  Remove staging deploy notification

---

eslint-local-rules/disallowSideEffects.js
packages/core/src/boot/init.ts
packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/experimentalFeatures.spec.ts
packages/core/src/domain/configuration/experimentalFeatures.ts
packages/core/src/index.ts
packages/logs/src/domain/loggerSession.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumSession.spec.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/recorderApi.spec.ts

Related to (internal) [RUMF-1004](https://datadoghq.atlassian.net/browse/RUMF-1004).
Currently prop drill-down is required to pass the configuration object around to access `configuration.isEnabled()`. This is a lot of work, and requires care to not introduce further bugs. Instead we can leverage a singleton to import `isEnabledExperimentalFeatures`.
Moving from `configuration.isEnabled` prop drill-down  to instead `import {isEnabledExperimentalFeatures} from '@datadog/browser-core'`;
---

♻️ Feature flag refactor: no more "prop drilldown", now just import

---

.gitlab-ci.yml

During our release process, the release branch and the tag run nearly the same ci jobs, making the checks twice. 
This PR removes the release branch jobs to save resources and time.
Update gitlab-ci.yml
Gitlab
---

👷 Remove gitlab jobs on release branches

---

packages/core/src/domain/sessionManagement.ts

Some cookies does not seem to be set or still have a previous value on a single tab session.
Add extra data to ease check and add real cookie value to double check the state.
Add extra monitoring info during cookie check
staging
---

🔊[RUMF-1021] cookie check: add extra monitoring infos

---

packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/domain/configuration/transportConfiguration.ts

Currently, monitoring requests use the `clientToken` instead of the `internalMonitoringApiKey` when sending monitoring requests.
Use the right token.
unit
---

🐛 [Internal monitoring] use monitoring api key for monitoring requests

---

packages/core/src/domain/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring.ts
packages/logs/src/boot/logs.entry.spec.ts
packages/logs/src/boot/logs.entry.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/boot/startLogs.ts
packages/rum-core/src/boot/startRum.ts

Avoid collecting potential sensitive data in monitoring logs
Remove following data from monitoring logs:
- global context
- view name
- view referrer
- view url
local
---

🔇 [RUMF-1076] remove unneeded monitoring fields

---

packages/rum/README.md

Exhaustive documentation.
Introduce:
- `replaySampleRate`
- `defaultPrivacyLevel`
Add a link from `allowedTracingOrigins` to dedicated guide.
NA
---

 📄 [RUMF-1075] add missing initialization parameters

---

packages/core/src/domain/error/trackRuntimeError.spec.ts
packages/core/src/domain/error/trackRuntimeError.ts
packages/core/src/domain/tracekit/index.ts
packages/core/src/domain/tracekit/tracekit.spec.ts
packages/core/src/domain/tracekit/tracekit.ts
packages/core/src/domain/tracekit/types.ts

In the same spirit as #1133 and #1124 , this PR allows to stop/unpatch the tracekit instrumentation.
By using the `instrumentMethod` helper, it also fixes #541 (superseds #542)
* Simplify tracekit tests a bit to make them synchronous and factorize the subscribe/unsubscribe in before/afterEach hooks
* Make Tracekit stoppable by using `instrumentMethod`
* Add a non-regression test for #541 collocated to the similar test for `onerror`
Unit, manual, staging
---

[RUMF-1046] make Tracekit stoppable

---

packages/rum/src/transport/send.ts

Fix Replay recorder support for Safari 11.0.
Replace `FormData.set` (see [caniuse support](https://caniuse.com/?search=formdata.set)) usages by `FormData.append`
Manual, staging.
---

🐛 [RUMF-1062] fix support for Safari 11.0

---

packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts

This will help confirming the assumption that LCP value is not sent by the browser when the tab is not visible. The 'discard_reason' is not enough, because it is filled only when a LCP value is emitted (and discarded), but in most cases it seems that the LCP value is not emitted at all.
Add `document.visibilityState` in `@context.lcp.initial_visibility_state`
---

🔊 [RUMF-1041] add initial visibilityState to lcp infos

---

packages/rum/src/transport/send.ts
packages/rum/src/types.ts

Start field missing during the parsing of some segments
Add a monitoring log when segment meta start is not a number
---

🔊 [RUMF-1080] try to detect segment sent without start

---

packages/core/src/index.ts
packages/core/src/transport/eventBridge.spec.ts
packages/core/src/transport/eventBridge.ts
packages/core/src/transport/index.ts
packages/core/test/specHelper.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/transport/startRumEventBridge.ts
packages/rum/src/boot/recorderApi.ts
test/e2e/lib/framework/createTest.ts
test/e2e/lib/framework/pageSetups.ts

The mobile SDKs (Android and iOS) want to track events that happen inside a webview using the browser SDK. To do so the browser SDK will send events to a bridge injected by the mobile SDK. 
Because WebView can be used to display websites not owned by the customer, we need to guarantee that if these websites also have the browser SDK, they won’t send their events to the mobile SDK. 
Add webView host checking
---

✨ [RUMF-1074] bridge host checking

---

packages/core/src/domain/session/oldCookiesMigration.spec.ts
packages/core/src/domain/session/oldCookiesMigration.ts
packages/core/src/domain/session/sessionManagement.spec.ts
packages/core/src/domain/session/sessionManagement.ts
packages/core/src/domain/session/sessionStore.ts
packages/core/src/domain/sessionManagement.ts
packages/core/src/index.ts

First part of session management rework
Next:
- Replace session cookie cache
- Introduce session context history
Extract session store from session management
---

♻️ [RUMF-1083] extract session store from session management

---

.gitlab-ci.yml
developer-extension/src/background/domain/replaceBundles.ts
scripts/deploy.sh
scripts/dev-server.js

Inititally, the `-head` bundle reflected the top of the `main` branch, thus the name. Since the new release workflow, this is no longer the case at is now reflects the top of the current `staging-xx` branch. 
To remove confusion, this PR changes the `-head` suffix to `-staging`.
---

👷 rename -head suffix to -staging suffix

---

packages/core/src/domain/session/sessionStore.spec.ts
packages/core/src/domain/session/sessionStore.ts

Allow to monitor session inconsistencies improvements
- consider session outdated if type change
- add monitoring message fo session inconsistencies
---

🔊 [RUMF-1083] add monitoring message for session inconsistencies

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/domain/configuration/transportConfiguration.ts
packages/core/src/transport/httpRequest.spec.ts

To promote usages of intakes v2, we want to remove support for “classic domains” and intakes v1, to keep only “alternate domains” and intakes v2. This will greatly reduce the complexity of computing the transport configuration
- Remove classic domain code
- Remove intake v1 code
---

🔥 [RUMF-1089] Cleanup legacy intake URLs

---

packages/core/src/domain/internalMonitoring/internalMonitoring.ts
packages/core/src/tools/utils.ts
packages/logs/README.md
packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domainContext.types.ts
packages/rum/README.md
scripts/cli
test/app/package.json
test/app/yarn.lock

Allows to use newer TS features in consumed typings (ex: `import type`)
Update minimal TS version to 3.8.2 (the first stable release of TS 3.8)
---

✅ [RUMF-1090] update minimal version to 3.8.2

---

packages/core/src/domain/configuration/configuration.spec.ts
packages/logs/src/boot/logsPublicApi.spec.ts
packages/logs/src/boot/logsPublicApi.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/boot/startLogs.ts
packages/logs/src/domain/configuration.spec.ts
packages/logs/src/domain/configuration.ts
packages/logs/src/domain/logsSessionManager.spec.ts
packages/logs/src/domain/logsSessionManager.ts
packages/logs/src/domain/trackNetworkError.spec.ts
packages/logs/src/domain/trackNetworkError.ts
packages/logs/src/entries/main.ts
packages/logs/src/transport/startLoggerBatch.ts

Followup of #1216 . This PR focuses on the logs part.
* Move init configuration typings into a new `logs/src/domain/configuration` module
* Introduce a new `LogsConfiguration` to be used internally in the Logs SDK 
* Validate and build the configuration in `init()`, by using the previously introduced `validateAndBuildConfiguration` function from `core`
* Add `forwardErrorToLogs` to `LogsConfiguration`, to avoid using `InitConfiguration` outside of `init()`
---

♻️ [RUMF-1097] revamp configuration - logs

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts

With the current proxyUrl implementation, if a user set the same url for his proxy and his backend, we con't collect backend requests as resources. 
Example:
```js
init({proxyUrl: 'https://www.proxy.com'...})
fetch('https://www.proxy.com/foo') // no resource collected
```
Update buildIntakeUrl logic 
---

🐛 Fix proxy url intake detection

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts

Bump in session time spent matching the deployment of #1187. 
Suspected root cause: regression allowing views to send updates while the session is expired
For view updates, check if the session is currently tracked instead of if the session was tracked at the beginning of the view.
---

🐛 [RUMF-1122] fix view updates while session is expired

---

.eslintrc.js
packages/core/src/browser/xhrObservable.ts

Don't expose internal XHR context to users. Also, it will avoid any conflict between double instrumentation when two SDKs are present.
Use a WeakMap instead of a property to store the XHR context
---

♻️ [RUMF-1092] use a WeakMap to store XHR context

---

packages/rum/src/constants.ts
packages/rum/src/domain/record/mutationObserver.spec.ts
packages/rum/src/domain/record/observer.spec.ts
packages/rum/src/domain/record/privacy.spec.ts
packages/rum/src/domain/record/privacy.ts
packages/rum/src/domain/record/serialize.spec.ts
packages/rum/src/entries/internal.ts

Some cleanup in preparation for the next major release
Removed deprecated privacy attributes, and took the opportunity to revamp privacy tests a bit.
---

 🔥 [RUMF-1094] remove deprecated privacy attributes 

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/configuration/transportConfiguration.ts
packages/core/src/index.ts
packages/logs/src/domain/configuration.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/configuration.ts

Improve init configuration typings 
* 🚚 Move some `InitConfiguration` properties to their own package.
* 🎨 Group/reorder properties
---

🏷️ [RUMF-1098] move init options into their related interfaces

---

.eslintrc.js
LICENSE-3rdparty.csv
developer-extension/package.json
package.json
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/tools/catchUserErrors.spec.ts
packages/core/src/tools/observable.spec.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/test/forEach.spec.ts
packages/core/test/specHelper.ts
packages/rum-core/src/domain/internalContext.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum/src/domain/record/record.spec.ts
performances/src/profilers/startCpuProfiling.ts
performances/src/profilers/startMemoryProfiling.ts
performances/src/profilers/startNetworkProfiling.ts
performances/src/profilers/startProfiling.ts
yarn.lock

Enforce `import` path consistency
* Enable the `import/no-useless-path-segments` rule to make sure import paths are the simplest possible. 
* Enable the `import/no-unresolved` rule and  extend the `plugin:import/typescript` ESLint configuration to make sure ESLint is able to resolve all files (currently there is some imports that work with TS but not with ESLint)
* Enable the` import/no-extraneous-dependencies` rule to make sure we don’t import from the same package (ex: importing from @datadog/browser-core in the core package). 
---

👷 [RUMF-1106] enable some ESLint import rules

---

packages/rum/src/domain/record/privacy.spec.ts
packages/rum/src/domain/record/privacy.ts

When specifying multiple privacy mode on a single node, the result is not intuitive:
* First, if a privacy attribute is present, it will always take precedence over the class name.
* Then, if two privacy class names are specified, the precedence order is weird (ex: ALLOW takes precedence over MASK or HIDDEN).
This commit make sure class names and attributes are treated equally and that the most restrictive privacy level takes precedence over the other.
---

🐛 improve privacy computation on a single node

---

CHANGELOG.md

Guide users who want to update from v3 to v4. [Rendered](https://github.com/DataDog/browser-sdk/blob/benoit/prepare-update-guide/CHANGELOG.md#v400)
Add a migration guide in CHANGELOG
---

📝 [RUMF-1130] add migration guide to the CHANGELOG

---

packages/core/src/tools/boundedBuffer.spec.ts
packages/core/src/tools/boundedBuffer.ts

The BoundedBuffer is used to buffer api calls before the SDK initialisation. It stores views, actions, and errors and has a limit of 10000 api calls. In case of big user defined contexts or if the init() is never called, it can have a significant impact.
This PR decrease the limit from 10000 to 500 buffered api calls to lower our memory impact.
Decrease bounded buffer limitation to 500
---

⚡️ [RUMF-1030] Decrease BoundedBuffer limitation to 500

---

packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.ts

Using programmatic action names from children to format an element action name breaks some use cases where the user expects that the programmatic action only shows up when the action comes from the child element.
Instead of using the programmatic action names from children, remove those children inner text from the action name. This will bring the same guarantees on sensitive data mentioned by the [related PR](https://github.com/DataDog/browser-sdk/pull/1200).
---

🐛 remove child with action-names innerText instead of replacing them

---

packages/core/src/domain/configuration/tags.spec.ts
packages/core/src/domain/configuration/tags.ts

The backend has sanitization rule that may differ from the actual documentation.
Let's keep it simple and only print a warning if we detect that something look weird, and let the backend do the actual sanitization.
---

🐛 let the backend do most of the tags sanitization

---

packages/rum-core/src/domain/rumEventsCollection/view/trackFirstHidden.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackFirstHidden.ts

#1256 
Also listen for `VISIBILITY_CHANGE` when tracking the first time a page is hidden. `PAGE_HIDE` alone is not sufficient.
---

🐛 [RUMF-1143] make sure to drop LCP timings if the page was previously hidden

---

packages/rum/README.md

As mentioned below the example:
> In the example above, 50% of all sessions are collected. The Session Replay RUM option tracks half of these sessions while the Browser RUM option tracks the remaining half of these sessions.
meaning:
- 25% of sessions are collected using the Browser RUM option
- 25% of sessions are collected using the Session Replay RUM option
- 50% of sessions are not collected
Reverts DataDog/browser-sdk#1266

Revert "[Documentation] Fix typo"

---

CHANGELOG.md

- avoid to duplicate content with slight differences between [changelog](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v400) and [migration guide](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade)
- avoid double doc reviews for future major versions
Replace major changes description by links to the upgrade guide
N/A
---

📝 [RUMF-1137] replace major changes description by links to the upgrade guide

---

packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/domain/record/observer.ts
packages/rum/src/domain/record/record.spec.ts
packages/rum/src/domain/record/record.ts
packages/rum/src/domain/record/viewports.spec.ts
packages/rum/src/domain/record/viewports.ts
packages/rum/test/utils.ts
test/e2e/scenario/recorder/viewports.scenario.ts

It's been a while, time to enable visual viewport recording by default. The is a follow up from implementation https://github.com/DataDog/browser-sdk/pull/1089.
---

[REPLAY-564] ♻️ Remove FF - enable visual viewport recording

---

.gitlab-ci.yml

Move deployment notification to dedicated browser sdk channels
gitlab ci
---

👷 [RUMF-1148] Move deployment notification to dedicated channels

---

packages/core/src/domain/session/sessionCookieStore.ts
packages/core/src/domain/session/sessionStore.ts

Try to understand what leads to missing value in session cookie 
Will be reverted after investigation
- Audit read/write to session cookie
- Expose audit logs in a global variable to share the between logs/rum
- Add audit logs to session inconsistencies messages
---

🔊 [RUMF-1079] audit cookie operations at start of the session

---

packages/core/src/boot/init.ts
packages/logs/src/boot/logsPublicApi.spec.ts
packages/logs/src/boot/logsPublicApi.ts
packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts

- Allow to easily check the SDK version for test/debug purposes
- Could use future integration use cases
Expose SDK version through:
- `DD_RUM.version`
- `DD_LOGS.version`
---

✨[RUMF-1135] expose SDK version through global variable

---

packages/core/src/domain/session/sessionCookieStore.spec.ts
packages/core/src/domain/session/sessionCookieStore.ts
packages/core/src/tools/browserDetection.ts

On firefox, the cookie lock strategy seems to increase the lost of some cookie writes:
```
task 1
...
set cookie value1
task 2
get cookie value1
set cookie value1+lock
get cookie value1+lock
set cookie value2+lock
get cookie value2+lock
set cookie value2
task 3
get cookie value1 // expected value2
```
Enable cookie lock only on chromium browsers
---

⚗ [RUMF-1079] restrict cookie-lock to chromium browsers

---

.github/dependabot.yml

Still issue with some minor versions
Avoid notifications for `@types/connect-busboy` and `@types/node`
N/A
---

👷 tweak dependabot ignore list

---

packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
packages/core/test/specHelper.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/boot/startLogs.ts
packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/transport/startRumEventBridge.ts

The mobile SDKs tracks events that happen inside a webview using the browser SDK. Mobile SDK inject a JS bridge to receive event from the browser SDK.
Now, RUM event won't be deserialized on the Mobile side so we don't have to differentiate rum event types in the bridge. We can flag them as "rum".
- update rum event bridge
- improve bridge unit tests
---

✨ [RUMF-1174] forward event to bridge with rum type

---

packages/rum-core/src/domain/rumEventsCollection/action/trackActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/waitIdlePage.spec.ts
packages/rum-core/src/domain/waitIdlePage.ts
packages/rum-core/test/specHelper.ts

Loading time was computed from the start of the activity tracking. In the case of initial view, the loading time should be computed from the start of the view which can be quite different from the start of the tracking, especially for async setup.
Compute the activity loading time from the start of the associated parent
---

🐛 [RUMF-1153] fix initial view loading time computation

---

packages/core/src/domain/session/sessionCookieStore.spec.ts
packages/core/src/domain/session/sessionCookieStore.ts
packages/core/src/domain/session/sessionStore.spec.ts
packages/core/src/domain/session/sessionStore.ts

Investigations are done, avoid to collect unneeded logs
Remove:
- audit cookie operations
- reach max log retry
- session inconsistencies
---

🔇[RUMF-1079] remove session inconsistencies monitoring

---

packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/fixtures.ts

Add this field to ease the error tracking processing for hybrid app
cf https://github.com/DataDog/rum-events-format/pull/46
add `error.source_type` attribute
---

✨ [RUMF-1180] add `error.source_type` attribute

---

.gitlab-ci.yml
scripts/export-test-result.js

Hard to investigate test failure occurrences with current setup:
- can't filter on test type
- not all jobs are reported to datadog (retry and unit failure are missing)
- use standard `test.type` tags instead of `type`
- split `unit`, `e2e`, `unit-bs`, `e2e-bs`
- ensure to report to datadog after each execution
manual
---

👷 tweak dd ci configuration

---

packages/core/src/domain/session/sessionCookieStore.spec.ts
packages/core/src/domain/session/sessionCookieStore.ts
test/e2e/lib/helpers/session.ts

Mitigate session inconsistencies due to concurrent access to cookies by different tabs on chromium browsers.
Enable changes introduced by:
- #1230 
- #1283 
---

🐛 [RUMF-1079] limit session inconsistencies issue on chromium browsers

---

scripts/generate-changelog.js

Avoid some manual cleanup while releasing 😅
Remove version and maintenance entries while generating the changelog
---

👷 [RUMF-1185] remove some useless entries from changelog generation

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts

Simplify loading time tracking logic
- remove `trackActivityLoadingTime`
- call `waitIdlePage` directly into `trackLoadingTime`
---

♻️ Simplify trackLoadingTime

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts

Improve intensive `addTimings` usage performance
Throttling the resulting view update
---

[RUMF-1115] throttle view updates by addTiming

---

LICENSE-3rdparty.csv
package.json
packages/core/package.json
packages/core/src/boot/init.ts
packages/core/src/domain/configuration/configuration.spec.ts
packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/domain/configuration/transportConfiguration.ts
packages/core/src/index.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/test/forEach.spec.ts
packages/core/test/specHelper.ts
packages/logs/src/boot/buildEnv.ts
packages/logs/src/boot/logsPublicApi.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/domain/configuration.ts
packages/rum-core/src/boot/buildEnv.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/requestCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceUtils.spec.ts
packages/rum-core/src/domain/tracing/tracer.spec.ts
scripts/replace-build-env.js
test/unit/karma.base.conf.js
webpack.base.js
yarn.lock

Remove e2e test specific code from release bundles.
- Inject `BUILD_MODE` and `SDK_VERSION` through global variable replaced by their value at build time
- Do not replace the build env variable in unit tests in order to test behaviors related to those variables
---

👷[RUMF-1170] Tweak build env

---

packages/core/src/domain/internalMonitoring/telemetryEvent.types.ts
packages/rum-core/test/formatValidation.ts
packages/rum-core/test/specHelper.ts
scripts/generate-schema-types.js
test/e2e/lib/framework/createTest.ts
test/e2e/lib/helpers/validation.ts

Update types generated from rum-events-format with telemetry events
Generate types from telemetry event schema
---

✨[RUMF-1188] add telemetry event types

---

packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/rawRumEvent.types.ts

Since there is no more network error in RUM (cf [PR](https://github.com/DataDog/browser-sdk/pull/930)) we don't have to map the resource. 
Update errorCollection
---

🔥 Clear remaining code of network error removal

---

.eslintrc.js
eslint-local-rules/disallowEnumExports.js
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
packages/core/src/domain/session/sessionManager.spec.ts
packages/core/src/domain/session/sessionStore.spec.ts
packages/core/src/tools/error.ts
packages/core/src/tools/utils.ts
packages/logs/src/domain/logsSessionManager.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/lifeCycle.ts
packages/rum-core/src/domain/rumSessionManager.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum/src/domain/record/types.ts
test/e2e/lib/types/serverEvents.ts
test/e2e/scenario/recorder/recorder.scenario.ts

Minified size in bytes:
| Package  | Before  | After | Delta |
|---- |--- | -- | -- |
| datadog-logs.js  | 33188 | 32690  | -1.5%
| datadog-rum-slim.js | 63867 | 60910  | -4.6% |
| datadog-rum.js  | 113044 | 109360 | -3.3% |
* Enforce and change enum to const enums
* Fix the `disallowEnumExports` rule because I noticed that some enums were still exported, and convert the `IncrementalSource` enum to a plain object
---

⚡️ [RUMF-1171] prefer const enums 

---

packages/core/src/domain/internalMonitoring/index.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
packages/core/src/index.ts
packages/logs/src/boot/startLogs.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/transport/startRumBatch.ts
test/e2e/lib/framework/eventsRegistry.ts
test/e2e/lib/framework/serverApps/intake.ts
test/e2e/scenario/internalMonitoring.scenario.ts

Experiment with dual shipping telemetry events in existing and new system
Superseed https://github.com/DataDog/browser-sdk/pull/1351
Behind telemetry feature flag:
- core: update internalMonitoring to handle new telemetry events
- RUM: send them in the batch of RUM events
- logs: send them in a new "RUM" batch
---

⚗️ [RUMF-1181] collect telemetry events

---

packages/rum/src/domain/segmentCollection/deflateWorker.js

In some cases, where a Browser SDK user is using babel on their dependencies, it can lead to a broken Session Replay recorder because some helpers inserted by Babel are not accessible in the worker.
* enable ESLint in the DeflateWorker, to spot unused code paths
* Remove problematic and useless code from the DeflateWorker
---

🔥 [RUMF-1198]  remove problematic and useless code from the DeflateWorker

---

.github/dependabot.yml
LICENSE-3rdparty.csv
developer-extension/package.json
developer-extension/src/background/domain/flushEvents.ts
developer-extension/src/background/domain/getConfig.ts
developer-extension/src/background/domain/logEventsFromRequests.ts
developer-extension/src/common/actions.ts
developer-extension/src/panel/app.tsx
developer-extension/src/panel/panel.tsx
developer-extension/src/panel/tabs/actionsTab.tsx
developer-extension/src/panel/tabs/configTab.tsx
developer-extension/src/panel/useStore.ts
developer-extension/tsconfig.json
package.json
yarn.lock

Keep dependencies up to date and maintanable
* Replace [bumbag](https://bumbag.style/) with [mantine](https://mantine.dev/).
*  Reasons:
* Bumbag still ships with a [fixed and outdated version of lodash](https://github.com/jxom/bumbag-ui/blob/44ffaa1c90b799edaa7c152c3d144833dcebb3bf/packages/bumbag/package.json#L34). This version is known to have [a vulnerability](https://github.com/advisories/GHSA-35jh-r3h4-6jhm), but the bumbag team doesn't [seem to be motivated to change that](https://github.com/jxom/bumbag-ui/issues/105#issue-823987605). Overriding the dependency version with yarn works, but is combursome.
* Bumbag typings [are incompatible with `strictNullChecks`](https://github.com/jxom/bumbag-ui/issues/97), so the whole extension codebase lacks stricter types.
* Bumbag did release …

📦 [RUMF-1162] update developer-extension

---

scripts/replace-build-env.js

NPM packages of v4.6.0 are broken because `__BUILD_ENV__SDK_VERSION__` is not always replaced in `esm` and `cjs` files.
The `replace-in-file` package works just like JS `string.replace`: if a string is provided, a single occurrence is replaced. Sadly, we are using __BUILD_ENV__SDK_VERSION__ [two times in `endpointBuilder`](https://github.com/DataDog/browser-sdk/blob/c1eb0487c676dcf43408f4cf34804f0bbaecad45/packages/core/src/domain/configuration/endpointBuilder.ts#L45-L48,) so the second occurrence is not replaced.
This has not been found during E2E tests because the endpoint builder is overriden in this case. We'll work on improving the situation in a future PR.
To work around this, we have to use a regex with the "global" flag.
--- …

🐛 fix build-env replacement in npm packages

---

performances/package.json
yarn.lock

The dependabot PR has unecessary changes in the yarn.lock, and breaks type checking.
---

👷 Bump @types/node-forge

---

.github/dependabot.yml

The number of updates to do daily is a bit overwhelming. Let's run dependabot once a week, at the beginning of each IH shift

👷 run dependabot weekly

---

packages/rum/README.md

For people on older SDKs we need to call out to update to a newer SDK version
"hi team, my customer XXXXX has let me know they were [configuring their SDK](https://docs.datadoghq.com/real_user_monitoring/browser/#browser-and-session-replay-sampling-configuration) to remove long tasks and resources but i still see in the plan and usage page that they are technically on the session replay SKU-can someone help me confirm if they have turned off these features? thanks!" 
"- did they check their SDK version? from what I can see they are still on 2.18.0"

Update browser config to include SDK version

---

.github/dependabot.yml

In #1368 , I forgot to remove some dependabot ignored packages
Remove forgotten dependabot ignores
---

👷 [RUMF-1168] remove forgotten dependabot ignores

---

packages/core/src/index.ts
packages/core/src/tools/instrumentMethod.spec.ts
packages/core/src/tools/instrumentMethod.ts
packages/rum/src/domain/record/observer.ts
packages/rum/src/domain/record/types.ts
packages/rum/src/domain/record/utils.ts

As observed in #1397  , we badly instrument a few native methods in the recorder:
* `cssStyleSheet.insertRule()` and `cssStyleSheet.deleteRule()`
* some form input `.value` property setters
This causes unexpected behavior when calling `stopSessionReplayRecording()` after another library instrumented those.
* Use `instrumentMethod` on `CssStyleSheet` methods
* Implement and use `instrumentSetter` on input property setters
---

 🐛 [RUMF-1203] fix `stopSessionReplayRecording` instrumentation cleanup

---

packages/rum-core/src/index.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/record/record.spec.ts
packages/rum/src/domain/record/record.ts
packages/rum/src/domain/record/types.ts
packages/rum/src/domain/segmentCollection/segment.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/types.ts

Currently, when a new view is generated we get the current timestamp to define the view date.
Then we take a full snapshot, which consists [in 3-4 records](https://github.com/DataDog/browser-sdk/blob/c050a2006a2b0f9ed1175478abb90bc0cec7f250/packages/rum/src/domain/record/record.ts#L36-L70) every time a record is emitted, we get the current timestamp to define its date
This causes an issue during replay, when seeking: when the user clicks on a View event, the player actually shows the previous view, because the records corresponding to the new view are a few milliseconds after the view start.
This PR set the view date to the fullsnapshot emitted records when a view change
Set the view date to the fullsnapshot emitted records when a view change
--- …

🐛   Adjust records generated during view change so their date matches the view date

---

packages/core/src/transport/eventBridge.spec.ts
packages/core/src/transport/eventBridge.ts

When  a bridge is injected by mobile with `AllowedWebViewHosts`
The browser SDK should send data to the bridge if on domains and subdomains that match AllowedWebViewHosts
Update canUseEventBridge
---

✨ [RUMF-1237] The event bridge allowed hosts should also match subdomains

---

packages/logs/README.md
packages/logs/src/boot/logsPublicApi.spec.ts
packages/logs/src/domain/assemble.spec.ts
packages/logs/src/domain/configuration.ts
packages/logs/src/domain/logger.spec.ts
packages/logs/src/domain/logger.ts
packages/logs/src/domain/logsCollection/console/consoleCollection.spec.ts
packages/logs/src/domain/logsCollection/console/consoleCollection.ts
packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.spec.ts
packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.ts
packages/logs/src/domain/logsCollection/runtimeError/runtimeErrorCollection.spec.ts
packages/logs/src/domain/reportRawError.ts

This PR enables the `forward-logs` feature implemented in #1316 
* Remove "forward-logs" flag usage
* Add README doc
---

✨ [RUMF-1192] forward `console.*` logs to Datadog

---

packages/logs/README.md
packages/rum/README.md

When looking for links on tokens I noticed the links on `npmjs.com` and `github.com` are broken.
Update the links to the `docs.datadoghq.com` pages.
---

Update links to api key docs

---

packages/core/src/domain/configuration/configuration.spec.ts
packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
test/e2e/lib/framework/createTest.ts

Add a sample rate to control which percentage of pages can send telemetry events.
- New init option `telemetrySampleRate?: number`
- default value `20`, like in the volume projection, could be tweaked when starting to enable customers
---

⚗️ [RUMF-1182] add telemetry sample rate

---

packages/rum/src/domain/record/mutationObserver.spec.ts
packages/rum/src/domain/record/mutationObserver.ts

Fix HTML elements incorrect visual state when replay.
The SDK incorrectly sent empty attribute mutations as `null`. But `null` is also used for removed attributes, so instead setting the attribute to an empty string, the player removes the attribute, which may have an impact on the visual state of some elements.
To fix the issue, this PR sends empty attribute mutations as an empty string instead.
---

🐛 [RUMF-1240] fix attribute mutating to an empty value

---

packages/core/src/transport/batch.spec.ts
packages/core/src/transport/batch.ts
packages/core/src/transport/httpRequest.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/segmentCollection/segment.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts
packages/rum/src/transport/send.ts

Remove XHR fallback failed logs since it is the main source of telemetry logs and we don't use them.
We could reintroduce them when needed.
Remove code introduced by #902 and #1035
---

🔇 Remove useless debug logs

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/domain/trackEventCounts.spec.ts
packages/rum-core/src/domain/trackEventCounts.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/fixtures.ts
test/e2e/lib/framework/eventsRegistry.ts
test/e2e/lib/types/serverEvents.ts
test/e2e/scenario/rum/actions.scenario.ts

Count the number of frustration occuring during a view
* Do a bit of renaming, `userAction` are now `action`
* Implement the counter
---

✨ [RUMF-1214] implement frustration signals counters

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/domain/configuration/transportConfiguration.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts

Prepare telemetry rollout
- Add logic to enable telemetry by site
- allow to override with feature flag to keep sending telemetry for internal orgs
Data centers will be enabled in following PRs
---

✨ [RUMF-1251] allow to enable telemetry by site

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/internalMonitoring/index.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
packages/core/src/index.ts
packages/core/src/transport/startBatchWithReplica.ts
packages/logs/src/boot/startLogs.ts
packages/rum-core/src/transport/startRumBatch.ts

Ensure that telemetry events of different datacenters are not mixed together.
Keep sending staging events to prod for reliability.
Add an extra flag on `batch.add` to control replication by message.
---

✨[RUMF-1257] prevent dual shipping of telemetry events

---

packages/rum-core/src/domain/configuration.spec.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
test/e2e/scenario/rum/actions.scenario.ts

Allow to opt-in to frustrations tracking. This change is still behind the `frustration-signals` experimental feature flag.
Introduce the `trackFrustrations` initialization parameter, and use it in `trackClickAction`.
---

⚗✨ [RUMF-1210] add a `trackFrustrations` initialization parameter

---

test/e2e/lib/framework/pageSetups.ts

Run E2E tests faster when running outside of the CI. This is something I always did manually when running E2E tests locally.
Use only the 'bundle' setup by default when running E2E tests outside of the CI
---

👷 use only the 'bundle' setup when running E2E tests locally

---

packages/rum-core/src/browser/domMutationObservable.spec.ts
packages/rum-core/src/browser/domMutationObservable.ts

The workaround we are using to support Zone.js is only possible since 0.8.6 (see in [commit](https://github.com/angular/zone.js/commit/0d0ee53974601738fb16235baa3e5cca8b95be4e)). 
This commit introduces another workaround for older Zone.js versions.
---

🐛 [RUMF-1259] support Zone.js < 0.8.6

---

packages/rum-core/src/domain/rumEventsCollection/action/rageClickChain.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/rageClickChain.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
test/e2e/scenario/rum/actions.scenario.ts

Having actions spaning on multiple views is a bit weird.
* Stop any ongoing action and rage click chain on view end 
* Adjust the VIEW_ENDED event so we have a chance to increase the counter when the view ends
* Add a E2E test to make sure this works
---

⚗️✨ [RUMF-1258] stop ongoing action on view end 

---

packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts

Tests were failing with seed 58106 because the internal monitoring was
not correctly reset after each case.
Make sure to reset internal monitoring tests after each test case.
---

✅ fix internal monitoring test flakiness

---

packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/configuration.spec.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum-core/src/domain/rumSessionManager.spec.ts
packages/rum-core/src/domain/rumSessionManager.ts
packages/rum-core/test/mockRumSessionManager.ts
packages/rum-core/test/specHelper.ts
packages/rum/README.md
packages/rum/src/boot/recorderApi.spec.ts
packages/rum/src/boot/recorderApi.ts
packages/rum/src/boot/startRecording.spec.ts

New premium plan name to reduce confusion between replay feature and replay plan.
- introduce `premiumSampleRate` option and deprecate `replaySampleRate`
- rename `replay` plan occurrences to `premium`

✨ Rename Replay plan to Premium plan

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/configuration/intakeSites.ts
packages/core/src/domain/configuration/transportConfiguration.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts

fixes https://github.com/DataDog/browser-sdk/issues/1547
Avoid circular dependency around `internalMonitoring` and `endpointBuilder`
---

🐛 Fix dependency issue

---

packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts

Avoid to collect customer URLs in telemetry errors
Filter out stack trace frames that are not from:
- empty / anonymous url
- localhost
- DD CDN
---

✨ [RUMF-1264] scrub customer frames from telemetry errors

---

packages/core/src/domain/internalMonitoring/internalMonitoring.spec.ts
packages/core/src/domain/internalMonitoring/internalMonitoring.ts
test/e2e/scenario/eventBridge.scenario.ts

Regional rollout of telemetry, step 4/4
Enable us1
---

✨ [RUMF-1191] enable telemetry on us1 site

---

packages/core/src/domain/configuration/configuration.spec.ts
packages/core/src/domain/configuration/configuration.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/segmentCollection/index.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts
packages/rum/src/transport/send.ts

Given  RUM / Logs / Replay
When  they send requests at the same time with sendBeacon
Then  collisions may happen
This PR experiment lower batch size limits to be under the sendBeacon limit when RUM / logs / replay are enabled and leave some space for third party apps.
- Batch limit from: `60KB (replay) + 16KB (RUM) + 16KB (Logs) ` to `22KB (replay) + 10KB (RUM) + 10KB (Logs)`
- Remove SEND_BEACON_BYTES_LIMIT and only use SEGMENT_BYTES_LIMIT
---

⚡️ [RUMF-1038] Lower batch size limit

---

packages/rum/src/domain/record/types.ts

This is in preparation to support nested CSS rules in Session Replay.
Adjust StyleSheetRule records `index` properties to allow an "index path" 
---

🏷️  [RUMF-1256] adjust StyleSheetRule records to support index paths

---

packages/core/src/transport/failedSendBeacon.spec.ts
packages/core/src/transport/failedSendBeacon.ts

Use a specific failed sendbeacon feature flag to monitor them even when lower-batch-size is disabled
User `failed-sendbeacon` FF in `failedSendBeacon.ts`
---

🔊 Update failSendBeacon FF

---

package.json

Datadog frontend teams are migrating from nodenv to volta. Let's follow the trend
* Add volta config to `package.json`
* Keep `.node-version` for now, to let the @DataDog/rum-browser team migrate when they have time
---

👷 add volta config

---

packages/rum-core/src/boot/rumPublicApi.ts
packages/rum/src/entries/internal.ts

* the Datadog app is using `startView(undefined)`, but the types don't allow that anymore
* the Datadog app is mocking Records, which now have `TimeStamp` values
* Adjust `startView` typing
* Export `TimeStamp` from `/internal`
*
---

🏷️ adjust types to allow updating the SDK in Datadog app

---

packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/internalContext.spec.ts
packages/rum-core/src/domain/internalContext.ts
packages/rum-core/src/domain/urlContexts.spec.ts
packages/rum-core/src/domain/urlContexts.ts
packages/rum-core/src/domain/viewContexts.spec.ts
packages/rum-core/src/domain/viewContexts.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts

RUM assembly has a quite convoluted logic to handle the various contexts. More precisely:
- All context extends `Context` making us beleave they can contain any attribute (`[x: string]: ContextValue`) which is false.
- It's hard to follow the overridden logic of context with the [combine](https://github.com/DataDog/browser-sdk/blob/336ebe7c6cd3dc9c87499cbf9cac6bb5e8fe6da8/packages/rum-core/src/domain/assembly.ts#L134-L138)
- It's hard to understand the [service and version logic](https://github.com/DataDog/browser-sdk/blob/336ebe7c6cd3dc9c87499cbf9cac6bb5e8fe6da8/packages/rum-core/src/domain/assembly.ts#L127-L132)
- Only RumContext now extends Context
- Remove urlContext, viewContext, { action: { id: actionId } } from the combine and use simple assignment
- Remove convoluted viewContext …

♻️ Simplify RUM assembly

---

.github/dependabot.yml
package.json
test/e2e/lib/framework/serverApps/intake.ts
yarn.lock

Update `busboy` which now rely on `streamsearch` instead of `dicer`. So this PR also fix the security issue on dicer.
- Upgrade busboy
- Update e2e intake implementation
---

👷 Update busboy

---

packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts

In the context of sub-apps, web and mobile developers want to only see RUM events happening in their area of ownership. 
For example, a developer working on the Log Management product at Datadog wants to see RUM events that happened in the Log Management only. To do so we make the service attribute first-class-citizen in RUM and allow customers to update the current `service` and `version` with the `startView` API.
Remove the `sub-app` feature flag
---

✨[RUMF-1225] Enable service and version update on startView

---

packages/core/src/tools/utils.ts
packages/rum-core/src/domain/rumEventsCollection/action/clickChain.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/clickChain.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenEvents.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenEvents.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
packages/rum-core/test/createFakeClick.ts

Do not consider clicks as dead or rage if the selection changed
* Bit of refactoring, to compute frustrations at a single place
* Track selectionchange events, store this information in `Click` objects, and use it when computing frustrations
---

[RUMF-1209] frustration signals: track selection change

---

packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
packages/rum-core/test/createFakeClick.ts
test/e2e/scenario/rum/actions.scenario.ts

Do not consider clicks that trigger an `input` event as dead.
* Do some light refactoring
* Track input events occurring during and after every click to adjust frustration signals assigned to them
---

[RUMF-1297] frustration signals: track input changes

---

packages/rum/README.md

Fixing intrapage broken links to configuration to match header
Fixes 2 links
---

Fixing intrapage broken links

---

packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getSelectorFromElement.spec.ts
packages/rum-core/test/createIsolatedDom.ts
test/e2e/scenario/rum/actions.scenario.ts

In some cases, we cannot track whether a click leads to a meaningful UI change. 
This PR implements a list of elements that should never be associated with a dead click.
---

🐛  [RUMF-1294] ignore dead clicks based on the click event target

---

.gitlab-ci.yml

Following #1614, mutualizing `BUILD_MODE` make it unavailable from scripts 🤦‍♂️ 
promote `BUILD_MODE` as an env variable
---

🐛 [RUMF-1273] fix BUILD_MODE scope

---

packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
packages/rum-core/src/domain/waitPageActivityEnd.ts
test/e2e/scenario/rum/actions.scenario.ts

When the user clicks and the application is using `window.open` to open an url in a new tab/window, a dead click is reported as we are not aware of it.
Track `window.open` calls and consider them as "page activity", in the same spirit as DOM mutations.
---

🐛 frustration signals: track window open

---

package.json
yarn.lock

Fix security alerts due to transitive dependency: `parse-url` and `parse-path`
---

👷 Bump lerna from 5.0.0 to 5.1.8

---

.github/dependabot.yml

Keep github actions up to date
Configure dependabot to watch github actions
None
---

👷 configure dependabot for github actions

---

packages/core/src/tools/limitModification.ts

To please the code scanner
In `limitModification`, ensure that modified field is owned by the object and not only exist on the object.
No risk on the current state since we are controlling which fields can be modified and that those fields are owned by the objects.
This change should not change current behavior.
---

👷 [RUMF-1336] guard against prototype pollution

---

packages/core/src/tools/utils.ts
packages/core/src/transport/eventBridge.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.ts

Fix hasarduous string escapes 
https://github.com/DataDog/browser-sdk/security/code-scanning/8
https://github.com/DataDog/browser-sdk/security/code-scanning/7
Remove the need to escape strings.
---

🔒 [RUMF-1335] fix incorrect string escape

---

packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts

The previous implementation only removed toJSON on the input value and its prototype. We usually pass an Object as input, so it was focused on Object.
But websites using outdated libraries that define toJSON to Array objects (ex: prototype.js before 1.7) are still an issue with this strategy.
This new implementation assumes that internally, the SDK won't use other objects than Array and Object (primitive types like string and number are unaffected), and those objects won't be defined with an own toJSON method. So, it focuses on removing toJSON to Array and Object prototypes, which completely solves the issue.
---

🐛 improve `jsonStringify` implementation

---

packages/core/src/browser/xhrObservable.spec.ts
packages/core/src/browser/xhrObservable.ts
packages/core/test/specHelper.ts

Avoid telemetry spam on this specific error
Handle correctly requests to `undefined` or `null`
---

🐛 [RUMF-1274] track request to undefined/null URL

---

.eslintrc.js

We have 2 ESLint rules that are fighting each other:
```
'prefer-object-spread': 'error',
```
and
``` 
'no-restricted-syntax': [
'error',
{
selector: 'ObjectExpression > SpreadElement',
message: 'Object spread is not authorized. Please use "assign" from the core package utils instead.',
},
{
selector: 'ArrayExpression > SpreadElement',
message: 'Array spread is not authorized. Please use .concat instead.',
},
],
```
Drop `'prefer-object-spread': 'error',`
---

Remove `prefer-object-spread` lint rule

---

.eslintignore

We do not want to apply linting rules to the subdirectory rum-events-format
add `rum-events-format` to `.eslintignore`
---

Remove rum-events-format from linting

---

packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/record/elementsScrollPositions.ts
packages/rum/src/domain/record/index.ts
packages/rum/src/domain/record/mutationObserver.spec.ts
packages/rum/src/domain/record/mutationObserver.ts
packages/rum/src/domain/record/observers.spec.ts
packages/rum/src/domain/record/observers.ts
packages/rum/src/domain/record/record.spec.ts
packages/rum/src/domain/record/record.ts
packages/rum/src/domain/record/serialize.spec.ts
packages/rum/src/domain/record/serialize.ts
packages/rum/test/htmlAst.ts

Accessing scroll positions of DOM elements during serialization is costly so let's avoid to do it when we can.
Following #1670, remove more scroll attributes accesses by:
- keeping in memory scroll positions during initial full snapshot and scroll events
- retrieve from memory scroll positions during subsequent full snapshot
---

⚡ [RUMF-1344] Access scroll attributes only on initial full snapshot

---

scripts/cli

* We previously removed node_modules without reinstalling, so the parent TS version was used instead of the test/app one. By installing test/app dependencies, we make sure the correct version of TS is installed. Note: compatibility errors were caught by our ssr compatibility check
* A sed command worked on Mac but not on Linux, so we didn't test for `exactOptionalPropertyTypes` compatibility on CI
* Install test/app dependencies before checking compatibility
* Replace sed by perl
---

🐛 fix compatibility check

---

packages/rum/src/domain/record/elementsScrollPositions.ts

Following #1680, some telemetry events show that some documents seems to lack scrolling element:
- specific debug log: 'unable to find document scrolling element'
- error on setting null as a weak map key
I have not been able to reproduce the behavior while going on available customer pages.
- access document.scrollingElement only on document scroll
- try to fallback on document.documentElement
- improve logging
---

🐛 [RUMF-1344] try to improve document scrolling element handling

---

packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts

Explore various selector strategies for heatmaps. Don't use class names in CSS selector, as they might be unreliable in some cases.
Implement a new selector without class names.
---

[RUMF-1356] selectors using stable attributes and no class names

---

packages/rum/src/domain/record/elementsScrollPositions.ts

Following #1688, current fallback does not improve much the situation.
- Remove fallback when scrolling element is null and don't handle document scroll in this case.
- Remove try/catch around weakmap as it should not happen anymore
---

🐛 [RUMF-1344] remove fallback for null scrollingElement

---

packages/core/src/index.ts
packages/core/src/transport/batch.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/index.ts
packages/core/src/transport/startBatchWithReplica.ts
packages/core/test/forEach.spec.ts
packages/core/test/specHelper.ts
packages/logs/src/boot/startLogs.spec.ts
packages/rum-core/src/transport/startRumBatch.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/transport/send.ts

In order to improve our data transfer, experiment with fetch keepalive in order to later be able to access to intake response.
Behind `fetch-keepalive` flag, use fetch keepalive except on visibility hidden and before unload
---

⚗️ [RUMF-1333] Experiment with fetch keepalive

---

packages/logs/README.md

Update the Doc to reflect the updated Logger Global Context APIs. Relates to changes make in RUM Global Context https://github.com/DataDog/documentation/pull/15013
- Change the API names
-  Add `removeGlobalContextProperty` and `clearGlobalContext` examples
---

Update logger Global Context APIs

---

packages/core/src/tools/instrumentMethod.spec.ts
packages/core/src/tools/instrumentMethod.ts

Issue #1570 is causing noisy errors when wrapping a null/undefined method that also has third party wrappers.
Adds a condition when executing a wrapped function to protect against the case when we "unwrap" the function ourselves and set it to null (its previous value).
---

🐛 Fix instrumention of null function with 3rd party wrapper (#1570)

---

packages/rum/src/domain/record/observers.spec.ts
packages/rum/src/domain/record/observers.ts
packages/rum/src/domain/record/record.ts
packages/rum/src/domain/record/utils.spec.ts
packages/rum/src/domain/record/utils.ts
test/e2e/scenario/recorder/recorder.scenario.ts

Some customers use CSS-in-JS libraries to style their applications. One of those libraries [(Stitches)](https://stitches.dev/) insert CSS rules inside CSSMedialRule `@media`, which is not tracked nowadays. The replay of those sessions seems to be broken and non-styled. 
Not all browsers support `CSSGroupingRule` (see [CSSGroupingRule](https://caniuse.com/?search=cssgroupingrule), [CSSConditionRule](https://caniuse.com/?search=cssconditionrule), [CSSMediaRule](https://caniuse.com/?search=cssmediarule) & [CSSSupportsRule](https://caniuse.com/?search=csssupportsrule)
- New observers are added to watch over `insertRule` and `deleteRule` of `CSSGroupingRule` prototype if supported by the browser. If not supported, we fall back to `CSSMediaRule` (which is supported by all browsers) and …

RUMF-1309: Implement nested CSS support

---

packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/transport/send.ts

In order to improve our data transfer, send request with fetch keepalive and fallback in order to later be able to access to intake response.
Follow up of #1682 
Remove `fetch-keepalive` flag
---

✨ [RUMF-1333] Send request with fetch keepalive + fallback

---

.gitlab-ci.yml
test/e2e/lib/framework/httpServers.ts

During e2e tests, requests to local intakes are logged. Having those logs for gitlab jobs could be heplfull to debug flaky tests.
- save `specs.logs` as gitlab artifact
- log intake request payload
---

👷 e2e: improve logging capabilities

---

packages/core/src/transport/httpRequest.ts

Request can throw if the URL contains credentials
- use endpoint url instead of current url
- wrap Request check in try/catch
---

🐛 [RUMF-1333] fix keepalive support check

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/tools/utils.ts
packages/core/src/transport/batch.spec.ts
packages/core/src/transport/batch.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts
packages/core/test/specHelper.ts
packages/logs/src/domain/configuration.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/transport/send.ts

We want to improve our data transfer to:
- limit our impact on end user bandwidth
- not loose data in case of short intake unavailability
Introduce new request strategy allowing us to:
- limit the number of concurrent requests to the intake -> max 32 by product
- limit the total ongoing bytes of requests to the intake -> max 80kb by product
- retry requests if the intake is momentarily unavailable -> exponential backoff strategy 1s to 256s
- limit the size of queued requests due to throttling or failure -> max 3Mb by product
Behind `retry` flag, use this new strategy for logs/rum for non exit requests.
---

⚗️[RUMF-1351] experiment request retry strategy

---

.eslintrc.js

The `no-restricted-syntax` related to enums introduced in #1364 is overridden by other restricted syntaxes on transpiled files introduced by #1347, so it's not actually applied to source files.
Because the enum limitation is also about transpilation optimization, simply move it to the special casing.
---

👷 fix ESLint rule on non-const enum

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Differentiate queue full cases
Add different reason to the log
---

🔉 [RUMF-1351] retry: add extra context to queue full log

---

packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/src/rumEvent.types.ts
test/e2e/scenario/rum/views.scenario.ts

Allow to track the [time to first byte](https://developer.mozilla.org/en-US/docs/Glossary/time_to_first_byte) of the resource corresponding to the document loading at the view level.
Add `view.first_byte` from response start [navigation timing](https://www.w3.org/TR/navigation-timing/#processing-model).
---

✨ [RUMF-1371] Collect view time to first byte

---

.eslintrc.js
eslint-local-rules/disallowSideEffects.js
eslint-local-rules/disallowSpecImport.js
packages/core/src/domain/tracekit/computeStackTrace.spec.ts
packages/core/src/domain/tracekit/computeStackTrace.ts
packages/core/src/tools/createEventRateLimiter.spec.ts
packages/core/src/tools/error.ts
packages/core/src/transport/batch.spec.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/test/capturedExceptions.ts
packages/core/test/specHelper.ts
packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/action/computeFrustration.ts
packages/rum-core/src/domain/rumEventsCollection/action/getActionNameFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceUtils.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/tracing/getDocumentTraceId.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/domain/record/serialize.spec.ts
packages/rum/test/htmlAst.ts
test/e2e/lib/helpers/browser.ts
test/e2e/scenario/eventBridge.scenario.ts
test/e2e/scenario/logs.scenario.ts
test/e2e/scenario/telemetry.scenario.ts

Prettier already does its best to keep lines below the limit, so max-len is more annoying than anything else. Also, sometimes this rule conflicts with Prettier, and vjeux himself (prettier author) [advises to disable the rule when using Prettier](https://github.com/prettier/prettier/issues/1954#issuecomment-310457491)
Disable the ESLint rule
Remove unneeded `eslint-disable` comments (using [`reportUnusedDisableDirectives`](https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments))
---

Disable ESLint `max-len`

---

packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Following #1700, try to improve the strategy
- consider transport down on status code `429` (too many request)
- reduce retry max time to `1min` to be more likely to send the data on transport up
---

⚗️ [RUMF-1351] tweak retry strategy

---

packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts

We've seen that when fixing #1721 , this strategy yields slightly but strictly better results than the default strategy.
Use the "stable attributes" experimental selector strategy by default.
---

✨⚗️ [RUMF-1378] use stable attributes when computing heatmap selector

---

packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Following #1700, improve the strategy
consider transport down on status code 408 (request timeout)
---

⚗️ [RUMF-1351] retry request on timeout

---

packages/core/src/domain/tracekit/computeStackTrace.spec.ts
packages/core/src/domain/tracekit/computeStackTrace.ts

We accidentally parse error messages that looked similar to stackTrace:
Example:
```
HttpError: 400 Bad Request, see context.apiResponse for more details
at s (spa.min.js:2:2418592)
```
would output
```
[{
args: [],
column: undefined,
func: '?',
line: undefined,
url: 'HttpError: 400 Bad Request, see context.apiResponse for more details',
}, {
args: [],
column: 5,
func: 's',
line: 3,
url: 'spa.min.js',
}]
```
`'HttpError: 400 Bad Request, see context.apiResponse for more details'` is not a valid URL
Get the `toString` of the error (casting error as a `String`) and remove it from the beginning of the stack trace if present
---

🐛 [RUMF-1369] Exclude error message from stacktrace parsing

---

developer-extension/src/panel/components/infosTab.tsx
packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/configuration.spec.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.ts
packages/rum-core/src/domain/rumSessionManager.spec.ts
packages/rum-core/src/domain/rumSessionManager.ts
packages/rum-core/src/rumEvent.types.ts
packages/rum-core/test/mockRumSessionManager.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/recorderApi.spec.ts
packages/rum/src/boot/recorderApi.ts
packages/rum/src/boot/startRecording.spec.ts
sandbox/index.html
test/e2e/lib/framework/createTest.ts

Introduction of new RUM pricing plans.
- Remove `Browser Lite` and `Browser Premium` plans
- Introduce:
- `Browser Pro`: collect all RUM events but don't allow replay
- `Browser Replay`: collect all RUM events and allow replay
- Use `replaySampleRate` to control repartition between Pro and Replay, default value: `0`
---

💥[RUMF-1391] introduce new RUM plans and remove old ones

---

packages/core/src/tools/contextHistory.spec.ts
packages/core/src/tools/timeUtils.ts
packages/rum-core/src/domain/contexts/foregroundContexts.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/listenActionEvents.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
packages/rum-core/src/domain/rumEventsCollection/resource/matchRequestTiming.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/test/createFakeClick.ts
test/e2e/scenario/rum/actions.scenario.ts

When the click starts (mouse/pointer down) on an element and ends (mouse/pointer up) on another element, the `click` event target is set to the `BODY` element by the browser. This is problematic, because we report  clicks occuring on the `BODY` even if the user uses a whole other element. This impacts the RUM click action target name (`@action.target.name`), as well as the experimental heatmaps CSS selector generation.
Using the `pointerdown` event target instead improves the situation: the element used to compute the action target name and CSS selector is the element the user intended to click.
Some application add a temporary class name when an element is being clicked (similarly to the [`:active`](https://developer.mozilla.org/en-US/docs/Web/CSS/:active) CSS pseudo-class) or focused. …

♻️ [RUMF-1368] use the PointerDown event target for click actions

---

packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts

All experiments introduced in #1726 proved to be benefical.
Use all experimental strategies by default
---

⚗✨ [RUMF-1379] use experimented CSS selectors strategies by default

---

developer-extension/src/panel/components/infosTab.tsx
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/domain/configuration.spec.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
packages/rum-core/src/domain/rumSessionManager.spec.ts
packages/rum-core/src/domain/rumSessionManager.ts
packages/rum-core/src/rawRumEvent.types.ts
packages/rum-core/src/rumEvent.types.ts
packages/rum-core/test/fixtures.ts
packages/rum-core/test/mockRumSessionManager.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/recorderApi.spec.ts
packages/rum/src/boot/recorderApi.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/types/sessionReplay.ts
sandbox/index.html
test/e2e/lib/framework/createTest.ts

Reflect modification of pricing plans content and behavior while keeping current behavior for existing customers.
New configuration parameters:
- `trackResources`: allow to collect resource events
- `trackLongTasks`: allow to collect long task events
- `sessionReplaySampleRate`: replace `premiumSampleRate` but only control the percentage of sessions that have session replay (and are billed for it).
```
premiumSampleRate | sessionReplaySampleRate | trackResources/LongTasks || do track resources/long tasks
========================================================================================================
used             | undefined               | undefined                || true if session replay, false otherwise
used             | undefined               | false …
```

✨ [RUMF-1391] Introduce trackResources, trackLongTasks and sessionReplaySampleRate

---

.gitlab-ci.yml
package.json
scripts/publish-npm.sh

Avoid to publish to npm from developer laptop
- new script to publish to npm using a npm automation token
- add extra manual step on the deploy tag stage
only a `npm whoami` to test the token setup
we will see how it goes with the next release
---

👷‍ Setup publish to npm from ci

---

webpack.base.js

Source maps are not uploaded on our CDN, so having source map comments in bundles is useless.
Change the webpack configuration to avoid appending source map comments to bundles.
---

👷 remove source map comment from bundles

---

packages/core/src/domain/report/reportObservable.ts

fix issue raised by telemetry
add a fallback message when policy is undefined
---

🐛 report: handle undefined policy

---

packages/rum-core/src/browser/performanceCollection.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts

fix issue raised by telemetry
remove useless toJSON call and checks
---

🐛[RUMF-1276] handle performance entry without `toJSON`

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/configuration/simulation.ts
packages/core/src/domain/telemetry/telemetry.ts
packages/core/src/index.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts
packages/core/src/transport/startBatchWithReplica.ts
packages/logs/src/domain/assembly.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/transport/startRumBatch.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts

Analyze behavior of retry strategy during intake issue
- Introduce simulation parameters:
```
simulationStart?: string | undefined
simulationEnd?: string | undefined
simulationLabel?: string | undefined
```
- consider request to primary as failed during simulation
- add simulation label to events during simulation
---

⚗️[RUMF-1405] add mechanism to simulate intake issue

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/index.ts
packages/core/src/domain/telemetry/index.ts
packages/core/src/domain/telemetry/rawTelemetryEvent.types.ts
packages/core/src/domain/telemetry/telemetry.spec.ts
packages/core/src/domain/telemetry/telemetry.ts
packages/core/src/domain/telemetry/telemetryEvent.types.ts
packages/core/src/index.ts
packages/logs/src/boot/logsPublicApi.spec.ts
packages/logs/src/boot/logsPublicApi.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/boot/startLogs.ts
packages/logs/src/domain/assembly.spec.ts
packages/logs/src/domain/configuration.ts
packages/rum-core/src/boot/rumPublicApi.spec.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/configuration.ts
packages/rum/src/domain/segmentCollection/startDeflateWorker.spec.ts
sandbox/index.html
test/e2e/lib/framework/createTest.ts
test/e2e/lib/framework/eventsRegistry.ts
test/e2e/lib/types/serverEvents.ts
test/e2e/scenario/telemetry.scenario.ts

Engineering and product would like to easily analyze how customers configure the SDKs in order to:
- Ease troubleshooting, ex: traffic spike/drop due to sampleRate change or to customer traffic
- Track feature usage, ex: what percentage of orgs use a proxy 
This PR collect customer configuration through telemetry events.
Add `addTelemetryConfiguration`
---

🔊 Collect configuration telemetry event

---

packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts

We want to improve our data transfer to:
- limit our impact on end user bandwidth
- not loose data in case of short intake unavailability
Enable new request strategy for logs/rum for non exit requests allowing us to:
- limit the number of concurrent requests to the intake -> max 32 by product
- limit the total ongoing bytes of requests to the intake -> max 80kb by product
- retry requests if the intake is momentarily unavailable -> exponential backoff strategy 1s to 60s
- limit the size of queued requests due to throttling or failure -> max 3Mb by product
---

✨[RUMF-1377] Enable new request strategy

---

packages/core/src/transport/sendWithRetryStrategy.ts

A couple of orgs generated some telemetry errors where payload is undefined in:
https://github.com/DataDog/browser-sdk/blob/34223e32f59b94e1a0eca2abd9b9ab6d2b145fa5/packages/core/src/transport/sendWithRetryStrategy.ts#L73-L74
- add some debug info when the first payload of the queue is not defined
- remove unnecessary `resume after transport down` debug log
---

🔉[RUMF-1423] Add debug log for retry issue

---

packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Following #1790, investigate some telemetry errors related to retry strategy.
From added debug logs, before starting a retry the queue is empty and the transport is up.
Hypothesis: we somehow received multiple responses from a single send, one down followed by one up could lead to the observed issue.
Added some debug logs to validate / invalidate the hypothesis
---

🔉[RUMF-1423] Investigation for retry issue - part 2

---

.prettierignore
packages/core/src/domain/console/consoleObservable.ts
packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts

Fix for https://github.com/DataDog/browser-sdk/issues/807
Added a replacer within the jsonStringify function that removes cyclic references while serializing.
---

🐛 [RUMF-1410] Allow serialization of objects with cyclic references

---

packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Following #1790, #1793, our new request strategy can be disturb if our xhr instances are reused to send other requests.
Prevent our xhr instances callback to be called multiple times.
---

🐛[RUMF-1423] prevent unexpected behavior when our xhr are reused

---

yarn.lock

https://access.redhat.com/security/cve/CVE-2022-3517
Update minimatch subdependency from 3.0.3 to 3.0.5
---

📦 update minimatch to fix vulnerability

---

packages/rum/src/domain/record/serializationUtils.spec.ts
packages/rum/src/domain/record/serializationUtils.ts
packages/rum/src/domain/record/serialize.ts

Resolve relative urls to absolute in CSS Style Sheets in order to properly fetch resource by the player 
Extracting cssRules from a style sheet and converting them to text, switch absolute urls to relative ones based on the attribute href of the style sheet.
---

REPLAY-1075: Resolve relative URLS to absolute in stylesheets

---

packages/rum/src/domain/record/viewports.spec.ts

When the [viewports.spec tests](https://github.com/DataDog/browser-sdk/blob/62b88f934a5cd5c949435c6b5d2df51b79e864cf/packages/rum/src/domain/record/viewports.spec.ts#L8) are run, a "scroll" event is dispatched *after* they finish to run. This scroll event can impact test cases that are run directly after them, for example the [record.spec tests](https://github.com/DataDog/browser-sdk/blob/62b88f934a5cd5c949435c6b5d2df51b79e864cf/packages/rum/src/domain/record/record.spec.ts) which are doing many assertions on generated records.
This is reproductible with Jasmine seed 67707.
Note: I also observed a similar issue with the `visualViewport` resize event, but couldn't reproduce it anymore.
Conditionnally wait for the scroll event to happen before ending the test.
--- …

✅ fix flaky test caused by an async scroll event

---

yarn.lock

See https://www.cve.org/CVERecord?id=CVE-2022-2421
Update socket.io-parser to 4.0.5
---

📦 update socket.io-parser to fix vulnerability

---

packages/logs/README.md

Follow up of the issue #1764. 
Clarify log SDK usage in the readme
Remove the mention of `other Javascript clients` in the readme
---

📝 Clarify log SDK usage in the readme

---

packages/core/src/index.ts
packages/core/src/transport/index.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/boot/startRecording.ts
packages/rum/src/domain/segmentCollection/buildReplayPayload.spec.ts
packages/rum/src/domain/segmentCollection/buildReplayPayload.ts
packages/rum/src/domain/segmentCollection/segment.spec.ts
packages/rum/src/domain/segmentCollection/segment.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts

With this PR, Session Replay Segments will benefit from the same features introduced for RUM/Logs data in https://github.com/DataDog/browser-sdk/pull/1770
* Replace the `send` module with a `buildReplayPayload` and use `HttpRequest` directly in Segment Collection
* Store the flush reason in flushed segments
* Use the right `HttpRequest` strategy to send segment data
---

⚗️ ✨ [RUMF-1425] use the retry/throttle transport strategy to send segments

---

packages/core/src/domain/user/index.ts
packages/core/src/domain/user/user.spec.ts
packages/core/src/domain/user/user.ts
packages/core/src/domain/user/user.types.ts
packages/core/src/index.ts
packages/logs/README.md
packages/logs/src/boot/logsPublicApi.spec.ts
packages/logs/src/boot/logsPublicApi.ts
packages/logs/src/boot/startLogs.spec.ts
packages/logs/src/domain/assembly.spec.ts
packages/logs/src/domain/assembly.ts
packages/logs/src/rawLogsEvent.types.ts
packages/rum-core/src/boot/rumPublicApi.ts
packages/rum-core/src/domain/assembly.ts
packages/rum-core/src/rawRumEvent.types.ts

Issue raised here: https://github.com/DataDog/browser-sdk/issues/1675
The RUM SDK provides convenient user-related functions. This change brings the same functions to the LOGS SDK.
Added the following functions to the logs public API: 
setUser, 
setUserProperty, 
getUser,
removeUserProperty,
clearUser
---

✨ [RUMF-1409] Provide setUser and related functions for logs SDK

---

packages/core/src/domain/configuration/endpointBuilder.spec.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/domain/user/user.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/index.ts
packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts

Flag data that has been ingested after a retry to ease investigations
On retried requests, add the following tags:
- `retry_count`: number of times this payload has been retried
- `retry_after`: last failure status
---

✨[RUMF-1435] Add some retry info on events

---

packages/rum-core/src/domain/rumEventsCollection/resource/matchRequestTiming.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/matchRequestTiming.ts

If we match 2 performance entries on a request, we try and check if one of them is a [preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) option request. 
This behaviour is no longer present on modern browsers.
- remove check
- delete adjacent test
---

🗑️ [RUMF-1433] Remove Preflight request Performance Entry check

---

packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts

Make retry/throttle strategy used by default for requests sent to the replay intake
Enable change introduced in https://github.com/DataDog/browser-sdk/pull/1807 
---

✨ [RUMF-1425] enable request retry/throttle for replay intake

---

packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.ts

Reverts DataDog/browser-sdk#1819 until we know more about duplicated events caused by the retry strategy

Revert "✨ [RUMF-1425] enable request retry/throttle for replay intake"

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/telemetry/telemetryEvent.types.ts
packages/rum/src/types/sessionReplay.ts

Collect `trackResources` and `trackLongTasks`
- add `trackResources` and `trackLongTasks` to `serializeConfiguration`
---

📈[RUMF-1432] Collect trackResources and trackLongTasks configs

---

developer-extension/src/panel/components/eventsTab.tsx
developer-extension/src/panel/components/json.tsx
developer-extension/src/panel/hooks/useEvents.ts

Improve the event description in the event list of the developer extension
---

Improve event description message in developer extension

---

yarn.lock

Upgrading `selenium-standalone` fixes webdriver failing to install chromedriver on M1 mac. See https://github.com/webdriverio/selenium-standalone/issues/709
Also, upgrade a couple of other vulnerable dependencies while I was at it.
You can test this by running the following steps (the `yarn` command may still fail, see https://github.com/DataDog/browser-sdk/pull/1843 ):
```
rm -r node_modules
yarn
yarn test:e2e
```
---

⬆️ [RUMF-1434] fix running e2e tests on M1 macs

---

performances/package.json
performances/src/profilers/startCpuProfiling.ts
performances/src/profilers/startProfiling.ts
performances/src/proxy.ts
performances/src/scenarios/twitterScenario.ts
performances/src/trackNetwork.ts
yarn.lock

https://github.com/DataDog/browser-sdk/issues/1772
Upgrade puppeteer and fix a few issues related to the performances script
```
rm -r node_modules
yarn
cd performances
yarn start
```
---

⬆️ [RUMF-1434] fix yarn failing to install puppeteer on M1 mac

---

packages/core/src/domain/configuration/endpointBuilder.spec.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/test/specHelper.ts
packages/logs/src/boot/startLogs.spec.ts
packages/rum-core/src/domain/requestCollection.spec.ts

Flag events with the api used for transport to help investigation.
Add `api: 'xhr' | 'fetch' | 'beacon'`  tag on events
---

✨[RUMF-1435] Add transport api on events

---

scripts/staging-ci/staging-reset.js

During staging reset, if the staging branch already exists, it is not updated and all subsequent `merge-into-staging` checks are failing. 
Delete staging branch if it already exists and create a fresh one.
None, we'll see how it will go next week.
---

👷Fix staging reset

---

packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/trackEventCounts.spec.ts
packages/rum-core/src/domain/trackEventCounts.ts
packages/rum-core/test/specHelper.ts

We noticed that child event counters were often inaccurate. This first PR goal is to imporve the situation by only taking child events related to the current parent event into account.
When computing child event counters, only take events related to the current parent event into account.
---

🐛 [RUMF-1421] improve counters by filtering child events

---

packages/rum-core/src/boot/startRum.spec.ts
packages/rum-core/src/boot/startRum.ts
packages/rum-core/src/domain/assembly.spec.ts
packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
packages/rum-core/src/domain/contexts/featureFlagContext.ts
packages/rum-core/src/domain/contexts/viewContexts.spec.ts
packages/rum-core/src/domain/contexts/viewContexts.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/error/errorCollection.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
packages/rum-core/test/specHelper.ts
packages/rum/src/boot/startRecording.spec.ts
packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts

Extracting feature flag management to a dedicated component.
- Remove feature flag logic from trackViews
- Create featureFlagContexts
- Use featureFlagContexts in viewCollection and errorCollection
---

♻️ [RUMF-1440] improve feature flag collection implementation

---

.gitlab-ci.yml

The publish-npm job is only using the cache and does not install yarn dependencies itself. Because the cache is shared among all other job, it can be updated with other dependency versions in the meantime, and causing the publish-npm job to use the wrong versions.
This commit fixes the issue by running `yarn`, ensuring the right dependencies are installed before running the publish-npm script.
---

👷 fix publish-npm job

---

packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts

In the context of the investigation of resources with  long durations, I want to assess the performance entry durations correctness.
To do it, I want to colllect xhr and fetch computed durations and corresponding performance entry durations to identify:
- happens when we got a the duration from performance entry, computed duration or both
- compare entry duration with computed duration that could highlight an issue from the browser
Adds `resource._dd.computed_duration` and `resource._dd.entry_performance_duration`
Under feature flag resource_durations
---

🔊 Collect computed and perf entry durations

---

packages/core/src/domain/configuration/configuration.ts
packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/domain/configuration/transportConfiguration.spec.ts

To mitigate ad blockers for internal analytics monitored sites, we can now configure a specific subdomain.
Add new init config option `internalAnalyticsSubdomain`
Only allow internal analytics intake for traffic going to `datadoghq.com` (including replica)
---

✨Allow internal analytics intake

---

packages/core/src/tools/getZoneJsOriginalValue.spec.ts
packages/core/src/tools/getZoneJsOriginalValue.ts

We observed that some website define a `Zone` global variable unrelated to Zone.js, and this variable doesn't have a `__symbol__` method, so it crashes the SDK.
Related: https://github.com/angular/zone.js/issues/434
Check for the `__symbol__` method before using it.
---

🐛 [RUMF-1449] fix Zone support when __symbol__ is missing

---

packages/rum-core/src/domain/rumEventsCollection/view/trackViewEventCounts.spec.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewEventCounts.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViewMetrics.ts
packages/rum-core/src/domain/rumEventsCollection/view/trackViews.ts
packages/rum-core/src/domain/trackEventCounts.spec.ts
packages/rum-core/src/domain/trackEventCounts.ts

Improve View child event counters accuracy
Keep updating View child event counters after the view ends.
---

🐛 [RUMF-1421] keep updating the view event counters after view end 

---

packages/core/src/domain/configuration/endpointBuilder.ts
packages/core/src/transport/httpRequest.spec.ts
packages/core/src/transport/httpRequest.ts
packages/core/src/transport/sendWithRetryStrategy.spec.ts
packages/core/src/transport/sendWithRetryStrategy.ts

If the browser somehow consider the intake response as [opaque](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque), we won't be able to access its true status and may wrongly retry it.
- do not retry opaque response
- force [request mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) 'cors'
- add extra debug tag with response type
---

🐛[RUMF-1435] don't retry opaque response

---

packages/core/src/browser/cookie.ts
packages/core/src/tools/utils.spec.ts
packages/core/src/tools/utils.ts
packages/rum-core/src/domain/configuration.spec.ts
packages/rum-core/src/domain/configuration.ts
packages/rum-core/src/domain/tracing/tracer.spec.ts
packages/rum-core/src/domain/tracing/tracer.ts
packages/rum-core/src/domain/tracing/tracer.types.ts

Users would like to use RUM alongside backends that are instrumented with OpenTelemetry, and benefit from the correlation of traces in APM. 
Added a new RUM configuration property: 
allowedTracingUrls: { match: MatchOption,  propagatorTypes: ("datadog" | "tracecontext" | "b3" | "b3multi")[] }
* datadog: Datadog (x-datadog-*)
* tracecontext: Trace Context (traceparent)
* b3: B3 Single Header (b3)
* b3multi: B3 Multi Headers (X-B3-*)
This allows to select which propagator types to use when creating the request headers.  It also gives more flexibility by providing the full URL to the match function (instead of origin).
---

✨ [RUMF-1236] Add support for OTel headers

---

package.json
scripts/cli

This is problematic because rum-events-format can change at any time independently of the Browser SDK repository, and it can make the CI fail when running various unit and e2e tests jobs or when publishing to NPM.
Don't update the submodule, just initialize it during `postinstall`.
---

👷 [RUMF-1287] don't update rum-events-format on postinstall

---

.gitlab-ci.yml
scripts/check-licenses.js
scripts/check-release.js
scripts/utils.js

Prevents https://github.com/DataDog/browser-sdk/issues/1881
Add a CI job to do some checks before doing a release. It checks that:
* the version tag matches the lerna version
* the git HEAD and the version tag are pointing to the same commit
* package.json files have the correct version in their `version` field and their prod/dev/peer dependencies
* packages entry points are pointing to existing files
---

👷  add a CI job to do some checks before the release
