DataDog/browser-sdk

- .gitlab-ci.yml
- scripts/ci-cbt.sh
- for ci docker images
- for cbt credentials
> 💚[gitlab] use new project name

- packages/core/src/requestCollection.ts
> [RUMF-188] add traceId to fetch calls

- .gitignore
- .gitlab-ci.yml
- package.json
- test/server/server.js
- yarn.lock
Flaky e2e tests are tricky to reproduce, add server logging to have extra context on failed tests.
> 🔊[e2e] output test server log

- .codecov.yml
- .gitlab-ci.yml
- package.json
- scripts/codecov.sh
- test/unit/karma.local.conf.js
- yarn.lock
https://codecov.io/gh/DataDog/browser-sdk
>  🔧[coverage] setup codecov

- test/app/app.ts
- test/e2e/scenario/helpers.ts
- test/static/bundle-e2e-page.html
- fresh cookies for every test
- stop tracking some sdk requests
- wait to process the event loop before flushing events
> ✅[e2e] cleaner tests

- packages/rum/src/viewTracker.ts
- track when load event is greater than page duration
- add extra context
> 🔊 [RUMF-257] add extra abnormal load info

- packages/rum/src/resourceUtils.ts
Add some internal loging to understand why we got abnormal timing durations. This PR is a preliminary step to solve negative durations (related: #246)
> 🔊 [RUMF-71] add internal logs messages when an abnormal duration is spoted

- packages/core/package.json
- packages/logs/package.json
- packages/rum/package.json
> 🔧 add repository link for each package

- packages/rum/src/resourceUtils.ts
- packages/rum/src/rum.ts
- packages/rum/test/resourceUtils.spec.ts
- test/e2e/scenario/helpers.ts
remove connect, dns timings when persistent connection or cache
cf.https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings
> ✨[RUMF-375] do not collect irrelevant timings

- test/e2e/browsers.conf.js
- test/unit/browsers.conf.js
> 🔧 update cbt chrome mobile

- test/e2e/wdio.cbt.conf.js
- test/getTestName.js
- test/unit/karma.cbt.conf.js
Give more information on which test is running on CBT
> 🔧 improve CBT test names

- packages/core/src/cookieMigration.ts
- packages/core/src/sessionManagement.ts
- packages/core/test/cookieMigration.spec.ts
Add a migration from new cookie format to old cookie format in case of a rollback
> 🥅[RUMF-430] handle potential session rollback

- scripts/generate-changelog.js
- fix spawn promise to not stop the main process
- git add changelog update
> 🐛add Changelog update to the release

- packages/rum/src/rum.ts
userAction was not snake cased
> 🐛[RUMF-383] fix custom user action type case

- packages/core/src/sessionManagement.ts
- packages/core/test/sessionManagement.spec.ts
- packages/logs/src/loggerSession.ts
- packages/logs/test/loggerSession.spec.ts
- packages/rum/src/rum.ts
- packages/rum/src/rumSession.ts
- packages/rum/test/rumSession.spec.ts
synthetics instrumentation is delayed on new page creation
avoid to mess the session type of all the events of the page
and ♻️session type naming collision
> 🐛[RUMF-451] compute session type for each event

- test/e2e/scenario/agents.scenario.ts
- test/server/fake-backend.js
increase `/ok` duration but only for timings tests
> ✅ try to fix flaky edge test

- README.md
Add extra information for each packages
Packages table in Readme with:
- npm badge
- size badge
- cdn links
- doc links
---
> 📝 add packages section

- packages/rum/src/rum.entry.ts
- packages/rum/src/viewCollection.ts
- packages/rum/test/specHelper.ts
Add a FF to allow to test only on datadog first
Put keep alive behind a feature flag
---
> [RUMF-513] put keep alive behind a feature flag

- packages/rum/src/chromeCustomEvents.ts
- packages/rum/src/rum.ts
> send a custom event on any lyfecycle notification

- extension/README.md
- extension/manifest.json
- extension/src/background/background.ts
- extension/src/contentscript/contentscript.ts
- packages/rum/src/chromeCustomEvents.ts
receive rum events in the extension contentScript
> receive rum events in the extension contentScript

- extension/src/contentscript/contentscript.ts
- extension/src/lib/rumEvents.ts
- packages/rum/src/chromeCustomEvents.ts
> add event typing to extension

- .gitlab-ci.yml
- Dockerfile
- test/e2e/wdio.local.conf.js
Synchronize chrome ci version with local version
- update chrome driver version
- update docker image with updated chrome
---
> Update chrome version

- test/app/yarn.lock
- yarn.lock
security issue
Bump version
---
> Bump serialize-javascript@3.1.0

- scripts/build-env.js
issue introduced by #476 fb155807dd3eedfbb8a04b1818d738169ac37fb4
Provide falsy value with correct type
`yarn dev`
---
> 👷 fix yarn dev

- package.json
- yarn.lock
Security issue on bl
Fix version
---
> 📌 bl vulnerability

- .gitlab-ci.yml
- Dockerfile
- test/e2e/wdio.local.conf.js
Follow local chrome update
Update ci chrome version + chrome driver
---
> Update chrome + driver to v86

- scripts/generate-changelog.js
submodule log is reported in stderr which fail the command
make fetch tags quiet
node scripts/generate-changelog.js
---
> 🐛 fix changelog generation

- packages/rum/src/boot/rum.ts
- packages/rum/src/domain/lifeCycle.ts
- packages/rum/src/domain/rumEventsCollection/action/actionCollection.spec.ts
- packages/rum/src/domain/rumEventsCollection/action/actionCollection.ts
- packages/rum/src/domain/rumEventsCollection/error/errorCollection.spec.ts
- packages/rum/src/domain/rumEventsCollection/error/errorCollection.ts
Simplify `addError` and `addAction`. 
Remove their lifecycle event and provide a function to call directly.
---
> ♻️ [RUMF-748] cleanup add user add action events

- package.json
- tslint.json
Remove ajv from implicit dependencies
Add ajv in project dependencies
ci
---
> Add ajv in project dependencies

- packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.spec.ts
- packages/rum/src/domain/rumEventsCollection/resource/matchRequestTiming.ts
- packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
- packages/rum/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum/src/typesV2.ts
cf #609 
Revert added debug infos
---
> ⚗️[RUMF-766] Revert add match request timing debug infos

- packages/rum/src/transport/batch.ts
Replica application overwrite does not work in v2
Use the right format
manual test
---
> 🐛 fix replica application overwrite

- test/unit/karma.bs.conf.js
A lot of disconnect errors on bs unit tests
Test if karma retry can help
none
---
> 🔧 [bs] try to increase disconnect tolerance

- scripts/deploy.sh
Improve local browser cache for SDK bundles.
Adjust the Cache-Control header.
Tests on staging from devtools + validation with collected RUM data.
---
> [RUMF-793] tweak the cache-control header

- packages/rum/src/rumEventsFormat.ts
#649 was merged without updating against `master` first, so a newly introduced file missed the new format. 
`yarn format -w`
---
> 🎨 fix packages/rum/src/rumEventsFormat.ts format

- scripts/bs-wrapper.js
When sending a SIGTERM, yarn [doesn't wait for its children before exiting][1].
This commit removes the use of `yarn` in bs-wrapper.  This should be fine, because yarn was only used for setting the environment (mostly PATH).  Since bs-wrapper is run via yarn scripts, the environment should already be set up.
This commit also changes bs-wrapper to make sure to send SIGTERM only once if child process sends more data to STDOUT before exiting.
CI
[1]: https://github.com/yarnpkg/yarn/issues/4667
---
> 🐛✅ fix bs-wrapper tests termination

- yarn.lock
https://github.com/advisories/GHSA-3329-pjwv-fjpg
Update urijs to latest version
---
> ⬆️ update urijs

- packages/rum-recorder/src/domain/rrweb/observer.ts
Mouse positions occuring during a segment should not leak to a next segment.  Batching should be done at the segment level.
Remove mousemove batching from RRWeb
Manual testing: replays mouse position should be smoother
---
> [RUMF-812] remove mousemove batching from RRWeb

- package.json
- yarn.lock
Following #695, karma 6 should now work with IE and safari
Bump to latest karma version
ci
---
> ⬆️ Bump karma to 6.1.0

- packages/core/src/browser/fetchProxy.ts
- packages/core/src/browser/xhrProxy.ts
- packages/core/src/domain/internalMonitoring.spec.ts
- packages/core/src/domain/internalMonitoring.ts
- packages/core/src/domain/sessionManagement.ts
- packages/core/src/index.ts
- packages/core/src/tools/utils.ts
- packages/rum-recorder/src/boot/recorder.ts
- packages/rum-recorder/src/domain/rrweb/observer.ts
- packages/rum-recorder/src/domain/rrweb/record.spec.ts
- packages/rum-recorder/src/domain/rrweb/record.ts
- packages/rum-recorder/src/domain/rrweb/utils.ts
Monitor RRWeb codebase to have better visibility on what goes wrong in the wild.
Use the Browser SDK internal monitoring on all RRWeb "observer" asynchronous functions.
---
> [RUMF-843] monitor rrweb codebase

- packages/core/src/domain/internalMonitoring.ts
Monitor the issue in the wild
- Check every minute the difference between `Date.now()` and `navigationStart + performance.now()`
- Add a monitoring log if the difference is > 1s
- Stop the monitoring if a difference is detected
manual
---
> 🔊 [RUMF-844] Add clock drift monitoring

- packages/core/src/transport/transport.ts
in order to monitor behavior of monotonic clock compared to system clock
add current monotonic time when sending batch
manual
---
> ⚗ [RUMF-858] add monotonic batch time

- package.json
Small trick that I always use when writing unit tests
Add a `yarn test:unit:watch` script
---
> ✅ add `yarn test:unit:watch` script

- packages/logs/README.md
* New feature
* Modified docs to change the definition of `setHandler()` and the examples
---
> [rum] modified docs on simultaneous logging

- packages/rum-core/src/domain/foregroundContexts.ts
Add context to internal logging in foreground context
- Add context to internal logging in foreground context
---
> Add context to internal logging in foreground context

- .gitlab-ci.yml
- scripts/deploy.sh
Reducing risks related to production changes
- Update the deployment script (deploy.sh) to handle suffixes
- Add a new gitlab job called deploy-canary
Locally
---
> 👷 [RUMF-941] canary setup cdn

- packages/core/src/transport/transport.ts
Occasionally replay segments are being dropped. We have very little understanding of the circumstances of why certain requests are failing. Here we collect more information to log the circumstance- and implicitly hope the next network request succeeds.
JavaScript in the wild can be a funny place, with many different vendor patches and frameworks fighting with each other. We take a few unconventional approaches to cover all our bases around what is going on:
1. Use of try/catch with XHR open + send. This code _should_ not throw, but this is critical code so let's add ~200 bytes and see what happens.
2. `event.isTrusted` Maybe a vendor is dispatching poorly crafted error events on XHR, so let's detect if this is a native event.
We can run this code in production for a while, see if it …
> 🐛 [REPLAY-325] Add verbose error details on XHR transport failure

- scripts/deploy.sh
Fix malformed suffixed package names
Add suffixed packages invalidation
Update deployment script
Locally
---
> 🐛  Fix suffixed packages deployment

- .gitlab-ci.yml
- scripts/deploy.sh
Fix deployment invalidation and how to get major version 
Update deployment script and gitlab ci
Locally
---
> 🐛 Fix deployment invalidation

- packages/rum/README.md
Feature is GA and doc is available.
Update init parameters doc
N/A
---
> 📝 document `trackViewsManually` option

- packages/rum-core/src/browser/performanceCollection.ts
Avoid to break performance collection on older browsers
In case of PerformanceObserver without entryType option is not supported, use main observer for experimental entries
tested on chrome 67 with browserstack
---
> ⚗ [RUMF-970] Buffered PerformanceObserver: add fallback for older browsers

- packages/rum-core/src/domain/foregroundContexts.ts
Add check as part of investigating error in SDK
https://docs.google.com/document/d/17FsROHTNE8hh_Ra6blCgNwyZn8m2PqRefS_WIWjfBSk/edit#
---
> Add monitoring on untrusted events

- packages/rum/src/internal.ts
Export serialise dom function to be used in other datadog repo
> Export serialise dom function

- scripts/dev-server.js
Allow to use dev-server with `xxx-v3.js` files
add v3 in the suffix regex
manual
---
> 👷 [dev-server] handle v3 suffix

- packages/rum-core/src/transport/batch.ts
Misconfiguration introduced here https://github.com/DataDog/browser-sdk/commit/a04cff587bba2ea085e9132c6a33632224ccf769#diff-f3138d2f0317b247df11f808e89776d6fe860b5e417f4cb5e2f41ed36a8076a9R38
use the right endpoint
staging
---
> 🐛 fix rum replica

- scripts/bs-wrapper.js
- scripts/check-licenses.js
- scripts/dev-server.js
- scripts/generate-changelog.js
- scripts/generate-schema-types.js
- scripts/replace-build-env.js
- scripts/staging-ci/check-staging-merge.js
- scripts/staging-ci/merge-into-staging.js
- scripts/staging-ci/staging-reset.js
- scripts/utils.js
During the new staging ci process development utils have been introduced. 
This PR updates all the scripts which can have a use for utils.
- Update scripts
Locally, Gitlab
---
> ♻️  CI scripts refactoring

- .gitlab-ci.yml
Add a dummy job to tell `to-staging` it's fine to merge early
---
> 👷 [RUMF-1049] add tests-passed job

- scripts/staging-ci/staging-reset.js
Fix staging reset script
Staging reset script
Gitlab
---
> 🐛 Fix staging reset

- packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
Investigate why a lot of LCP are missing on Initial Views
Add a log behind a FF every time we drop the first LCP.
The same kind of log have been present on staging for a few days. I opened this PR with a feature flag so we can quickly enable or disable it to avoid too many logs.
---
> 🔊 [RUMF-1041] log a message when the first LCP gets discarded

- package.json
- yarn.lock
> 👷 update vulnerable dependencies

- packages/core/src/domain/sessionManagement.ts
Try to quantify cookie corruption at init
add a check after init session to see if cookie has changed
staging
---
> 🔊[RUMF-1021] check cookie after init

- scripts/staging-ci/merge-into-staging.js
In some cases the merge into staging can fail because the staging is already up to date. 
It can happen if:
1. we rerun the job after resolving a conflict
2.  someone else merge is branch with main and uses the to-staging
This PR prevents the script from failing when the staging is already up to date.
Update merge into staging script
Locally
---
> 👷 Check if merge into staging already done

- .github/PULL_REQUEST_TEMPLATE.md
Add PR checklist on testing section to serve as a reminder and have consistent description
Update the pull request template
---
> 👷  Add PR template testing checklist

- packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackInitialViewTimings.ts
- packages/rum-core/src/domain/rumEventsCollection/view/viewCollection.ts
We finished the investigation on missing LCP.
Revert change brought by #1159 #1129
---
> 🔥 [RUMF-1041] remove LCP debug infos

- packages/rum/src/transport/send.ts
Reverts DataDog/browser-sdk#1158
> Revert "🔊 [RUMF-1080] try to detect segment sent without start"

- packages/rum/README.md
Update the configuration section to include details about how to configure Browser and Session Replay
> 📝 add details about sampling configuration

- .github/CODEOWNERS
Changes on `rum/README.md` do not request a review from doc team
Put doc ownership at the end of the code owners file
NA
---
> 👷 tweak code owners

- .gitlab-ci.yml
Fix bump chrome driver ci task notifications
Update TARGET_TASK_NAME
---
> 🐛 Fix bump chrome notifications

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- performances/src/main.ts
- performances/src/proxy.ts
Remove the proxyHost option and related implementation
Update endpoint builder
---
> 🔥 [RUMF-1093] deprecated proxyhost option

- test/e2e/scenario/eventBridge.scenario.ts
- test/e2e/scenario/rum/actions.scenario.ts
- test/e2e/scenario/rum/errors.scenario.ts
Ensure Error collection works in e2e scenarios
Add some error collection e2e tests
---
> ✅ [RUMF-731] add some error collection E2E tests

- packages/rum/README.md
> [Documentation] Fix typo

- test/e2e/scenario/recorder/viewports.scenario.ts
As per comment https://github.com/DataDog/browser-sdk/pull/1247#discussion_r784838985 we have a minor change that was missed (though has approvals). 
---
> 👌 Minor Regex enhancement

- package.json
- performances/package.json
- yarn.lock
Fix potential [security issues](https://github.com/DataDog/browser-sdk/security/dependabot)
Upgrade some dependencies (see commits).
---
> 📦 upgrade dependencies with security issues

- packages/core/src/domain/session/sessionStore.ts
Ease debugging
add a specific case for missing tracking type in cookie
---
> 🔊 [RUMF-1079] add extra inconsistency logs cause

- packages/core/src/domain/session/sessionCookieStore.ts
Following #1277, ensure that lock operations are working as expected during issue
Audit read/write corresponding to lock operations
---
> 🔊 [RUMF-1079] audit lock operations

- .github/dependabot.yml
Help keep our dependencies up to date
Enable dependabot
---
> 👷 [RUMF-1149] enable dependabot

- .github/dependabot.yml
Categorize dependabot PRs
Use [commit-message](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message) configuration
N/A
---
> 👷 add prefix to dependabot PRs

- packages/logs/README.md
Cf https://github.com/DataDog/browser-sdk/issues/1321
Edit the documentation to reflect more accurately which properties are added to logs events. 
---
> 📝 improve logs documentation

- .github/dependabot.yml
- package.json
- packages/core/src/browser/xhrObservable.ts
- packages/core/src/tools/utils.ts
- packages/logs/src/domain/trackNetworkError.ts
- packages/rum/src/domain/segmentCollection/deflateWorker.js
- packages/rum/src/domain/segmentCollection/startDeflateWorker.ts
- test/e2e/lib/framework/httpServers.ts
- yarn.lock
Have an up-to-date TS toolchain
Update typescript, ts-loader and ts-node dependencies to their latest version
---
>  📦 [RUMF-1168] update typescript 

- .eslintrc.js
- packages/core/src/browser/cookie.ts
- packages/core/src/domain/configuration/endpointBuilder.ts
- packages/core/src/domain/configuration/transportConfiguration.spec.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionStore.spec.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum/src/domain/record/mutationObserver.spec.ts
- packages/rum/src/domain/record/serialize.spec.ts
- packages/rum/src/domain/segmentCollection/segment.ts
- performances/src/scenarios/twitterScenario.ts
- scripts/bump-chrome-driver-version.js
- scripts/check-licenses.js
- scripts/cli
- scripts/staging-ci/check-squash-into-staging.js
- scripts/staging-ci/check-staging-merge.js
- scripts/staging-ci/merge-into-staging.js
- scripts/staging-ci/staging-reset.js
- scripts/utils.js
- test/e2e/scenario/logs.scenario.ts
- test/e2e/scenario/rum/tracing.scenario.ts
- test/e2e/scenario/rum/views.scenario.ts
Avoid template syntax when not needed
Avoid useless concat (no issue related in the code but useful for future development)
Update eslintrc
---
> 🎨  Avoid template syntax when not needed

- .gitlab-ci.yml
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/formatValidation.ts
- test/e2e/lib/helpers/validation.ts
Update rum-events-format to unblock all CI pipelines
* Update rum-events-format reference
* Include the newly created file
* Regenerate TS typings
---
> 🏷️  [RUMF-1206] update rum-events-format

- developer-extension/src/panel/components/eventsTab.tsx
Ease the usage of the extension
- clarify search syntax
- better light mode render
- better support for telemetry events
---
> 👷 developer extension minor improvements

- .github/dependabot.yml
too much generated PRs
ignore minor and patch dependency updates
N/A
---
> 👷 [RUMF-1233] only notify on major version update

- developer-extension/package.json
- yarn.lock
https://github.com/DataDog/browser-sdk/pull/1480
https://github.com/DataDog/browser-sdk/pull/1484
Update react and react-dom
---
> 👷 Bump react and react-dom

- developer-extension/src/panel/components/eventsTab.tsx
- developer-extension/src/panel/hooks/useEvents.ts
- developer-extension/src/panel/panel.tsx
Clear events when we want to
Add a button to clear events
---
> ✨ add a button to clear events in the developer extension

- .gitlab-ci.yml
- scripts/bump-chrome-driver-version.js
Only notify when the PR as been created
---
> 👷 Bump chrome version refine notifications

- .github/CODEOWNERS
As the lead writer for RUM & Session Replay, I will be tagged along with a review from the Documentation team.
---
> Adds Docs Secondary Reviewer

- package.json
- yarn.lock
In particular, lerna v5.3 is fixing an issue I have when doing a `yarn release`: https://github.com/lerna/lerna/issues/3214
Upgrade lerna to 5.3
---
> ⬆️ upgrade lerna

- LICENSE-3rdparty.csv
- developer-extension/package.json
- developer-extension/src/panel/components/actionsBar.tsx
- developer-extension/src/panel/components/eventsTab.tsx
- developer-extension/src/panel/panel.tsx
- yarn.lock
Keep up to date with major versions.
Update `@mantine/*` packages, and fix [breaking changes](https://mantine.dev/changelog/5-0-0/)
---
> Update mantine to v5

- package.json
- yarn.lock
Fix dependabot alert
Upgrade node-fetch to latest version
---
> ️👷 Bump node-fetch version

- packages/core/src/domain/configuration/experimentalFeatures.ts
Enforce snake case flag to be consistent with conventions used in other repositories
Add check + warn when setting flags
---
> 👷 Warn for snake cake flag

- test/e2e/scenario/rum/actions.scenario.ts
The rage click scenario is the most flaky one.
Do not perform the click sequentially
---
> 👷 e2e: improve rage click scenario

- packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/action/getSelectorsFromElement.ts
- packages/rum-core/src/domain/rumEventsCollection/action/trackClickActions.spec.ts
Implement proposals to improve selectors
Implement three proposals as separate experimental selectors, and a 4th one regrouping all proposals.
---
> ⚗ [RUMF-1379] heatmaps: refine selectors pass 2

- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/formatValidation.ts
- test/e2e/lib/helpers/validation.ts
Inroduction of sub schema broke our ci
- Update to latest schema version
- Add new schema for test validation
---
> 👷 add new schema in test event validation

- scripts/publish-npm.sh
error during publish-npm script 
Call lerna through yarn
---
> 🐛 fix `lerna: command not found`

- package.json
- yarn.lock
Fix vulnerability
Upgrade to latest lerna version
---
> 👷 Bump lerna version

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-needed.md
Provide some guidance for customers that want to open issues.
Tweak a bit bug and feature templates provided by github and add a support one as well.
> [RUMF-1415] Bootstrap issue templates

- mergequeue.yml
> Disable the mergequeue for now

- yarn.lock
Fix vulnerability
Bump engine.io and socket.io versions
---
> 👷 Bump engine.io, socket.io

- packages/core/src/browser/fetchObservable.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
- packages/rum-core/src/domain/requestCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.spec.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum-core/src/rawRumEvent.types.ts
- test/e2e/scenario/rum/resources.scenario.ts
Reverts DataDog/browser-sdk#1862
> Revert "🐛 [RUMF-1337] Fix incorrect fetch duration"

- .eslintrc.js
- developer-extension/src/panel/components/eventsTab.tsx
- developer-extension/src/panel/disconnectEvent.ts
- developer-extension/src/panel/hooks/useEvents.ts
- packages/core/src/browser/addEventListener.ts
- packages/core/src/tools/readBytesFromStream.ts
- packages/core/src/tools/utils.ts
- packages/core/test/stubReportApis.ts
- packages/rum-core/src/domain/contexts/displayContext.ts
- packages/rum-core/src/domain/rumEventsCollection/action/getSelectorFromElement.ts
- packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
- packages/rum-core/src/domain/rumEventsCollection/view/trackViewEventCounts.spec.ts
Motivated by https://github.com/DataDog/browser-sdk/pull/1890#discussion_r1054443629, enforce curly braces
- Add curly eslint rule
- Update the code accordingly
---
> 🎨 Enforce curly braces

- .eslintrc.js
- eslint-local-rules/index.js
- eslint-local-rules/secureCommandExecution.js
- scripts/bs-wrapper.js
- scripts/bump-chrome-driver-version.js
- scripts/check-licenses.js
- scripts/check-release.js
- scripts/export-test-result.js
- scripts/generate-changelog.js
- scripts/staging-ci/check-squash-into-staging.js
- scripts/staging-ci/check-staging-merge.js
- scripts/staging-ci/merge-into-staging.js
- scripts/staging-ci/staging-reset.js
- scripts/upload-source-maps.js
- scripts/utils.js
Improve our tooling security against shell injections. See Jira card for details.
Introduce a new helper to run executables without spawning a shell. Use it in our various node.js scripts.
---
> 🔒 [RUMF-1330] secure command execution

- packages/rum/src/domain/record/shadowRootsController.ts
Add telemetry for shadow dom error `no shadow root in map`
Let's find out if the shadow root is undefined or not
---
> [REPLAY] Add telemetry for shadow DOM

- developer-extension/src/panel/panel.tsx
Have quicker feedback between events created and visible
Populate event list from sdk events by defaut instead of intake requests + auto flush
---
> 👷[Extension] switch default event source to SDK

- .gitlab-ci.yml
Allow to see unminified code for telemetry errors in ap1
Upload sourcemaps to ap1 during `deploy-prod-stable`
---
> 👷[RUMF-1462] upload sourcemaps to ap1

- .eslintrc.js
Impose code structure
Configure `no-restricted-import` rule on `tools` files
---
> 👷[RUMF-1517] Restrict import of other packages into tools

- renovate.json
Almost up to date with other dependencies, let's see if we can tackle those ones as well
- Remove packages ignore rules
- Exclude previously ignored packages from `Update all non major` to avoid to impact the updates of other packages for now
---
> 👷 Remove renovate ignored packages

- yarn.lock
Dependabot alert
Bump to a non vulnerable version
---
> 👷 Bump socket.io-parser resolution

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
Avoid format differences when switching from main to v5 work
Update rum-events-format 
---
> 👷Update rum-events-format

- packages/rum-core/src/rumEvent.types.ts
Keep in sync with schema changes
Use latest schemas
---
> 👷 update rum-events-format

- developer-extension/README.md
Following latest changes on the developer extension (#2337), avoid installation errors 
Update instructions
---
> 📝 Update developer extension installation instructions

- developer-extension/manifest.json
Remove unneeded permission to ease publication process
Remove webRequest permission
---
> 👷[Extension] Remove webRequest permission

- developer-extension/README.md
Document the chrome web store link for Datadog employees
Split extension's **Getting started** section into:
- From the Chrome Web Store
- By loading the extension unpacked
---
> 📝 [RUM-254] Document extension internally available on store

- .gitlab-ci.yml
- Dockerfile
- LICENSE-3rdparty.csv
- package.json
- scripts/deploy/publish-developer-extension.js
- scripts/deploy/publish-npm.js
- scripts/deploy/publish-npm.sh
- scripts/lib/secrets.js
- yarn.lock
Ease datadog internal usage of the extension
Add a `publish-developer-extension` step to the release pipeline 
---
> 👷[RUM-254] Publish developer-extension to chrome web store

- packages/rum/src/domain/record/serialization/serializeAttributes.spec.ts
- packages/rum/test/toto.css
- test/e2e/scenario/telemetry.scenario.ts
- test/unit/karma.base.conf.js
Housekeeping
- avoid warning in unit test log
- update e2e telemetry message to something more specific to exclude
---
> 👷 Misc cleanup

- renovate.json
I managed to upgrade wdio in #2496
Revert #2482
---
> 👷 remove wdio exception from renovate.json

- yarn.lock
Dependabot alert
Bump axios resolution from `1.1.3` to `1.6.0`
---
> 👷 Bump axios resolution

- .github/CODEOWNERS
> 👷 Adjust session-replay code ownership

- yarn.lock
Dependabot alert
Bump es5-ext resolution to latest version
---
> 👷 Bump es5-ext resolution

- yarn.lock
Fix dependabot issue https://github.com/DataDog/browser-sdk/security/dependabot/75
Bump resolution of follow-redirects to the patched version
---
> 👷Bump follow-redirects resolution

- scripts/report-bundle-size/report-as-a-pr-comment.js
Show the bundle size difference in bytes in the pr comment.
---
> 👷 show difference in bytes in pr comments

- yarn.lock
Resolve dependabot alert
Bump tar resolution to 6.2.1
---
> 👷[deps] Bump tar resolution

- yarn.lock
Fixes https://github.com/DataDog/browser-sdk/security/dependabot/79
Upgrade ejs to 3.1.10
---
> 👷 Upgrade ejs to 3.1.10

- scripts/performance/memory-performance/compute-memory-performance.js
- scripts/performance/report-as-a-pr-comment.js
Update some parts of performance test, such as number of runs as the time has been decreasing a lot with the new scenario we can add some, difference for memory (since we don't calculate percentage in the array no need to call the function), markdown 
---
> 🐛 [RUM-4178] Update performance difference memory

- .gitlab-ci.yml
fixes #2806 by cherry picking the commit to sign it 🤷 
---
> 👷 Bump chrome to 126.0.6478.55-1

- .gitlab-ci.yml
The production freeze have been lifted, let's re-enable production deployments.
Revert https://github.com/DataDog/browser-sdk/pull/2826
---
> 👷 enable canary deployments

- packages/rum/src/domain/record/record.spec.ts
- packages/rum/src/domain/record/record.ts
- packages/rum/src/domain/record/serialization/index.ts
- packages/rum/src/domain/record/serialization/serialization.types.ts
- packages/rum/src/domain/record/serialization/serializeNode.spec.ts
- packages/rum/src/domain/record/serialization/serializeNode.ts
- packages/rum/src/domain/record/startFullSnapshots.spec.ts
- packages/rum/src/domain/record/startFullSnapshots.ts
- test/unit/karma.base.conf.js
Reverts DataDog/browser-sdk#2829
> Revert "⚡ [RUM-157] Caching Stylesheets serialisation"

- scripts/release/generate-changelog.js
Path was not correctly updated after last pr about changelog
Updated the path for yarn release
---
> 🐛 Update path for contributing and changelog file

- .gitlab-ci.yml
The job is blocking everything
Disable test-performance
---
> 👷 disable test-performance job

- .gitlab-ci.yml
> 👷 Bump chrome to 129.0.6668.58-1

- .gitlab-ci.yml
Releases should also be merged into the next major feature branch
---
> 👷 allow release to be merged into next major feature branch

- packages/rum/src/boot/startRecording.ts
This PR is a followup to fix typo and simplify the logic
- Fix Typo
- Simplify logic for caching and emitting records
---
> Simplify logic

- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/rum-core/src/rumEvent.types.ts
> 👷 sync rum-events-format

- packages/core/src/browser/addEventListener.spec.ts
- packages/core/src/tools/getZoneJsOriginalValue.spec.ts
- packages/core/src/tools/instrumentMethod.spec.ts
- packages/core/src/tools/timer.spec.ts
- packages/core/test/emulate/mockZoneJs.ts
- packages/rum-core/src/browser/domMutationObservable.spec.ts
Use registerCleanupTask for zonejs cleanup 
---
> ♻️ Use registerCleanupTask for zonejs cleanup

- packages/core/src/browser/fetchObservable.spec.ts
- packages/core/src/domain/report/reportObservable.spec.ts
- packages/core/test/emulate/mockFetch.ts
- packages/core/test/emulate/mockReportingObserver.ts
- packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
- packages/logs/src/domain/report/reportCollection.spec.ts
- packages/rum-core/src/domain/error/trackReportError.spec.ts
- packages/rum-core/src/domain/requestCollection.spec.ts
Use registerCleanupTask for fetch and report cleanups
---
> ♻️ [RUM-5101] Use registerCleanupTask for fetch and report cleanups

- static-analysis.datadog.yml
Disable Datadog static analysis for now.
---
> 👷 disable datadog static analysis

- .gitlab-ci.yml
> 👷 freeze next major canary deploy

- .gitlab-ci.yml
Reverts DataDog/browser-sdk#3176
> Revert "👷 freeze next major canary deploy"

- .gitlab-ci.yml
Reverts DataDog/browser-sdk#3175
> Revert "👷 freeze canary deploy"

- .gitlab-ci.yml
> 👷 freeze canary deploy

- packages/core/src/domain/configuration/configuration.ts
- packages/core/src/domain/session/oldCookiesMigration.spec.ts
- packages/core/src/domain/session/sessionManager.spec.ts
- packages/core/src/domain/session/sessionManager.ts
- packages/core/src/domain/session/sessionState.ts
- packages/core/src/domain/session/sessionStore.spec.ts
- packages/core/src/domain/session/sessionStore.ts
- packages/core/src/domain/session/sessionStoreOperations.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
- packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
- packages/core/src/domain/telemetry/telemetryEvent.types.ts
- packages/core/src/domain/user/user.ts
- packages/core/src/tools/experimentalFeatures.ts
- packages/core/test/coreConfiguration.ts
- packages/logs/src/boot/startLogs.spec.ts
- packages/logs/src/domain/assembly.ts
- packages/logs/src/domain/logsSessionManager.ts
- packages/rum-core/src/domain/assembly.spec.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/configuration/configuration.spec.ts
- packages/rum-core/src/domain/rumSessionManager.spec.ts
- packages/rum-core/src/rumEvent.types.ts
- packages/rum-core/test/mockRumConfiguration.ts
- test/e2e/lib/helpers/session.ts
- test/e2e/scenario/rum/sessions.scenario.ts
- test/e2e/scenario/sessionStore.scenario.ts
Remove the anonymous id feature flag to prepare for v6 release
Removed feature flags everywhere
Fixed unit and e2e tests of session storage to include anonymous id
---
> 💥 [RUM-7704] Remove anonymous user feature flag for v6

- .gitlab-ci.yml
re-enable check staging CI job
---
> 👷 re-enable check staging merge CI job

- .gitlab-ci.yml
Don't try to merge main into next major as the branch don't exist anymore.
---
> 👷 skip merge-into-next-major-job when undefined

- packages/rum-core/src/domain/tracing/identifier.spec.ts
- packages/rum-core/src/domain/tracing/identifier.ts
Fix some flacky unit tests
---
> ✅ clear identifier implementation cache between tests

- .gitlab-ci.yml
Upload source maps for next-major-canary CI job. There is no reason for them to not be uploaded.
---
> 👷 upload source maps for next major canary

- packages/core/src/domain/error/error.ts
- packages/core/src/domain/error/error.types.ts
- packages/logs/src/domain/createErrorFieldFromRawError.spec.ts
- packages/rum-core/src/boot/preStartRum.ts
- packages/rum-core/src/boot/rumPublicApi.ts
- packages/rum-core/src/domain/error/errorCollection.spec.ts
- packages/rum-core/src/domain/error/errorCollection.ts
- packages/rum-core/src/domain/plugins.ts
- packages/rum-core/src/index.ts
- packages/rum-core/src/rawRumEvent.types.ts
- packages/rum-react/src/domain/error/addReactError.spec.ts
- packages/rum-react/src/domain/error/addReactError.ts
- packages/rum-react/src/domain/error/errorBoundary.spec.tsx
- packages/rum-react/src/domain/reactPlugin.spec.ts
- packages/rum-react/src/domain/reactPlugin.ts
- packages/rum-react/src/domain/reactRouterV6/startReactRouterView.ts
- packages/rum-react/test/initializeReactPlugin.ts
Original -> https://github.com/DataDog/browser-sdk/pull/3285
> ✨ Report original error from `addReactError` instead of fake rendering error

- developer-extension/src/panel/hooks/useEvents/eventFilters.ts
- test/unit/karma.base.conf.js
See #3057 
With IE out of the picture, it should be fine! 🤞
---
> 🔧✅ enable splitChunk for tests again

- package.json
Node has been upgraded to v23.9.0 in the CI image. Let's use the same version locally
Update volta config
---
> 🔧 update volta config

- packages/rum-core/src/domain/contexts/featureFlagContext.ts
> ⚡️ [RUM-8664] do not update customer data when value does not changes

- packages/core/src/domain/console/consoleObservable.spec.ts
- packages/core/src/domain/console/consoleObservable.ts
- packages/rum-core/src/domain/error/trackConsoleError.spec.ts
> 🐛 Add missing original error for beforeSend context 

- .github/PULL_REQUEST_TEMPLATE.md
* It seems like the current PR template is not explicit enough, and we often don't use the checkboxes
* We should not trust contributions that were generated by AI, as it's often wrong but *looks* pertinent.
[Rendered](https://github.com/DataDog/browser-sdk/blob/benoit/update-pr-template/.github/PULL_REQUEST_TEMPLATE.md)
* Use more explicit checklist items
* Add a checkbox about AI contributions
* Add a "Test instructions" to help the reviewer test the change
* Change the contribution mention to a comment, as it's often irrelevant.
---
> 👷 Update PR template

- packages/core/src/tools/experimentalFeatures.ts
- packages/core/src/tools/valueHistory.ts
- packages/rum-core/src/domain/assembly.ts
- packages/rum-core/src/domain/contexts/internalContext.spec.ts
- packages/rum-core/src/domain/contexts/urlContexts.ts
- packages/rum-core/src/domain/contexts/viewHistory.ts
- packages/rum-core/test/mockContexts.ts
Remove url missing telemetry
---
> 🔥 Remove url missing telemetry

- developer-extension/src/panel/backgroundScriptConnection.ts
When opening the extension, previous settings are re-used (persisted), so the UI is showing them correctly, but the network rules associated to those settings are not re-applied.
The root cause was that the message to update the rules was sent before the connection to the background script was available.
We fix it by buffering messages while the connection is not there yet.
* open the extension
* use dev bundle override
* close the extension
* reopen the extension
* refresh the page -> the bundles should but overridden
> 🐛 [devext] synchronize network rules on extension start

- .gitlab/deploy-auto.yml
- .gitlab/deploy-manual.yml
- eslint.config.mjs
- scripts/lib/executionUtils.js
- scripts/lib/gitUtils.js
- scripts/release/create-github-release.mjs
Make our deployments more visible
Create a GitHub release on successful deployment based on the CHANGELOG
See https://github.com/DataDog/browser-sdk/releases for a preview
Let's check if the gitlab job works during next release
> 🔧 create a GitHub release when deploying

- test/e2e/playwright.base.config.ts
Recently I have noticed higher failure rates, reducing the number of workers playwright can use improve the situation locally and should also improve the situation on the CI.
> 👷 reduce playwright workers to improve reliability

- scripts/lib/gitUtils.ts
- scripts/lib/secrets.ts
Node.js 24 supports [explicit resource management](https://v8.dev/features/explicit-resource-management). Let's try and use it for octo tokens!
Use ERM to dispose of Octo tokens
> ♻️ use exclicit resource management for octo tokens
